### ISSUE TITLE
Refactor container cache

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#1000]
As part [attach](https://github.com/vmware/vic/pull/681) a container cache was introduced at the docker persona layer.  This needs to be refactored to the port layer to allow for easier integration with the infrastructure event stream.

**Comment by corrieb** [comment]
Clint and I had a constructive conversation about this and I want to add some architectural notes about caching. I'll copy these somewhere to GitHub. 

I think we're all agreed that caching is an optimization and that it's a second order concern beyond functional correctness, but of course if we get it wrong, it's can be a big problem.

The best way to think about this is to focus on the kind of data we're caching, while also taking into consideration the architectural intent behind the various layers. I would assert that we have 3 kinds of data:
1 - Constant data (set once on Container creation and never changes)
2 - Variable data that is created/modified only by a single-source - either a client connecting to a persona or a port layer client
3 - Variable data that is updated both by multiple sources (be it event-driven, a different kind of client or whatever).

- Type 1 is safe to cache anywhere. Container ID is an example. Cache it where you like.
- Type 2 is also safe to cache at any layer of the stack since there is only one source from which the data can be modified. It may indeed be desirable to cache that data in multiple layers. As an example, in the Docker persona, there's a Config struct https://github.com/vmware/vic/blob/master/vendor/github.com/docker/engine-api/types/container/config.go that is a blueprint for creating or modifying a container. When a container is created or modified, data from this struct will need to be modified into a container-agnostic format the port layer can understand. The port layer may then choose to also cache that same data in its own format. If querying the port layer and marshaling the data is expensive, that's fine. Since changes to that data are only ever going to come from that one persona, it should be perfectly safe. The caveat there is if we were to introduce multiple personas. In that case, the personas could not safely cache that data.
- In the case of Type3, we can only cache state in the layer that the event update mechanism reaches. In other words, if our state change events update our port layer cache, then fine - but no caching of that state in any port layer client would be safe.

For example, in the case of a docker inspect, it will take stuff from the persona and it will also have to query stuff from the port layer; combine that together and produce the output.

**Comment by corrieb** [comment]
So in this particular case, it doesn't appear that anything that is being cached in the persona is being cached inappropriately. It may be caching more than it needs to, but hopefully we can all agree that the same data may need to be cached in multiple layers, but in different formats.

**Comment by sflxn** [comment]
Hey, just want to add a comment.  Docker does something similar as what we're doing in the personality server.  One reason they keep this cache around is so they can lock access to the rest server.  For instance, if you're doing docker inspect, they lock access so you can't do some operations, such as start and kill.  Whether we do any caching in the personality server, we *might* still need some mechanism to grab a lock on a container.  I say might because Docker doesn't use this lock everywhere, and there might actually not be a need for the lock in VIC.  I need to spend some time and analyze the reason for that lock.

**Comment by corrieb** [comment]
If you're reading mutable data that could be being concurrently modified, for sure you need a lock, but ultimately what's returned should just be a snapshot of the state at the time you made the call. Locking is another good reason by the way for splitting up the state above in the way I describe. Type1 doesn't need any kind of lock. Type2 only needs a lock if you anticipate multiple clients trying to concurrently modify the same container.

**Comment by hickeng** [comment]
@corrieb Docker use the lock because their container structure is the _definitive_ structure for the container and is central to all operations on it - in our case the container structure is purely informational. As such the important thing is that the data returned to the user is internally consistent, and ordering is preserved, but it does not need to be globally consistent - in fact it cannot be as it's always potentially out of date given infrastructure is source of truth.
We could avoid the scale issues of locks for inspection by only locking for modify operations, and doing atomic update of entire container structure in global map on completion.

**Comment by hickeng** [comment]
@cgtexmex I don't think this is a TP3 item is it? If it is, please let me know, assign it to the TP3 milestone and move it into todo

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage

**Comment by mdubya66** [comment]
If this is part of the port-layer refactor it should be medium priority. marking as such. please move if it is not.
