### ISSUE TITLE
Trace calls missing from some function calls in the storage handler

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#1031]
Trace calls needed to be added at the top of the storage handler calls to improve the debugging experience in the portlayer logs.

**Comment by fdawg4l** [comment]
@matthewavery Do you mean in the REST API handlers?  I added trace where appropriate in the storage layer already.  I didn't see the point in tracing every frame in the stack especially when the frame doesn't have any blocking calls.

**Comment by hickeng** [comment]
@fdawg4l I'm actually going to be adding entry/exit trace as I needed it to track down the issue with #1191 WIP. We can/should discuss having a more controllable logging solution - but entry/exit is needed in a debug scenario.

**Comment by fdawg4l** [comment]
Trace calls are missing by design.  They didn't provide value when you can simply increase the debug log level and get more relevant information.

I would rather not make the storage logging story more verbose than it already is.  If you want more granular logging, we need to talk about using a different log library that allows for component/loglevel twiddling.

**Comment by fdawg4l** [comment]
@hickeng what is the issue with 1191?

**Comment by hickeng** [comment]
@fdawg4l agreed we need a better library and much better dynamic config - but the trace calls are going in for TP3.

**Comment by fdawg4l** [comment]
We need better logging and george added tracing (to my dismay) to (the otherwise parseable) storage log messages.  Will address logging with a better library in a different issue.
