### ISSUE TITLE
docker attach not recognizing escape sequence

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1038]
It appears that neither ctrl-c, ctrl-p, ctrl-q is recognized:

docker -H 192.168.254.215:2375 start 17e5b970b2f8fd7ecc7e581dc0ff88161fb161e5d6f7350d94c17e7c48419f39
17e5b970b2f8fd7ecc7e581dc0ff88161fb161e5d6f7350d94c17e7c48419f39
docker -H 192.168.254.215:2375 attach 17e5b970b2f8fd7ecc7e581dc0ff88161fb161e5d6f7350d94c17e7c48419f39

^C
^C
^C
^C

My terminal just appears hung and doesn't return at all.

**Comment by mhagen-vmware** [comment]
Probably the same as #996

**Comment by sflxn** [comment]
Can you provide more info?  What was the params for create, how the appliance VM was deployed, etc?

**Comment by sflxn** [comment]
ctrl-p, ctrl-q is handled by the CLI and will detach if you create your container with -it.  If you specify just -i, ctrl-p, ctrl-q does not detach.  ctrl-c works with some process not all (e.g. /bin/bash).

This can all be readily tested with regular docker.  It's been like this for as long as I have used docker, pre 1.0.

Try this with regular docker:

create -i busybox /bin/top
create -it busybox /bintop
create -i debian /bin/bash
create -it debian /bin/bash

Notice the difference.  Then try with VIC.  Noticed the same behavior.

I do not believe this issue is the same as #996.

**Comment by sflxn** [comment]
One more note, if you create -i, ctrl-c is handled by the CLI.  We do not get these ctrl key sequence.  The CLI will then try to call Container Kill, which we have not yet implemented.  It is possible that once we implement container kill, it will break out of the attach, but again, ctrl-c does not break out of a bash shell with regular docker if you do create -i.

**Comment by hagenmt** [comment]
create -i busybox /bin/top
create -it busybox /bin/top

Don't work for me at all with VIC.  When I start the containers and attach they don't show me anything and don't allow any escape.  With docker, as you mentioned I can ctrl-p ctrl-q out when I specify -it, but with VIC I am not seeing the output of top, nor will it let me escape.

**Comment by mhagen-vmware** [comment]
create -i busybox /bin/top
create -it busybox /bin/top

Don't work for me at all with VIC. When I start the containers and attach they don't show me anything and don't allow any escape. With docker, as you mentioned I can ctrl-p ctrl-q out when I specify -it, but with VIC I am not seeing the output of top, nor will it let me escape.

**Comment by sflxn** [comment]
@mhagen-vmware Hey, can you pull both the docker engine and portlayer logs?  Also, can you capture what the container VM console shows?

**Comment by mhagen-vmware** [comment]
@sflxn :
[container-logs.tar.gz](https://github.com/vmware/vic/files/309003/container-logs.tar.gz)
[logs.tar.gz](https://github.com/vmware/vic/files/309004/logs.tar.gz)

**Comment by sflxn** [comment]
I just confirmed with @mhagen-vmware his configuration.  He is running esxi under vmware workstation.  I'm running esxi under fusion which should be equivalent.  I looked at the logs and saw no errors.  The fact that the CLI handles CTRL sequences and VIC is completely not involved makes this issue very, very strange.

@mhagen-vmware, which version of the docker client are you running?  It shouldn't have changed that much, but it's the only thing I can think of.  The other thing is possibly host OS?  I believe Mikkel is running under Ubuntu and his VM Workstation is the Linux version.  I have noticed a difference with the Linux version of VM Workstation, but it should not cause this discrepancy.  @mhagen-vmware, can you also try this in a non-nested (physical machine) scenario?

**Comment by sflxn** [comment]
@mhagen-vmware When you can reproduce this again, can you also grab the container log?  This one is not quite as easy to grab.  You can use a datastore browser or use scp.

1. Make note of the container id
2. Browse to the datastore and find the folder for that id
3. The log is named <container id>.debug

I will look and see if the tether reports any errors.

btw, I want these logs to see why you're not getting any output.  The ctrl key handling is unrelated.  That issue is definitely not VIC.  It's handled by the CLI.  There is something wrong with your environment that's screwing up the ctrl key handling.  It could very well be related to you not getting output, but I want to eliminate all possibilities first.

**Comment by sflxn** [comment]
Hey, @mhagen-vmware.  When you grab the container logs, can you also report the following:

1) Linux version (with distro)
2) CLI version
3) info on how you installed docker

My current suspicion right now is that you somehow have a very old version of docker on your machine and it's not handling ctrl keys properly.  Docker is moving so fast that software repos (e.g. install with apt-get) have sometimes fallen really far behind.  I find this to be the case with many modern OSS software.

**Comment by sflxn** [comment]
I just want to add, I've been doing my testing with my devbox in nested esx, vic-machine in nested esx, vic-machine on one of our remote autoroot machine located in Seattle.

**Comment by mhagen-vmware** [comment]
Just checked again, still happening for me.  Attaching to busybox /bin/top just hangs my terminal.

1. ubuntu 16.04
2. Docker version 1.10.3, build 20f81dd
3. Just the method on their page to install: curl -sSL https://get.docker.com/ | sh

**Comment by mhagen-vmware** [comment]
Updating to docker version Docker version 1.11.2, build b9f10c9 appears to have the same problem.

**Comment by mhagen-vmware** [comment]
Tested this on nimbus and it works as expected. Seems like it could be a problem related to VMware workstation on Linux.

**Comment by hickeng** [comment]
@mhagen-vmware perfect opportunity to attach a log bundle so we can see what's going on and whether the logs contain sufficient info to diagnose it.

**Comment by mhagen-vmware** [comment]
@hickeng : more than the 2 tarballs attached with the screenshot above?

**Comment by hickeng** [comment]
@mhagen-vmware my bad - saw the screen shot but missed the links.

**Comment by hickeng** [comment]
@mhagen-vmware almost certainly this is because you've got ESX firewall configured to block outbound on 2377.
This shouldn't be an issue about Ctrl-P Ctrl-Q as much as the fact you're not getting any output at all from attach.

#1128 captures the need for a fix to the hang in this circumstance, #918 addresses the firewall config, #802 is for the programmatic check of that configuration, and #845 is for the documentation of the requirement

**Comment by mhagen-vmware** [comment]
Yep, that was the issue @hickeng
