### ISSUE TITLE
Error response from daemon: vSphere Integrated Containers does not implement container.ContainerWait

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1119]
This is a failure in the docker integration tests. Not really anymore details than the subject. Lots of instances of this, we need to implement this seemingly if we want to be able to run the tests at all.

**Comment by sflxn** [comment]
I'm not sure ContainerWait was on the list of operations we were going to do.  Maybe we should add it.  In any case, until we add the event stream listener (which tells us when containers are created, started, paused, stopped, etc.), we won't be able to do ContainerWait.

**Comment by hickeng** [comment]
@mhagen-vmware please track test failures due to _not implemented_ errors via the issues to implement them - if enough of the core tests are blocked by the lack of a specific function then we can adjust it's priority. As @sflxn says, wait was not in plan for GA and is dependent on the event stream.

Closing with #384 to implement.
