### ISSUE TITLE
Write assigned IP to vch guestinfo (docker endpoint)

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#1178]
The assigned IP for the appliance VM needs to be written to guestinfo to be able to displayed by the UI as the Docker endpoint

**Comment by hickeng** [comment]
@jak-atx 

There are multiple IPs assigned. We have the following network roles:
* management - lets you connect to vSphere
* client - access the Docker API
* external - where forwarded ports are exposed
* bridge - the internal container network

The one that we really care about is client in order to generate the DOCKER_API. This is currently found as a byte representation at key:
`guestinfo..init.networks|client.ip`
The port that it is listening on is not embedded in this fashion and is instead a part of another structure.

That said, there is an `init.Common.notes` key (not the lack of a guestinfo prefix) which is explicitly intended for holding freeform information to be referenced by an Admin.
We can also add an array dedicated to detailing the URL at which a personality API can be accessed - this would be my preference as it would let us add another personality, Kubernetes for example, without needing a plugin update to support it. Let me know what your prefer.. we can whiteboard it in the morning if you want.

**Comment by jak-atx** [comment]
@hickeng I think having it in notes could become a bit problematic as it is one field and it could have as you said freeform data. Right now the requirements are to have it labeled something like "DOCKER_API" with only that data displayed. If we had init.Common.notes.dockerApi or something that might work.

As far as having another array dedicated to this that makes sense as long as I know where to access this.  Can you provide an example of what this might look like?

**Comment by hickeng** [comment]
Copying in from email on 6th July:

a.	The IP address is available as a base64 encoded byte quartet at:
guestinfo..init.networks|client.ip.IP
b.	As of last week, image name is available as:
guestinfo./repo
c.	Port mapping data doesn’t exist as port mapping is not yet implemented.

To get the IP address bytes from the encoded address you can pass it through 
https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Decoder.html#decode-java.lang.String-
and then to the following to get a printable form.
http://download.java.net/jdk7/archive/b123/docs/api/java/net/InetAddress.html#getByAddress(byte[])

**Comment by corrieb** [comment]
George/Ben review: Needs half a day of thought and small amount of coding to have it published. The Docker personality should set this in guestInfo.

Ben and George to figure out the structure for this at a later date

**Comment by jooskim** [comment]
This issue is already resolved. VCH portlet now shows the Docker endpoint
