### ISSUE TITLE
Datastore upload/download without resolvable ESX hostnames.

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1219]
This is the appliance side portion of the issue in #1164. The appliance cannot resolve the ESX hostnames that it gets from VC. This was also seen by @cormachogan.

Not sure what the best ordering for these is - given the image prep isn't a crucial fast path I would recommend the VC approach as primary initially given it's less logic to implement.
- [ ] try the FQDN for a host
- [ ] if unresolveable get the IP address of the host from vCenter
- [ ] fall back on all upload/download paths to going via vCenter if IP/FQDN isn't available

There is host IP info available in the following location:
config.network.vnic[*].spec.ip

Selecting an appropriate IP may be a matter of:
a. trying all of them and finding which works
b. looking at the config.network.netStackInstance entries, finding the ones that permit datastore access and using the dnsConfig.virtualNicDevice entry to identify the NIC.

**Comment by hickeng** [comment]
@dougm please provide commentary on the datastore upload/download mechanism and viable approaches.

**Comment by dougm** [comment]
We originally switched from the VC host to ESX host in order to support certificate based authentication:
https://github.com/vmware/govmomi/commit/6d4932af8843455825027239651df2f8c3128732

For now, we can just revert back to using the ESX IP address by default.  Use of the ServiceTicket HostName field was only added to support the simulator case, we can just have the sim enable that behavior instead.

I can look again to see if there's a clean way to use the VC host/ip with cert based auth.

**Comment by dougm** [comment]
Note that #1164 has been merged, that change applies to the appliance side as well.

**Comment by corrieb** [comment]
Ben/George review: Related to asymmetric DNS resolution domains. If the FQDN you use for vsphere when you use vic-machine create --target cannot be resolved by the management network, it will be broken. 

Closing as fixed by #1164
