### ISSUE TITLE
attach should check vm state

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1254]
Otherwise portlayer attempts to get ssh session and gets stuck

**Comment by mdubya66** [comment]
@caglar10ur : this is TP3 because?

**Comment by caglar10ur** [comment]
create followed by attach (without start) causes everything to freeze and you can only recover if you kill docker.

**Comment by caglar10ur** [comment]
but of course feel free to move it into another milestone as we can document the problem for tp3 as a known problem

**Comment by mdubya66** [comment]
I consider that a TP3 stopper. Thanks. Moving it to the ToDo list.

**Comment by hickeng** [comment]
We can implement this in the personality as:
1. container.Inspect - check VM is powered on and attach is enabled
2. if yes to both, continue with attach.

We should also allow for a check in the port-layer, but the logic there is less evident because I think there could easily be a use-case for the following ordering:
1. call attach on container that isn't started and block until attached
2. call start on container
@corrieb what do you think?

**Comment by corrieb** [comment]
If we go with the policy of a container transitioning to RUNNING state the moment we commit a state change, then blocking attach in the PL would be the correct solution. I would be inclined to simply reject an attach if the container is STOPPED though

**Comment by hickeng** [comment]
@corrieb Expanding on why we might want to allow the opposite ordering. Docker run is:
* create
* start
* attach

The behaviour people _assume_ is:
* create
* start-and-attach

The difference here is between attaching to get all subsequent output, with the potential to miss some, and the intent to attach without missing any.

The reversed ordering of start/attach (namely, attach then start) is a very simple way of expressing the intent that you receive all output from process launch onwards.

**Comment by sflxn** [comment]
@hickeng and I were discussing this last week.  This ability to check if vm is running is dependent on ps.  I'll add the check, assuming it'll get done.

As far as whether to ditch if the container is stopped or paused, yes, we should do that.  The original attach code had a FIXME comment saying to add this check when ps is implemented.  We decided to do an optimistic attach instead of checking.  It's apparently wrong.  We should do the check.

**Comment by sflxn** [comment]
start
attach

vs 

start-attach

There is no difference.  The API server provide distinct operation.  The CLI will sequence them, but there is no start + attach at the same time operation.

**Comment by sflxn** [comment]
This check alone does not resolve the "stuck" issue.  It's actually multiple issues.  #1129 and #1128 discuss other scenarios that can cause the CLI to hang on a long delay.

**Comment by hickeng** [comment]
@sflxn is there anything else in this issue that's not addressed by #1388 ? If not can you move this to done.

**Comment by sflxn** [comment]
github automatically moves it to done if you specify the issue # in the PR and the PR is merged.
