### ISSUE TITLE
Pulling the same image concurrently with multiple clients

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1298]
Some functionality needs to be added to deal with multiple clients attempting to pull the same image at the same time.

- [ ] The storage portlayer needs to return an "already exists" error when multiple clients call `WriteImage` simultaneously for the same image. One call will inevitably win, making it impossible for the losing caller(s) to create the vmdk on the backend. This occurrence needs to be reported to the losing caller(s) so that appropriate action can be taken - this will likely occur before the layer is fully created so the loser will need to wait for it to complete before continuing with other layers.

- [ ] Once imagec is converted into a library, it must be able to track what image layers are currently being pulled. This will allow other clients currently attempting to pull the same layers to avoid duplicate downloads, also to handle and display progress output properly.

**Comment by jzt** [comment]
https://github.com/docker/docker/tree/master/distribution/xfer

This package is what docker uses to deal with the 2nd issue here.

**Comment by jzt** [comment]
@hmahmood and I sad down with this yesterday and came up with an approach. It's currently prioritized under p0 bugs, but it will be the next thing I move to.

**Comment by shadjiiski** [comment]
@jzt, anything new on this issue? I am using JFrog Bintray build 4715 and have just run this command in 2 different terminals:
```ts
docker --tls run -itd alpine:3.1 sh
```
Both `docker run` calls did not find the alpine:3.1 image locally and both started pulling it from registry, however one of them succeeded (and provisioned an alpine container) and the other one failed with
```ts
C:\Program Files\Docker Toolbox\docker.exe: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc4203e6370 Message:file already exists}.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```
From your first message on this issue I couldn't get whether this is the expected behavior or this will change to be just like it is in plain Docker (two fully functional alpine containers in the end, single alpine image downloaded). Could you please elaborate on this?

**Comment by jzt** [comment]
@shadjiiski The plan is to have the functionality match that of Docker's, just as you described. Unfortunately it is a non-trivial change that is currently prioritized below other changes to the same area of code that are making this somewhat of a moving target. At the point when things settle down and higher-priority items like p0 bugs are addressed, we can begin the rather large refactor that will be necessary to achieve this behavior. Right now, the caveat exists that concurrent pulls will exhibit this behavior.

**Comment by mdubya66** [comment]
JZT, let's get this going. Refactor needs to be complete before we are dev complete.
Required for Admiral
