### ISSUE TITLE
Stopping container removes extraconfig information

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#1337]
When issuing a stop command for a container VM the extraconfig information is removed from the VMX file.  This extraconfig information (guestinfo fields) is used by the portlayer and specifically the exec.List command to identify container VMs.  

Since this information is removed on container stop the exec.List is unable to identify container VMs and subsequently they do not appear in the docker ps output.  

Either some extraconfig information should be left upon container stop or we need to identify container vms via an alternative mechanism.

**Comment by hickeng** [comment]
Extraconfig data will be removed if the keys were created while the VM was powered on, OR if extraconfig was supplied to a VMOMI reconfigure operation when the VM was powered on (treated as add, delete, rather than update).

This is likely because of an inversion of poweroff/reconfigure ordering when committing the change on the stop path. We currently have no case where a reconfigure is needed with the VM powered on, and if we need it in the future we'll have to move to `namespaces` or do a pause/resume to preserve the config.

Update is needed here:
https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L109
