### ISSUE TITLE
List volume stores

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1507]
To support listing of configured volume stores on the VCH.  

VolumStores are added when `vic-machine create <...>  --VolumeStore` is used.  The user should be able to identify the volume store names these correspond to.

**Comment by fdawg4l** [comment]
cc @hickeng @corrieb

**Comment by fdawg4l** [comment]
The only remaining item is documenting the behavior.

**Comment by stuclem** [comment]
@fdawg4l we mention in the table of supported Docker commands that `docker info` returns a list of configured volume stores. We'll be adding that `docker volume ls` does the same when https://github.com/vmware/vic/issues/1679 is implemented. 

Is there currently anything else to doc right now, that might be for the vSphere admin's eyes, rather than for the Docker app devs? I'm thinking about the enhancements to `vic-machine inspect` in https://github.com/vmware/vic/issues/1476 or the `vic-machine ls` command that @emlin is working on in https://github.com/vmware/vic/issues/810.  

If this Epic is purely about the Docker side of things then I think that we've got this one covered, with the vSphere admin stuff covered in other open doc issues.

**Comment by matthewavery** [comment]
@stuclem looks like we are not going to go through with #1679, see the discussion on pr #1705. If you feel that We should include this feature, then we should start another conversation on it. Otherwise I believe this ticket is ready to close. cc @fdawg4l @corrieb @hickeng

**Comment by fdawg4l** [comment]
For clarity (and because #<number>) is the least descriptive way to refer to a ToDo item;

#1679 - Adding the volume store to the `docker volume ls`.  Not doing that sounds like the right thing to do.

@stuclem as long as we document that you can get the volume store name in the `docker info` output, I think that closes this epic.

**Comment by stuclem** [comment]
Thanks @fdawg4l and @matthewavery. If we aren't doing https://github.com/vmware/vic/issues/1679 then I think that we're good from the docs perspective, so you can close this one.

**Comment by fdawg4l** [comment]
Awesome.  Thanks @stuclem!
