### ISSUE TITLE
Add special characters & error handling to DatastoreToURL

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#1535]
We found an issue with some special characters, namely `-`, causing Datastore paths to not parse properly. The regex needs to be expanded to allow vSphere-permitted special characters in paths, the unit test needs to be expanded to cover these cases, and the call to `DatastoreToURL` found in `DeleteVolumeStoresIfForced` in store_files.go needs to handle errors output by this method properly so that even if a path is not parsed properly, the user gets a real error instead of a nil pointer.

**Comment by emlin** [comment]
So if user create VCH with volume configuration like
```
 --volume-store "Datastore/volume-test":volume1
```
vic-machine delete --force will fail, with following error message:
ERRO[2016-07-15T20:05:19Z] vic-machine-linux failed: runtime error: invalid memory address or nil pointer dereference

**Comment by emlin** [comment]
I think this should be in Onsite Beta.

**Comment by emlin** [comment]
@mdubya66 @hickeng

**Comment by stuclem** [comment]
@gigawhitlocks, since we're just supporting what vSphere supports, I assume that there's no need to call this out in the docs. Correct?

**Comment by gigawhitlocks** [comment]
@stuclem this issue should be closed later today, as I have a PR open to address it, although I wouldn't be surprised if we find a few more special characters that vSphere supports that vic-machine does not, as the regex I'm using is fairly strict.

It might be helpful to call it out in the docs as I've been as-of-yet unable to find documentation listing which characters are legally allowed by vSphere, otherwise I would simply expand the regex to support all of those.

**Comment by Simon321vmware** [comment]
Hello @gigawhitlocks, @emlin.

I have recently started to work with VIC and the VCH. I`m trying to use Photon OS to deploy VIC, however i think i could find an issue.

Heres what i`m trying to do:

./vic-machine-linux create --target 192.3.1.12 --image-datastore /DC_Name/Shared/VLABDS03/ -name vch01 --user administrator@vsphere.local --password ZZZZZZ --compute-resource /DC_Name/host/ClusterName/Resources/RP_VCH --bridge-network dvs_Mgmt --volume-store "gtavols:/DC_Name/Shared/VLABDS03/"

And heres the output which i`m getting:

INFO[2016-07-10T15:26:49Z] ### Installing VCH ####
INFO[2016-07-10T15:26:49Z] Generating certificate/key pair - private key in ./vch01-key.pem
INFO[2016-07-10T15:26:49Z] Validating supplied configuration
ERRO[2016-07-10T15:26:49Z] Datastore for images is nil
INFO[2016-07-10T15:26:49Z] Firewall status: ENABLED on /DC_Name/host/ClusterName/esx01.domain.com
INFO[2016-07-10T15:26:49Z] Firewall status: ENABLED on /DC_Name/host/ClusterName/esx02.domain.com
INFO[2016-07-10T15:26:49Z] Firewall status: ENABLED on /DC_Name/host/ClusterName/esx03.domain.com
INFO[2016-07-10T15:26:49Z] Firewall configuration OK on hosts:
INFO[2016-07-10T15:26:49Z]   /DC_Name/host/ClusterName/esx01.domain.com
INFO[2016-07-10T15:26:49Z]   /DC_Name/host/ClusterName/esx02.domain.com
INFO[2016-07-10T15:26:49Z]   /DC_Name/host/ClusterName/esx03.domain.com
INFO[2016-07-10T15:26:50Z] License check OK on hosts:
INFO[2016-07-10T15:26:50Z]   /DC_Name/host/ClusterName/esx01.domain.com
INFO[2016-07-10T15:26:50Z]   /DC_Name/host/ClusterName/esx02.domain.com
INFO[2016-07-10T15:26:50Z]   /DC_Name/host/ClusterName/esx03.domain.com
INFO[2016-07-10T15:26:50Z] DRS check OK on:
INFO[2016-07-10T15:26:50Z]   /DC_Name/host/ClusterName/Resources/RP_VCH
**ERRO[2016-07-10T15:26:50Z] --------------------
ERRO[2016-07-10T15:26:50Z] datastore hostname came back empty
ERRO[2016-07-10T15:26:50Z] Create cannot continue: configuration validation failed
ERRO[2016-07-10T15:26:50Z] --------------------
ERRO[2016-07-10T15:26:50Z] vic-machine-linux failed: validation of configuration failed**


I`m trying to deploy VIC into Vsphere Instance (6.0), heres structure:

DC_Name
-------Shared
--------------DS

I have tried to move particular DS straight into DC_Name DC, but it did not work either. I have tried to look for similar issue (datastore hostname came back empty) but i have found nothing.

I would be glad if you could take a look onto this matter as this issue is the closest one i could figure out.

Thanks!

**Comment by fdawg4l** [comment]
Hi @Simon321vmware!

The error being reported is that the `--image-datastore` arg is wrong.  Just pass the name of the datastore.  In this case it looks like it should be `--image-datastore DC_Name`.  

Give that a try and let us know if it's still unhappy.   Thanks!

**Comment by stuclem** [comment]
Thanks @gigawhitlocks. I created the above doc issue for this. To confirm, we're just permitting hyphens, right, or hyphens and underscores?

I'll have a look around the vSphere docs to see if I can find a list of permitted characters.

**Comment by stuclem** [comment]
@gigawhitlocks so far I have found the following doc about special characters:

- [KB 2012890](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2012890) says that square brackets and forward slashes are not permitted (but this is for VC 4.x-5.0.x)
- [KB 2046088](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2046088) includes a much longer list of forbidden characters, but is relevant to releases up to and including 5.1.x.

Otherwise, I can't find anything that lists which characters ARE supported in 6.0....

**Comment by Simon321vmware** [comment]
@fdawg4l Hello, Provided Datastore name only (so no path  with '\' like with the resources) and it worked out.
