### ISSUE TITLE
Improve docker run for quick ending containers by delaying attach

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#1578]
When users use the CLI to call attach with individual operations, they usually use the following sequence:
1. docker create
2. docker start
3. docker attach

When users use the CLI to call docker run, the actual sequence occurs
1. docker create
2. docker attach
3. docker start

For quick ending containers, start will end quick but attach will continue to wait till it times out.  If we delay attach for start to provide some results, we can improve the user experience.  We'll need to try and detect docker run.

**Comment by mdubya66** [comment]
@hickeng : please triage for prioritization

**Comment by sflxn** [comment]
Since @hickeng is sick, I'll mentioned he said he wanted this of onsite during our meeting on Monday.  I looked for a pre-existing issue and created this new one when I didn't find one.

**Comment by hickeng** [comment]
I don't think we'll be able to get this in for onsite given we're going with a build tomorrow, but I'll still work on it as time allows.
My approach is very simple for now conceptually:
1. in the personality, check if there's an active attach for the container about to be started. This likely requires the addition of a map to record active attach connections in the personality side.
2. when starting a container check for an active attach session and, if so, modify the session configuration to enable a blocking mode
3. in the tether, launch the session in a deferred Go routine that blocks on a channel. That channel will be closed either by establishing an attach connection or via timeout

From a concrete perspective my initial implementation will be:
1. modify tether so that the attach server is started before sessions are launched rather than after.
2. launch the session in a deferred fashion if attach is configured for the session

This approach is because the problem interacts with the on-demand attach behaviour we need to enable vMotion.  Attach enabled/disabled is already present in the tether - what we need to add is to determine if the serial connection is enabled. There is a toolbox mechanism for doing this connect/disconnect within the guest (@dougm) however we can infer this from whether the base ssh connection can be established for now.

**Comment by hickeng** [comment]
Let's do this:

attach.Join(...) - configures the VM for attach at all (e.g. add serial port configured as network client) 
attach.Bind(...) - configures the VM for interaction (configures the serial port for connect)

This is exactly the model that the other port layer components use and also allows us to perform the on-demand attach via a call to attach.Bind and disconnect via a call to attach.Unbind.

**Comment by hickeng** [comment]
@caglar10ur

**Comment by hickeng** [comment]
Ran through the logic with @caglar10ur. This requires:
1. move extension initialization ahead of session launch (lib/tether)
2. modify the session reader/writers to be plain Writer interface (lib/tether)
3. check whether reader/writers are already populated during tether.launch and combine with the standard reader/writers if they are (lib/tether)
4. change meaning of session.attach boolean to block in attach extension until session has a backchannel established (cmd/tether)
5. update attach.go so that it's permissible to attach to a session that's not yet launched (cmd/tether)
