### ISSUE TITLE
tag of images pulled from private repo do not have repo prefix

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1638]
Having pulled the voting app from a local registry it cannot then be run. We appear to lose the registry prefix from the tag.

```
vagrant@devbox:~/voting$ docker -H 192.168.78.216:2376 --tls create --volume=voting-app:/app --publish=5000:80 --link=redis --net=front-tier --name voting-app 192.168.78.160:5000/vote
Unable to find image '192.168.78.160:5000/vote:latest' locally
latest: Pulling from vote
a3ed95caeb02: Pull complete
e110a4a17941: Pull complete
880658c84ac0: Pull complete
d0fa457e42cb: Pull complete
8683daf6ebec: Pull complete
36812b0dc8c7: Pull complete
b3628d62696c: Pull complete
Digest: sha256:1b71896e0168e00cda17a234623d6513a7023c47c59d47dcbd98a4c5f4ad780d
Status: Downloaded newer image for vote:latest
Error: No such image: 192.168.78.160:5000/vote
vagrant@devbox:~/voting$ docker -H 192.168.78.216:2376 --tls images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vote                latest              e5e77aee8221        15 minutes ago      68.47 MB
vagrant@devbox:~/voting$ docker -H 192.168.78.216:2376 --tls create --volume=voting-app:/app --publish=5000:80 --link=redis --net=front-tier --name voting-app vote
9c85ffd47d142b56edbca2e077be0c12cc4015bd6c2be8638bd885395e74024e
vagrant@devbox:~/voting$
```

**Comment by hickeng** [comment]
@cgtexmex @jzt could you guys take a look at this please?

**Comment by corrieb** [comment]
Seems related/dup of #1942. This is going to get a lot more focus as it prevents containers being deployed from Bellevue

**Comment by mdubya66** [comment]
Moving this up in the priority list. @jzt please take a look

**Comment by mdubya66** [comment]
Asking anchal to take a look at this.

**Comment by anchal-agrawal** [comment]
This seems to be an image cache issue. An image from a private registry, such as `localhost:5000/ubuntu` is tagged as `ubuntu`, so a subsequent `run localhost:5000/ubuntu` fails because a cache lookup for `localhost:5000/ubuntu` fails. However, a `run ubuntu` succeeds after picking up the image that was pulled from the private registry since it was tagged as `ubuntu`. 

This is different from docker's behavior, which differentiates `ubuntu` and `<private registry>/ubuntu`. In docker, a `pull localhost:5000/ubuntu` and a subsequent `run ubuntu` will pull two images.

**Comment by corrieb** [comment]
@anchal-agrawal We need to be functionally consistent with Docker here. 

We urgently need to have a proposal for a fix and a size for how long it's going to take. This and #368 are currently flagged as must-haves for VMworld. If you need to get with other folks such as Caglar and George in order to hammer out a plan, we need to do that today.

**Comment by jzt** [comment]
Since imagec currently cannot yet report back to the persona when it pulls an image, the persona needs to reach out to the portlayer to ask for information on what to cache once the pull is complete. Because of this, the repository information must be stored either in or alongside the image metadata on the PL side. Obviously this is going in the opposite direction from what we want (image immutability). We can correct this when the portlayer's key/value store is implemented in the near future. I can't think of another way to handle it given the current state.

**Comment by jzt** [comment]
related:  https://github.com/vmware/vic/issues/2064

**Comment by jzt** [comment]
This is currently working (fixed in #2154) with the known caveat that a single image cannot currently contain multiple tags. This in effect means that you cannot tag the same image with multiple repos.

```
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker -H 192.168.218.235:2376 --tls pull 192.168.218.180:5000/busybox
Using default tag: latest
Pulling from busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:2130edda90b78fc58d77ecb1c4a512b08942dd7156fafcd5f9890bc08b1dc954
Status: Downloaded newer image for busybox:latest
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker -H 192.168.218.235:2376 --tls images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
192.168.218.180:5000/busybox   latest              332de81782ef        9 weeks ago         1.093 MB
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker -H 192.168.218.235:2376 --tls create 192.168.218.180:5000/busybox /bin/date
895cb89a8df4812547294661d904d9367550218bbd10fb44b58b5bb7c0c9233b
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker -H 192.168.218.235:2376 --tls start 895
895
```

**Comment by stuclem** [comment]
For release notes: a single image cannot currently contain multiple tags. This in effect means that you cannot tag the same image with multiple repos.

**Comment by npakrasi** [comment]
Added to known issues for 0.7.0.
