### ISSUE TITLE
unable to run postgres:9.4

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1643]
For some reason we're missing `/run/postgresql`

A quick hunt suggests that 60a4daae58264b9e52dbadafdc809e2d27a899fc2a5840f67a610cdbcf234289 is the ID in which this directory can be found, however it doesn't exist in our containers.

My hypothesis on the basis of a quick inspection is that the systemctl switch-root that we're using to move into the container filesystem is purging /run (or /var/run - which is a symlink to /run).

**Comment by hickeng** [comment]
@caglar10ur assigned this to you for validation of hypothesis as we've previously discussed how to drop systemd from the bootstrap image.

**Comment by caglar10ur** [comment]
It is not purging but just propagating the mount points into the new environment so we end up with a tmpfs /run instead of Dockerfile created (static) one. 

IMHO that's docker bug.  Their images should not assume /run/XYZ directories existence as systemd clearly says "Applications must ensure to recreate their own files/dirs on startup, and cannot rely that doing this at package installation will suffice. It" but since fixing all those images are not possible I'll send a PR for unmounting /run in tether.

**Comment by hmahmood** [comment]
@caglar10ur @hickeng with my recent PR (#2182), I notice that with /run unmounted, the `poweroff` and `reboot` command do not work on the vch anymore. If I don't unmount `/run`, they work fine. I don't understand how it used to work before.

**Comment by hmahmood** [comment]
```
root@virtual-container-host [ ~ ]# poweroff
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.
```

**Comment by hmahmood** [comment]
```
root@virtual-container-host [ ~ ]# journalctl -u systemd-udevd
-- Logs begin at Thu 2016-09-01 21:17:54 UTC, end at Fri 2016-09-02 00:38:38 UTC. --
Sep 01 21:17:54 Photon systemd-udevd[106]: RUN{builtin}: 'uaccess' unknown /usr/lib/udev/rules.d/73-seat-late.rules:15
Sep 01 21:17:54 Photon systemd-udevd[167]: error opening ATTR{/sys/devices/system/cpu/cpu0/online} for writing: Permission denied
Sep 01 21:17:55 virtual-container-host systemd-udevd[106]: could not touch /run/udev/queue: No such file or directory
Sep 01 21:17:55 virtual-container-host systemd-udevd[106]: could not unlink /run/udev/queue: No such file or directory
Sep 01 21:18:01 virtual-container-host systemd-udevd[266]: inotify_add_watch(8, /dev/sda, 10) failed: No such file or directory
```
