### ISSUE TITLE
Document that docker run supports the -c and -m parameters for containerVMs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1695]
Per https://github.com/vmware/vic/issues/1517.

**Comment by npakrasi** [comment]
Added to the docker run command in the [Supported Docker Commands](https://github.com/npakrasi/vic-1/blob/master/doc/user_doc/vic_app_dev/container_operations.md) table.

**Comment by stuclem** [comment]
Implemented in PR https://github.com/vmware/vic/pull/2946 (not merged yet).

**Comment by stuclem** [comment]
PR #2946 is now merged yet.

**Comment by jzt** [comment]
@stuclem Just FYI, our usage has changed a little from the PR description.

Memory and CPU are now limitless (meaning a user can set them to be any value they want, however large). ESX will send an error back down if they exceed the available CPU count. Additionally, `--cpuset-cpus` takes a single argument, an integer representing how many CPUs on which the containerVM should be able to run. They may or may not be worth documenting, as they could very likely change or simply become required explicitly by the user at VCH deploy time, but here are the current min/default values:

Minimum memory is 512MB, max unlimited.  If an amount is unspecified, a default of 2GB is used.
Minimum CPU count is 1, max is unlimited. Default is 2.

Depending on the amount of memory specified for a container VM, memory may be added in order to reach an amount that is 128MB aligned.

**Comment by stuclem** [comment]
Thanks @jzt. @npakrasi, can you please update accordingly? Thanks!

**Comment by jzt** [comment]
@stuclem @npakrasi It may also be worth documenting that `--cpuset-cpus` does not behave in VIC in the same manner as in Docker.  In Docker, `--cpuset-cpus` specifies which CPUs the container is allowed to utilize during execution whereas in VIC, it specifies the number of CPUs with which to provision the container VM.

**Comment by stuclem** [comment]
Definitely. Thanks @jzt!

**Comment by npakrasi** [comment]
Added these details to the docker create parameters table.
