### ISSUE TITLE
--volume-store doesn't seem to take effect.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic#1758]
VIC version:0.4.0
I setup VCH via the following command:
`./vic-machine-darwin create --name VCH --target root:vmware@x.x.x.x/Datacenter --image-datastore Stephen_Hu --no-tls --compute-resource Cluster2 -b DPortGroup --volume-store "vicvol:Stephen_Hu/myvol" -v 1`

Then I saw error when creating a volume:
```
docker -H 10.117.4.161:2375 volume create --name testvol
Error response from daemon: Server error from Portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError
```

And such message in portlayer log:
`time="2016-08-01T10:51:02Z" level=error msg="storagehandler: VolumeCreate error: volumestore (http://VCH/storage/volumes/default) not found" `
Though in portlayer log I also see such message:
`time="2016-08-01T10:50:49Z" level=info msg="Adding volume store vicvol ([Stephen_Hu] myvol)"`

attaching the log file:

[logs.tar.gz](https://github.com/vmware/vic/files/393535/logs.tar.gz)

**Comment by reasonerjt** [comment]
Or maybe is this "(http://VCH/storage/volumes/default) " misleading?  
But then how can I verify that VCH is trying to access the volume store as I configured?
And I created directory "**myvol**" under datastore  "**Stephen_Hu**" why it says the volumestore not found?

**Comment by fdawg4l** [comment]
The docker invocation is missing the volume store name.  In your example, from `vic-machine`, you specified `vicvol` as the volume store name.  Try:

`docker -H 10.117.4.161:2375 volume create --name testvol --opt VolumeStore=vicvol`

We use volume store names to be able to specify more than 1 location that you may want to create volumes on.  For instance 
`vic-machine create ... --volume-store "fastVolumeLocation:datastoreSSD/volumes" --volume-store "hugeSpace:datastoreVNX/volumes"`

Now, to create volumes, you need to specify which volume store you'd like to create the volumes on;  e.g. 

`volume create --name myVol --opt VolumeStore=fastVolumeLocation` 
`volume create --name myOtherVol --opt VolumeStore=hugeSpace`

**Comment by fdawg4l** [comment]
@matthewavery we need to make the error messages here more useful to the user.  If they are missing the volume store name we should probably mention what volume stores exist.

**Comment by matthewavery** [comment]
@reasonerjt all volume-stores are configured at `vic-machine create` time. However, `docker -H 10.117.4.161:2375 volume create --name testvol` does not specify a volume store to create against so `default` is the volume store that is targeted. so, in order to make a volume using the store that was configured you would do. `docker -H 10.117.4.161:2375 volume create --name testvol --opt VolumeStore=vicvol`. Also please not that the volume store ordering is now `--volume-store=<path for store>:<store label>`

You are correct that the error messages need some work and we are working on it 👍 . as for the misleading error message, the `(http://VCH/storage/volumes/default)` is indicating that you did not tag a volumestore location as `default` and that is what was being used since a volume store was not specified in the `docker volume create`.

**Comment by reasonerjt** [comment]
@fdawg4l @matthewavery thanks a lot!
