### ISSUE TITLE
Document how VIC handles images that contain volumes

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#1827]
Per https://github.com/vmware/vic/issues/1819. No milestone yet.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1819 is implemented and merged in PR https://github.com/vmware/vic/pull/2618.

**Comment by hickeng** [comment]
@stuclem the VOLUME mechanism referenced is part of [the dockerfile spec](https://docs.docker.com/engine/reference/builder/#/volume).

The only real item of note here is that we require the VCH to have been deployed with `--volume-store=xxx:default` to enable anonymous volumes. Otherwise it'll be necessary to explicitly specify a `-v volname:/path/in/container` option for every `VOLUME` statement in the image

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by stuclem** [comment]
Hi @matthewavery, I see that you added a section about this in Using Volumes with VIC Engine. Thank you very much! I took the liberty of tweaking the wording a bit:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#image_volumes

Can you please confirm that I haven't changed the meaning? Thanks!

**Comment by matthewavery** [comment]
@stuclem Looks great! Yes I had some spare cycles and noticed that I had forgotten an initial pass on that. Thank you for cleaning it up!

**Comment by stuclem** [comment]
Thanks @matthewavery! Closing as reviewed.
