### ISSUE TITLE
vic-machine does not ask for bridge network in certain cases

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#1862]
When you specify the -n option and use the name of an existing bridge network, vic-machine does not  prompt you for the -b option. This might not be the intended behavior for certain customers.

**Comment by mdubya66** [comment]
@emlin please triage for GA inclusion

**Comment by emlin** [comment]
@karthik-narayan @hickeng @mdubya66  this issue is actually because customer thought the "-n" is to set network, instead of name. If they're clear for what they did, this is not confusing.
Just we might add one more description into the bridge-network option, to as following:
```
   --bridge-network value, -b value                 The bridge network (private port group for containers), default to VCH name
```

If you think it's not good, two options available:
- Change the short name -n to bridge-network, and remove short name for --name option. Looks like we all tends to believe -n is network.
- Remove bridge-network default value, if the env is VC, but that means the behavior between VC and ESXi will be different.

Which one is your preference?
