### ISSUE TITLE
task waiter should return the actual error or preserve it upon wrapping

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1909]
```go
func WaitForResult(ctx context.Context, f func(context.Context) (ResultWaiter, error)) (*types.TaskInfo, error) {
	task, err := f(ctx)
	if err != nil {
		cerr := errors.Errorf("Failed to invoke operation: %s", errors.ErrorStack(err))
		log.Errorf(cerr.Error())
		return nil, cerr
	}

	info, err := task.WaitForResult(ctx, nil)
	if err != nil {
		cerr := errors.Errorf("Operation failed: %s", errors.ErrorStack(err))
		if info != nil && info.Error != nil {
			cerr = errors.Errorf("%s - (%s)", cerr, info.Error)
		}

		log.Errorf(cerr.Error())
		return nil, cerr
	}
	return info, nil
}
```

We are unable to inspect the `*types.TaskInfo` that comes along with this error. This makes it impossible to distinguish between various situations that may call for a different type of error propagation (for example, when the exec portlayer calls `vm.VirtualMachine.Reconfigure`, we can't know if it failed because the VM didn't exist or because of some other error, which is something we need to be able to do in order to bubble the appropriate error up to the persona. 

We should either preserve the error while wrapping (perhaps using [github.com/pkg/errors](https://github.com/pkg/errors/blob/master/errors.go#L160) or just simply return the original error along with the `types.TaskInfo` returned by `task.WaitForResult()`.

**Comment by matthewavery** [comment]
This was fixed along with the retry logic for `TaskInProgress`. Now it is possible to introspect into the faults and type check against those if the caller so chooses. This was caused by the fact that all fault errors were squashed by string formatting them into a generic error. This made it impossible to check against specfic fault cases without string checking. This is no longer the case.
