### ISSUE TITLE
local docker images duplicates? 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#1941]
This may require a bit more testing but I wanted to flag it sooner than later. 

I am iterating on an app that I am dockerizing and one of its components has been downloaded (docker pull) already on a VCH. 

As I pushed a new version to docker hub I re-pulled it (with the same name). VIC seemed to recognize it was a different images (despite the same name:latest being already pulled locally) and it pulled the new bits from the hub. 

However when I do "docker images" there is something (that appears to be?) weird: 

```
root@docker-client:~# docker --tls images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
mreferre/go-frontend   latest              1a9e87abc6a8        17 hours ago        33.03 MB
mreferre/go-frontend   latest              74dc4523fe1b        19 hours ago        777.2 MB
mreferre/haproxy       latest              133f500cd16c        2 days ago          190.6 MB
mongo                  latest              7b8befa2ba79        13 days ago         326.7 MB
busybox                latest              332de81782ef        7 weeks ago         1.093 MB
nginx                  latest              0d409d33b27e        10 weeks ago        182.7 MB
```

I have two "mreferre/go-frontend:latest" images. 

Not sure if this is proper behavior or not.

**Comment by anchal-agrawal** [comment]
I can repro this. Possibly related to #2064.

**Comment by anchal-agrawal** [comment]
This is happening because we cache images both by ID and name, and we have 2 entries for this image in the ID cache because the ID has changed. The name cache still has one entry.

Without changing the caching mechanism, this issue can be worked-around by populating the output of `docker images` using the `cacheByName` index. While this is a simple change, I'm holding off on it because #2080 tracks the implementation of a kv store to refine our image cache/store.

**Comment by cgtexmex** [comment]
The build workflow that @mreferre describes above is pretty common IMO and is problematic in vic due to a few remaining issues.  When the issue was filed the lack of multi-tag support and persistence caused the initial problems -- that is now implemented (v0.7.0 and later) and this workflow has uncovered a few other issues.  I'm working through those issues now and will update the issue shortly with a more detailed explanation.

**Comment by mlh78750** [comment]
cc @mlh78750

**Comment by cgtexmex** [comment]
As @mreferre noted above the issue he encountered was during an iterative build / deployment of a custom image.  His result was incorrect due to the fact that multi-tag support wasn't present.  Unfortunately the code base still has issues with this iterative approach.

Here are the steps I've followed:

1. In a standard docker environment (A) I've built a simple image based on busybox
2. via environment A I push that custom image to the docker hub
3. In an different docker environment (B) I'll pull that custom image
4. In a vic environment I'll pull the custom image
5. via environment A I'll modify and build a new image -- keeping the same name and tag
6. In environment B I'll pull the updated custom image
7. In the vic environment I'll pull the updated custom image

Docker Results:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
cgtexmex/tester     latest              2593ad97c5d9        28 hours ago        1.093 MB
<none>              <none>              818ab186abf8        28 hours ago        1.093 MB
```

vic Results:
```
docker pull cgtexmex/tester
Using default tag: latest
Pulling from cgtexmex/tester
56bec22e3559: Already exists
a3ed95caeb02: Already exists
44a05f322140: Download complete
Unable to Add Image Reference(cgtexmex/tester:latest): Conflict: Tag cgtexmex/tester:latest is already set to image 88dd58d4159343445dec8196aa62c81f85825fa7c99920db19a181be2ea93544, if you want to replace it, please use -f option
```

Two changes are required to address the issue.  Those are being tested and will be pushed for review shortly.

**Comment by mreferre** [comment]
Thanks @cgtexmex. For the records 3069 doesn't add broad tagging support for images right? It only fixes the (wrong) behaviour in this specific workflow. Is that correct?

**Comment by cgtexmex** [comment]
@mreferre it address this workflow and untagged images.  When you say "broad tagging support" I assume you're referring to the `docker tag` command -- that is not implemented yet.

**Comment by mreferre** [comment]
@cgtexmex sorry for the delay Clint. Yep I meant `docker tag`. Do we have an ETA out of curiousity?
