### ISSUE TITLE
VCH should not reboot endlessly on panic

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#1999]
Currently if the vic-init process (which is the default process on the VCH) panics, we reboot the VCH. This is not useful at all because we need to look at the logs for the panic call stack, etc.; these are obliterated on reboot.

We need to:
1. stop rebooting on panic
2. launch vic-admin as a separate (systemd) service so that it is always running on the VCH, even if vic-init crashes

**Comment by hickeng** [comment]
@hmahmood In general I agree, but this is actually awkward to accomplish while preserving the restart behaviour for the cases where it does help.

First pass at this should be to stash a log bundle prior to restart - that allows for diagnostics irrespective of subsequent behaviour.

**Comment by hmahmood** [comment]
@hickeng stashing the log bundle is fine, but it doesn't stop the infinite reboot cycle, and could possibly lead to running out of space on the datastore eventually.

I would argue that when we panic there is more of a chance that a subsequent boot will always panic, as opposed to say a configuration error like not being to get an IP address from DHCP. This I am basing on just my experience with vch panics thus far.

Perhaps we can do a compromise here. We can reboot _n_ number of times before we give up, although again tracking if we are in a reboot cycle may be impossible.

**Comment by hickeng** [comment]
@hmahmood it entirely depends on the cause of the panic - if it's because of a malformed configuration for example then rebooting is not going to help. If it's because of out-of-space or similar runtime error then a reboot should address it. As you say (and part of what I was referencing in my comment) - detecting a reboot cycle is awkward.

I've opened #2079 for persisting the log bundle (so we can tell what the panic was about).

The first thing we should do here is:
- [ ] prevent the reboot if deployed with debug > 0

**Comment by hmahmood** [comment]
I think this is sufficiently tackled by debug > 0, which has been implemented.

**Comment by hmahmood** [comment]
Stopping reboot on debug > 0 has not been implemented.
