### ISSUE TITLE
Running integration tests concurrently fails

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2043]
Not sure how to tackle this any better, so creating this epic as a bundle and we can either start breaking it up into constituent issues or start dissecting some other way.

The bundle to end all bundles:
[concurrent.zip](https://github.com/vmware/vic/files/425217/concurrent.zip)

The bundle contains 4 directories (test1,test2,etc) for each run that includes the robot output and then a single directory called concurrentLogs that has all of the VIC bundles for all 4 runs.

As a customer of VIC, I would like to have confidence that running multiple VCH within a single vsphere server works and doesn't corrupt each others information because that is a deployment model I expect to use.

As an engineer on VIC, I would like VCH to be able to run concurrently with other VCH in order to increase efficiency and effectiveness of testing.

**Comment by mdubya66** [comment]
can we throw hardware at this? what would it take?

**Comment by hickeng** [comment]
@mdubya66 We should be able to do this however. Unless this is a nested issue throwing resources at it isn't going to eliminate the root cause and that root cause could impact customers.

**Comment by hickeng** [comment]
@mhagen-vmware looking at concurrent.zip\test1\log.html:
The test `Docker ps all containers` is failing because there's no `dmesg` container. This is deceptive as the reason for that is that this test depends on the successful completion of the prior test `Docker ps only running containers`.
This test should be rewritten to have a setup phase that creates the containers the subsequent tests operate on.

**Comment by hickeng** [comment]
@mhagen-vmware the test1 suite 1-16 (network ls) tests are failing because the port layer has come up so slowly that the personality has given up (failed to repopulate container cache message).

This is only a code problem if, subsequent to that message, additional `network ls` commands continue to  report no bridge network even once the port layer is up.

**Comment by hickeng** [comment]
Definitely don't think this is low - getting this addressed is necessary to getting us running in a more customer representative configuration in CI.
I'm hoping there's an associated issue about reusing a single VCH for all of the CI tests which is sort of related work.
