### ISSUE TITLE
Document what happens if you run vic-machine ls on a host that is managed by VC 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2134]
Per https://github.com/vmware/vic/issues/1998, which is implemented and merged in https://github.com/vmware/vic/issues/2110.

**Comment by stuclem** [comment]
Added the following topics in Admin:

- [Running vic-machine ls on an ESXi Host Fails with an Error](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/ts_ls_error.md)
- [Deleting or Inspecting a VCH Fails with a Resource Pool Error](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/ts_delete_inspect_error.md)

@emlin are these OK? Thanks!

**Comment by emlin** [comment]
@stuclem vic-machine delete/inspect do not support target validation at this time, the reason is that if user create VCH from VC, but check that from ESXi, the resource path is different. VC resource pool is not ESXi resource pool.
So in theory, user cannot get any VCH information from a ESXi managed by VC, no matter from vic-machine or from vSphere interface.
this is why I didn't add the target check into vic-machine inspect/delete.
But if you think it's better to make them consistent, it's easy to add them as well.

**Comment by stuclem** [comment]
Hi @emlin, yes, I had guessed that this was the case, and I imagined that there was no way around it. That's why I created that troubleshooting topic. I think that should be enough, and there is no need to add the target check, in my opinion.

**Comment by emlin** [comment]
@stuclem ok, then I think for the solution of delete/inspect failure, vic-machine ls will be better.
User could easily list all VCHs for one VC/ESXi, and then use the output to delete/inspect.

**Comment by stuclem** [comment]
@emlin, I like the idea. Duly updated the topic:
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/ts_delete_inspect_error.md

Is this OK?
Thanks!

**Comment by emlin** [comment]
This one is nice. 👍
