### ISSUE TITLE
remove winscp from shipping bundle

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2204]
The winscp binary that is pulled into the bundle uses OpenSSL 1.01 which has published CVEs.
While this is only used for a single point-in-time setup it's still not acceptable and nor is download of the binary without checking thumbprints.

There is a wider question about whether this should be in the main bundle at all. While we need to have a lowest common denominator solution as a fallback for deploying the plugins I am of the opinion that:
a. it doesn't need to be shipped in the main bundle
b. we should not be shipping winscp regardless

**Comment by jooskim** [comment]
@hickeng I agree with your concern and that WinSCP should be excluded from the main package. It is used in a scenario where the user insists on using SFTP to install the UI plugin:(https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_vc_sftp.md)

So if we remove this package, do you think it makes sense that we include a step that instructs the user to download WinSCP as a prerequisite? The other approach is to drop this method altogether so that the user of vCenter for Windows will have two options for plugin installation: 1) using a web server, 2) neither sftp nor web server.

Including @stuclem as this will directly affect the documentation.

**Comment by jooskim** [comment]
Just talked with Joshua Kenney that we can simply drop this option (using SFTP) altogether, as this approach 1) is not any part of requirements for the UI to be installed, 2) is significantly more complicated than the other options, and 3) adds more security concerns that George has raised.

@stuclem Could you please review if this makes sense and have the documentation reflected? While you're working on that I could make changes to the build configuration as well as the installer script so that WinSCP gets completely removed.

**Comment by jooskim** [comment]
@jak-atx @karthik-narayan FYI, we decided to drop an installation option for vCenter Windows using SFTP for the reasons above. Please let us know if you have any concern or suggestion on this.
