### ISSUE TITLE
Document how to create named volumes

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2349]
Per https://github.com/vmware/vic/issues/2317, which is implemented and merged in https://github.com/vmware/vic/pull/2339. 

Requires an update in [Virtual Container Host Deployment Options](https://vmware.github.io/vic/assets/files/html/vic_installation/vch_installer_options.html#datastore) and in [Using Volumes with vSphere Integrated Containers Engine](https://vmware.github.io/vic/assets/files/html/vic_app_dev/using_volumes_with_vic.html).

**Comment by anchal-agrawal** [comment]
Hi @stuclem, I'm adding a quick note to explain the functionality added in my PR. We now support commands such as

`docker create -v volume-name:/directory busybox`
`docker run -v volume-name:/directory busybox`

This would check if a volume named `volume-name` exists, and if it doesn't, creates it. We then join the volume to the container. However, a command such as

`docker create -v /mycode:/directory busybox`

is invalid since we don't support mounting directories as a data volume (#2303).

**Comment by stuclem** [comment]
I have updated the following topics:

- [`vic-machine create --volume-store` option](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#volume-store)
- [Using Volumes with vSphere Integrated Containers Engine](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md)

@anchal-agrawal are these updates OK?
Thanks!

**Comment by anchal-agrawal** [comment]
Perfect, thanks Stuart!

**Comment by stuclem** [comment]
Reviewed by @anchal-agrawal via Slack.
