### ISSUE TITLE
portlayer is not closing the api session it creates

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2398]
hence restarting it over and over renders ESXi useless as hostd starts to throw "Out of HTTP sessions: reached the limit of 500 sessions" errors

@dougm any idea whether we can do this in govmomi automagically?

**Comment by dougm** [comment]
PortLayer would need to call Logout() on shutdown to discard its session.  Or cache and reuse its session, govc does this for example in ~/.govmomi/sessions

**Comment by anchal-agrawal** [comment]
@caglar10ur Please post a comment if you come across the PL server panic'ing again. Any logs would help us debug the issue.

**Comment by caglar10ur** [comment]
I'm confused. This bug is not about debugging the PL panic, this is about handling the case when it does panic. You can just call panic yourself in the PL to reproduce

**Comment by dougm** [comment]
I don't think we should persist the session, as it adds some complexity and does not provide any benefit under normal operations - since the PL uses persistent connections w/ session keepalive.

@anchal-agrawal mentioned the idea of handling panic() - this option is worth looking into, if we can use the panic/recover mechanism just to "cleanup" before exiting.

I am also adding session.ls and session.rm commands to govc, we can use in CI to remove active sessions on test suite teardown.

**Comment by anchal-agrawal** [comment]
These are my findings so far:

*  A panic while handling a request is limited to the handling goroutine - the PL server itself doesn't panic or crash. If there's a panic while handling a request, a new session is not created since the server isn't restarted - so this wouldn't cause the `out of HTTP sessions` issue.
* However, vic-init has a [`reboot`](https://github.com/vmware/vic/blob/master/cmd/vic-init/main_linux.go#L119) func that restarts the applianceVM w/o shutting down VIC services. `reboot` is called if vic-init panics. I suspect that if vic-init calls `reboot` repeatedly, we could run into the issue @caglar10ur mentioned.
