### ISSUE TITLE
docker-compose complains if bringing up app on a VCH with a running container

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2525]
As a VIC and docker compose user, I should be able to bring up a compose app on a VCH that already have running containers.

Acceptance Criteria:  Robot scripts that attempts to bring up a compose app on a VCH with a running container.

---

On a VCH, I have a private registry running:

```
loc@ubuntu:~/docker-tests/compose/voting-app$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                            NAMES
9b08d0ce5b18        registry:2.0        "registry cmd/registr"   6 days ago          Up 23 minutes       192.168.218.132:5000->5000/tcp   registry
```

I then try to bring up a compose app, it panics and dumps the following call stack:

```
loc@ubuntu:~/docker-tests/compose/voting-app$ docker-compose up -d
WARNING: Found orphan containers (egistry) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 379, in up
  File "compose/project.py", line 179, in get_services_without_duplicate
  File "compose/service.py", line 481, in remove_duplicate_containers
  File "compose/service.py", line 495, in duplicate_containers
  File "compose/container.py", line 87, in number
ValueError: Container 9b08d0ce5b18 does not have a com.docker.compose.container-number label
docker-compose returned -1
```

If I attempt this with regular docker, it runs fine.  I suspect it's looking for something in docker inspect and we're not returning the correct data.

**Comment by sflxn** [comment]
#431

**Comment by sflxn** [comment]
Upon investigating this in order to unblock myself, this may not be an issue.  It may just be a very bad limitation with docker-compose.  If I execute

```
docker-compose up --help
```

It displays the following snippet:

```
    --remove-orphans           Remove containers for services not
                               defined in the Compose file
```

It seems to indicate it does not like containers for services not defined in the compose file.  It still doesn't explain why with regular docker, it does not complain.

**Comment by mdubya66** [comment]
Backlog for post dev complete

**Comment by anchal-agrawal** [comment]
https://ci.vmware.run/vmware/vic/6370 and https://ci.vmware.run/vmware/vic/6390

**Comment by sflxn** [comment]
@anchal-agrawal It's not the same issue.  I'm looking at the build failures right now.  I know what's causing the failure in the CI.

**Comment by chengwang86** [comment]
Update:

Base on the error trace from the original post, I find that "duplicate_container()" calls this function:
```
containers = sorted(
            self.containers(stopped=True),
            key=lambda c: c.get('Created'),
        )
```
which uses "filters" below:
```
def containers(self, stopped=False, one_off=False, filters={}):
        filters.update({'label': self.labels(one_off=one_off)})

        return list(filter(None, [
            Container.from_ps(self.client, container)
            for container in self.client.containers(
                all=stopped,
                filters=filters)]))
```
The goal is to find out all existing containers with labels of "com.docker.compose.oneoff=False" and then mark them as "duplicate containers" which are to be removed.

When there is one existing container which is created by regular docker commands instead of docker-compose, the container will not have any labels by default (**Labels:{}**). So the above code will not return any duplicate container. This can be verified by
```docker ps -a --filter label=com.docker.compose.oneoff=False``` 
showing nothing even if there is an orphan container.

Howerver, on vic, due to #1676 , we haven't implemented the "--filter" feature. Therefore, the same cmd
```docker ps -a --filter label=com.docker.compose.oneoff=False``` 
would always return the orphan container (also **Labels:[**}). 

Before docker-compose actually remove the orphan container, it would like to collect the container-number information from the container label (com.docker.compose.container-number), which then causes the error msg of "ValueError: Container 9b08d0ce5b18 does not have a com.docker.compose.container-number label", since an orphan container created by regular commands does not have labels by default.

**Comment by sflxn** [comment]
We can't resolve this for GA.  This has a dependency on docker ps filtering, which we have iceboxed.

**Comment by mdubya66** [comment]
Depends on #1676 and #380. Moving out of .8

**Comment by sflxn** [comment]
This isn't an issue anymore.  After #1676, this issue seems to have been resolved.

Note, there are two cases where existing containers will prevent compose from deploying.  The first case is when an existing container unrelated to the compose yml defined app is running.  This is the case described in the original comment above.  This case requires docker ps filtering, which has been implemented and merged.

The second case is when an app related to the compose yml defined app is running.  In that case, docker rename is required.

I believe we should close this issue as it's related to ps filtering and not rename.

**Comment by sflxn** [comment]
#4170 fullfills the robot script acceptance criteria for verifying this is fixed.
