### ISSUE TITLE
[docs] Broken link in `Using Volumes with VIC engine`

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#2614]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md

First paragraph - the link to `Virtual Container Host Deployment Options` is broken. It should point to `vch_installer_options.md`, instead of `vch_installer_options.html`.

**Comment by stuclem** [comment]
Hi @anchal-agrawal,

Thanks for spotting this - am glad to see that someone is reading the docs attentively :)

However, this is actually deliberate. This link goes outside of the App Developer doc, to the Install VIC doc. Github supports linking from one MD file to another MD file in a different folder, but unfortunately the HTML conversion tool that we use to generate the HTML output from the MD source files does not. Basically, if I include links to an MD file that is in the same folder as the file that I am linking from, the HTML converter is smart enough to convert the `.md` suffix in the link to `.html` in the output, so that the link works in the HTML. However, if the link points to an MD file in a different folder, the HTML converter does not convert the `.md` suffix in the link to `.html` in the output. So, in cases in which I want to link to a file in another folder, I have to hand-code the `.html` suffix in the source file. In this way, the links work when I publish the HTML output on https://vmware.github.io/vic/. For example, see the [Using Volumes](https://vmware.github.io/vic/assets/files/html/vic_app_dev/using_volumes_with_vic.html) topic as it appears in its HTML version on github.io. In this version, the link works. If I had included the `.md` suffix  in the source file, the HTML output would have included `using_volumes_with_vic.md` and would therefore have been broken.

However, having stated all of the above, links to files in different folders only work in the HTML output. They don't work in PDFs either. 

So, what do you think is the best (as in least bad) solution? Include these HTML links that only work in the HTML output, but not in PDF or Github, or include no clickable links at all for references to topics in other books?

Thanks!

**Comment by anchal-agrawal** [comment]
The former sounds better. I'm not sure which format we anticipate most customers accessing the docs in, but in cases where we can't link directly to other books, an inline/footer text reference should suffice.

**Comment by mdubya66** [comment]
As I see it we have three customers to contend with, our dev community who build from source, our OSS users who may use the latests bits  and finally VMware customers.

For our first release we have the docs in the format we need for the VMware customers. They have a certain expectation for their documents and we need to make sure that is being met.

I would prioritize next, the OSS users. Perhaps there is a way to build the docs and distribute them as part of the download?  Something to think about post GA for sure.

**Comment by stuclem** [comment]
OK, thanks @anchal-agrawal, I agree. According to the execs, once VIC hits GA, 99% of customers will not look at the Github repo, and will only consult the "official" VMware docs. So, since the official end-user doc will be the HTML that we publish on vmware.github.io, we should leave things as they are.

**Comment by stuclem** [comment]
@mdubya66 you replied at the same time as I did. I think we're on the same page, for this release at least.
