### ISSUE TITLE
Inconsistent naming in VIC Admin portal

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2708]
The title that appears in browser tabs is **VCH Admin**. The name that appears in the links to the logs is **VIC Admin Server**. The service that runs the admin portal is `vicadmin`.

![vicadmin](https://cloud.githubusercontent.com/assets/16718369/19344679/683c0b0a-913b-11e6-9c58-f9a7e235107c.png)

@sgairo and @hickeng, should we settle on **VIC Admin** or **VCH Admin** as the official name for this portal?

Also, neither **VIC Admin** nor **VCH Admin** appears in the main body of the page. Should we change **_VCH_Name_ Admin** to something like **VIC/VCH Admin Portal for  _VCH_Name_**?

**Comment by hickeng** [comment]
I think the following:

1. change the title to be `VIC: <VCH Name>` so tabs can be distinguished. Don't think there's any need for the Admin suffix there. @stuclem @lweitzman for what ordering is used in tab titles (names vs product identifier), and :, -, or otherwise as separator
2. Drop the VCH and VIC prefix for the log names - that's implicit in their presence in the list and is stuttering
3. Rename `VCH` in both bundle links - it's going to cause confusion if VCH is used to mean the entire deployment. @stuclem I think we've mentioned `endpoint` and `appliance`. We could dodge that question entirely and go with `Log Bundle` and `Log bundle with container logs`.

For all of them a little (?) with tooltip brief description could help.

**Comment by stuclem** [comment]
@hickeng:

1. If you have a lot of tabs open, then people might only see VIC: and then the first few characters of the VCH name. Why not just have the VCH name in the tab?
2. Agree
3. Yes, I have been using **endpoint VM** and either **vApp** or **appliance** (picking one and using it consistently is on my to do list).

**Comment by stuclem** [comment]
Also, the official name is VIC Admin, right, not VCH Admin?

**Comment by sgairo** [comment]
Okay so for Title (in the tab) I have VIC: <VCH Name> , as for the page title (previously <VCH Name> Admin)  I like Admin Portal for <VCH Name> , I agree with removing all VCH/VIC from the logs and have renamed the bundles to Log Bundle and Log Bundle with container logs .

**Comment by sgairo** [comment]
per George's comment on #2718 , Initialization & Startup log is now Initialization & watchdog
