### ISSUE TITLE
Add opid to log messages from our calls to vsphere

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2739]
Don't know if govmomi returns the OP ID but the api calls that it is using does according to @derekbeard

It would help future debugging efforts if we added this.

As an engineer on VIC, it would be useful for debugging purposes to include the OP ID on vsphere operations so that we can track operations through vsphere related logs while debugging.

**Comment by hickeng** [comment]
@carlsone Has mentioned the utility of this opid for full stack performance analysis in the past.
The pkg/vsphere/task package was supposed to provide logging for the bridging between VHC operation and vSphere operations.
This should be glued together with the recent pkg/trace operation code.

**Comment by matthewavery** [comment]
I could not find the exact opID listed in the `hostd` operation calls. I have not yet found a way to obtain that opID from the `TaskInfo` object that is returned to us. @derekbeard @hickeng Any advice on where to find it? I went

**Comment by derekbeard** [comment]
I tracked this down a bit more.  I spoke with Kira on our team about how VCQE is able to log the opid.  It turns out, that VC supports client-generated OpIDs, so VCQE generates it and passes it as an “operationID” SOAP element in the SOAP header.  My guess is that we could update the govmomi SOAP client (https://github.com/vmware/govmomi/tree/master/vim25/soap) to pass an OPID generated upstream.

**Comment by hickeng** [comment]
Blocked by vmware/govmomi#749 - zenhub doesn't seem to support cross repo linking for blockers.
