### ISSUE TITLE
personality becomes unresponsive if an ongoing call blocks

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2773]
Personality stops responding queries if an operation blocks (let's say ContainerStart)

**Comment by mdubya66** [comment]
Moving to ToDo as it's a P0

**Comment by caglar10ur** [comment]
This seems to be happening because of https://github.com/vmware/vic/pull/2687 

concise pprof output shows following

```
1 @ 0x42ef9a 0x42f08e 0x43f19d 0x43ee30 0x4def00 0x7c4536 0x7cbe28 0xb85f0a 0x45fd11
#	0x43ee2f	sync.runtime_Semacquire+0x2f							/usr/local/go/src/runtime/sema.go:47
#	0x4deeff	sync.(*Mutex).Lock+0xcf								/usr/local/go/src/sync/mutex.go:85
#	0x7c4535	github.com/vmware/vic/lib/portlayer/exec.(*Container).CurrentState+0x35		/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:160
#	0x7cbe27	github.com/vmware/vic/lib/portlayer/exec.eventCallback+0xc7			/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/exec.go:118
#	0xb85f09	github.com/vmware/vic/lib/portlayer/event.(*Manager).Publish.func1+0x359	/opt/go/src/github.com/vmware/vic/lib/portlayer/event/manager.go:151

1 @ 0x42ef9a 0x42f08e 0x43f19d 0x43ee30 0x4def00 0x7c49bd 0x7c43ac 0x5dbdbd 0x5f22a8 0x665644 0x665811 0x652129 0x596b64 0x652695 0x596b64 0x65274b 0x596b64 0x59895d 0x5953e7 0x45fd11
#	0x43ee2f	sync.runtime_Semacquire+0x2f												/usr/local/go/src/runtime/sema.go:47
#	0x4deeff	sync.(*Mutex).Lock+0xcf													/usr/local/go/src/sync/mutex.go:85
#	0x7c49bc	github.com/vmware/vic/lib/portlayer/exec.(*Container).NewHandle+0x3c							/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:212
#	0x7c43ab	github.com/vmware/vic/lib/portlayer/exec.GetContainer+0x6b								/opt/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:130
#	0x5dbdbc	github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetHandler+0x14c		/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:203
#	0x5f22a7	github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetHandler-fm+0x47		/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:53
#	0x665643	github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.GetHandlerFunc.Handle+0x43			/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get.go:17
#	0x665810	github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*Get).ServeHTTP+0x1a0			/opt/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get.go:49
#	0x652128	github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1+0x68	/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23
#	0x596b63	net/http.HandlerFunc.ServeHTTP+0x43											/usr/local/go/src/net/http/server.go:1726
#	0x652694	github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1+0x554			/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78
#	0x596b63	net/http.HandlerFunc.ServeHTTP+0x43											/usr/local/go/src/net/http/server.go:1726
#	0x65274a	github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1+0x7a		/opt/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36
#	0x596b63	net/http.HandlerFunc.ServeHTTP+0x43											/usr/local/go/src/net/http/server.go:1726
#	0x59895c	net/http.serverHandler.ServeHTTP+0x7c											/usr/local/go/src/net/http/server.go:2202
#	0x5953e6	net/http.(*conn).serve+0x4b6												/usr/local/go/src/net/http/server.go:1579
```

one possible solution might be using atomic for State given its type is int. Anotther might be addressing @hickeng's post-merge comments https://github.com/vmware/vic/pull/2687#pullrequestreview-4320301

/cc @vburenin @hickeng

**Comment by caglar10ur** [comment]
Looks like WaitForState is problematic as well (https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L191) as it won't allow obtaining new handles while someone else waiting a state change.

**Comment by caglar10ur** [comment]
[logs.zip](https://github.com/vmware/vic/files/537563/logs.zip)

**Comment by hickeng** [comment]
### The crux of the matter
There are two main problems here:
1. we're using shared state in handles when we shouldn't be.
2. operations are directly updating state instead of informing the event logic of a change

### Shared state in handles
Handles are supposed to be entirely self-contained representations of all state needed to perform an operation, with a _new_ handle returned from every operation.
We have a, probably premature, optimization in place that avoids us sending a serialized representation across the wire, however we should still be treating handles as if they are self-contained, immutable, and _with no shared back-end state_. As an example:
```
h1 := GetHandle(id)
h2 := attach.Join(h1)
h3 := network.Join(h1, net7)

// h1 is still the unmodified handle returned from the original call
// h2 does not include the network change
// h3 does not include the attach change
```

We should not be needing to lock to make changes to a handle because it is unique to a specific invocation of an operation.

Handle:
```
type Handle struct {
	// desired
	Spec spec.VirtualMachineConfigSpec
	// copy from container cache
	Container Container

	// allow for passing outside of the process
	key       string
}
```

Container is actually two parts, one that holds data relevant to the Handle, and a second that holds data that _should_ be consistent within the process (i.e. in the shared cache):
Shared with handle:
```
type Container struct {
	// populate this lazily from Config
	execConfig *executor.ExecutorConfig

	// original - can be pointers so long as refreshes
	// use different instances of the structures
	Config  *types.VirtualMachineConfigInfo
	Runtime *types.VirtualMachineRuntimeInfo

	// doesn't change so can be copied here
	vm *vm.VirtualMachine
}

func (c *Container) ExecConfig() *executor.ExecutorConfig {
	if c.execConfig == nil {
		// demand populate the executor config from Config
		c.execConfig = generatorMethod(c.Config)
	}
	return c.execConfig
}
```

Holds state that _can_ be shared
```
type ContainerCacheEntry {
        Container
	state     State

	m sync.Mutex

	// Size of the leaf (unused)
	VMUnsharedDisk int64

	logFollowers []io.Closer

	newStateEvents map[State]chan struct{}
}
```

### State update and event injection
There should be a single piece of code responsible for updating the cached state of containers. This code should be handling updates from a variety of channels, including internally generated state changes such as container.start setting the state to Starting as well as vsphere events.

The extent of the update can be decided by this code - if it's a reconfigure operation then we will _need_ a refresh because the ChangeVersion will have updated and that's necessary for any subsequent operations to succeed. This could also be by direct request (such as GetHandle requesting updated state, or ChangeVersion conflict handling forcing a refresh).


### Notes:

State fields:
- handle.state
- handle.container.state (aka Container.state)
- hande.container.Runtime.PowerState

Uses:
- handle.state - declare a power state change
- hande.container.Runtime.PowerState
  - determine if power state change is actually required
  - determine if we need to strip extraconfig from a reconfigure (if powered on)
- Container.state
  - container.WaitForState (used by ContainerWaitHandler)
  - filter containers returned in container list

State update mechanisms:
- Refresh (poll) - explicit update
- Event (push)
- Operation declaring _transitional state_

Handle.state - handles _must_ not be shared between operations
- handle.state _should_ not need locking as there's no concurrent access. Locking _may_ be used to enforce sharing restrictions.
- should be updated only by StateChangeHandler/handle.SetState

Container.state - should be updated only by the following:
- explicit refresh
- vsphere event (handled by eventCallback)
- _speculative_ updates by operations into _transitional states_

**Comment by vburenin** [comment]
@caglar10ur hopefully last change will fully eliminate a danger of possible deadlock or not desired read-state lock.

**Comment by vburenin** [comment]
seems like fixed in a different PR.
