### ISSUE TITLE
Make VCH editable after creation

### ISSUE THREAD

**Issue by marcohelmerich** [vmware/vic#2910]
We are just betatesting VIC, so far pretty cool solution, but we are a bit confused, is there no possibility to change the configuration of a VCH after creation? e.g. Adding Volume Stores, changing Network config etc.  

Deleting and reinstalling the VCH will not be possible in an production environment as all associated containers are deleted with the vch. Changes should be possible in the GA Version.

**Comment by mdubya66** [comment]
Good feedback, thank you. We have plans to allow for some editing of the VCH and upgrade should be usable but I'm not sure it can be used to add volume stores, etc.

**Comment by hickeng** [comment]
#1797 is specifically about post-creation adjustment of volume stores.

I thought we had a discrete issue for reconfiguration, but was expecting it to be an inherent part of the upgrade workflow as we have to load the existing configuration, apply changes, validate the new config and commit it.  Upgrade comes with more complexity due to potential data migration, but that's the primary difference.

To my chagrin I've not found a discrete issue when searching.

**Comment by stuclem** [comment]
This is a feature request rather than a bug. @mdubya66 does it really need to go into the release notes?

**Comment by stuclem** [comment]
Removing kind/note

**Comment by emlin** [comment]
#2911 is the epic to track all vic-machine reconfigure features. Let's use that issue to track the issue, and close this one as duplicate issue.
