### ISSUE TITLE
"User Agent" of imagec should be recognisable.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic#2934]
This is an issue we saw when using **vic-product**

**VIC Version:**
0.6.0

**Description:**
Harbor filters the user-agent of the request to pull image, only request by docker will be recorded as access log.
The vanilla docker has user-agent like "docker/1.12.3 ......"

But when user runs "docker pull" via VIC engine the user agent is "Go-http-client/1.1", and this results that Harbor will not know if it's a real pull or just an API GET call.

I wish to suggest imagec should either use "docker..." or some other user-agent to identify itself.

**Comment by hainingzhang** [comment]
Maybe user-agent like "vic/0.6.0" is good for VIC engine?

**Comment by hickeng** [comment]
@hainingzhang Is there a fix scheduled from the Harbor side? Not logging a pull because user-agent wasn't recognized is only permissible if the pull itself is also rejected and there's a log entry explaining why.
IMO the user-agent isn't part of the API contract and is informational at best - from a functional perspective it shouldn't matter what imagec identifies itself as.

**Comment by mdubya66** [comment]
May go into Icebox depending on the discussion

**Comment by hickeng** [comment]
@mdubya66 There should a workaround at least in the GA timeframe. A _known_ user-agent in imagec is not a good fix, but does address the immediate issue of events not showing up. This would also require a change to harbor to recognize an additional user-agent as probably going to pull the image after grabbing the manifest.

**Comment by hainingzhang** [comment]
@hickeng Yes, harbor needs to know the agent of VIC-engine in order to log the pull. Once the agent name of vic-engine is determined, we can adjust harbor's code accordingly. @reasonerjt can explain more on why the agent name is used to log pull operation.

**Comment by mdubya66** [comment]
@hickeng let's get this done. @jzt is thus something you could knock out quickly?

**Comment by reasonerjt** [comment]
@hickeng George I agree with you on the comment that the "User-Agent" is not part of API contract.

Currently Harbor leverage the "notification" mechanism of docker registry v2 to collect the pull/push access logs.  The notification is an event fired by a sink in docker registry and when certain API calls happens it fires an event.  The request of the event doesn't carry "token" and when we were implementing the feature we didn't see a good way to correlates the events, and we decided to use "user-agent" to filter the events to differentiate a regular http GET in contrast to a pull action.

We may revisit this part later, but given the design of docker registry, filtering "user-agent" maybe the only way.

**Comment by mdubya66** [comment]
This fix is available in build https://bintray.com/vmware/vic-repo/build/6402

**Comment by mreferre** [comment]
@mdubya66 @jzt quick question: I understand that now @hainingzhang and team need to add support for this in Harbor (for Harbor to recognize it and increase the pull count). Is that correct? 

If that is correct ... does a similar support need to be added to third party docker compatible registries? I did have test Quay, Artifact, Bintray etc and VIC can pull just fine. However I have not bothered to check if the pull count increased.

**Comment by mdubya66** [comment]
@mreferre you are correct that this was to allow harbor to work correctly. as @reasonerjt points out harbor is using User-Agen outside of the API contract and we needed to add this to prevent sizable changes in harbor. 

As for the others, we don't know as we aren't really testing against all possible combinations. We do use bintray, minimally, for our builds but that is it. 

If I were a guessing person I'd guess perhaps  they don't rely on user agent since it's not part of the API contract.
