### ISSUE TITLE
Containers labels now broken, causing Compose to fail

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2954]
Recent builds have complained about basic compose test failure.

Upon examining the issue, containers labels were broken.  I've identified the line causing the break but not yet sure why.

In a recent commit, I made a call to container.Refresh() in the portlayer rest server to update the network guest info data.  That somehow screwed up the labels.  The labels are actually there in the container's extraconfig when viewed with govc.

**Comment by anchal-agrawal** [comment]
See https://github.com/vmware/vic/issues/2525#issuecomment-257064691 for builds where this failure was seen.

**Comment by chengwang86** [comment]
Update:

This is because we set the "scope" of "annotation" to "hidden" in lib/config/executor/container_vm.go

Changing it to "read-only" solves the problem. 

Another workaround is to copy the annotation/labels in the extraconfig manually when refreshing the container but keeping "annotation" hidden to the container.

Need to discuss with @hickeng @sflxn about the workaround.
