### ISSUE TITLE
Document UI upgrade

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#2994]
Just realized that I haven't doc'd this yet.

**Comment by stuclem** [comment]
Created a very basic upgrade topic that just refers people to the install topics and tells them to run upgrade instead of install.

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/upgrade_ui_plugin.md

@jooskim does this do it, or am being too lazy in not repeating the whole procedure for each type of deployment?

**Comment by jooskim** [comment]
Once the user has downloaded a newer build it should already have the new binary for VIC UI as well so I don't think there's a need to copy either the zip file or the folder to their respective location. Simply running the `upgrade.sh` file should do the job.

There's a catch though that if, for some reason, we release a hotfix of the existing version (say v1.0.0) which has the exact same version then the user has to restart the Virgo server (Web Client server) so that the change takes effect. Hopefully we'll always increment version digits as we go, but I thought it would be nice if this case were covered.

**Comment by stuclem** [comment]
Hmm, @jooskim I'm not sure that I agree with your first point. If there's a new version of the `com.vmware.vicui.Vicui-version.zip` file or `com.vmware.vicui.Vicui-version` folder then surely you either need to copy the ZIP to your Web server or the folder to the machine where VC is running. The only scenario in which you don't need to copy it is deployment to VCVA without a Web Server, I think...

As for releasing a new version with an identical version number, we do have the topic on [vSphere Integrated Containers Engine Plug-In Does Not Appear in the vSphere Web Client](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/ts_ui_not_appearing.md). I can update this one and [Verify the Deployment of the vSphere Integrated Containers Engine Plug-In](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/plugin_verify_deployment.md) to include upgrade as well as install.

**Comment by jooskim** [comment]
@stuclem You're right. What I said above was for no web server case, and you definitely have to upload the newer zip file or folder to the target location when using the web server approach. Sorry for the confusion.

It's great that you already have that covered. It's been a while since I last looked at documentations.

**Comment by stuclem** [comment]
@jooskim no problem. I have made a couple of minor changes in the topics mentioned above. Details in https://github.com/stuclem/vic/commit/761cd2ce21945948ad006f54e4dee51e3d6ce9b7. 

Does this cover it? Thanks!

**Comment by jooskim** [comment]
@stuclem Sorry for the delayed response. Looks great to me. Thanks.

**Comment by stuclem** [comment]
Thank you!
