### ISSUE TITLE
Documentation: update and clarify the network overview

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3006]
The [Network Overview](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/networks.md) topic needs some attention. 

`vic-machine create` allows you to define 5 types of network:

-  `--bridge-network`
- `--client-network`
- `--external-network`
- `--management-network`
- `--container-network `

In the network overview and diagram, we mention 4 types. Bridge is missing. We need to add bridge and clarify how it is different to the container bridge networks. Also, we should match the names of the networks that are used in the overview to the names that are used in `vic-machine create.`

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/3007 for a general clarification of VIC/Docker terminology when referring to networks.

**Comment by stuclem** [comment]
From @mreferre :

![image](https://cloud.githubusercontent.com/assets/16718369/20009496/02f4b668-a2a5-11e6-984a-2ee578be27eb.png)

**Comment by stuclem** [comment]
Per https://github.com/vmware/vic/issues/3008#issuecomment-258508106 we need to get a really clear diagram in the docs overview. 

https://github.com/vmware/vic/issues/3008 also includes some nice discussion about the roles of the different networks.

**Comment by hickeng** [comment]
@stuclem We need significantly more in terms of diagram:
- client network - needs to be explicit that the DOCKER API is served on that interface
- external network - needs to be explicit that forwarded ports are served on that interface
- bridge network - needs to be explicit that it's a DVS, without DHCP, an no other VMs (very advanced setups could weaken those constraints but no point in confusing matters)

@mreferre 
I don't think container networks should be on the initial diagram as it confuses things - they certainly shouldn't be drawn in this fashion as they're not connected to the endpoint VM in any way.
The blue box in the middle I'm assuming is the endpointVM - it should NOT be called the VCH as this is part of the confusion people have about where the containers run.

**Comment by mreferre** [comment]
@hickeng Yeah.. I am still trying to find a proper way to visualize that. I think the text you are suggesting @stuclem to add would be better added outside the context of the image where it is explained what those networks are and, they do and what they are used for. 

I think the visual requires calling out more precisely that there is a VCH (vApp) and a VCH Docker Endpoint VM. 

At that point the container network (dotted) line could be tied to the VCH (vApp) meaning that is "available" to that VCH whereas the 4 can be tied to the VCH Docker Endpoint VM. Which would be confusing anyway because it is my understanding that, today, a VCH Endpoint VM can only have 2 vNICs and you have to share those 2 vNICs among the 4 network roles in the diagram. 

I am saying this because when I tried to configure those 4 networks with 4 different vSphere Port Groups vic-machine gave me a black eye with a message along the lines of "this is not possible, at least 2 of these networks need to share the same port group" (the message was different but the meaning was pretty much that).

**Comment by stuclem** [comment]
We should match the VIC networks to the default Docker networks that are listed in https://docs.docker.com/engine/userguide/networking/. 

|**Docker Nomenclature**|**VIC Engine Nomenclature**|
|---|---|
|Default bridge network, aka `docker0` |Bridge network|
|External networks for containers|Container networks|
|Host network|Client network?|
|`none` network|N/A?|
|User-defined bridge networks|Network addresses made available by `--bridge-network-ip-range?`|
|N/A|Management network|
|Exposed container ports|Public network|
|Overlay network|Not supported?|

This table is something of a wild stab in the dark, so corrections are most welcome.

**Comment by stuclem** [comment]
Also, when addressing this one, update the graphics to use the correct network names.

**Comment by stuclem** [comment]
I have harvested everything of note from this issue and added it to the networking overview. Review of this topic is being covered by https://github.com/vmware/vic/issues/3326. Closing this one.
