### ISSUE TITLE
Some network nomenclature (around the notion of "external") perhaps needs revisiting

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#3008]
Currently using build 6507 (0.7.0 candidate). 

As I am trying to get a bit deeper into the VIC networking model I think I found some of the fundamental issues and misleading aspects that made some of the discussions with @mlh78750 so hard in the past few weeks. In retrospect I think there was a language mismatch confusion that isn't only due to documentation to be perfected (e.g.  https://github.com/vmware/vic/issues/3006 , https://github.com/vmware/vic/issues/3007) but also due to some nomenclature we are using inside the product (baked into the code) that I think we should consider changing. 

In particular we have a notion of (as far as I understand) an `external network` that is the network connected to the VCH end-point VM which is where services/containers get exposed via the `-p` option of a `docker run`. This is configured via the `vic-machine` parameter `--external-network`. 

In addition to the above, we have the notion of `container networks` (configured via the parameter `--container-network`). These are networks that containers can be attached directly to via the `--net` option of a `docker run`. 

Now the problem is that if `container networks` are configured as part of the `vic-machine create` command they show up inside the Docker context as `external` networks. 

Consider this example:
```
user1@ubuntu:~/vic$ ./vic-machine-linux create --name VCH1 ........ --bridge-network BridgePG1 --container-network PG2 --container-network PG3 --external-network "VM Network" ......
```
There is one external network (`VM Network`), one bridge network (`BridgePG1` and two container networks (`PG2` and `PG3`). 

However if I query the networks using the docker client I get: 

```
user1@ubuntu:~/vic$ docker -H 192.168.8.64:2375 network ls
NETWORK ID          NAME                DRIVER              SCOPE
96bbd64fe0fe        PG2                 external                                
83aac42374d0        PG3                 external                                
c3120e9089d3        bridge              bridge    
```

This is (IMO) creating a huge amount of confusion as people tend to give different meanings to what an `external network` actually is.  

My suggestion would be to consider changing the name of either the `--external-network` parameter or the `driver` we show in the `docker network ls`.

/cc @hmahmood @stuclem @hickeng

**Comment by hickeng** [comment]
@mreferre Part of the issue here is that you're bridging two distinct roles:
1. viadmin/vicadmin
2. docker user

While the same individual could be performing both roles, the expectation is that they will likely be separated. The nomenclature was chosen for the role, and to be consistent with docker usage.
If we were to change anything, I'd prefer to change the --external-network naming for vic-machine - do you have any suggestions for alternatives?

**Comment by mlh78750** [comment]
I agree with @hickeng. But I do understand how it could be confusing for someone that is playing both roles. Perhaps we should rename the vic-machine "external" network to "public" or something like that? It's where the published ports that go through the VCH connect and public might help in that sense. 

The external scope from a docker user perspective fits well since it implies that the docker user cannot modify the network.. It's controlled "externally" by the vsphere admin that maps it into the VCH via vic-machine.

**Comment by mreferre** [comment]
Yes I appreciate that but for someone approaching the product for the first time and testing the end-to-end workflows etc it's super difficult to understand what's going on with all these names crossing and matching. 

I am fine with changing the --external-network parameter as long as we change one :) 

We could call this: 

--outside-network (you must be kidding) 
--internet-network (mh...) 
--public-network (I like this from @mlh78750)

**Comment by hickeng** [comment]
My preference would be for --public-network.

I think a lot of the problem relates to the fact we don't have some clear diagrams front and center in our docs. A connectivity diagram would go a long way towards helping document the various network options vs attempting to describe it.
Without people having a mental model that is somewhat correct for how things hang together, attempting to finesse nomenclature is mostly wasted effort.

**Comment by mlh78750** [comment]
Let's go with public. @hickeng the docs you are asking for are something we need and something I hope to have for the beta2 customers by next week. I think this is enough of a usability thing that I'd like to see this change make it into GA. It is largely a doc change. I'd prefer to keep basic options on vic-machine stable after we've GAed. 

So the todo here is to change --external-network to --public-network in vic-machine and to change the documentation to reflect that. This should include the user-documentation as well as the docs in docs/design/networking. Whomever picks this up please make sure PR includes the docs/design/networking changes with the code.

**Comment by stuclem** [comment]
I have two doc issues open to update the docs with the comments/decisions from this one: https://github.com/vmware/vic/issues/3006 and https://github.com/vmware/vic/issues/3056. Removing the kind/doc flag as this is the engineering issue.

**Comment by hickeng** [comment]
For GA release:
- [ ] rename --external-network to --public-network in vic-machine
- [ ] update references in vic-machine to use `public` instead of `external` (otherwise arguments and output will mismatch)
- [ ] update appliance code to use `public.localhost` instead of `external.localhost` and any explicit interface references, e.g. ip tables config
