### ISSUE TITLE
Volumes misbehaviour 

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#3046]
Using version 0.7.0

Apparently there is an issue where if you deploy multiple VCHs using the same values for `--volume-store` and `--image-store`, upon deletion of a single VCH the remaining VCHs will not be able to create volumes any more. 

Steps to recreate:

```
./vic-machine-linux create --name VCH4 --target 192.168.8.211 --user user4@vsphere.local --password Vmware123! --external-network "VM Network" --bridge-network PG4 --image-store sharedstorage --volume-store sharedstorage:default --insecure-registry 192.168.8.222 --no-tls --force

./vic-machine-linux create --name VCH5 --target 192.168.8.211 --user user4@vsphere.local --password Vmware123! --external-network "VM Network" --bridge-network PG5 --image-store sharedstorage --volume-store sharedstorage:default --insecure-registry 192.168.8.222 --no-tls --force
```
At this point trying to create a volume on VCH5 will succeed. 
```
./vic-machine-linux delete --name VCH4 --target 192.168.8.211 --user user1@vsphere.local --password Vmware123! --force
```
At this point trying to create a volume on VCH5 will fail. 

/cc @emlin

**Comment by emlin** [comment]
@hickeng @fdawg4l this is the issue we talked today in the meeting

**Comment by emlin** [comment]
it's doable to warn user from vic-machine create for the volume dir is already used by other vch, but no idea for which.

**Comment by emlin** [comment]
But there still have chance to have two vch deployed at the same time, and is using the same volume directory. In that case, vic-machine cannot warn user cause the volume directory is not used yet. That's a racing issue.

**Comment by emlin** [comment]
@stuclem the document for volume store configuration, mentioned this
```
You can designate the same datastore as the volume store for multiple virtual container hosts.
```
Though user could reuse same datastore for volume store, but in general, they should specify different folder for different vch.

User can share volume stores, only after one vch is deleted, and another vch want to take over the volumes created by the previous vch.
Otherwise, user need to specify different folder for different vch.

**Comment by mreferre** [comment]
Wouldn't it help it we just create automatically a folder for the user with the VCH name? So if I do `vic-machine create --name VCH1 --volume-store datastore1:default ........` we create automatically a folder called `datastore1/VCH1`. 

This will help with:

1) the potential race condition (the VCH names need to be unique to start with)

2) honouring the fact that a new VCH can see the old volumes (a VCH with the same name will point to the same dir and will see the old volumes)

3) making easier if we want to enable a default volume-store (see https://github.com/vmware/vic/issues/2899)

**Comment by stuclem** [comment]
@mreferre but if the image store is on datastore1 with no path specified, then the VCH appliance files will be in a folder with the VCH name....

**Comment by stuclem** [comment]
Just played about a bit with volumes and think I get what @mreferre is talking about. Is it normal that, `--volume-store` still creates `VIC/volumes` at the root of the datastore if you don't specify a folder? If you don't specify a folder, `--image-store` now puts the `VIC/.../images` folder inside the folder with the VCH name. Shouldn't `--volume-store` follow the same pattern as `--image-store`, and create the `VIC/volumes` folder in the VCH folder, for consistency?

@mreferre, is this what you're talking about?

**Comment by emlin** [comment]
The dynamic folder name will always have problem between unique folder name and reusable folder name. 
We cannot guarantee the VCH name is unique, because it's in hierarchy resource pool structure, name itself is not unique. That's why images store is using vch uuid, instead of vch name as the images boundary.
And with this solution, we're forcing user to use same vch name to reuse vch volumes.

**Comment by emlin** [comment]
@stuclem the reason for volume not to use same solution with image store, is just because user will need to reuse volumes created by other VCH.
Though we still didn't really reuse same volume vmdk between two different container vms.

The case is like user created one VCH, and then created volumes and write data into those volumes from containers. 
But later on, this VCH can be removed with volumes still there. Those volumes with data can be reused by later created VCH, with specified volume store point to existing datastore folder.

In this process, we don't want to dynamically create folder, to make sure the old volumes vmdk can be find by new VCH.

**Comment by stuclem** [comment]
Hi @emlin, thank you for the explanations. This definitely deserves to be mentioned in the doc, as it helps clarify how volumes work. Thanks!

**Comment by matthewavery** [comment]
I want to make an additional note that the main issue here when this ticket was filed is that the delete was issued with a `--force` which removes volume stores. As of 0.7.0 there is a check to see if the path exists on every volume create operation and if it is suddenly gone we recreate it.

**Comment by matthewavery** [comment]
pending @fdawg4l 's input I planning to close this issue. Explanation: If you remove a VCH using `--force` it is documented that all volume stores associated with it will be removed. In this case the only issue I can see is that the error message reported currently(in 0.8.0) is `Error response from daemon: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:500 Message:ServerFaultCode: Cannot complete file creation operation.}` which is not user friendly. Otherwise in these cases a `--force` should not be used on a VCH that is sharing a volume store with another VCH. Additionally, we do not support sharing Volume Store's between multiple VCH's currently. We do support VCH deployments picking up preexisting volume stores.

**Comment by fdawg4l** [comment]
Makes sense @matthewavery.  I don't know if you'll be able to capture the ERRINUSE error, however, since it's vsphere that's throwing it.  We don't know that the volume is locked by another VM and the error returned may not make it that obvious but I don't know for sure.

**Comment by matthewavery** [comment]
Closing this issue, since we do not support sharing volume stores between VCHs. The `--force` performed its function correctly in this instance.

**Comment by matthewavery** [comment]
@stuclem the docs may need some additional input on volume stores not being shareable. this may have been missed during the doc hackathon, if so I apologize.
