### ISSUE TITLE
Simplify and cleanup vic-admin tests

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3058]
instead of pull/create/start could just use a simple docker run -itd for log, etc.

**Comment by hickeng** [comment]
@mhagen-vmware I think this will require a Robot keyword for clarity of usage.

At the moment the pull/create/start flow is used so that the output of `create` can be used directly as the container ID - if we start using run we'll need to extract that ID somehow.
If we do do this, is it viable to add some variability as to whether a given image uses pull/create/start or run? That way we'd be exercising more distinct paths/timings than if we're coding explicitly for one.

**Comment by mhagen-vmware** [comment]
Yep, good idea. Can certainly switch off a random number and do either mechanism. Should be good and interesting then :)

**Comment by mhagen-vmware** [comment]
Really not necessary, closing this. There are only a total of 2 tests that use this pattern in all the vicadmin tests, little to no readability improvement would be had here.
