### ISSUE TITLE
Remove systemd from bootstrap image

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#306]
The container bootstrap image should be as small as possible and it should allow us to delete the contents of the initramfs once we pivot - systemd doesn't align well with these goals and we only need it to provide device management.

Look into, and if viable, replacing systemd with libudev linked to tether. Alternatively, given we've a _very_ narrow set of possible hardware changes, perhaps we can consume the netlink messages directly and act appropriately.

**Comment by hickeng** [comment]
unlikely to be viable for GA as I think it requires a udev alternative for populating /dev/disk/by-label

**Comment by matthewavery** [comment]
@hickeng there is an alternative possibility for populating that by reading the ext4 superblocks. I have a branch that does this. but it is not fully tested. @fdawg4l thoughts on this issue?

**Comment by fdawg4l** [comment]
@matthewavery reading the superblock is only part of the story.  That only identifies the filesystem (by virtue of being able to decode the superblock).  You still need to identify the block devices and mount them appropriately.  Currently `systemd` is doing this for us by way of `udev` in the container.  HOWEVER, on the VCH, I added disk detection by crawling the `vmw_pvscsi` driver's `/sys` interface.  Thereby not requiring udev to setup disks for us.

In any case, those are all just details.  We still need `udev` for network interfaces.  Disks aren't the only thing we're using `udev` for.  And since this isn't critical or in the PRD, i'm setting this to a low priority and adding a research spike tag since the details need to be fleshed out to deal with both network AND disk.

**Comment by hickeng** [comment]
@fdawg4l We're using the pcislot address and netlink for ethernet currently; we will be moving to using the `label` file in a vmxnet3 sys node soon (#2802) and we explicitly load vmxnet3 so I don't think we need anything from udev for the network.
Do you have doc/pointer/PoC code for the vmw_pvscsi walk to get the disk labels?

**Comment by fdawg4l** [comment]
@hickeng It's been a long time since I've looked at this code, but I think the relevant bits are here (https://github.com/vmware/vic/blob/caa9bb3886b10fbf282925e063a2d3725564fcad/pkg/vsphere/disk/util.go#L46).  The disk label, IIRC, is in a file in the extracted LUN's directory.   I don't have an environment to confirm however.  The `vmw_pvscsi` code is the reference, however.

**Comment by hickeng** [comment]
@fdawg4l Thanks!

**Comment by zjs** [comment]
Customers could create their own custom bootstrap image.
