### ISSUE TITLE
Document the default DNS servers when using static VCH IP

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3206]
Per https://github.com/vmware/vic/issues/3060, which is implemented in PR https://github.com/vmware/vic/pull/3157 (merged).

**Comment by stuclem** [comment]
Updated the description of the [--dns-server option](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md).

Changes are in https://github.com/stuclem/vic/commit/f341d59802d89820c4c042a5e84d489657563eb7.

@andrewtchin is this OK? Thanks!

**Comment by andrewtchin** [comment]
looks good 👍

**Comment by andrewtchin** [comment]
actually maybe instead of 
`If you specify `dns-server`, `vic-machine create` always uses the `--dns-server` setting for all three of the client, external, and management networks, even if all three networks use DHCP to obtain their IP addresses.`
use
``If you specify `dns-server`, `vic-machine create` always uses the `--dns-server` setting for all three of the client, external, and management networks.`

**Comment by stuclem** [comment]
Fix is in https://github.com/stuclem/vic/commit/5ad161eefefd6628f012420acd108a0e69a0ddf5. Thanks @andrewtchin !
