### ISSUE TITLE
Network connectivity in admin portal when proxy is set

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#3213]
VIC Version 0.7.0 - Ran into this issue with a HTB customer this morning. 

When the proxy is set, the network connectivity details in the admin portal show an error. The message describes that the container VMs are not able to ping google(?) and another location.

**Comment by mlh78750** [comment]
Well, they can't ping those locations. But it could be confusing. What we should likely do is see that proxy is set and then switch to doing something that fetches through the proxy. We'll need to make sure that we don't make them think it's broken when it's not.

**Comment by mlh78750** [comment]
@stuclem: release note for 0.7 and 0.8: If VCH is configured with a proxy setting, then the vic-admin status page will show a network failure even when connectivity through the proxy is working.

**Comment by stuclem** [comment]
Added the following in the release notes for 0.7:

----

- <b>VCH Admin shows network failure when virtual container host uses a proxy. [#3123](https://github.com/vmware/vic/issues/3123)</b><br>If a virtual container host is configured to use a proxy, the VCH Admin status page shows a network failure even if connectivity through the proxy is working.

----

Removing kind/note because we carry over the Known Issues from one release to the next, and remove the ones that are fixed. So, this will make it into the RNs for 0.8 by default.

**Comment by stuclem** [comment]
Already in the release notes so removing kind/note tag.
