### ISSUE TITLE
Doc Review: Unknown or Non-Specified Argument Error or Incorrect User Name Error

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3322]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_cli_argument_error.md#problem

> Image datastore path must be specified; use format datastore/path

I cannot find this error msg in our code.

I have read the rest of the doc and I have no additional comment on it.

**Comment by stuclem** [comment]
Thanks @chengwang86. I wrote this a long time ago and so those error messages have obviously been improved since. 

However, I just tested this again by using a value of `vic bridge` (with space, but no quotes) for the `--bridge-network` option and I get the following error:

```
$ vic-machine-windows create --target 10.153.199.35 --user 'Administrator@vsphere.local' --password 'xxx' --bridge-network vic bridge --no-tlsverify --thumbprint 12:A6:19:A5:BE:E6:68:EE:58:E6:DB:5B:C0:ED:32:17:C1:1B:15:48
INFO[2016-11-29T15:45:33+02:00] ### Installing VCH ####
WARN[2016-11-29T15:45:33+02:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2016-11-29T15:45:33+02:00] Loaded server certificate virtual-container-host\server-cert.pem
ERRO[2016-11-29T15:45:33+02:00] Common Name must be provided when generating certificates for client authentication:
INFO[2016-11-29T15:45:33+02:00]   --tls-cname=<FQDN or static IP> # for the appliance VM
INFO[2016-11-29T15:45:33+02:00]   --tls-cname=<*.yourdomain.com>  # if DNS has entries in that form for DHCP addresses (less secure)
INFO[2016-11-29T15:45:33+02:00]   --no-tlsverify                  # disables client authentication (anyone can connect to the VCH)
INFO[2016-11-29T15:45:33+02:00]   --no-tls                        # disables TLS entirely
INFO[2016-11-29T15:45:33+02:00]
ERRO[2016-11-29T15:45:33+02:00] Create cannot continue: unable to generate certificates
ERRO[2016-11-29T15:45:33+02:00] --------------------
ERRO[2016-11-29T15:45:33+02:00] vic-machine-windows.exe failed: provide Common Name for server certificate
```
I did another test by removing the quotes from around the password, which contains `@`, and got the same error. So, it now seems that if you include an argument that includes spaces or special characters, the validator only parses the command as far as that argument. It therefore thinks that you haven't specified any TLS options, even if you have, and so throws the TLS error message. Since this isn't a TLS issue, this is highly misleading. I'll open an issue for this.

I ran the command again, this time specifying `--no-tls` immediately after `--target`, and this time got a more appropriate error: `vic-machine-windows.exe failed: invalid CLI arguments`.

In the meantime, I have rewritten the topic to reflect the situation above. New version is here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/ts_cli_argument_error.md

Changes are in https://github.com/stuclem/vic/commit/f1cf4594e65a6af9f800f1450577130987ca423a.

Is this OK now? Thanks!

**Comment by chengwang86** [comment]
@stuclem I repeated your cmds and saw the same behavior. I agree with your reasoning about the tls option.

**Comment by stuclem** [comment]
Hi @chengwang86. Did you review the new version at https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_cli_argument_error.md? If so, can I close this one?

Thanks!
s

**Comment by chengwang86** [comment]
The new version looks good :)

LGTM

**Comment by stuclem** [comment]
Thanks @chengwang86 !
