### ISSUE TITLE
Doc Review: Running vic-machine ls on an ESXi Host Fails with an Error

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3324]
The content looks good to me. 

One comment: I see the same error msg when I run "vic-machine create". So shall we change the title and content of this section to also incorporate "vic-machine create"?

**Comment by stuclem** [comment]
Thanks @chengwang86, There's actually another topic for the `vic-machine create` case: https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_resource_pool_error.md, which is reviewed by @emlin  in https://github.com/vmware/vic/issues/3390. Emma confirms what you say about `create`. 

When I first wrote these topics for `create` and `ls`, the errors were a lot less clear. Now the errors state clearly that you need to specify the VC in the `target` option. So, do we even need this topic? I think that it's stating the obvious...

Of more interest is running `vic-machine inspect` on a VCH and specifying the ESX in the target instead of the VC. In this case you see the following:

```
$ vic-machine-windows inspect --target 10.153.199.206 --user 'root' --password 'ca$hc0w' --thumbprint E7:6F:32:A2:49:49:F6:A6:3D:02:94:75:8E:AC:6C:1A:8D:43:61:0D --id vm-404
INFO[2016-12-01T20:25:27+02:00] ### Inspecting VCH ####
ERRO[2016-12-01T20:25:27+02:00] Failed to get Virtual Container Host virtual-container-host
ERRO[2016-12-01T20:25:27+02:00] Failed to query appliance ("VirtualMachine:vm-404"): ServerFaultCode: The object has already been deleted or has not been completely created
ERRO[2016-12-01T20:25:27+02:00] --------------------
ERRO[2016-12-01T20:25:27+02:00] vic-machine-windows.exe failed: inspect failed

```
Should I make this topic about running `inspect` in the same circumstances, instead of `ls`?

**Comment by chengwang86** [comment]
@stuclem I agree that this topic is nothing special and we could just remove it. 

For "vic-machine inspect", you have this topic here https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/ts_delete_inspect_error.md

maybe you can add what you have above to that topic. In my comment for that topic (https://github.com/vmware/vic/issues/3325), the error msg I found is different from yours above, which is probably because you specified --id for "inspect/delete" whereas I was using "--name".

**Comment by stuclem** [comment]
Thanks @chengwang86. I deleted the topic. Change is in: https://github.com/stuclem/vic/commit/2656e7c6c6f97d1e1bc2f2897ceecb3130a07984
