### ISSUE TITLE
Comments/suggestions for "Networking Options" doc

### ISSUE THREAD

**Issue by hmahmood** [vmware/vic#3327]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#networking

> A VCH supports a maximum of 3 distinct networks. Because the bridge and container networks require their own distributed port groups, at least two of the public, client, and management networks must share a network.

"A VCH supports connecting to a maximum of 3 network port groups. Because the bridge and container networks require their own port groups, at least two of the public, client, and management networks must share a network port group."

**Comment by hmahmood** [comment]
For the `--bridge-network` option:

> A distributed port group that container VMs use to communicate with each other.

"A port group that the container VMs use to communicate with each other"

... since on standalone ESX there are no distributed port groups.

**Comment by hmahmood** [comment]
> Short name: --en

"Short name: --pn"

**Comment by hmahmood** [comment]
The `--bridge-network` documentation references port groups, while the other options like `--public-network`, `client-network`, and `management-network` all use the term "network". This should consistent as all of these options require a port group name in the end. We should either use "port group" or "network".

**Comment by hmahmood** [comment]
For `--container-network`, we need to add that this can be specified multiple times to add multiple vSphere networks to docker.

**Comment by mlh78750** [comment]
> IMPORTANT: A VCH supports a maximum of 3 distinct network interfaces. Because the bridge and container networks require their own distributed port groups, at least two of the public, client, and management networks must share a network interface.

Can we mention in this that this is just a current restriction that will be resolved with #2802.

**Comment by mlh78750** [comment]
> The network that the VCH uses to generate the Docker API. The Docker API only uses this network.

I'd prefer: "The network where the VCH will provide the Docker API. This network will be used by the docker clients to issue docker API requests to the VCH.

**Comment by mlh78750** [comment]
> Container VMs use the public network to publish network services. If you define the public network, you can deploy containers directly on the public interface.

Strike those two lines.

Add:  

The public interface is where the container's network services will be exposed when using port mapping. Note: VIC adds a new capability to directly map containers to a network using --container-network and that is the recommended deployment for container services.

**Comment by mlh78750** [comment]
under management network:
> Ideally, use separate networks for the management network and the container network.

Strike that line. It's confusing and already covered elsewhere.

**Comment by mlh78750** [comment]
For --container-network

At the top please add something like this:

You can optionally specify one or more container networks. These networks are used to allow containers to directly attach to a network without needing to route through the VCH via network address translation (NAT). Container networks added with this option will show under the 'docker network ls' command and are available for use by the containers. The containers using these networks are directly attached to the container network and will not go through the VCH or share the VCH public IP.

**Comment by mlh78750** [comment]
> The descriptive name appears under Networks when you run docker info on the deployed VCH.

And when they run 'docker network ls'

**Comment by mlh78750** [comment]
> If you do not specify the container-network option, or if container developers run docker run or docker create without specifying --net, container VMs use the bridge network. 

Even if you do not specify any container-network or if the container is deployed without using a container network, the network services will still be available via port mapping through the VCH using network address translation through the public interface of the VCH.

**Comment by mlh78750** [comment]
I'm done with this section.

**Comment by andrewtchin** [comment]
agree with the above, lgtm

**Comment by stuclem** [comment]
Thanks @hmahmood, @mlh78750 and @andrewtchin !

- @hmahmood, regarding the limit of 3 PGs per VCH, I changed your suggestion somewhat, to remove container networks from the 3 PGs: "A VCH supports a maximum of 3 network port groups. Because the bridge network requires its own port group, at least two of the public, client, and management networks must share a port group. Container networks do not got through the VCH, so they are not subject to this limitation." 
- Replaced "distributed port group" with "port group" throughout the entire doc set.
- Fixed `--pn`
- Changed "network" to "port group" wherever it seemed appropriate. I'd appreciate it if you'd look at the diff to make sure that I didn't change any that I shouldn't have.
- Added "You can specify `--container-network` multiple times to add multiple vSphere networks to Docker."
- Added " This limitation will be removed in a future release." to the IMPORTANT note about the 3 PG limit.
- Added "A port group on which the VCH will make the Docker API available to Docker clients. Docker clients use this network to issue Docker API requests to the VCH."
- Added "Containers that use use port mapping expose network services on the public interface. **NOTE**: vSphere Integrated Containers Engine adds a new capability to Docker that allows you to directly map containers to a network by using the `--container-network` option. This is the recommended way to deploy container services."
- Removed "Ideally, use separate networks for the management network and the container network."
- Added: "You can optionally specify one or more container networks. Container networks allow containers to directly attach to a network without having to route through the VCH via network address translation (NAT). Container networks that you add by using the `--container-network` option appear when you run the `docker network ls` command. These networks are available for use by containers. Containers that use these networks are directly attached to the container network, and do not go through the VCH or share the public IP of the VCH."
- Updated "The descriptive name appears under `Networks` when you run `docker info` or `docker network ls` on the deployed VCH."
- Added If you do not specify `--container-network`, or if you deploy containers that do not use a container network, the containers' network services are still be available via port mapping through the VCH, by using NAT through the public interface of the VCH.

Changes are in https://github.com/stuclem/vic/commit/a6e9c144d52c7b1a72129386b0c82cf7c0e390c4.

I'd really appreciate another pass. Thanks!

**Comment by mlh78750** [comment]
One minor addition. I commented in the commit.

LGTM

**Comment by hmahmood** [comment]
got -> go in line 11. Same for line 158. lgtm otherwise.

**Comment by stuclem** [comment]
Thanks @hmahmood and @mlh78750. @mlh78750 I think that your comment was on the examples file, so I'm closing this one.
