### ISSUE TITLE
Doc Review: vSphere Target Options

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3330]

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--thumbprint
`--thumbprint` value is required to be in upper case, colon delimited form e.g. `C1:7A:E4:A4:22:B8:8A:68:F9:A4:E4:C2:38:91:3B:0D:8E:E0:C8:FB`

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by emlin** [comment]
> If you are deploying to an ESXi host that has no resource pools, vic-machine create automatically uses the default resource pool. 

In esxi host, even there is resource pool, the default resource pool will be used if no resource pool specified

**Comment by emlin** [comment]
> An ESXi host includes multiple resource pools.

Should be removed for the above reason

**Comment by stuclem** [comment]
Thanks @andrewtchin, @mhagen-vmware and @emlin !

- Added "If you obtain the thumbprint by other means, use upper-case letters and colon delimitation rather than space delimitation when you specify `--thumbprint`."
- Reworded to "If you are deploying to an ESXi host and you do not specify `--compute-resource`, `vic-machine create` automatically uses the default resource pool. "
- Removed "An ESXi host includes multiple resource pools."

Changes are in https://github.com/stuclem/vic/commit/f3005f3b93db961e1cc9d6f78de9a0d29165bad9.

Straightforward changes with no need for another pass. Closing.
