### ISSUE TITLE
Doc Review: Datastore Options

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3331]

**Comment by andrewtchin** [comment]
lgtm, but i haven't touched this in a while

**Comment by fdawg4l** [comment]
https://github.com/vmware/vic/blob/90fae4fdf6c905d1bd1d1b0d337f7e118595b0f8/doc/user_doc/vic_installation/vch_installer_options.md#datastore

**Comment by fdawg4l** [comment]
I'm not sure of the use of "folder" in this section.  Is "folder" the preferred word for "directory" in the vsphere docs at large?

**Comment by fdawg4l** [comment]
No comments.  Looks fine to me!  LGTM.

**Comment by fdawg4l** [comment]
> No comments.

Actually thinking about this, examples I think would be helpful.

> You can specify a datastore folder to use as the image store in the format datastore_name/path. If the path to the folder that you specify does not already exist, vic-machine create creates it. In this case, vic-machine still creates the folder for the files of the VCH appliance and the key-value store at the top level of the datastore. However, vic-machine create creates the VIC folder inside the datastore_name/path folder, rather than in the same folder as the VCH files.

A few lines later, there are some examples.  We just need to include the result and I think that will clarify things.  How about the following

|  | command | result |
|-|-|-|
|Specify a datastore as the image store |```--image-store datastore_name```| <code><i>datastore_name</i>/VIC/<i>vch_uuid</i>/images</code> ; <code><i>datastore_name</i>/<i>vch_name</i></code> ;  <code><i>datastore_name</i>/<i>vch_name</i>/kvstores</code> |
|Specify a datastore folder as the image store|--image-store datastore_name/path|<code><i>datastore_name/folder</i>/VIC/<i>vcu_uuid</i>/images</code> ;<code><i>datastore_name</i>/<i>vch_name</i></code> ;  <code><i>datastore_name</i>/<i>vch_name</i>/kvstores</code>   |

**Comment by matthewavery** [comment]
No comments, LGTM.

**Comment by stuclem** [comment]
Thanks @andrewtchin, @matthewavery, and @fdawg4l 

@fdawg4l as much as I like your table, it wouldn't fit in with what I've done for all of the other options, and there's no time to do that now. But, I did include the resulting folders in bullets, and reorganized a bit. 

And yes, the vSphere docs use "folder" rather than "directory", since most vSphere admins are Windows folk rather than Mac/Linux monkeys.

Changes are in https://github.com/stuclem/vic/commit/a1e7f8464908c784fd8770e5c283010080bff29c.

If I can get a last LGTM from you @fdawg4l, I'll close this one. Thanks!

**Comment by fdawg4l** [comment]
Your changes look great!  LGTM.

**Comment by stuclem** [comment]
LGTMs from everyone. Closing.
