### ISSUE TITLE
Doc Review: Networking Examples

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#3334]

**Comment by hmahmood** [comment]
> the VCH uses the default VM Network for public network traffic.

"the VCH uses "VM Network" for public network traffic."

**Comment by hmahmood** [comment]
> A VCH supports a maximum of 3 distinct network interfaces. Because the bridge and container networks require their own distributed port groups, at least two of the public, client, and management networks must share a network interface.

Should say just "port groups", instead of "distributed port groups" to accommodate standalone ESX use case.

**Comment by hmahmood** [comment]
> you cannot set a static IP address on the management network.

I would add here that the ip specified with the `--public-network-ip` option will end up being the ip for the management network as well. The limitation is that they cannot use the `--management-network-ip` option; the ip address ends up being set implicitly for the management network via the `--public-network-ip` option.

**Comment by hmahmood** [comment]
> --container-network-gateway vic-containers:gateway_ip_address/255.255.255.0

Should be: `--container-network-gateway vic-containers:gateway_ip_address/24`

**Comment by mlh78750** [comment]
> You can direct the traffic between the VCH, container VMs, and the internet to a specific network by specifying the public-network option.

You can direct the traffic between the VCH (including container VM traffic routed through the VCH) and the internet to a specific network by specifying the public-network option.

**Comment by mlh78750** [comment]
> IMPORTANT: A VCH supports a maximum of 3 distinct network interfaces. Because the bridge and container networks require their own distributed port groups, at least two of the public, client, and management networks must share a network interface.

IMPORTANT: A VCH supports a maximum of 3 distinct network interfaces. Because the bridge network requires its own port group, at least two of the public, client, and management networks must share a network interface and therefore a port group.

**Comment by mlh78750** [comment]
> Sets a static IP address for the VCH endpoint VM on the public and client networks. Because the management network shares a network with the public network, you cannot set a static IP address on the management network.

Sets a static IP address for the VCH endpoint VM on the public and client networks. Because the management network shares a network with the public network, you only need to specify the public network IP. You cannot specify a management IP since you are sharing one port group for the management and public network.

**Comment by mlh78750** [comment]
> For example, the descriptive name appears as an available network in the output of docker info.

and docker network ls

**Comment by mlh78750** [comment]
Done with review.

**Comment by andrewtchin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @andrewtchin, @hmahmood and @mlh78750 !

- Replaced "default VM Network" with "VM Network" throughout the entire doc set.
- Replaced "distributed port group" with "port group" throughout the entire doc set when dealing with https://github.com/vmware/vic/issues/3327.
- Added "Because the management network shares a network with the public network, the management network uses the same IP address as the public network."
- Changed 255.255.255.0 to /24 for `--container-network-gateway` example.
- Added: "You can direct the traffic between the VCH and the Internet to a specific network by specifying the `--public-network` option. Any container VM traffic that routes through the VCH also uses the public network."
- Updated the 3 PGs note to "A VCH supports a maximum of 3 distinct network interfaces. Because the bridge network requires its own port group, at least two of the public, client, and management networks must share a network interface and therefore a port group. Container networks do not got through the VCH, so they are not subject to this limitation. This limitation will be removed in a future release."
- Added "Sets a static IP address for the VCH endpoint VM on the public and client networks. Because the management network shares a network with the public network, you only need to specify the public network IP address. You cannot specify a management IP address because you are sharing a port group between the management and public network."

Changes are in https://github.com/stuclem/vic/commit/1defe1a7b75ed7edaac6c22cadbff8ae2083846b.

I'd really appreciate another pass, at least of the diff above. Thanks!

**Comment by andrewtchin** [comment]
looks good. mike made a comment

**Comment by stuclem** [comment]
Thanks @andrewtchin, @hmahmood and @mlh78750.

Implemented @mlh78750 's comment.

Change is in https://github.com/stuclem/vic/commit/7b5a3da99bcb479c7928b1d3c776fbe99fefa289.

Closing.
