### ISSUE TITLE
Doc Review: Common vic-machine Options

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#3359]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/common_vic_options.md

**Comment by anchal-agrawal** [comment]
For this part in the section on `--id` (https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/common_vic_options.md#--id):

`This option is not used by vic-machine ls.`

It should say - "This option is not used by vic-machine **create and vic-machine version**."

`--id` is listed as an available option for `vic-machine ls`.

**Comment by chengwang86** [comment]
I agree with Anchal's comments and do not have additional comments.

**Comment by emlin** [comment]
hmm... Looks like the common options are also described in section https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#vsphere

You might want to consolidate them, otherwise the changes in that place need to be redo here.

**Comment by stuclem** [comment]
Thanks @anchal-agrawal, @chengwang86 and @emlin !

Fixed the `--id` option to state that it doesn't apply to `create` or `version`. However, I just ran `ls` with `--id` and it doesn't actually do anything:

```
Administrator@win2k8r2-0 MINGW64 /
$ vic-machine-windows ls --target 10.153.199.35 --user 'Administrator@vsphere.local' --password 'xxx' --thumbprint 12:A6:19:A5:BE:E6:68:EE:58:E6:DB:5B:C0:ED:32:17:C1:1B:15:48
INFO[2016-12-02T09:03:31+02:00] ### Listing VCHs ####
INFO[2016-12-02T09:03:31+02:00] Validating target

ID            PATH                                NAME                          VERSION
vm-404        /dc1/host/cluster1/Resources        virtual-container-host        v0.8.0-rc2-7234-191d796
vm-406        /dc1/host/cluster1/Resources        vch2                          v0.8.0-rc2-7234-191d796

Administrator@win2k8r2-0 MINGW64 /
$ vic-machine-windows ls --target 10.153.199.35 --user 'Administrator@vsphere.local' --password 'xxx' --thumbprint 12:A6:19:A5:BE:E6:68:EE:58:E6:DB:5B:C0:ED:32:17:C1:1B:15:48 --id vm-404
INFO[2016-12-02T09:03:44+02:00] ### Listing VCHs ####
INFO[2016-12-02T09:03:44+02:00] Validating target

ID            PATH                                NAME                          VERSION
vm-404        /dc1/host/cluster1/Resources        virtual-container-host        v0.8.0-rc2-7234-191d796
vm-406        /dc1/host/cluster1/Resources        vch2                          v0.8.0-rc2-7234-191d796
```
I felt sure that I had submitted an issue about this, but I can't find it.

Regarding consolidation of the common options in the Admin doc with their counterparts in the `vic-machine create` options in the Installation doc, my initial assumption was a) `vic-machine create` is so big that it deserves to be treated separately, and b) `vic-machine create` is where people will encounter these options for the first time, so they deserve to addressed in more detail in the context of `create`. Furthermore, `vic-machine create` is in the Install doc and `version`, `ls`, `delete`, `inspect ` (and `upgrade`, when we reintroduce it) are in the Admin doc. Finally, there's the question of tense: in `create`, we're talking about where you're going to deploy the VCH, but for the other commands we're talking about where you already deployed it. However, I have been wondering recently whether we actually need to have separate install and admin docs. But I think that it's too late to make such a major change this close to GA, because of the risk of breaking lots of links if I merge the two docs. 

So, in the meantime, I have done the following to the common options in Admin:

- Updated `--compute-resource` to remove "The ESXi host includes multiple resource pools"
- Added "If you obtain the thumbprint by other means, use upper-case letters and colon delimitation rather than space delimitation when you specify `--thumbprint`."

Changes are in https://github.com/stuclem/vic/commit/bc175432d4bf7ab77be64bb945c0185ab187fe11.

Marking as done, pending your LGTMs.

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by chengwang86** [comment]
LGTM

**Comment by chengwang86** [comment]
@stuclem I think https://github.com/vmware/vic/issues/3001 might relate to your concern about --id not functioning.

**Comment by stuclem** [comment]
@chengwang86 yes you're right - #3001 is the issue.

Just need an LGTM from @emlin before I close this one.

**Comment by emlin** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @emlin !
