### ISSUE TITLE
Doc review: Basic Deploy a VCH to a vCenter Server Cluster

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3361]
review https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/deploy_vch_vcenter.md

**Comment by emlin** [comment]
same to Deploy to ESXi, suggest to link user how to get vCenter's thrumbprint for following description:
```
If your vSphere environment does not use trusted certificates that have been signed by a Certificate Authority (CA), obtain the thumbprint of the vCenter Server or ESXi host certificate.
```

**Comment by emlin** [comment]
```
Because the vCenter Server instance only has one datacenter, one cluster, one network, and one datastore, vic-machine create automatically detects and uses these resources.
```
If the single network is not named with "VM Network", user will still need to specify public network name. So suggest to add that requirement in the network requirement, instead of say "for example"
```
One network, for example the default VM Network
```

**Comment by emlin** [comment]
```
vic-admin portal:
```
to 
```
VCH Admin Portal:
```

**Comment by stuclem** [comment]
Thanks @emlin. 

- Regarding the thumbprint, I link to the topic on obtaining the thumbprint from the **Result** section, so I deleted this bullet from the **Prereqs** section.
- For the network, changed the prereq to "The default VM Network and no other networks".
- Fixed "VCH Admin Portal" (thought that I had done that already :) )

Changes are in https://github.com/stuclem/vic/commit/e6f5d0d9590e57a73bbeb7d8e472e6c48761adb9. Are these OK? Thanks!

**Comment by mhagen-vmware** [comment]
Same comment on the ESX deploy on the PATH var

**Comment by mhagen-vmware** [comment]
On the prereqs, if the datastore is not a shared datastore then it will get tricky later on, better to define it as a shared on to make it easier.

**Comment by mhagen-vmware** [comment]
In the commands I think you need to specify the resource pool as the cluster and you need to specify which datastore you want to use ( preferably the shared one ^^^, otherwise you might pick the wrong datastore that is local to the ESX that the VCH doesn't end up on)

**Comment by mhagen-vmware** [comment]
Same comment from ESX deploy for thumbprint/force option

**Comment by emlin** [comment]
Same with #3354
otherwise, lgtm

**Comment by stuclem** [comment]
Thanks @emlin and @mhagen-vmware.

- Removed PATH, added force option, stated that VM Network must be present (deleted the bit about "no other networks".
- Added "A shared datastore, that is accessible by both of the ESXi hosts."
- Regarding specifying the `compute-resource`, the intention here is to keep things as simple as possible (per request from @karthik-narayan to provide very basic deployment examples). Since we state in the prereqs that VC should have one cluster and one DC, and since we state at the end of the procedure that `vic-machine` automatically selected the compute resources because there's only one of each, I vote against including `compute-resource` here. We have more advanced examples that include deploying to VC with multiple DCs, clusters, etc. in [Examples of Deploying a VCH](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md) that cover this (and that topic is linked to at the end of this one).
- Added `--image-store <i>shared_datastore_name</i>` to all three commands.
- Renamed the topic "Deploy a VCH to a Basic vCenter Server Cluster".
- Renamed the examples topic "Advanced VCH Deployment Examples"
- Moved the bit about wrapping things in quotes to before the examples.

Changes are in https://github.com/stuclem/vic/commit/8d326d937e0865937fdaeca8b60bcba1fd60a08c.

@karthik-narayan we just need a review from you and we can close this one. Thanks!

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Moving to Done, pending LGTM from @mhagen-vmware and review by @karthik-narayan.

**Comment by karthik-narayan** [comment]
LGTM!

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware and @karthik-narayan !
