### ISSUE TITLE
Doc review: Verify the Deployment of a VCH

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3364]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/verify_vch_deployment.md

**Comment by emlin** [comment]
```
If you deployed the VCH with either of the --no-tlsverify or --no-tls options, disable TLS in the Docker client.
set DOCKER_TLS_VERIFY=0
```
Tried in my deployment, but looks like if I installed with --no-tlsverify, I cannot export DOCKER_TLS_VERIFY=0, I need to leave DOCKER_TLS_VERIFY unset.
 @hickeng for confirmation.

**Comment by emlin** [comment]
```
vSphere Integrated Containers Engine creates a folder named VIC in which to store container image files.
```
Now the default image files are moved to docker endpoint vm directory, instead of datastore root directory. VIC is still created, and with same file structure with before. Just the root path is changed.

**Comment by emlin** [comment]
```
You should see a VM for every container that you run, including a VM named test.
```
Is this clear enough? The container vm is actually named as <container name>-<ID>.

**Comment by stuclem** [comment]
I confirm that you don't need to set `DOCKER_TLS_VERIFY=0`. Removed it from the doc.

Updated the container VM line to "You should see a VM for every container that you run, including a VM named <code>test-<i>container_id</i></code>."

Changes are in https://github.com/stuclem/vic/commit/7f5714347141e50e7f4c9fbcca1abbdde012009d. @emlin is this OK? Thanks!

**Comment by mhagen-vmware** [comment]
Prereqs: Deploy a VCH link is a dead link

**Comment by mhagen-vmware** [comment]
Step 2, just to be clear - I would add (option) to each of those command, i.e.

**Comment by mhagen-vmware** [comment]
Step 3 - don't really need busybox:latest on the pull. Just a bit of over complication here, I would just have them pull busybox

**Comment by mhagen-vmware** [comment]
Do we want to specify somewhere either here, or on another page that you can set DOCKER_HOST var in order to avoid having to type it every docker command?

**Comment by emlin** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks for the LGTM @emlin.

Thanks @mhagen-vmware:
- The link to the Deploy VCH to VC works for me. Maybe I fixed it and don't remember doing so. 
-  Re adding options for no TLS auth, this topic is supposed to be a follow-on from the two Deploy VCH examples, in which we specified `--no-tlsverify`, so if people used the commands in the previous two examples, then including `2376 --tls` is correct. Added "You ran `vic-machine create` with the `--no-tlsverify` option" to the pre-reqs. How the docker commands change depending on the TLS options that you used with `vic-machine create` is being documented elsewhere, with the TLS docs and in the app dev book. I did initially include commands for all three TLS options, but it cluttered up this topic. And @karthik-narayan  specifically requested a simple example to be followed to the letter, just so that people could get a simple VCH running.
- Removed `:latest` from BB
- Re setting DOCKER_HOST, that's covered in the App Dev book. Didn't think that vSphere Admins would be bothered.

Changes are in https://github.com/stuclem/vic/commit/ed876338a24f466ec1a20dfcf12555bc67f7ab30.

LGTY?

**Comment by emlin** [comment]
@stuclem Not sure who is reviewing the graph directories. But one minor issue is the external network is renamed to public network, but in there, external network is still used.

**Comment by stuclem** [comment]
@emlin yep, that's another thing that's on the list to do before GA!

**Comment by stuclem** [comment]
Need an LGTM from @mhagen-vmware before I close this one.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware !

**Comment by karthik-narayan** [comment]
LGTM
