### ISSUE TITLE
Doc review: Advanced Resource Management Options

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3370]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#adv-mgmt

**Comment by emlin** [comment]
>Limit the amount of memory that is available for use by the VCH appliance and container VMs. Specify the memory limit value in MB. If not specified, vic-machine create sets the limit to 0 (unlimited).

> A folder named VIC inside the VCH folder. The VIC folder contains a folder that uses the UUID of the VCH endpoint VM as its name.

The "VCH appliance" and "VCH endpoint VM" is mixed used in this installer options document, do we need to unify them?

**Comment by emlin** [comment]
Do we have any wehere to describe the resource limitation and reservation will be the resource limitation of vch vApp or vch resource pool in vsphere? Feels like that will help vsphere customers to understand these resource management options.

**Comment by emlin** [comment]
>NOTE Use the --cpu option instead of the --appliance-cpu option. 

Feels confused for this suggestion. Will this be more clear? 
``` NOTE Use the --cpu option instead of the --appliance-cpu option for VCH resource management? ```

>The --appliance-cpu option is mainly intended for use by VMware Support.

Where comes this suggestion? I think user still need to use large vcpu and memory to download large images in GA, cause we're writing image files into memory first. @hickeng to confirm

**Comment by stuclem** [comment]
Thanks @emlin. 

- I have removed all mentions of "appliance", except for in the `--appliance-mem/cpu` option names. Where we are referring to the VCH as a whole (i.e. the vApp on VC, or the RP on ESX) we use "VCH". Where we are referring to the VM inside the vApp/RP, we use "VCH endpoint VM" (incidentally, this gives us the situation where the `--appliance-mem/cpu` options modify the cpu/memory on the endpoint VM, and the `--cpu-xxx`/`--memory-xxx` options modify the memory/cpu on the whole VCH. I opened https://github.com/vmware/vic/issues/2760 about this a while ago.
- Added something along the lines of "Set memory shares on the VCH vApp in vCenter Server, or on the VCH resource pool on an ESXi host.  This limit also applies to the container VMs that run in the VCH vApp or resource pool." to each of the `--memory` and `--cpu` options. The --appliance-xxx options already state that they apply to the endpoint VM. I think that this clarifies things, https://github.com/vmware/vic/issues/2760 notwithstanding.
- The notes about not using the `--appliance-xxx` options came about because @hickeng doesn't really want people messing about with the endpoint VM settings. He (I believe) only wants people to adjust the settings for the vApp/RP. @hickeng please confirm!

Changes are in https://github.com/stuclem/vic/commit/eb0d90da16b7fbba3bffd9dfdd09e7ed775dc4e6 and https://github.com/stuclem/vic/commit/c6d151da0d32a47fbfc52c668401617284e7a555

Leaving this one in progress, pending response from @hickeng and review by @dougm.

**Comment by dougm** [comment]
LGTM @stuclem .  Would be great if we could link to vCenter docs on this topic for more details, in particular for the concept of "shares".

**Comment by stuclem** [comment]
Thanks @dougm. Added the following at the beginning of the section: "You can set limits on the memory and CPU shares and reservations on the VCH. For information about memory and CPU shares and reservations, see [Allocate Memory Resources](https://pubs.vmware.com/vsphere-65/topic/com.vmware.vsphere.vm_admin.doc/GUID-49D7217C-DB6C-41A6-86B3-7AFEB8BF575F.html), and [Allocate CPU Resources](https://pubs.vmware.com/vsphere-65/topic/com.vmware.vsphere.vm_admin.doc/GUID-6C9023B2-3A8F-48EB-8A36-44E3D14958F6.html) in the vSphere documentation."

Change is in https://github.com/stuclem/vic/commit/518bedd1537a8ddb668fd052185c9773d7d528c1.

Now we just need an answer from @hickeng to the question about the `--appliance-xxx` options above before we close this one.

**Comment by hickeng** [comment]
@stuclem emma is correct that larger images may need customers to increase the appliance memory in this release - I cannot think of any reason why a customer would need to adjust the appliance-cpu options however.

> memory in the VCH VM

should this be VCH endpoint VM? I suggest noting that `--appliance-memory` may need to be adjusted if pulling large images and keeping the pointer to `--memory` for the overall VCH limit and the `docker create -m` for individual containers.

**Comment by stuclem** [comment]
Thanks @hickeng. Updated as follows:

### `--appliance-cpu ` ###

Short name: none

The number of virtual CPUs for the VCH endpoint VM. The default is 1. Set this option to increase the number of CPUs in the VCH VM, for example if the VCH will handle large volumes of containers, or containers that require a lot of processing power.

**NOTE** Use the `--cpu` option instead of the `--appliance-cpu` option to increase the overall CPU capacity of the VCH vApp, rather than on the VCH endpoint VM. The `--appliance-cpu` option is mainly intended for use by VMware Support.

<pre>--appliance-cpu <i>number_of_CPUs</i></pre>

### `--appliance-memory ` ###

Short name: none

The amount of memory for the VCH endpoint VM. The default is 2048MB. Set this option to increase the amount of memory in the VCH endpoint VM if the VCH will pull large container images.

**NOTE** With the exception of VCHs that pull large container images, always use the `--memory` option instead of the `--appliance-memory` option to increase the overall amount of memory for the VCH vApp, rather than on the VCH endpoint VM. Use docker create -m to set the amounts of memory on container VMs. The `--appliance-memory` option is mainly intended for use by VMware Support.

Change is in https://github.com/stuclem/vic/commit/93f09fae6e693729500138b93d5beb87ccf4326b.

Last LGTM before closing?

**Comment by cgtexmex** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks!
