### ISSUE TITLE
Doc review: Other Advanced Options

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3373]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#adv-other

**Comment by emlin** [comment]
> --bridge-network-range 192.168.100.0/24

This sample is wrong. User cannot use subnet mask smaller than 16, suggest to use 12 or larger subnet. #3227

**Comment by emlin** [comment]
> The size of the base image from which to create other images. You should not normally need to use this option. Specify the size in GB or MB. The default is 8GB.

It will be better to describe the base image is provisioned in thin provisioning model, so normally does not consume this many spaces.

**Comment by emlin** [comment]
> Provide verbose logging output, for troubleshooting purposes when running vic-machine create

Debug does not only debug vic-machine create. It will set debug level in vch services, container initialization service, tether. So it will impact the whole product verbosity of logging, and larger number means more information. @hickeng for more details

**Comment by stuclem** [comment]
Thanks @emlin !

- Added "The smallest subnet that you can specify is 16" to `--bridge-network-range`.
- Added "Images are thin-provisioned, so they do not usually consume 8GB of space" to `--base-image-size`.
- Added "Deploy the VCH with a more verbose level of logging, for troubleshooting purposes. Specifying the `--debug` option increases the verbosity of the logging for all aspects of VCH operation, not just deployment. For example, by setting `--debug`, you increase the verbosity of the logging for VCH initialization, VCH services, container VM initialization, and so on." 
- Added information from https://github.com/vmware/vic/issues/852 in `--debug`: "For example, setting `--debug` to 2 or greater automatically enables SSH access to the VCH endpoint VM. Setting `--debug` to 3 suppresses the restart of failed components." I do feel that this is very incomplete, though. I would really like to obtain a proper list of what each logging level does, but that question is the subject of https://github.com/vmware/vic/issues/852, rather than this review issue.

Changes are in https://github.com/stuclem/vic/commit/a48f8746a3f2bf23cf48597435b2c26962aeb8df.

Moving to Done pending LGTMs from @emlin and @hmahmood.

**Comment by emlin** [comment]
lgtm 👍

**Comment by stuclem** [comment]
Thanks @emlin. Now I just need an LGTM from @hmahmood.

**Comment by hmahmood** [comment]
> The smallest subnet that you can specify is 16.
should say /16

**Comment by stuclem** [comment]
Thanks @hmahmood. Done.

Change is in https://github.com/stuclem/vic/commit/518bedd1537a8ddb668fd052185c9773d7d528c1.

Closing.
