### ISSUE TITLE
Doc review: Interoperability of vSphere Integrated Containers Engine with Other VMware Software

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3379]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_admin/interop.md

**Comment by mhagen-vmware** [comment]
Not sure what you mean by:
You do not require a native agent on the ESXi host.

**Comment by mhagen-vmware** [comment]
The appliance VM does not need to be running for vMotion to occur.  for vmotion to occur *on the containers* ?

**Comment by mhagen-vmware** [comment]
The VCH maintains filesystem layers inherent in container images by mapping to discrete VMDK files, all of which can be which can be housed in shared vSphere datastores, including vSAN and NFS datastores.

Too many 'of which can be'

**Comment by mhagen-vmware** [comment]
The VCH maintains filesystem layers inherent in container images by mapping to discrete VMDK files, all of which can be which can be housed in shared vSphere datastores, including vSAN and NFS datastores.

and iSCSI datastores.

**Comment by hickeng** [comment]
vMotion: impacted by https://github.com/vmware/vic/issues/3243

Multiple VLAN - is this really something we need to tell people? If it is I think the phrasing needs to change as I can only guess at the specific scenario we're claiming to support.

Features not supported:
- powering container VMs on and off, or the endpoint VM, should work without issue. The only aspect I'm aware of is that powering off a containerVM may result in an incorrect end-time

**Comment by stuclem** [comment]
Thanks @mhagen-vmware and @hickeng !

- "You do not require a native agent on the ESXi host." Not sure what this means either, or where it came from. Deleted.
- Added "on the container VMs" to the vMotion section.
- Fixed the double "which can be".
- Added iSCSI
- https://github.com/vmware/vic/issues/3243 looks like a release note issue rather than core doc, so added kind/note to that issue.
- The Multiple VLAN section came from https://github.com/vmware/vic/issues/2935. Delete it?
- Moved the stuff about powering off/on into a new section, as this isn't really a feature and it doesn't belong in the unsupported list.
- The vRealize info was pure marketing guff, so replaced it with a paragraph copied from the App Dev book: "You can use VMware vRealize Automation to provide a self-provisioning service for VCHs, by using the vRealize Automation interface or APIs to request VCHs. At the end of such a provisioning process, vRealize Automation can communicate the VCH endpoint VM address to the requester." This blurb was suggested by @mreferre.
- Deleted the first para of the vMotion section as it had nothing to do with VIC Engine. 

Changes are in https://github.com/stuclem/vic/commit/a8dd0495f019322c1d2d6cf9e7bb74650561bc13. Updated topic is here: https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_admin/interop.md

Would benefit from another pass.

**Comment by hickeng** [comment]
@stuclem delete the multiple VLAN section - it's so basic it should be assumed.

**Comment by stuclem** [comment]
Done. Am taking this as an LGTM, so closing. Thanks @hickeng !
