### ISSUE TITLE
Doc Review: Overview for vSphere admins

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3403]
https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/introduction.md

**Comment by corrieb** [comment]
OK. George and I both came to the conclusion that we need to largely re-write this section. It needs to convey more information in a manner that's easy to skim through. We don't need to create too much content from scratch, but the first place to start is a summary of what we want to convey.

**Scope and target audience**

This is specifically for vSphere admins, so it needs to cover all the bases such as:
- What is this thing? What will it do to my system? What are the main concepts I need to understand? What are the benefits for me and my users?
- Many admins struggle with the basics of containers, so we may want to start from first principles before we dive into VIC concepts.
- It shouldn't touch on any of the internals such as the Port Layer and Tether.

**Comment by stuclem** [comment]
Thanks @corrieb and @hickeng. Yes, I am aware that this section needs a total rewrite. It is marked **NOT READY YET** in the Review Status column of the doc review wiki. I have https://github.com/vmware/vic/issues/2512 open for this, and I'll use your points above as a guide.

**Comment by corrieb** [comment]
@stuclem. I've written the section for you and got George to review it. It includes a basic "what is a container" section that we may want to put somewhere else.

Feel free to edit the style etc. Since it's such a major change, I'm going to create a pull request

**Comment by corrieb** [comment]
@stuclem see the PR I just created. Happy to make changes if you want to delegate or you can take it from here.

**Comment by stuclem** [comment]
The merge closed this one, so reopening.

**Comment by stuclem** [comment]
I have made an editorial pass over @corrieb's new version, for style and presentation. I wish that I had had access to this doc a year ago :)

I also created a truncated version for container developers, for inclusion in the Developing Container Applications with VIC doc. 

Changes are here: https://github.com/stuclem/vic/commit/5680a42f1e2e2bdc5fb38c3d6a87ef256a2905ad

Or, if you would rather see the whole topics:

- [Overview of vSphere Integrated Containers for vSphere Administrators](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md)
- [Overview of vSphere Integrated Containers Engine For Container Application Developers](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/overview_of_vic_engine.md)

I integrated @hickeng's comments from https://github.com/vmware/vic/issues/3383. These are in https://github.com/stuclem/vic/commit/cd47f7267fb52fcd5f03c865405fd93f94870c07. 

I'd really appreciate another pass, including from @karthik-narayan and @mreferre.

@hickeng, regarding your comment "_I know it's likely because of trademark rules or somesuch, but the reuse of vSphere Ingrated Container Engine makes the documentation really awkward to read - can we not use an acronym, or just reword to avoid the name of the product where ever possible?_" You're absolutely right. We are not allowed to use acronyms because of trademarking rules. Furthermore, editorial guidelines dictate that we must avoid the passive because it causes problems in translation.We can't just say "things are done". We have to say "X does things". When X is a 4 word product name, it gets wordy.

**Comment by mlh78750** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#runtime last para. 
Any that a container writes is non-persistent
should be 
Any data that a container writes is non-persistent

**Comment by mlh78750** [comment]
https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#packaging might point to Harbor as an example of registry at the end of this para.

**Comment by mlh78750** [comment]
@corrieb Very nice job on this. LGTM from me.

**Comment by cgtexmex** [comment]
Some minor suggestions / questions -- hope my editing format makes sense.  :) 

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#packaging
States:
As long as you have a destination that is running a container engine, for example Docker, 
and a compatible kernel ABI, you can download and run an image on it.

Suggest:
drop ABI -- doubt many vi Admins could identify that acronym 

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#what-does-vsphere-integrated-containers-engine-do

**Scenario 1**

States:
In this scenario, what you have given to the is user something like a nested hypervisor that they have to manage and which is opaque to you.

Suggest:
In this scenario, what you have provided is similar to a nested hypervisor that they have to manage and which is opaque to you.

**Scenario 2**

States:
You set aside a certain amount of storage, networking, and compute on your cluster by using a tool called vic-machine.

Question:
Is this a forward looking statement?  It is my understanding that vic-machine does nothing with regards to quotas or limits on storage.


States:
In this scenario, you have provide the user with a service portal.

Suggest:
In this scenario, you have provided the user with a service portal.

States:
It is better for you because every container that the user spins up is a VM known as a container VM.

Suggest:
It is better for you because every container that the user deploys is a known container VM.

States:
With vSphere Integrated Containers Engine in Scenario 2, you can perform a simple 
reconfiguration that is completely transparent to the user.

Question:
Forward looking statement?

https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#virtual-container-hosts

States:
A virtual container host (VCH) is the virtual functional equivalent of a Linux VM that runs Docker, but with some significant benefits

Suggest:
A virtual container host (VCH) is the functional equivalent of a Linux VM that runs Docker, but with some significant benefits

States:
A an isolated Docker API endpoint. (3rd bullet point)

Suggest:
A isolated Docker API endpoint

States:
There is no local image cache. This is kept on a datastore somewhere in the cluster.

Suggest:
There is no local image cache. This is kept on a datastore in the cluster specified by you.  ( or some reminder that they configure this on appliance deployment)

**Comment by stuclem** [comment]
Thanks @mlh78750 and @cgtexmex! 

Fixed all of the typos (won't enumerate here). Changes are in https://github.com/stuclem/vic/commit/3927531f0af67ec7b0c4a0c1fa42f7edfcb627ef.

I'm not sure what to do about @cgtexmex 's questions below, but had a go at resolving them:

- "You set aside a certain amount of storage, networking, and compute on your cluster by using a tool called vic-machine." Question from @cgtexmex: "Is this a forward looking statement? It is my understanding that vic-machine does nothing with regards to quotas or limits on storage."  Reworded as follows: 
  - You set aside a certain amount of storage, networking, and compute on your cluster. 
  - You use a utility called `vic-machine` to install a small appliance. The appliance represents an authorization to use the infrastructure that you have assigned, into which the user can self-provision container workloads.
- "With vSphere Integrated Containers Engine in Scenario 2, you can perform a simple
reconfiguration that is completely transparent to the user." Question from @cgtexmex: "Forward looking statement?" Reworded as follows:
  - "With vSphere Integrated Containers Engine in Scenario 2, you can redeploy the VCH with a new configuration in a way that is completely transparent to the user."

Some questions from me:
- We don't mention the VCH endpoint VM. Is the section [The vSphere Integrated Containers Engine Appliance](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/introduction.md#the-vsphere-integrated-containers-engine-appliance) actually talking about the endpoint VM?
- Did anybody look at the truncated version for container developers that I included in the app dev doc? [Overview of vSphere Integrated Containers Engine For Container Application Developers](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/overview_of_vic_engine.md). I carried over the comments above that were relevant into this topic.

More changes are in https://github.com/stuclem/vic/commit/999a82bc53f85f2badb7030448620c74dd1e229c.

**Comment by mlh78750** [comment]
@stuclem  Yes. The Engine Appliance is the same as the endpoint VM.

**Comment by hickeng** [comment]
@stuclem There is no storage quota currently - if storage quotas are needed then the viadmin needs to create a datastore specifically for this use and size it appropriately. I do not know if that's viable with vSAN.

**Comment by corrieb** [comment]
This has edited together beautifully. LGTM

**Comment by corrieb** [comment]
WRT to @cgtexmex comments forward-looking statements above.

The statement on "certain amount of" could be construed to mean number of datastores, rather than specific amounts of a particular datastore. Personally I don't read it to suggest quotas. For a high-level perspective, I think it's fine unless anyone strongly objects.

With respect to reconfiguration of a VCH resource limits, you can do that today through the vCenter client. Obviously we will support modification via vic-machine soon. Docs tend to stick around long enough that again, I don't think we need to hedge here.

**Comment by corrieb** [comment]
@stuclem I modified the Wiki to show TBD for @cgtexmex @hickeng and @mlh78750 on https://github.com/stuclem/vic/commit/999a82bc53f85f2badb7030448620c74dd1e229c. You should all give it a once-over to make sure that you think the subset is sufficient.

**Comment by stuclem** [comment]
Thanks @corrieb, @mlh78750 and @hickeng. 

- Changed "appliance" to "VCH endpoint VM", since that's the terminology that we agreed upon.
- Regarding storage quotas and whatnot, I replaced "assign" with "identify" and changed "storage" to "datastores":
  - You identify datastores, networking, and compute on your cluster that the user can use for their Docker environment. 
  - You use a utility called `vic-machine` to install a small appliance. The appliance represents an authorization to use the infrastructure that you have identified, into which the user can self-provision container workloads.
- Regarding reconfiguration, reworded as follows:
  - With vSphere Integrated Containers Engine in Scenario 2, you can reconfigure the VCH in vSphere, or redeploy the VCH with a new configuration in a way that is completely transparent to the user.

Changes are here: https://github.com/stuclem/vic/commit/c6b55725288c6d2ddad05c8893228b0d67939f54

@mlh78750, @cgtexmex and @hickeng if we can get LGTMs on [Overview of vSphere Integrated Containers Engine For Container Application Developers](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/overview_of_vic_engine.md) then I think that we can close this out. Thanks again!

**Comment by stuclem** [comment]
Fixed the typo "If you discover than you need..." in https://github.com/stuclem/vic/commit/4389a77a43c05eca2e89f4198cdeecd661bbb3d3.

**Comment by cgtexmex** [comment]
LGTM

**Comment by stuclem** [comment]
Thanks @cgtexmex !

**Comment by mlh78750** [comment]
lgtm

**Comment by karthik-narayan** [comment]
LGTM

**Comment by stuclem** [comment]
Good enough for me. Closing.
