### ISSUE TITLE
Restarting VC changes moIDs - needs code review and testing

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3490]
We learned recently that we cannot depend on moIDs of vSphere objects being consistent over time. If VC is restarted, the moIDs can change. 

We're likely caching moIDs in Port Layer hashtables and may also be caching them in guestInfo. We'll likely need a trigger for cache rehydration and also need to review any persistence of moIDs anywhere.

**hickeng update**
How is vCD managing this issue for Virtual Datacenters?

**Comment by hickeng** [comment]
We were explicitly using IDs because we were told that customers expect to be able to rename inventory objects and have things continue to work.

I'm unsure how we could reconcile these requirements.
@dougm I don't know if there's anything that can be done here - if the inventory folder work leads you to anything applicable please could you note it here.

**Comment by mdubya66** [comment]
This is not a stop ship for 1.1.

**Comment by hickeng** [comment]
@mdubya66 I think we need a separate label for stop ship/urgency or severity - this is a potentially severe issue and dropping it into the mix of medium priority items loses that differentiation.

**Comment by hickeng** [comment]
bumping to high for 1.2 work and tentatively adding to project.

**Comment by mhagen-vmware** [comment]
this needs to be estimated before it is ready for the backlog and as it looks more feature like than bug like we need details (user statement/details/acceptance criteria) on how we want to accomplish this and a plan moving forward for this story

**Comment by mdubya66** [comment]
i'm not sold on this being high, which is why i've bumped it down. let's keep it medium

**Comment by hickeng** [comment]
@mhagen-vmware this is investigation - I've literally zero idea how long it'll take to come up with a solution so setting it to 8. This is not a feature, this adds no capabilities.
@mdubya66 I'm not sold on this being medium - that's why it was high, we currently have zero workaround other than delete and redeploy.

**Comment by mhagen-vmware** [comment]
8 sounds good, so let's make this an Epic then and peel off a research spike to figure out what we want to do here then?

**Comment by dougm** [comment]
My suggestion for step 1 would be stop using mo-refs and use names (or paths) everywhere.

Then instead of 0 workarounds, user has the workaround to change the name back to what it was (until we have vic-machine reconfig).

Also seems more likely for a VC upgrade/restart to happen than for admins to be renaming existing datastores, networks, etc.

In the process, we can document where mo-refs are currently used and in a separate issue look at how we can properly handle resource re-names without having to use vic-machine reconfig in a separate issue.

**Comment by zjs** [comment]
Closing as moids may change in some cases, but are not known to change as a result of a VC restart.
