### ISSUE TITLE
vic-machine should be able to take env vars for common params

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3531]
Being able to set username, password, target and thumbprint as env vars would make vic-machine usage so much more pleasant. 

As an example, going from 
> vic-machine ls
> vic-machine info --name=<name>

... is so much cleaner if all the common options are implied.

**Comment by mhagen-vmware** [comment]
User statement: As a customer of VIC, it would be nice if VIC also took environment variables options for some of the common parameters that are used, so that it would be faster and easier to deploy,upgrade,delete,etc a VCH

Details: vic-machine should probably just check whether env var is set and use it other look for the command line option.  I am estimating assuming this is fairly easy to do within our current arch.

Acceptance Criteria:
1. vic-machine allows for any combination of env var or explicit args on execution
2. New test is created that exercises this behaior
