### ISSUE TITLE
Bogus --opt input values on volume create are ignored

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#3535]
This led to the weird situation where I created a volume using the --opt capacity=4gb flag and it created a 1GB volume. Why? Because I didn't capitalize "capacity". Equality, entering --opt bogus=bogus successfully creates a volume with no warning.

This may be a limitation of the Docker client, but I'd like to at least return a warning of some kind that the option wasn't understood

**Comment by matthewavery** [comment]
The proposed solution here is that we should be more tolerant of our arguments. i.e. "Capacity", "capacity", "CaPaCiTy". this should be doable by checking that we only got 2 args from the user since we only accept 2 for now. Then we will filter through those and lower case them to make sure they are a recognized arg. Then pass those to the portlayer as they are being passed now.
