### ISSUE TITLE
ImageStore operation is super slow

### ISSUE THREAD

**Issue by thefallentree** [vmware/vic#3574]
Hi,

I am using a iscsi backed datastore for image , I setup VCH with no issue, pulled 2 images (~10 layers total) and restarted VCH,  the VCH takes about 10minutes to start , blocking on imageStore operations.

And when deleting VCH, it takes even longer to delete all the files from datastore.

It is simply way too slow

**Comment by thefallentree** [comment]
On a newly created VCH that have 1 image "ubuntu" pulled.

```
time="2017-01-05T20:43:03Z" level=info msg="found 1 repositories" 
time="2017-01-05T20:43:03Z" level=info msg="found 1 image layers" 
time=2017-01-05T20:43:03.574968113Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.NewRepositoryCache:131] [2.791035ms]  
time="2017-01-05T20:43:03Z" level=info msg="Repository cache updated successfully" 
time=2017-01-05T20:43:03.575628189Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [3.041885ms] images 
time=2017-01-05T20:43:03.576453028Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.InitializeImageCache:75] [3.889459ms]  
time="2017-01-05T20:43:03Z" level=info msg="Image cache initialized successfully" 
time=2017-01-05T20:43:03.576977103Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [4.629658ms] layers 
time=2017-01-05T20:43:03.577295356Z level=debug msg=[ END ] [github.com/vmware/vic/lib/imagec.InitializeLayerCache:68] [4.973627ms]  
time="2017-01-05T20:43:03Z" level=info msg="Layer cache initialized successfully" 
time="2017-01-05T20:43:03Z" level=info msg="Container cache updated successfully" 
time="2017-01-05T20:43:03Z" level=info msg="Creating image store" 
```
NOTE here that it takes an solid 2 minutes to finish "creating image store" and start up.

```
time="2017-01-05T20:45:14Z" level=info msg="TLS enabled" 
time="2017-01-05T20:45:14Z" level=info msg="Client verification enabled" 
```

**Comment by mdubya66** [comment]
without the logs there is no way for us to tell what is causing this delay. Also, more details on the iSCSI setup would be needed. please attach the logs from the vicadmin portal.

**Comment by mdubya66** [comment]
please attach the logs from this VCH See https://vmware.github.io/vic-product/assets/files/html/0.8/vic_admin/log_bundles.html for instructions on gathering them from the VCH Admin portal

**Comment by thefallentree** [comment]
[logs.zip](https://github.com/vmware/vic/files/690986/logs.zip)

Here's the log bundle, the VCH instance takes 5 minutes to startup and function, there is just a few images in it.

**Comment by fdawg4l** [comment]
Odd. This operations generally complete on the order of seconds. What device is the iscsi lun backed by? I'll look st the logs and get back to you if there is something obvious there. But, it would be helpful if you could describe the topology you're installing the VCH onto.

**Comment by thefallentree** [comment]
It was a 42disk raid10 freenas setup, which itself it is pretty fast.

**Comment by fdawg4l** [comment]
```

**Comment by fdawg4l** [comment]
Yep, 5m an image.  That's waaaaay tooo sloooowwww...

So in that operation (`GetImage`), all we're doing is `stat`'ing some files and walking a directory tree.  The amount of `I/O` per image found is on the order of < 1k.  

Are you using Virtual Center?  If so, can you see any alerts related to storage performance?  Also do you have other VMs on this host also with suspiciously slow IO throughput?

**Comment by thefallentree** [comment]
No, nothing is running on that data store. Actually the vch has no mounted
disk, how was it doing the stat and disk ops? Through which esxi? Might
that be a problem?

**Comment by fdawg4l** [comment]
> Actually the vch has no mounted disk, how was it doing the stat and disk ops?

The VCH VM doesn't mount any disks on startup, just on `docker pull`.  We stat by way of the ESX APIs.  Essentially, the VCH uses the VMOMI API to ask the host to stat the files for the VCH.  That way, the VCH itself is out of the IO path on startup.  If you're using VC, the host stating the files can vary.  If you aren't using VC, then the host configured when installing the VCH is the one servicing requests.

Just to level-set, can `docker run ubuntu` on that VCH.  I know it will be slow, but once running, can we try `dd`'ing a file to see how long it takes?

```
root@98d51eaaa928:~# time dd if=/dev/zero of=~/empty count=10240 bs=8024
10240+0 records in
10240+0 records out
82165760 bytes (82 MB) copied, 0.0622657 s, 1.3 GB/s

real    0m0.066s
user    0m0.000s
sys     0m0.060s
```

That's what I see using a container VM with an SSD backed datastore without iscsi.  I want to rule out iSCSI LUN performance being the bottleneck.

**Comment by thefallentree** [comment]
i have tested the store with at least 2k ops and ~70mbps random io
bandwidth , it is not fast. But it is not slow like this.

I am using vc and there is a lot of esxis connected to this store , so it
may be scheduling. Stay on a lot of random esxis?

In any case it seems very inefficient to have request proxy to vc and to
esxi and back, are all of your testing done with single esxi? That would
seems to be faster.

**Comment by fdawg4l** [comment]
> it seems very inefficient to have request proxy to vc and to esxi and back. 

It's not a proxy exactly. It's an API constraint we have to live with. The datastore doesn't have a VFS one can make remote operations on. And VC clusters require VC to do all arbitration of operations in order to do things like load balancing and scheduling. Without vfs, this is the constraint we designed for. 

We test and develop with iscsi backed datasores, nfs, and vsan. 

I'm still curious as to your iscsi performance. Can you try the dd test I copied above and paste the results.

**Comment by fdawg4l** [comment]
> i have tested the store with at least 2k ops

Do you mean IOPS?  If so, that's actually kinda low even for a single spindle.

**Comment by fdawg4l** [comment]
> i have tested the store with at least 2k ops

To be clear, that's still more than enough for VIC and enumerating images like we are at startup.  5m is still way too long.  Very eager to see the result of `dd` in a container using that datastore.

**Comment by thefallentree** [comment]
![image](https://cloud.githubusercontent.com/assets/1256464/21785041/d3422b42-d672-11e6-9a09-7ec1bbd895ff.png)

**Comment by corrieb** [comment]
I took this on because I also have a FreeNAS iSCSI store in my personal lab. Apologies that no progress has been made in a couple weeks. We've just grown the team and it's been a busy time. I am keen to get to the bottom of this though. Thanks for your patience.

I'm assuming that the datastore for containers, volumes and images is the same datastore in this scenario? From the logs it seems like it took 3 seconds to read the KV JSON, 10 seconds to refresh the Volume store (which I assume is empty) and 90 seconds to verify the image store.

The dd test you ran is inconclusive IMHO, because it wasn't forced to go to disk. If I run dd in my own Ubuntu container per above, I get 1.7GB/s, but there's no way my iSCSI drive has this bandwidth. Instead, if I run:

```
root@1fc50e50a813:/# time dd if=/dev/zero of=~/empty count=10240 bs=8024 conv=fsync
10240+0 records in
10240+0 records out
82165760 bytes (82 MB, 78 MiB) copied, 1.43152 s, 57.4 MB/s

real	0m1.445s
user	0m0.020s
sys	0m1.160s
```
That's much more realistic. It's actually forcing a write to the datastore. If you have a moment, it would be great to repeat this experiment so that we can get at true sense of the I/O bandwidth.

The logs don't really have enough detail for us to know how many Stat calls we made or how long they took. If the above proves inconclusive, a good next step would be to eliminate VIC completely and just stat something on the Datastore using govc directly and see how long it takes. If we can replicate with that, then we should dig into vSphere logs and see what's going on.

Again, thanks for sticking with this.

**Comment by corrieb** [comment]
Actually a simple test would be simply to go to the Datastore browser in the VC client. Find the datastore you selected, select the "Manage" tab, the Files button and start browsing in /<vchname>/VIC/<ID>/images/<imageid>. Does it seem responsive? in displaying the folder contents of images? No guarantee, but this is almost certainly doing the same Stat calls.

**Comment by corrieb** [comment]
@thefallentree Did your problem go away? Keen to continue working on this if you are.

**Comment by corrieb** [comment]
Suggest we close this unless we're able to re-open comms with the originator
