### ISSUE TITLE
Whitelist Container Registries

### ISSUE THREAD

**Issue by mrchrispo** [vmware/vic#3586]
**Story**
As an administrator of a VCH I would like to be able to restrict where images can be obtained from during VCH deployment

**Details**
This will specifically deal with `pull` as the image acquisition mechanism, not import/load/et al. As such this issue is about restricting registries that may be used as image sources for a given VCH.
Registry whitelist will be specified by a vic-machine list option `--whitelist-registry` taking the following values:
* IP address
* FQDN

`vic-machine` should confirm that at least one registry is accessible with the supplied configuration - i.e. certificate validation succeeds using public or `--registry-cas`, or registry is specified as insecure.
If `vic-machine` cannot connect to the specified registries a warning should be given that the configuration could not be validated.

**Acceptance**
- [ ] `pull` from a whitelisted registry succeeds, whether FQDN, IP, or shortname is used (latter may require DNS search suffix: #2582) - assumes appropriate registry TLS IPSANs, etc.
- [ ] `pull` from a non-whitelisted registry fails, whether FQDN, IP, shortname, IPv6 addr, etc.
- [ ] `pull` from an "insecure" whitelisted registry succeeds only if registry is also listed via `--insecure-registry`
- [ ] vic-machine reports an error if no registry can be verified
- [ ] if no whitelist is specified, pulls from secure registries succeed and pulls from insecure registries fail without `--insecure-registry`
- [ ] scenario doc for restricting to:
  - only docker hub
  - only harbor
  - _other probable scenarios_

Related: #2582 

**Original request**
To ensure use only of approve registries, would it be possible to allow whitelisting of registries in VIC Engine? This would allow VIC Engine and Harbour to be setup in a private, corporate environment, and then restrict access in VIC Engine to images in the local Harbour registry only.

Something similar has has been implemented in OpenShift (https://docs.openshift.com/enterprise/3.2/install_config/install/docker_registry.html#whitelisting-docker-registries)

**Comment by hickeng** [comment]
#151 is the high level issue for adding this capability. Adding this as a sub issue for initial pass at whitelisting only.

There are a variety of ways in which whitelisting can be phrased which work well in static or pre-defined environments where the registry is long lived:
1. IP/hostname
2. FQDN wildcard match

For more dynamic environments (and also static) we could consider:
3. subnet mask (not IP, just the mask)
4. maximum hops (TTL)

And for complete flexibility, but requires TLS configuration during deployment:
5. certificate based auth

@mrchrispo (1), (2), and (5) are the simplest to implement - do those meet your specific scenario if you have one?

**Comment by mhagen-vmware** [comment]
@mrchrispo Can you clarify whether 1,2,5 are enough for your needs  - so that we can estimate and prioritize this work?

**Comment by hickeng** [comment]
Estimated at a 5 to encompass:
* vic-machine changes - some thought required:
  - should be whitelist by default. Should error if no registryca's, or insecure-registry arguments are specified - error message should provide the argument to disable whitelist behaviour.
  - we could use --registry-ca as a whitelist identifier, but it can identify a set of registries if the same CA is used. We could use this anyway and people can provide the actual server certificate as a CA (I _think this works, but needs checking) to identify individual registries - this is actually a very solid approach, but would require proper delegate certificate authorities, and might require the desired groupings to be know when certs are generated.
  - if we need to specify ip/fqdn for a secure registry (i.e. the option above is insufficient), what flag do we use? `--registry-tls-cname` - keep it in line with the other cert based options? Should this then accept domain wildcards? ip subnets - this would allow pulling from a registry running in a container on the bridge, which might be of interest?
  - how to disable the default whitelist behaviour? `--disable-registry-whitelist`?
* imagec changes
  - need to check set of permitted registries against specified registry in pull command
  - simple direct check instead of being clever with resolving FQDN to IPs and visa versa?
* testing
  - positive testing - can still connect when target is specified in any/multiple of the available formats.
  - negative testing - cannot connect when target is not present in any format.
  - disabling whitelisting - allows negative tests to succeed if they're 'secure' (i.e. signed by common root CA), still doesn't allow insecure if not explicitly identified

**Comment by hickeng** [comment]
Dropped from inclusion in notary support by PM request

**Comment by sflxn** [comment]
Here's my thoughts on vic-machine options:

1. registry-ca is really a modifier on registries so I don't think we should use that for white list.  Registry CA certs can be used for both white list and non-white list registries.
2. For symmetry, we can call the secure white list registry --secure-registry since insecure registries can also be used while the VCH is in white list mode.  We can use that option to turn on/off white list mode.

**Comment by sflxn** [comment]
Some thoughts on reachability testing.  For whitelist registries that don't intersect with insecure registries, we cannot assume the CA certs passed into vic-machine are enough.  There is going to be a gap here.  If the whitelisted registry is a secure registry that uses public certs, we will have to either use the system certs or force users to pass in public certs.  If we rely on system certs, we may run into some trouble if the certs on the system that they run vic-machine on has additional correct certs that our photon vm does not.

**Comment by sflxn** [comment]
When testing if the specified insecure and whitelist registry are actually valid, I'm not sure whether we should remove the invalid server from the appropriate list or just inform the user.  Currently, I'm just informing the user.  If the registry is offline at the moment but will be back online later, we probably shouldn't prevent it from being used.  The login and pull code will also check the validity of the server again later.

**Comment by sflxn** [comment]
@stuclem This is a new feature and will require user documentation.  I'm writing up a design doc with info on how this works so you can use that as a starting point.

**Comment by stuclem** [comment]
Thanks for the headsup @sflxn

**Comment by sflxn** [comment]
There's a PR out for it now.  The robot scripts I wrote is under manual tests for now as these tests adds 30mins.  The design doc is in @stuclem .
