### ISSUE TITLE
port-layer: support in memory data migration for container configuration

### ISSUE THREAD

**Issue by emlin** [vmware/vic#3610]
As a user, I want to upgrade VCH to a newer version, and leave existing container in old version. If I need newer version's container, I will recreate new container, which should be in newer version. So that I get similar workflow with vanilla docker.

**Comment by emlin** [comment]
In this case, Portlayer need to support backward compatibility after VCH is updated. 
Cause old container is not updated, the newer configuration can only be consumed in portlayer memory, instead of write back to container configuration.

**Comment by emlin** [comment]
move back to high cause this need to be done in next sprint

**Comment by matthewavery** [comment]
Upon  talking more with @emlin it looks like we must check for migration when the container cache is synced and when new handles are created. Additionally we must abandon configs that have actual changes during the commit phase. Which means that on older versioned containers we will probably only support `start` and `stop` operations for controlling the container runtime. The spirit of this ticket is that we need to make sure that all in memory ExecConfigs must be checked for migration and migrated if possible. But we must also preserve the truth of what the containerVM is in vsphere since that is the operation model. If we allow a commit to a container of an older version and its config changes in vsphere there is a good possibility that the older container may be broken forever.

**Comment by matthewavery** [comment]
Passing this on to @emlin. The initial pr I opened for this ticket is now referenced here and closed. We have catalogued the additional changes needed and decided that this change is less trivial than previously thought. @emlin has my notes on this issue.
