### ISSUE TITLE
Add find by name support to govmomi inventory Finder

### ISSUE THREAD

**Issue by dougm** [vmware/vic#3620]
As a customer, I want to specify existing resources by name to vic-machine so I do not need to specify the full inventory path.

Inventory resource types specified as options to vic-machine include:

* Datacenter

* Datastore

* ResourcePool

* Network

* ComputeResource

When running vic-machine against ESX or VC without inventory folders, these resources can be specified by their name.  However, in the case of VC where existing resources live within inventory folders, vic-machine requires the resources to specified by inventory path.  For example, as an absolute path:

```
/my-folder1/datacenter1/host/my-clusters/cluster1
```

Or relative to the datacenter host folder:

```
my-clusters/cluster1
```

However, the vic-machine suggestions do not recurse into inventory folders.  In any case, customers expect to be able to specify resources by name, 'cluster1' in this case.  This has come in a number of times in gomvomi/govc as well.

Acceptance Criteria:

1. govmomi Finder tests against vcsim Model demonstrating find by-name for resources within inventory folders

2. govc tests where existing commands, such as {vm,host,datastore,etc}*.info are able to find resources by-name within inventory folders

In both cases, the following examples current work:
```
"/Datacenter-Name/vm/Folder-Name/VM-Name" // absolute path

"Folder-Name/VM-Name" // relative to "/Datacenter-Name/vm"

"*/VM-Name" // wildcard path
```

However using just the resource name, `"VM-Name"`, does not work.

**Comment by dougm** [comment]
Most of the changes should be within the govmomi finder package and tests.  Unknown if there are any assumptions within vic-machine that would require additional changes.

**Comment by emlin** [comment]
How this vic-machine command will look like? For example, one option is to add the folder into target option before datacenter e.g. 10.172.0.1/folder/dc1.
This might becomes sth back and forth, so raise this question here before we actually start to work on it.

**Comment by dougm** [comment]
I've already started working on it, but just within the govmomi Finder.  As I mentioned above, not expecting vic-machine to need changes yet.

**Comment by emlin** [comment]
Currently, the resource path of vic-machine is most likely to be relative, and datacenter is supposed to be in target option, instead of in resource path.
that's why I mentioned to have folder embedded in target is one option, if do not add one more option, e.g. --folder

For #3619, I assume there is no directly impact from the command line.

**Comment by dougm** [comment]
@emlin not sure what you mean.  If you read the description of this issue, we are talking about at least 5 different resource types (including the datacenter itself), all of which can be within different folders.  So, we can't have a single folder name within the target, nor can we have a single '--folder' option.  We just want to be able to find these resources by name rather than path, regardless of what folder they live in.  Along with listing suggestions within folders, which we don't currently do.

Regarding #3619, we do require vic-machine command line option changes to specify which folder container VMs are created in for example.  Currently they are created in the Datacenter top-level vm folder,  a new option is required to specify a different folder.

**Comment by emlin** [comment]
Well, what I want to do is to clarify how the command line will look like, and how to use it from user perspective, cause that usually take time to discuss during implementation.
And the resource specification is the most confusing part in vic-machine command, I'd like to see the assumption is clearly described in this issue, that's why I have those commends.

Based on your response, I figured out following changes:
1. --target option will have dc folder specified, e.g. "vc ip"/folder/dc, and it's also possible to be "vc ip"/dc (even the dc is under folder), but is "vc ip"/folder valid? In which case, there is only one dc in that folder.
2. --compute-resource, with same reason, it will be folder/cluster, folder/rp (in case there is only one cluster in that folder), cluster, or cluster/rp, four possible format. Is that right?
3. The storage options. It already have a format as datastore/path, and it's ok to leave path empty, but this change, it will vary as well. User might specify folder/datastore/path, folder/datastore, or datastore/path. 
4. network options are usually only name specified, that is easy in this change.

**Comment by emlin** [comment]
> Regarding #3619, we do require vic-machine command line option changes to specify which folder container VMs are created in for example. Currently they are created in the Datacenter top-level vm folder, a new option is required to specify a different folder.

got it. It also will help if there is command option for that, thanks

**Comment by dougm** [comment]
@emlin I'll rename the subject of this issue to just focus on the govmomi Finder changes, I had tried to call that out in this comment: https://github.com/vmware/vic/issues/3620#issuecomment-273319559

Again, the focus for this issue it to support finding resources by name, without specifying the folder.  The govmomi Finder already supports finding by path (folder/name).

If you can create a separate issue in this epic for vic-machine changes we may need to support both cases, that'd be great.  I thought vic-machine already supported finding resources by path.

**Comment by emlin** [comment]
Thought you've split all tasks related to this folder, so add comments here. 
The issue is added, but set to low priority cause it depends on this issue. Feel free to update that.
