### ISSUE TITLE
Investigate how to measure code coverage for integration tests

### ISSUE THREAD

**Issue by dougm** [vmware/vic#3631]
As a developer, I want to measure code coverage when running integration tests so I can find gaps that are not currently covered.  Having coverage for integration tests will also help to prioritize where to improve both unit test and integration test coverage.

**Comment by mdubya66** [comment]
#2938 for reference

**Comment by mdubya66** [comment]
Harbor is using this for every merge, https://coveralls.io/builds/9742425

**Comment by hmahmood** [comment]
This approach seems promising: https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests

**Comment by hmahmood** [comment]
I tried out the approach outlined in https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests for the port-layer-server binary. Results/recommendations:

1. Command used to build: `go test -c -coverpkg github.com/vmware/vic/lib/...,github.com/vmware/vic/pkg/...` . This resulted in a binary size of ~56MB, compared to without coverage enabled -- ~22MB.
2. Built appliance iso with this modified binary, run an install withe `vic-machine create`. Since the test binary for the port layer now requires extra arguments to run the test, the port layer failed to launch. Used govc to modify guestinfo to set required documents, per: 
```
govc vm.change -e "guestinfo.vice./init/sessions|port-layer/cmd/Args~=/sbin/port-layer-server|--host=localhost|--port=2377|--systemTest|--test.outputdir=/tmp|--test.coverprofile=coverage.out" -vm virtual-container-host
govc vm.change -e "guestinfo.vice./init/sessions|port-layer/cmd/Args=5" -vm virtual-container-host
```
3. Logged in to the VCH and restarted `vic-init` to start the port layer. Ran `kill -TERM <port layer pid>` to gracefully shutdown the port layer so that it would dump the coverage data. 
4. Retrieved the coverage file from `/tmp/coverage.out` on the VCH.

Overall this process can be repeated for each of our binaries, namely `docker-personality`, `port-layer-server`, and `vic-init`. The coverage output files can be merged into one file to post to `coverage.vmware.run`; this is outlined in the link above. All of these steps were done manually for this spike, and automating them as part of our CI process will the next step.
