### ISSUE TITLE
Research spike: Investigate which compose commands do not work with current docker personality

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3635]
As a user of VIC, I need to know which docker compose commands work and which do not.
As a user of VIC, I need to know what will and will not work in compose yaml files with VIC.

We need to survey all the compose commands, environment variables, and compose file syntax and come up with a list of

1) What works and what doesn't
2) For what doesn't work, what does the personality server need to make it work
3) New issues to plan for the work in completing compose support.

**Comment by mhagen-vmware** [comment]
Needs an estimate please @sflxn

**Comment by chengwang86** [comment]
Here is a brief summary of what docker-compose cmds work under vic:

| cmd  | description | support (cli parameters not tested)
| ------------- | ------------- | ------------- |
| build  | Build or rebuild service  | no; need docker build  |
| bundle  | Generate a Distributed Application Bundle (DAB) from the Compose file.  | no; need RepoDigests from docker inspect {image}  |
| config  | Validate and view the compose file  | yes  |
| create  | Create services  | yes  |
| down  | Stop and remove containers, networks, images, and volumes  | yes  |
| events  |	Receive real time events from containers  | no; need docker events  |
| exec  | Run commands in services. Equivalent of docker exec.  | no; need docker exec  |
| help  | Get help on a command  | yes  |
| kill  | Kill containers  | no, albeit docker kill works under vic. Need to investigate  |
| logs  | View output from containers  | yes  |
| pause  | Pause services  | no; need docker pause  |
| port  | Print the public port for a port binding  | 	yes  |
| ps  | List containers  | conditional; need --filter  |
| pull  | Pulls service images  | yes  |
| push  | Pushes images for service  | no; need docker push  |
| restart  |	Restart services  | yes  |
| rm  | Remove stopped containers  | yes  |
| run  | Run a one-off command  | yes  |
| scale  | Set number of containers for a service  | no; need --filter  |
| start  | Start services  | yes  |
| stop  | Stop services  | yes  |
| unpause  | Unpause services  | no; need docker unpause  |
| up  | Create and start containers  | conditional; does not work if there are orphan containers; need  docker rename and --filter  |
| version  | Show the Docker-Compose version information  | yes  |

**Comment by sflxn** [comment]
Talked to Karthik.  He is not interested in bundle support yet.

**Comment by sflxn** [comment]
Updated #380 and moved to backlog to address next sprint work to design docker rename.

**Comment by sflxn** [comment]
We won't be supporting docker build for 1st quarter.  This support may get delayed till the containerd migration.  At that point, we simply leave build to docker daemon.

**Comment by sflxn** [comment]
I have looked into the docker-compose kill issue.  We're not handling ContainerKill with sig==0.  docker-compose kill fails but running plain docker kill successfully kills the container.

**Comment by chengwang86** [comment]
Summary of compose cli env

| cli env  | description | support |
| ------------- | ------------- | ------------- |
| COMPOSE_PROJECT_NAME or -p  | Sets the project name  | yes  |
| COMPOSE_PROJECT_NAME or -p  | Sets the project name  | yes  |
| COMPOSE_PROJECT_NAME or -p  | Sets the project name  | yes  |
| COMPOSE_PROJECT_NAME or -p  | Sets the project name  | yes  |
| COMPOSE_PROJECT_NAME or -p  | Sets the project name  | yes  |

**Comment by chengwang86** [comment]
| top-level key 	| config options                                                                                                                                                                                                                                                            	| support                                                                                                                                                                                                                                  	|
|---------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| services      	|                                                                                                                                                                                                                                                                           	| yes                                                                                                                                                                                                                                      	|
|               	| build                                                                                                                                                                                                                                                                     	| no                                                                                                                                                                                                                                       	|
|               	| cap_add, cap_drop                                                                                                                                                                                                                                                         	| no; need docker run --cap-add --cap-drop                                                                                                                                                                                                 	|
|               	| command                                                                                                                                                                                                                                                                   	| yes                                                                                                                                                                                                                                      	|
|               	| cgroup_parent                                                                                                                                                                                                                                                             	| no; need docker run --cgrop_parent                                                                                                                                                                                                       	|
|               	| container_name                                                                                                                                                                                                                                                            	| yes                                                                                                                                                                                                                                      	|
|               	| deploy                                                                                                                                                                                                                                                                    	| no (only used when deploying to a swarm but ignored by docker-compose up/run)                                                                                                                                                            	|
|               	| devices                                                                                                                                                                                                                                                                   	| no; need docker create --device                                                                                                                                                                                                          	|
|               	| depends_on                                                                                                                                                                                                                                                                	| yes                                                                                                                                                                                                                                      	|
|               	| dns                                                                                                                                                                                                                                                                       	| yes                                                                                                                                                                                                                                      	|
|               	| dns_search                                                                                                                                                                                                                                                                	| no; need docker run --dns-search                                                                                                                                                                                                         	|
|               	| tmpfs                                                                                                                                                                                                                                                                     	| no; need docker run --tmpfs                                                                                                                                                                                                              	|
|               	| entrypoint                                                                                                                                                                                                                                                                	| no; need docker run --entrypoint                                                                                                                                                                                                         	|
|               	| env_file                                                                                                                                                                                                                                                                  	| yes                                                                                                                                                                                                                                      	|
|               	| environment                                                                                                                                                                                                                                                               	| yes                                                                                                                                                                                                                                      	|
|               	| expose                                                                                                                                                                                                                                                                    	| no; need docker run --expose                                                                                                                                                                                                             	|
|               	| extends                                                                                                                                                                                                                                                                   	| yes                                                                                                                                                                                                                                      	|
|               	| external_links                                                                                                                                                                                                                                                            	| no; need docker rename since there must be existing (orphan) containers to link with                                                                                                                                                     	|
|               	| extra_hosts                                                                                                                                                                                                                                                               	| no; need docker run --add-host                                                                                                                                                                                                           	|
|               	| group_add                                                                                                                                                                                                                                                                 	| yes                                                                                                                                                                                                                                      	|
|               	| healthcheck                                                                                                                                                                                                                                                               	| no; need docker run --health-cmd                                                                                                                                                                                                         	|
|               	| image                                                                                                                                                                                                                                                                     	| yes                                                                                                                                                                                                                                      	|
|               	| isolation                                                                                                                                                                                                                                                                 	| no; need docker run --isolation                                                                                                                                                                                                          	|
|               	| labels                                                                                                                                                                                                                                                                    	| yes                                                                                                                                                                                                                                      	|
|               	| links                                                                                                                                                                                                                                                                     	| yes                                                                                                                                                                                                                                      	|
|               	| logging, log_driver, log_opt                                                                                                                                                                                                                                              	| no; need docker run --log-driver and --log-opt                                                                                                                                                                                           	|
|               	| net                                                                                                                                                                                                                                                                       	| yes                                                                                                                                                                                                                                      	|
|               	| network_mode                                                                                                                                                                                                                                                              	| yes                                                                                                                                                                                                                                      	|
|               	| networks                                                                                                                                                                                                                                                                  	| yes                                                                                                                                                                                                                                      	|
|               	| aliases                                                                                                                                                                                                                                                                   	| yes                                                                                                                                                                                                                                      	|
|               	| ipv4_address,ipv6_address                                                                                                                                                                                                                                                 	| yes for ipv4; no for ipv6 (vic does not support ipv6)                                                                                                                                                                                    	|
|               	| link_local_ips                                                                                                                                                                                                                                                            	| no; need docker run --link-local-ip                                                                                                                                                                                                      	|
|               	| pid                                                                                                                                                                                                                                                                       	| no; need docker run --pid                                                                                                                                                                                                                	|
|               	| ports                                                                                                                                                                                                                                                                     	| yes                                                                                                                                                                                                                                      	|
|               	| userns_mode                                                                                                                                                                                                                                                               	| no; err msg: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.12.0 or greater                                                                          	|
|               	| volumes,volume_driver                                                                                                                                                                                                                                                     	| no                                                                                                                                                                                                                                       	|
|               	| volumes_from                                                                                                                                                                                                                                                              	| no                                                                                                                                                                                                                                       	|
|               	| security_opt, stop_grace_period, stop_signal, sysctls, ulimits, userns_mode, cpu_shares, cpu_quota, cpuset, domainname, hostname, ipc, mac_address, mem_limit, memswap_limit, oom_score_adj, privileged, read_only, restart, shm_size, stdin_open, tty, user, working_dir 	| yes if its docker run counterpart is supported                                                                                                                                                                                           	|
| volumes       	|                                                                                                                                                                                                                                                                           	| no; need shared volume support                                                                                                                                                                                                           	|
| networks      	|                                                                                                                                                                                                                                                                           	| yes                                                                                                                                                                                                                                      	|
|               	| driver                                                                                                                                                                                                                                                                    	| yes                                                                                                                                                                                                                                      	|
|               	| driver_opts                                                                                                                                                                                                                                                               	| no                                                                                                                                                                                                                                       	|
|               	| enable_ipv6                                                                                                                                                                                                                                                               	| no; vic does not support ipv6                                                                                                                                                                                                            	|
|               	| ipam                                                                                                                                                                                                                                                                      	| no; bug: some of the information is missing from docker network inspect and docker inspect                                                                                                                                               	|
|               	| internal                                                                                                                                                                                                                                                                  	| no; bug: if "internal: true" in compose file, docker inspect network would show "internal: false".                                                                                                                                       	|
|               	| labels                                                                                                                                                                                                                                                                    	| no (although servers:labels are supported). This is added after version 2.1. Err msg: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.12.0 or greater 	|
|               	| external                                                                                                                                                                                                                                                                  	| yes                                                                                                                                                                                                                                      	|

- For syntax introduced in version 2.1, docker-compose on vic would show error msg:  **The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.12.0 or greater**, even if the docker engine I use is 1.12.3.

- Most of the config options need support from their counterparts in docker run.

**Comment by sflxn** [comment]
@stuclem This issue might be useful for documentation.  It's a work in progress.

**Comment by sflxn** [comment]
To clarify, @chengwang86 was referring to the compose 2.1 format.

**Comment by sflxn** [comment]
At this point, the deliverable for this research spike are the issues I mentioned above.  @chengwang86 will write up issues for the networking bugs he listed for the compose file format and this spike should be concluded.

**Comment by mhagen-vmware** [comment]
lgtm
