### ISSUE TITLE
Investigate the VSAN nightly test failure

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#3652]
Currently, the VSAN tests are failing intermittently due to the nested nature of the nimbus deployment.

**Comment by mhagen-vmware** [comment]
most of the failures got overwritten because of:
#3725

but from what I can see this is not a nested problem at all, the problem is that VSAN complex builds out a multi-vc multi-datastore setup.  And from the looks of it, we might have a bug in vic-machine or govc. Because this line:
```
govc ls -t Datastore host/cluster-vsan-1/* | grep -v local | xargs -n1 basename | sort | uniq | grep vsan
```

Should ensure we don't get this error  (which we ended up with):
```
[31mERRO[0m[2017-01-20T04:24:31Z] Datastore "vsanDatastore" is not accessible by the compute resource 
```

**Comment by mhagen-vmware** [comment]
Alright, at this point I have modified our validator code in vic-machine to print some additional details and I am blasting the VSAN tests over and over again to try to repro.  I am leaning towards a problem within our validator code/govmomi that doesn't correctly verify write access to datastores under some scenarios.
