### ISSUE TITLE
Reporting VCH stats

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#3656]
As a user of Admiral, I should be able to see CPU and memory information for a VIC VCH.

Outstanding questions to be answered before work starts:
1. where should this data be presented and in what form (docker info is one option)
3. what resources should be included:
  a. cpu & memory - is it an issue if we report MHz for cpu or should it be translated into vCPU counts?
  c. disk? per datastore? per volume store?
  d. network IO metrics?
4. limits on cpu & memory are easy, but how should be present priority? i.e. over-commit behaviours

**Comment by igorstoyanov** [comment]
>where should this data be presented and in what form (docker info is one option)
- Having this data in the Docker Info will be great. 

>. cpu & memory - is it an issue if we report MHz for cpu or should it be translated into vCPU counts?
It should be similar to Docker Stats for Containers - CPU, Mem, .... MHz is preferable. 

>what resources should be included:
- CPU & Memory 


>c. disk? per datastore? per volume store?
CPU & Memory are needed right now. Anything else like disk, network IO ... could be nice but not needed right now.

**Comment by chengwang86** [comment]
1. Based on my discussion with @sflxn , we need to determine whether we want to provide the VCH stats to Admiral from (a) docker info, or (b) vic-machine or vicadmin. As of now it seems like we prefer (a) since it would a neat interface between Admiral and vic engine. However, (b) might be a more general option if Admiral want to support other container runtime (not just docker) in the future.

2. For the VCH stats, does Admiral want to obtain the resource usage/limits of the VCH itself (applianceVM) or those of the resource pool that is used to allocate containers created via this VCH? I think the latter makes more sense.

**Comment by igorstoyanov** [comment]
>2. For the VCH stats, does Admiral want to obtain the resource usage/limits of the VCH itself (applianceVM) or those of the resource pool that is used to allocate containers created via this VCH? I think the latter makes more sense.

Definitely, the latter. We need the usage/limits for the resource pool that is used to allocated containers. 


>1.... a) docker info, or (b) vic-machine or vicadmin.

For Admiral, the easiest would be docker-info. We can access only rest api and use the Docker Host client cert as authentication. vic-machine is command line where we don't access. vicadmin - not sure what this is but probably we wan't have credentials.
