### ISSUE TITLE
Add copyright to robot files

### ISSUE THREAD

**Issue by jzt** [vmware/vic#3660]
Our test files, both `.robot` and `.md` are missing copyrights. We need to add copyrights to these, and add the robot files to the copyright checker script.

**Comment by mhagen-vmware** [comment]
User statement: All files created by vmware need to have copyright notice on them.

Details:  The robot files need it not the md files, as none of the other md files have it. Need to mod the 

Acceptance criteria:
1. All robot files have a copyright notice
2. The build script checks all robot files for the copyright so that future robot files cannot be made without the copyright
