### ISSUE TITLE
Combination of vendor supplied server certificate and docker self-generated Docker client certificates

### ISSUE THREAD

**Issue by trinhv** [vmware/vic#3745]
Hello :),

**User Statement:**

I have a case with a customer where he would like to use the combination of server certificate from a vendor for its VCH web site, docker endpoint with the docker self-generated client certificates.

**Details:**
He used these vic-machine options to deploy the VCH : 

```
  --tls-cname                "virt-vic-$name-lab.andrew.local.cmu.edu"
  --tls-ca                "$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_interm.cer"
  --cert                "$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_cert.cer"
  --key                        "$certpath/virt-vic-$name-lab.key"
```

By reading the code from here (https://github.com/vmware/vic/blob/master/cmd/vic-machine/create/create.go line 649), he found out that when he provides the "--tls-ca" option, client certificate generation is disabled as the second argument "client" to generateCertificates() will always be set to flase because the "cas" varible contains all CAs given via the "--tls-ca" option : 

c.generateCertificates(keypair == nil, !c.noTLSverify && len(cas) == 0)

However, if he doesn't provide the intermediate and signing certs with the option "--tls-ca", he gets these logs warnings.

```
INFO[] Loaded server certificate /Users/jackson/vic-certs/virt-vic-storvirt-lab_andrew_local_cmu_edu_cert.cer 
DEBU[] Unable to locate existing CA in cert path
```

and the deployment fails with an error and these related messages (timestamps removed for clarity):

```
time= level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:709] 
DEBU[] Loading CAs for client auth                  
time= level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] 
time= level=debug msg=[ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [245.653µs]  
DEBU[] Loading CAs for client auth                  
DEBU[] Checked VIRT-VIC-STORVIRT-LAB.ANDREW.LOCAL.CMU.EDU., no match for host cert 
DEBU[] Checked W.X.Y.Z, no match for host cert 
WARN[] Unable to determine address to use with remote certificate, skipping API liveliness checks 
DEBU[] Assigning certificates for client auth       
DEBU[] connection refused                           
DEBU[] Components not yet initialized, retrying     
DEBU[] Unhandled net error type: x509.HostnameError{Certificate:(*x509.Certificate)(0xc4201c3200), Host:" W.X.Y.Z"} 
time= level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:709] [1.936117385s]  
time= level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:171] 
time= level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:171] [8.354µs]  
ERRO[] --------------------                         
ERRO[] vic-machine-darwin failed: x509: cannot validate certificate for W.X.Y.Z because it doesn't contain any IP SANs

```

**Work around from the customer:**

He runs the "vic-machine create" without the --tls-ca, then "vic-machine delete" to clean up from the failed installation, putting the vendor CA certs at the end of <name>/ca.cer, then running "vic-machine create" again.

**My analyse:**

At first sight, I thought the VCH failed because the customer specified a CIDR in its network options as I remember this issue https://github.com/vmware/vic/pull/2553 where we can find the same error message at the end of the deployment.
`ERRO[]` vic-machine-darwin failed: x509: cannot validate certificate for  W.X.Y.Z because it doesn't contain any IP SANs`
But it is not as I checked the customer vic-machine create command.

As far as I understand by reading the documentation, isn't a logical behavior as the self-generated client certificates are signed by a CA generated by the vic-machine and not by the CA he provides with the --tls-ca ? Would it explain why his workaround works as he pastes directly the cert on the client system ?

I did read documentation about certification in general, and the different security options for the VCHs. But still don't really feel confident about this topic, I would appreciate your help.

**Deployment details:**

```
./vic-machine-darwin create \
  --debug		1 \
  --name		"$name"-vch \
  --timeout		10m0s \cd
  --target		"vc-lab.andrew.local.cmu.edu/$datac" \
  --user		administrator@vsphere.local \
  --appliance-iso	appliance.iso \
  --bootstrap-iso	bootstrap.iso \
  --compute-resource	"$cluster" \
  --tls-cname		"virt-vic-$name-lab.andrew.local.cmu.edu" \
  --cert		"$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_cert.cer" \
  --key			"$certpath/virt-vic-$name-lab.key" \
  --registry-ca		"$certpath/virt-vic-harbor_andrew_local_cmu_edu_cert.cer" \
  --image-store		"$imagestore/$name" \
  --volume-store	"$volumestore/${name}:default" \
  --bridge-network	"virt-vic-$name" \
  --client-network	cyh-233-lab-priv \
  --public-network	cyh-233-lab-pub \
  --management-network	cyh-233-lab-priv \
  --container-network	"$contnet1" \
  --container-network	"$contnet2" \
  --container-network	"$contnet3" \
  --container-network	"$contnet4" \
  --container-network	"$contnet5" \
  --ops-user		vic-vch-user@vsphere.local \
  --dns-server			 W.X.Y.Z \
  --dns-server			 W.X.Y.Z \
  --public-network-ip		"virt-vic-$name-public-lab.andrew.cmu.edu" \
  --public-network-gateway	 W.X.Y.Z/XX \
  --management-network-ip	"virt-vic-$name-lab.andrew.local.cmu.edu" \
  --management-network-gateway	 W.X.Y.Z/X: W.X.Y.Z/XX \
  --http-proxy			http://proxy:XXXX \
  --bridge-network-range	"$bridgenet"

```

Many thanks for your help.

**Comment by mdubya66** [comment]
@hickeng please triage

**Comment by stuclem** [comment]
Adding myself here as this is a potentially interesting subject for the docs.

**Comment by mhagen-vmware** [comment]
@hickeng Please switch this to high if you think this could end up being a critical/immediate issue.

**Comment by hickeng** [comment]
@trinhv 

Apologies for the delay, didn't see this until this morning. What's the urgency on getting this addressed given there's a workaround?

**Assumption**
The host certificate does not have the IP as the CommonName, but either:
* the CommonName is the FQDN, or
* the FQDN is present in a DNSname subjectAltName

**Actions**
There's two code issues to be fixed:
- [ ] Instead of using a new CA pool, we should be using [pool.SystemCertPool](https://golang.org/pkg/crypto/x509/#SystemCertPool) so that the CA for the vendor signed host certificate is available: https://github.com/vmware/vic/blob/master/lib/install/management/dispatcher.go#L268
- [ ] We should blindly switch to using the Host Certificate CommonName, or perform a deeper check for the presence of subjectAltName's, when we cannot determine which address type to use. That would go in the error path here: https://github.com/vmware/vic/blob/master/lib/install/management/appliance.go#L786

While we have code in the API liveliness check to note `x509.UnknownAuthorityError` as a warning if we didn't have the Host Certificate CA available, we have to report the basic validation failure as an error as it's likely due to flawed or incorrect certificates. We need to ensure that we're hitting the UnknownAuthorityError case.
Should add regression tests for use of 3rd party certs in this manner:
- [ ] when vendor CA is in system pool
- [ ] when vendor CA is _not_ in system pool

**Notes**
The correct usage for this deployment would be: `-cert vendor-signed.cert -key vendor-signed.key --tls-cname="virt-vic-$name-lab.andrew.local.cmu.edu"` and in this case the following debug output (that was seen) would be expected:
```
INFO[] Loaded server certificate /Users/jackson/vic-certs/virt-vic-storvirt-lab_andrew_local_cmu_edu_cert.cer 
DEBU[] Unable to locate existing CA in cert path
```
While this will result in an error output the VCH should be fully functional if using `DOCKER_HOST=VIRT-VIC-STORVIRT-LAB.ANDREW.LOCAL.CMU.EDU:2376` and the vicadmin server should be up and running with the vendor signed cert

**Comment by hickeng** [comment]
@andrewtchin You may want to look at #3946 as well as the test criteria overlap significantly with this.
