### ISSUE TITLE
Document the docker compose commands that currently don't work

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3762]
Per https://github.com/vmware/vic/issues/3635. This definitely deserves a big table in the developer doc.

**Comment by stuclem** [comment]
@chengwang86, I have added the table of `docker compose` commands from https://github.com/vmware/vic/issues/3635 in https://github.com/stuclem/vic/blob/08-docs/doc/user_doc/vic_app_dev/container_operations.md#compose. 

I'm unncertain about the following: 

- `docker-compose ps`, `scale`, `up`. Is the `--filter` that they depend on the `docker ps --filter` option?
- `top` is not included in the table in https://github.com/vmware/vic/issues/3635
- Which version of compose are we supporting? 1.11?
- I assume that we also need to document the Compose File options from https://github.com/vmware/vic/issues/3635#issuecomment-275496609.

**Comment by chengwang86** [comment]
@stuclem Re: your questions:

- yes, I think they need "docker ps --filter". This may have been fixed by Clint's PR in Sprint 2. But I need to verify that and update my doc if needed.
- I did my research spike three weeks ago based on 1.10.0. At that time 1.11 was not released yet. But based on their release notes, they fixed some bugs and provided the new "top" command. So it shouldn't affect what I reported in the research spike. For the "top" command, I need to try it on vic and update my doc.
- I think it will be good if we can document the Compose File options support on vic. But then we need to update it every time when we add new feature support or fix existing bugs related to these compose file options.

**Comment by stuclem** [comment]
@chengwang86 thanks for the answers. 

- I should have made clearer that the updates I have made today are for 0.8 (I have a backlog of issues and want to update the 0.8 docs, since that's the only "official" version so far. I'll update the table to remove the dependency on filter when I update the docs for 0.9 in master.
- So, in the 0.8 docs, should I state that we support docker-compose 1.10?
- I agree that the compose file options should be documented. It's not a problem to update the table as we add support for options. That's what we do with the main docker commands tables.

Thanks!

**Comment by chengwang86** [comment]
@stuclem Yes for 0.8 docs, we should say we support compose 1.10, since 1.11 was not released at that time yet.

**Comment by stuclem** [comment]
OK, thanks for confirming @chengwang86

**Comment by stuclem** [comment]
@chengwang86 I made the requested updates. Changes are in https://github.com/vmware/vic/pull/3947/commits/3639a107df717daf6938cccb95d2373a6e24e122.

**Comment by stuclem** [comment]
I'll add the compose file options in another commit.

**Comment by stuclem** [comment]
Moving back to In Progress for the compose file options

**Comment by stuclem** [comment]
See https://github.com/vmware/vic/issues/4023 for the list of supported versions of the compose file.

**Comment by stuclem** [comment]
@chengwang86 now that we support `docker events` and `docker ps --filter`,  can we claim support for the following docker compose commands in VIC Engine 0.9?

- `docker compose events`
- `docker compose ps`
- `docker compose scale`

**Comment by stuclem** [comment]
Added new topic that includes the table of Compose file options: 
https://github.com/stuclem/vic/blob/docker/doc/user_doc/vic_app_dev/docker_compose_file_options.md

The following options were included in the Docker docs but are not in the table in https://github.com/vmware/vic/issues/3635#issuecomment-275496609. 

- [securityopt](https://docs.docker.com/compose/compose-file/compose-file-v2/#securityopt)
- [stopgraceperiod](https://docs.docker.com/compose/compose-file/compose-file-v2/#stopgraceperiod)
- [stopsignal](https://docs.docker.com/compose/compose-file/compose-file-v2/#stopsignal)
- [sysctls](https://docs.docker.com/compose/compose-file/compose-file-v2/#sysctls)
- [ulimits](https://docs.docker.com/compose/compose-file/compose-file-v2/#ulimits)

@chengwang86 do we need to add them?

Also, for the big bunch of `docker run` type options, your table says that they are supported if their `docker run` counterpart is supported. Looking at [Supported Docker Commands](https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_app_dev/container_operations.md), we only claim support for  `docker run --name`, `--detach`, `--detach-keys`, and `--dns`. Do we only support those 4 `docker run` options?

**Comment by chengwang86** [comment]
@stuclem @sflxn 

I have tried several examples of `docker-compose ps/events/scale` and they all worked fine. So I think we can claim that vic engine 0.9 support these features.

There is one issue with `docker events`. The output event sequence is not exactly the same with that from regualar docker. E.g., (1) if you do `docker stop`, regular docker output `kill --> die-->stop` whereas vic reports `die --> stop`. (2) when you do any container operation, e.g., `docker run`, regular docker always reports the name of the image (e.g., `busybox`), whereas vic reports something like `image=sha256:0d7e86beb406ca2ff3418fa5db5e25dd6f60fe7265d68a9a141a2aed005b1ae7` (I would say this is a bug). (3) For `docker events`, we don't report network related events yet.

`docker-compose events` is also limited on vic due to the above limitations on vic. So is it OK to say that we still support `docker-compose events` while reporting these limitations in the section for `supported docker commands`? @sflxn What do you think?

**Comment by chengwang86** [comment]
About this: https://github.com/vmware/vic/issues/3762#issuecomment-285404978

- security-opt: not supported since it is only used for windows containers (we only have linux containers I remember)
- stop-signal: yes
- stop-grace-period: not sure
- sysctl: not sure
- ulimit: not supproted

@stuclem @sflxn I didn't try all these `docker run` options when I did the research spike for `compose`. Maybe we need another research spike for `docker run` options. Any thoughts?

**Comment by stuclem** [comment]
Thanks @chengwang86. I have added support for `docker-compose ps/events/scale` and added the caveats about events to both `docker events` and `docker compose events`.
https://github.com/stuclem/vic/blob/docker/doc/user_doc/vic_app_dev/container_operations.md#container

I added the missing options in https://github.com/stuclem/vic/blob/docker/doc/user_doc/vic_app_dev/docker_compose_file_options.md. For those where you aren't sure, I said "no".

As for the `docker run` options, at present the doc is not strictly wrong because in the compose file options we state that these options are supported if their `docker run` equivalents are supported, and then in the `docker run` doc we only list a few supported options, none of which correspond to the list in the compose file options. So, it's a very untidy way of saying that none of them is currently supported, but I think that's OK for now. If we aren't sure, it's better to say that something is unsupported than supported.

If you do make another research spike for all of the `docker run` options, I create another doc issue specifically for that. In that way, we won't need to worry about `docker run` in this issue.

**Comment by chengwang86** [comment]
@stuclem 

I have several comments:

1) I think we should remove the two bugs from the documentation for `docker events`, and only leave `we don't support volume/network events`.

2) for `docker-compose file options`, 
- for `volumes` options, we do support all of them: driver, driver_opt, external,label. The only problem is that we do not support shared volumes. So if only one of the containers need a volume, it can still use all these options.
- for `network` options, in addition to what you already have in the table, we now support `label` and `internal` (based on today's code repo). 

3) https://github.com/stuclem/vic/blob/docker/doc/user_doc/vic_app_dev/docker_compose_file_options.md#service-configuration-options
You have `xxx` in the volume entry.

**Comment by stuclem** [comment]
@chengwang86 thanks for the comments

- Fixed  `docker events`.
- For the `docker-compose` file `volume` options, I added the options and the statement "vSphere Integrated Containers 0.9 does support shared volumes. You can use these options for containers that do not share volumes."
- For the `docker-compose` file `network` options, this doc is for 0.9, which is using build 8351 from 2nd March. So, I'm not sure that `label` and `internal` should be marked as supported.
- For the `xxx`, oops! Fixed.

Changes are in https://github.com/stuclem/vic/commit/8244c5f4970055cce1005267081429301c570110.
