### ISSUE TITLE
container filtering by volumes

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#3799]
`docker ps` allows for container filtering by volume name or volume mount point.  vic currently does not support filtering containers by their volume information.

The container_handler will need to be updated to return the container volume information when requesting a container list.

**Comment by matthewavery** [comment]
I believe @anchal-agrawal is actually looking into possibly adding data to the ps struct. This should allow for filtering by volume in the future. I will ask him to comment as well on this.

**Comment by cgtexmex** [comment]
I understood that @anchal-agrawal was working on volume filtering, but I assumed that was `docker volume ls` filtering

**Comment by anchal-agrawal** [comment]
For `volume ls` filtering, @fdawg4l and I discussed two approaches w.r.t. the `dangling` option:

* Add functionality to update volume metadata (specifically, the `dangling` value) in the PL when a volume has been joined to a container.
* Get all volumes, and if the `dangling` filter is specified, use `docker ps -a` to get all containers, extract non-dangling volumes from them, and populate the resulting volumes accordingly.

Since the former is pretty involved and given that volume filtering isn't a huge use case, I'm working on the latter as part of #1718. I'm working on populating volume information in the `ContainerList` handler. I should be able to close this issue with #1718.

**Comment by cgtexmex** [comment]
@anchal-agrawal so with #1718 you're actually working on populating the ContainerInfo object via PortLayer API calls to ContainerList or ContainerInfo?  I would've expected your work to focus primarily if not exclusively to the StorageHandlers and VolumeList, etc..

Just trying to understand...

**Comment by anchal-agrawal** [comment]
We currently don't have a mechanism to update volume metadata in the PL. My initial investigation involved adding an endpoint in the PL to modify volume metadata to support this workflow:
* `docker volume create --name=vol` (`vol`: dangling)
* `docker create -v vol:/dir busybox` (`vol`: non-dangling)
* `docker volume ls -f dangling=...`

This would involve work in the storage handlers and ties in with approach 1 in my comment above. We could then simply fetch all volumes from `VolumesList` in the PL and filter on the persona.

The metadata update mechanism is too involved to justify volume filtering's use case, so I'm working on approach 2 which adds some plumbing in the container handlers.
