### ISSUE TITLE
Design Container Rename

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#380]
As a VIC user, I should be able to rename a running container
As a docker compose user, I should be able to rename a running service.

---
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#rename-a-container
https://docs.docker.com/engine/reference/commandline/rename/

Please note, the engine-api's rest server already packaging these json struct into golang structs. The url above is just for reference on what the operation should do.

**Comment by sflxn** [comment]
Currently, container vmdk have the container name and ID in it's filename.  This name also shows up in vsphere.  It is also cached in both the portlayer and personality server.  We need to document everywhere the container name touches the system (e.g. storage, exec portlayer, personality server) and design how to implement this.

Also, we need to consider the current portlayer redesign and some code separation into the vmomi gateway, as that work will affect this work.  Perhaps, we should go ahead and design rename with the current portlayer design in place and then come back and update it later with the portlayer redesign in mind.

**Comment by chengwang86** [comment]
Update about docker rename on regular docker
- You can rename a container while its status is "created", "running" or "exited".
- since docker uses container long ID in the file names of container logs, config, and cgroups, docker rename does not touch these fields.
- docker keeps a struct called "**Registrar**" which stores the names and ids of the current container 

Docker rename workflow
- In vendor/github.co/docker/docker/api/client/rename.go:CmdRename(),  check whether the names are non-empty
- resti api call POST /containers/{name:.*}/rename
- In vendor/github.com/docker/docker/daemon/rename.go:ContainerRename(), 
 -- check that old/new names are non-emtpy
 -- GetContainer by old name
 -- allocate the new name to the container by daemon.reserveName(), which adds the new name to the list of existing/reserved/in-use container names (in the registrar)
 -- release old name by removing it from the registrar
 -- write the updated container config (with new name) to disk
 -- log containerRename as a docker event
 -- if container is running (meaning docker network inspect would show an entry for this container), update the container name and alias (if any) in each network endpoint connected to the container

**Comment by chengwang86** [comment]
Temporary workflow on vic:

 -- check that old/new names are not empty (persona)
 -- check the containerCache in docker persona to see if the new name is reserved by existing containers (persona)
 -- update container.name for the containerVM; update containerCache (persona)
 -- use govmomi to change the container's **display name** in vsphere; update containerCache (portlayer)
 -- DO NOT TOUCH names of storage/log files/directories.***
 -- DO NOT log events since docker event is not implemented on vic
 -- if container is running (meaning docker network inspect would show an entry for this container), update the container name and alias (if any) in each network endpoint connected to the container (portlayer?)

***Currently we name the storage folder and the log folder of a containerVM by containerName-containerID. When we rename the container, I don't think we need to also update the name of the storage/log folder and files. This is because these files are mostly used for us developer for debugging, whereas the customers may not care so much about them. If we (as well as our customers) do want to check out the storage files or log files after a containerVM is renamed, we can either (1) check the VM config from the vsphere web client, or (2) grep the vmx file to find the info about which file/folder is used by which containerVM.
