### ISSUE TITLE
Investigate approach to include and configure Lightwave in VIC-OVA

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#3906]
User statement: Lightwave should be part of the VIC-OVA. Investigate best approach to include and configure LW for usage by other components.

Detail: To achieve this goal we need to coordinate with the team in charge of creating and testing the VIC-OVA. In the previous project we have developed a set of Ansible scripts to install, configure and customize LW when deployed in GCE. Hopefully some of the code will be re-usable for installation and configuration inside VIC-OVA.

Acceptance criteria:
A note that describe the approach to include/configure/customize LW inside the VIC-OVA.

**Comment by lubronzhan** [comment]
Here is my summary
https://onevmw-my.sharepoint.com/personal/lzhan_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=QceNbojVWwS064wJdgXMc0LToTU2Pr93YbeGXhJorOY%3d&docid=2_1ab6163e8907d440dbe1a80b920226ee4&rev=1

**Comment by mdubya66** [comment]
@lubronzhan why not just pull your summary into this issue so we have it all in one place?

**Comment by lubronzhan** [comment]
@mdubya66 Sure.

Lightwave and Harbor both binds port 443. To deploy Lightwave and Harbor in single VM, I need to find way to bind Lightwave to other ports. Here are the steps I tried.

1. I first tried binding Lightwave port 443 to other another port (e.g. 2525) when starting the Lightwave container. However, since the Lightwave container includes many services and they communicate with each other through "localhost:443" , this resulted in various Lightwave errors (e.g. it doesn't pass Health Check)

2. I tried asking the Lightwave team if there is a configuration parameter to change its binding port. They suggested to change a parameter in the Catalina configuration file. I tried to build LW container based on their codes. However, there are bugs in `dev` branch and `master` branch which prevent a correct build. I was able to finish a container build (from the master branch) by splitting up some of the commands in the Lightwave Docker file, however when deployed the container runs for about 10 minutes and then it hits an out of memory error condition.

3. Finally I investigated an alternative way to put LW and Harbor in single VM. It is to put them under bridge network, so they could both use 443, but need a Ngnix in front as reverse proxy to forward requests to LW and Harbor. The tricky part is to assign both LW and Harbor with a hostname, in addition the remote machine should point those hostnames to the VM. The specific steps are in following document. [1]

Summary, need to help from Lightwave team to help build from their code on v1.0 branch.

[1]https://onevmw-my.sharepoint.com/personal/lzhan_vmware_com/_layouts/15/guestaccess.aspx?guestaccesstoken=1pzh4fybta222OZgpjT7svW1F0uXb7gOJkimm7gDg3I%3d&docid=2_1ef755db3a95d4a50b720a553734b8d8

**Comment by mdubya66** [comment]
should we open an issue against lightwave to get these resolved? @mlh78750 @lcastellano

**Comment by lcastellano** [comment]
We have more details now, this activity should be replaced by 4102, 4079. We consider this one finished.

**Comment by mhagen-vmware** [comment]
Should this be in Sprint 4 milestone?
