### ISSUE TITLE
docker info does not show volume plugins information

### ISSUE THREAD

**Issue by jdillet** [vmware/vic#3994]
**VIC version:**

0.8.0 / master / c8ac999

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
./vic-machine-darwin create --target 10.161.5.44 --thumbprint ... --user root --no-tls --image-store datastore1 --volume-store datastore1:default --name vch-7540-no-tls

**Steps to reproduce:**
docker -H 10.161.19.231:2375 info

**Actual behavior:**
Plugins:
 Volume: 
 Network: bridge

**Expected behavior:**
I expect the list of supported plugins in the Volume line
Plugins:
 Volume: vsphere
 Network: bridge

**Additional details as necessary:**
I'm verifying volumes integration between Admiral and VIC, and I have noticed that supported volume plugins are not listed (although supported network plugins are). We rely on the list of plugins supported by the host in order to place the containers in a suitable host.

**Comment by anchal-agrawal** [comment]
After checking with @matthewavery, the acceptance criteria here is to populate a list of supported drivers for the `Plugins:` section in `docker info`.

**Comment by mlh78750** [comment]
Let's also make sure that we don't conflate the docker volume plugin for docker engine with the volume support that exist in vic. Let's think if it makes sense to come up with another plugin name to report like vic-volume or vic-networking etc.. instead of the plugins used on vanilla docker.

**Comment by mreferre** [comment]
+1000 to what @mlh78750 said

**Comment by mlh78750** [comment]
Confirmed with admiral team that they just need it to show something in the volume plugin so that they know volumes are available. I recommend "vic-volume" listed as a plugin anytime a default volume store is available.

**Comment by mlh78750** [comment]
Changed to high priority. It's blocking admiral at this point.

**Comment by fdawg4l** [comment]
@mlh78750 

> We rely on the list of plugins supported by the host in order to place the containers in a suitable host.

Will a "dummy" plugin work for this use case?  It sounds like placement would require something slightly more nuanced.  For instance, we support volumes on vsphere as vmdk backed storage devices and will support named NFS targets.  How will the Admiral placement logic tease apart these two distinctly different usage models?  I would imagine they would need a list of available volume semantics in order to satisfy a placement request depending on the VCH configuration, no?

**Comment by fdawg4l** [comment]
@jdillet can you comment on the above? Do you really just need some string, any string, returned for volume plugins on VIC or do you require some more granularity to do placement given VIC support more than one type of volume?

**Comment by jdillet** [comment]
We need this in order to support multiple volume plugins. Let's say we have a docker file with one container and one volume, and the driver is of type A. We have several hosts, some of them supporting driver A, some of them not. So, we want to create the volume in one of the hosts supporting this volume type. For this, we filter the hosts based on the results of docker info command. This happens before the volume is created, so if we do docker volume ls at this point, it would return an empty list. Yes, we could always create a dummy volume, but that wouldn't be any clean design. Moreover, if a host supports several volume types, and we create a dummy volume, it would help to discover the default type, but no the other ones.

About the name, we need something that identifies the VIC volumes plugin (vic-volume or whatever you decide). For example, if plugin is vic-volume, a simple docker file would be:
```
version: "2"
services:
  redis:
    image: "redis"
    volumes:
    - "data-volume:/tmp/data"
volumes:
  data-volume:
    driver: "vic-volume"
```

**Comment by fdawg4l** [comment]
> Moreover, if a host supports several volume types, and we create a dummy volume, it would help to discover the default type, but no the other ones.

@jdillet this is my point exactly. VIC supports more than one volume type. So it sounds like you need a "vic plugin" string for each type we support. Yes?

**Comment by jdillet** [comment]
Yes, the list of all supported volume types, separated by spaces.

**Comment by mlh78750** [comment]
so maybe vic-vmdk vic-vsan vic-nfs etc..

**Comment by fdawg4l** [comment]
@mlh78750 that sounds right. Thanks guys!

**Comment by hickeng** [comment]
@jdillet Is that compose file you provided written by the user or generated by Admiral?
If it's written by the user then it requires the user to know significant detail about infrastructure, but what they actually care about is likely things such as:
* cluster wide volume
* concurrent access volume
* single access volume

**Comment by fdawg4l** [comment]
@hickeng why does `cluster` matter for placement in this case?  It's a level of granularity that, again, only the VI admin knows and is opaque to the user.  The only details the user knows is the name of the volumestores available to him/her.  And it's up to the VI admin to share the knowledge of which volumestore maps to which semantic (shared, vs non-shared).

**Comment by igorstoyanov** [comment]
@hickeng I agree with you. In most of the cases the user/dev will not care about the volume driver. This is the main use case. From a placement point of view, we care for the things you suggested: cluster wide volume , single access volume... 

So, first concern - if we have VCH configured, Admiral needs to know if there is clustered support for volumes. Assuming VCH is a cluster and always has a support for volumes, we can consider this as done. 

The other use case is when more IT people are trying to deploy such applications. They usually request for much finer grain control of where the placement to go based on such configurations. Since this is how it is done for native docker, the suggestion is for VIC to do it in the same way. 

The alternative is to say that this use case is not supported on VIC (not relevant for VIC). I don't see immediate problems. The only concern might be that there might be assumption that VIC is not fully supported in that aspect.

**Comment by hickeng** [comment]
@fdawg4l I was talking about the generic phrasing of compose, with the reference to cluster. My point remains, and is the same as you described to some extent. We shouldn't be requiring completely out of band means to communicate the properties of stores.... the issue atm is that we have no means of expressing those characteristics.

@igorstoyanov We have provided the volumestore mechanism for exposing storage with different characteristics, and we're explicitly NOT exposing the details of the infrastructure at the docker layer so that users do not require infrastructure knowledge.
We may need to use/abuse the driver field to allow selection of a volume store (e.g. fast, temp, shared) but I fear it'll lead to confusion in the future.

**Comment by anchal-agrawal** [comment]
@igorstoyanov @hickeng Based on my offline discussion with George, we think we should populate a list of configured volume stores for the VCH. The VI admin would specify the volume stores during VCH creation and tag them with names for the user.

For example, in a typical deployment, the volume store names would be:

* `default` for anonymous/image volumes
* `shared` or `nfs` or `foo` for custom volume deployments

Side note: the list of volume stores is already available in the output of `docker info`, albeit in a different top-level field:
```
$ sudo docker -H 192.168.77.225:2376 --tls info
Containers: 0
...
Storage Driver: vSphere Integrated Containers v0.9.0-0-8ae844c Backend Engine
VolumeStores: default foo bar
vSphere Integrated Containers v0.9.0-0-8ae844c Backend Engine: RUNNING
...
```

We can add functionality to list the volume stores in the `Plugins` section as well.

**Comment by anchal-agrawal** [comment]
Upon further discussion with George, we think it makes more sense to populate the supported drivers (currently only `vsphere`/`local`) in the `Plugins - Volume` section.

To be consistent with Docker semantics, whatever we show in the `Plugins - Volume` section should be able to be specified as a volume driver by the user. Displaying the volume stores in that field is misleading - volume stores cannot be specified as drivers with VIC.

**Comment by jdillet** [comment]
@anchal-agrawal populate the supported drivers in the Plugins - Volume section works for us.
