### ISSUE TITLE
Detect when an upgrade/update is in progress

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#4069]
**User Statement:**

If I am a VCH admin I don't want to be able to upgrade my VCH if an upgrade is already underway, because this could cause an inconsistent state.

**Details:**
Right now, we detect this by checking for the existence of a snapshot. When #3765 is resolved, at least one snapshot will be saved, so the existence of a snapshot is no longer a reliable method for detecting an ongoing upgrade. Another method will need to be used. 

Further, after performing an upgrade, vic-machine inspect sees the existence of the snapshot of the previous version and reports that the VCH is upgrading:

```Feb 28 2017 15:52:46.499-06:00 INFO  VCH upgrade status:
Feb 28 2017 15:52:46.504-06:00 INFO  Upgrade in progress
```

**Acceptance Criteria:**
If running a `vic-machine upgrade`, running a second in parallel should exit and make no changes to the system.

Also, running `vic-machine inspect` after performing an upgrade should no longer continue to erroneously display that the VCH is upgrading.

**Comment by emlin** [comment]
Update has same issue with upgrade, move this issue to update epic

**Comment by emlin** [comment]
We can use extraconfig to persist one update/upgrade flag for the VM.
- This should be done before everything is started, and reverted after the process is done no matter it's succeed or not.
- If the flag exists, fail the update/upgrade.
- If user knows the flag is set by interrupted process last time, s/he can remove the flag by `vic-machine upgrade/update --resetInProgressFlag`

The reason to use extraconfig is because that flag will not be dropped if we set attribute for a powered VM.

**Comment by chengwang86** [comment]
@emlin We also need to add a VCH upgrade plugin for this feature since we augment the extraconfig for the VCH, right?

**Comment by chengwang86** [comment]
Discussed with Emma just now. We don't support VCH upgrade using this new flag from an older-version VCH (without this falg), so there is no need to add VCH upgrade plugin.
