### ISSUE TITLE
Deploy drone 0.5 nodes 

### ISSUE THREAD

**Issue by jakedsouza** [vmware/vic#4267]
**User Statement:**

As a vic engineer, I want to run builds on the latest version of drone. 

**Details:**
Deploy a new ci environment using the latest drone build 

**Acceptance Criteria:**

- [ ] New drone master and 8 agents deployed with TLS enabled on a new domain 
- [ ] Ansible scripts to configure each node 
- [ ] New Domain ci.vcna.io for the tests

**Comment by mhagen-vmware** [comment]
For this story we want to start working on this in Sprint 6, and we want to change to reqs slightly.  We have 1 or 2 big servers idle in OVH now so we want to deploy a fresh drone .5 server and 8 workers on to one of those servers so that we have our own dedicated infra. We need to also take a new domain and migrate from ci.vmware.run to vic-ci.vmware.run or something like that.  @jakedsouza Can you please decompose and organize the stories around this?  Let me know if you have any questions.

**Comment by jakedsouza** [comment]
> For this story we want to start working on this in Sprint 6, and we want to change to reqs slightly. We have 1 or 2 big servers idle in OVH now so we want to deploy a fresh drone .5 server and 8 workers on to one of those servers so that we have our own dedicated infra. 

We cannot use the two big servers, they are not on the vrack hence can not access any of the esxi's 
We can re-use some of the other machines  ones with the older nested esxi's, VC's and drone-integration nodes

**Comment by mhagen-vmware** [comment]
lgtm, verified based on the ip list in our ansible repo. Drone .5 doesn't have a way to see number of nodes anymore.
