### ISSUE TITLE
Milestone: compose up

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#431]
Use `docker compose up` to bring up a multi-tier app

This breaks down into the following staged deliveries.
- single node app comes up
- multi-node, single tier app comes up
- multi-node, multi-tier app comes up

This should make use of the docker voting app as a good example of a tiered application. If available, this should be directly testing the scenarios from doc/design/application-topologies.md

**Comment by mdubya66** [comment]
GA feature from SSOD. Needs verification.

**Comment by mhagen-vmware** [comment]
Initial test development is complete on this, removing myself as the only assignee.

**Comment by mdubya66** [comment]
@hickeng help me find a good owner for this.

**Comment by sflxn** [comment]
I have started investigating compose.  Starting with basic learning of compose.  Just from the start, I can say there is a lot to learn, and probably no one on the team knows much about it.  Much like how we discovered the widespread dependencies on docker ps and container-wait, there will be a lot of these unknowns within docker-compose.  We should not go into this with assumptions as that has bit us in the past.

As an example, the initial tests already made some assumptions.  For those who have NEVER worked on the personality code, this may come as a surprise, but the docker documentation is very, very lacking.  There is only one method to discovering all the facts:

1. Read all the documents
2. Try many samples
3. Google
4. Read the docker github issues
5. Read the code

Note, the above must be done all together.  You cannot learn everything from doing one or a few of the above.

Back to the initial tests, I have discovered that docker-compose is really only meant to be used for the command up.  'docker-compose up' also creates a network compose-default.  Without this default network, docker-compose create will fail.  Unfortunately, this is not the only problem with docker-compose on VIC.  docker-compose is doing some other undocumented operations and failing so I will need to read the code.

I'm documenting all this to set expectations.  It might end up being another personality sized work.  It should be less work, but it will be safer not to assume!

**Comment by sflxn** [comment]
With some small changes to our docker create and inspect code, I can now perform compose up on VIC with a basic compose file.  Our tests will need to change.  There will be some variations between VIC's and regular docker's support for compose.  This applies to support for both CLI options and YAML options.

**Comment by hickeng** [comment]
@sflxn I presume that we're able to tolerate compose by ignoring labels rather than returning Not Implemented? The target we've got for compose is the voting-app example:
https://github.com/vmware/vic/blob/master/doc/design/application-topologies.md

**Comment by sflxn** [comment]
Labels are attributes in create.  We're going to handle labels correctly.  It must be supported for docker-compose to work.  It's a simple fix once you figure out it's because of incorrect labels support.

**Comment by sflxn** [comment]
The lamp yml tests returns the following error:

```
ERROR: for vic.php  Cannot create container for service vic.php: [POST /storage/volumes/][404] createVolumeNotFound  &{Code:0xc4203a5870 Message:volumestore (http://vic-docker/storage/volumes/default) not found}
```

**Comment by sflxn** [comment]
Looks like there are a few issues related to volumes.  First is we must install VIC using the volume-store flag for vic-machine.  Second, there is a new P0 bug for VIC, #2313 related to anonymous volumes.

I updated the compose lamp integration test for volume to use named data volume instead.  It's also failing, with the following error:

```
ERROR: Cannot create container for service vic.php: file does not exist
```

It appears #2313 is also affecting docker-compose for named data volumes.  This doesn't make sense since I can manually create the php container using the docker CLI with a named data volume that I created manually.

**Comment by sflxn** [comment]
I figured out the previous issue and created a new issue, #2317.  We're not creating named data volume in ContainerCreate.

**Comment by sflxn** [comment]
One comment.  The lack of support for mapped volumes (vs named or anonymous data volumes) really restricts what applications can be deployed.  Most real applications do want some configuration to be given to it during deployment.  Usually, these config are not baked into the application.  We do not yet support docker cp so we cannot get config files to the data volumes.  Without mapped volumes, there is no other way to get a config file to the application other than via docker build (baking config into the application).

I am still trying to get docker build to work via DIND, but so far, I have not figure out how to do this since the dockerfile and all pertinent files are on the local machine and not the VCH.  If this can't be done with DIND, customers will have to bake in their config into their apps with regular docker, upload to a registry, and deploy from that registry.

Another option is to recommend customers build 12-factor apps (config via env variables) or recommend they build containers that take config via command line options.

**Comment by sflxn** [comment]
Added Container Wait and Container Logs as requirements.  If you execute docker-compose up -d, there is no requirement for those.  If you just perform docker-compose up, then wait and logs are required.

**Comment by sflxn** [comment]
Port mapping works.  Links/Alias do not.  Apparently, alias issue is known -- #1459.  Links/alias is a legacy mechanism, but it would be nice to have.

**Comment by sflxn** [comment]
Also, there's the issue of how do they get their results?  A lot of apps output their results to log files.  Without docker cp or mapped volumes, this isn't viable.  If they restrict themselves to 12 factor apps, and output their data to stdout and stderr, then it will be useful.  If they change their app to not output results in logs and save their results to a database that is accessible, then this is another option.

**Comment by sflxn** [comment]
If a container with a name that is specified in a yaml already exist, docker-compose will attempt to call docker rename.

**Comment by sflxn** [comment]
Just discovered docker-compose uses volume inspect to determine a volume exist.  Somehow, we missed this functionality in volume.  Added an issue for this.

**Comment by mdubya66** [comment]
Removed bugs from Epic. Removing from VIC GA Release as all remaining issues are outside of that milestone

**Comment by mdubya66** [comment]
adding to 0.9.0 for now to complete the remaining issues.

**Comment by mdubya66** [comment]
feature requested for 1.1

**Comment by mdubya66** [comment]
All issues are closed. If we need to do more compose work it should be done under a new Epic
