### ISSUE TITLE
docker inspect invalid object on client versions 1.13+ returns an incorrect response

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4322]
**VIC version:**

0.9

**Docker client versions:**

1.13 and 17.03.0-ce

**Steps to reproduce:**

`$ docker -H <VCH> inspect fake`

**Actual behavior:**
```
[]
Error response from daemon: vSphere Integrated Containers does not yet support plugins
```

**Expected behavior:**
```
[]
Error: No such object: fake
```

**Comment by anchal-agrawal** [comment]
After debugging this @chengwang86, we found that on Docker clients v1.13 and v17.03.0-ce, `docker inspect` invokes inspect on plugins as well in addition to the usual objects like containers and images. Our code for inspecting plugins returns an error in all cases, which is why we see `Error response from daemon: vSphere Integrated Containers does not yet support plugins` on the client:

```go
func (p *Plugin) Inspect(name string) (*enginetypes.Plugin, error) {
	return nil, fmt.Errorf("%s does not yet support plugins", ProductName())   
}
```

We don't think this is related to vSAN. The reason the inspect integration tests aren't detecting this on CI is because we're using Docker client v1.11.2.

**Comment by anchal-agrawal** [comment]
Re-prioritizing to high because #4368 is marked high.

**Comment by chengwang86** [comment]
Based on discussion with Anchal, here is a temporary workaround before we actually support `docker plugin`.

```
func (p *Plugin) Inspect(name string) (*enginetypes.Plugin, error) {
	return nil, nil  
}
```
