### ISSUE TITLE
Milestone: container logs

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#433]
Retrieve the full logs for a container. The last of the targets here is to force persistence outside of the VCH appliance.

Docker API support for logs command
Port Layer API support for something
logs stream from live container - from time of command, is this the same as attach?
logs reported for stopped container
logs reported for live container - from time of start
logs reported for stopped container after VCH reboot

As it currently stands, logs for a container are found on the datastore in the containerVMs folder.
Do those logs move with Storage vMotion?

NOTE: currently there's no mechanism for persisting logs for `docker exec` processes

**Comment by corrieb** [comment]
#366 is currently targeted for GA, but this epic is marked for onsite. We need to resolve. Log collection should be a high priority item as soon as customers start getting their hands on this.

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by dougm** [comment]
@jzt similar story here.. I plan to start by figuring out how to stream the logs from the datastore, but the API/PortLayer work can be done in parallel.

**Comment by jzt** [comment]
@dougm sure, adding myself as an assignee here until subtasks are created (if needed).

**Comment by sflxn** [comment]
@hickeng @dougm and I just had a good conversation about docker logs.  Docker logs can do 2 things that we cannot currently do at this point.  The first is to tag all log lines with a timestamp.  The second is to be able to grab all log since a timestamp.  The importance of the latter may not be apparent immediately.  Docker logs interleaves containers logs, stdout, stderr into the output.  The tether returns the stdout and stderr streams at the point that we ask for data.  To fully support the docker logs behavior, we will need to keep stdout and stderr around as we do the container logs, and we need to do so with timestamp.

**Comment by mdubya66** [comment]
Needed for Admiral. All Items closed. Closing Epic
