### ISSUE TITLE
VIC + Harbor using self-signed certs not working

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4363]
I have installed harbor, and downloaded the self signed certs provided by harbor.
Next I install VIC with the certs I downloaded from harbor:
```
bin/vic-machine-linux create --debug 1 --name=VCH-0-1940 --target=xxxxx --thumbprint=xxxx --user=xxxx --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=xxxx --force=true --bridge-network=VCH-0-1937-bridge --public-network="VM Network" --timeout 30m --volume-store=datastore1/test:default --registry-ca=getcert --no-tls
```

When I then try to pull anything from the harbor, I get the following error:
docker -H xxxx:2375 pull xxxx/library/photon:1.0
Error response from daemon: Head https://xxxx/v2/: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Self-signed by VMware, Inc.")

Not sure if I am doing something wrong, but I think I am following our docs fairly accurately:
https://vmware.github.io/vic-product/assets/files/html/latest/vic_installation/deploy_vch_harbor.html

**Comment by gigawhitlocks** [comment]
Might be related to #3441

**Comment by hickeng** [comment]
Is there an error reported in the personality code when initializing? It's possible that they've not generated the cert as a CA which means we'll likely fail when adding it to the RootCA pool in the appliance.

**Comment by mhagen-vmware** [comment]
[container-logs.zip](https://github.com/vmware/vic/files/866266/container-logs.zip)

**Comment by mhagen-vmware** [comment]
@hickeng only error in personality log AFAICT is the final error when I try to do a pull...

**Comment by gigawhitlocks** [comment]
@mhagen-vmware and I talked about this in person, and because this is related to my issue I'm reading up on Docker's behavior when connecting to insecure registries. Note that since Harbor is using a self-signed certificate here, this is considered an insecure registry regardless of TLS, and so with the VCH installed without `--insecure-registry=`, I believe this is the correct behavior. My understanding is that the certificate on Harbor needs to be signed by a root CA in order to be able to omit `--insecure-registry` during VCH creation. @hickeng can you correct me on this if I am wrong?

**Comment by gigawhitlocks** [comment]
(my understanding is that docker takes `--insecure-registry` to mean what we mean when we say `--no-tls` or `--no-tlsverify`)

**Comment by gigawhitlocks** [comment]
https://github.com/vmware/vic/issues/3441#issuecomment-265646874 <- related to my comments above

**Comment by mhagen-vmware** [comment]
confirmed this procedure worked in VIC 0.8
