### ISSUE TITLE
Specifying volume-store == image-store leads to unintended volume loss (ESX)

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#4478]
Related to #4233, it turns out that VMFS on ESX has different behavior to the iSCSi datastore I was using in 4233. 

On ESX, if you specify ``--name=dev --image-store=datastore1 --volume-store=datastore1/dev:default`` in vic-machine create, then all your volumes will go into the *same* folder as your images and the VCH. On iSCSI, it creates a dev_1 folder (see #4233). 

There may be other datastore types that exhibit the ESX behavior.

If I then create a volume called foo and run vic-machine delete without --force, I get the message:

``Mar 30 2017 20:37:30.345Z WARN  Since --force was not specified, the following volume stores will not be removed. Use the vSphere UI to delete content you do not wish to keep.
	default: [datastore1] dev``

However, when I look at the datastore, my foo volume was deleted.

I would argue that any case where we delete persist data when we're not supposed to is serious. 

There are two courses of action here: 

(1) Prevent volume stores being specified as the same folder name as the VCH name. Although that is quite a natural thing to want to do if you want your volumes to have the same lifecycle as the VCH.

(2) Allow the current behavior, but don't delete the volumes unless --force is specified.

**Comment by mhagen-vmware** [comment]
please estimate and move to backlog when ready

**Comment by stuclem** [comment]
@mhagen-vmware does this need to go in the release notes for 1.1?

**Comment by mhagen-vmware** [comment]
@stuclem yes, this should be release noted

**Comment by stuclem** [comment]
Proposed release note:

------

- <b>Specifying the same datastore for volume store and images store leads to unintended volume loss on ESXi hosts. [#4557](https://github.com/vmware/vic/issues/4557)</b><br>When deploying VCHs directly to ESXi hosts, if you specify `vic-machine create --name dev --image-store datastore1 --volume-store datastore1/dev:default`, volumes will go into the same folder as images and the VCH. If you then run `vic-machine delete`, the volumes are deleted, even if you do no specify `--force`. This does not occur when deploying to vCenter Server.

------

@corrieb @mhagen-vmware is this OK?

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by stuclem** [comment]
Thanks @mhagen-vmware

**Comment by hickeng** [comment]
If we allow volumes to be placed into the endpointVM folder it is not solely a matter of preventing them from being deleted without `--force` - we also need to consider how they will be used by other or subsequent deployments of a VCH. If we were to deploy a new VCH with the same name as the old, expecting them to be in the same folder, then that assumption will be violated. The VCH would be placed into `[datastore1] dev_1` and the volumes would be in the old folder `[datastore1] dev/volumes` directory, so the implied lifecycle coupling would not be extant.

**Comment by maplain** [comment]
@hickeng actually, you don't have to create a new vch to make it happen. since createVolumeStore happens before createAppliance, vch is placed into `dev_1` already on vc because `dev` is created by createVolumeStore, if volumestore has the same name as vch. that's why this issue happens only on esx : https://github.com/vmware/vic/issues/4478

I don't understand your statement above. if we don't allow creating a new VCH with an existing name, we wouldn't break the implied lifecycle.

**Comment by emlin** [comment]
Same to @hickeng , my preference is the latter one.
Because if I am the user, and I have some sort of understanding of vSphere, if specify volume store directory same to VCH name, I would assume the volume is placed into the same folder with VCH.

I think we might be able to address the unstable behavior with some workaround, but think about the vSAN issue happened recently, I'd prefer to use vSphere in their traditional way for an not critical issue.

**Comment by maplain** [comment]
@hickeng I didn't make it clear.

My point is:
1. dev_1 behavior is already happening on vc, and in that case, delete with or without --force works correctly, which is to say, with --force, dev/volumes will be removed; without --force, dev/volumes is not removed since applianceVM is placed under dev_1
2. but above fact only holds true in vc, not in esx where applianceVM and volumes are put under dev so with or without force, dev/volumes will be removed, which is exactly this issue;
3. the reason applianceVM is placed under dev_1 in vc but not esx is:
    1. in createAppliance, vc employs vApp.createChildVM, esx uses folder.CreateVM;
    2. createChildVM will create 'dev_1' since 'dev' is already created by createVolumeStore, but createVM will not;

So there are two reasons:
1. 'dev' is created before createAppliance is called;
2. vApp.createChildVM and folder.createVM have different behaviors facing with an existed directory;

This can be reconciled if we make sure when createAppliance is called, 'dev' doesn't appear on datastore.

so my solution to this issue is:
1. make sure createVolumeStore is called after createAppliance;
2. make sure dev/volumes is not deleted if --force is not specified;

**Comment by maplain** [comment]
@emlin @hickeng @fdawg4l 
Current agreement is:
1. as long as volumestore has the same name with some vch no matter it’s the one we’re going to create or an existing one:
  1. we disallow this behavior by default with appropriate warning;
  2. we make it happen if --force is specified in create but ***with a warning*** they’re going to be deleted along with vch, because ***we assume*** when user decides to put volumestore under a vch folder, they want it to have the same lifecycle with that vch.

**Comment by hickeng** [comment]
@maplain Agree with the described behaviour - unsure how the referenced commit enforces (2)
