### ISSUE TITLE
Cannot pull images using a Proxy

### ISSUE THREAD

**Issue by lalegre** [vmware/vic#4511]
I am having this problem:

When i run the following command **docker -H VCH_ENDPOINT_IP:2376 --tls pull hello-world** i got the following error:

https://registry-1.docker.io proxy authentication required

I can push images locally on my Ubuntu machine where the vic engine is installed because i use CNTLM for NTLM proxy authentication. 

My doubt is how can i set the same on the VCH Endpoint because i don't see in which part of the virtual machine is the proxy configured.

Can you please help me with this?

Thanks in advance.

**Comment by mhagen-vmware** [comment]
@lalegre Hi! We currently don't have direct support for proxies that require logging in. Right now we only support the following options at VCH install:
```
   --https-proxy value, --sproxy value              An HTTPS proxy for use when fetching images, in the form https://fqdn_or_ip:port
   --http-proxy value, --hproxy value               An HTTP proxy for use when fetching images, in the form http://fqdn_or_ip:port
```
You can try to input that in the form of:
https://<username>:<password>@ip:port and see if that works (I suspect it probably won't), but otherwise that is a new feature that we will need to implement.

**Comment by mhagen-vmware** [comment]
@lalegre Any luck with the suggestion above?

**Comment by renmaosheng** [comment]
@lalegre please reopen if still needs this. (it has been more than 1.5 years.)
