### ISSUE TITLE
vic-machine reconfigure: Add volume stores

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4512]
**User Statement:**

As a VIC operation user, I need the ability to add new volumes to my VCH. Related to #1797

**Details:**
- supported operations:
  - add a volume store
- hot update:
  - no
- input/output data format:
  - input: e.g., `--volume-store datastore/path:label`, `--volume-store datastore:label`, `--volume-store nfs://host:port/nfs:nfs`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: no
  - containerVM: no
- is upgrade needed:
  - no

**Acceptance Criteria:**
- add the ability to addm volume store(s) from an existing VCH
- add relevant test cases

**Comment by emlin** [comment]
volume-store option sample: "datastore/path:label" or "datastore:label", and can be a url to like "nfs://host:port/nfs:nfs"

For remove operation, need to make sure no volumes exist in that volume store. If any volume created in that volume store, volume-store delete is not allowed, no matter if that volume is attached to container or not. (is discussing with @karthik-narayan in the PRD)

**Comment by emlin** [comment]
@karthik-narayan copy new comments from PRD:
technically speaking, vic-machine is managing the volume store, instead of volumes in that volume store. So vic-machine update is supposed to be able to remove one volume store, which make sense.
But if there is volumes in that volume store, should vic-machine delete volumes in that volume store, if no container attached to that volume?
My understanding is that vic-machine is managing volume store only, if there is volumes in one volume store, we should not allow to delete the volume store. How do you think?

**Comment by emlin** [comment]
Using #4642 tracking volume-store delete
