### ISSUE TITLE
vic-machine reconfigure: Update the Virtual Container Host memory and CPU details via the vic-machine CLI

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4513]
**User Statement:**

As a VIC operation user, I need the ability to update the VCH's CPU and memory details via the vic-machine CLI.

**Details:**
- supported operations (both vsphere UI and vic-machine cli):
  - update CPU details (cpu limit in MHz, cpu-reservation, cpu-shares)
  - update memory details (memory limit, memory-reservation, memory-shares)
- hot update:
  - yes.
- input/output data format:
  - input: e.g., `--cpu --cpu-reservation --cpu-shares --memory --memory-reservation --memory-shares`
  - output: N/A
- impact on VCH/containerVMs (setting CPU limit on vsphere UI as an example):
  - if we increase the limit to be more than the physical resource limit, vsphere will throw error msg `The available Memory resources in the parent resource pool are insufficient for the operation.`
  - if we increase the limit within the physical resource limit of the resource pool, the operation can succeed
  - if we decrease the limit to be less than its current usage, no error msgs. However, vch restart will fail due to lack of resource and we cannot run new containers.

- is upgrade needed: 
   -  no. We can directly call vSphere APIs to update the cpu and memory details of the resource pool. 

**Acceptance Criteria:**
- add the ability to update the VCH's cpu and memory details via vic-machone cli.
- add relevant test cases

**Comment by emlin** [comment]
- For this function, user can do it from vSphere UI, but that's out of vic-machine update scope, so please remove that description from the story.
- The change happens in resource pool and vApp, no need to restart VCH.
- Please try to manually reduce resource reservation to a smaller value than currently used, to see VC behavior. We'll use that as our reference.

**Comment by chengwang86** [comment]
@emlin 

On a Nimbus VC deployed using default settings, I deploy a VCH and then create several containerVMs such that the VCH as a vApp has outstanding CPU/memory usage.

CPU limit: From the vsphere UI, 
- if I increase the CPU limit (within the maximum), it always succeeds
- if I decrease the CPU limit, no matter the new value is lower or higher than the current CPU usage, sometimes the new values take effect but most of the time the CPU limit remains unchanged. Either case, VC does not throw any error msg.

Memory limit: same as above.

**Comment by emlin** [comment]
@chengwang86 Tried in VC, the settings for CPU and Memory all works well through UI. And if the settings is too big, will get error for like "The available Memory resources in the parent resource pool are insufficient for the operation."
But if we set one resource number less than currently used, VCH restart will fail for lack of resources, and it will fail to start any new containers.

For our behavior, my preference is not to check the number cause vSphere will guide on invalid settings, just have a warning message to let user know if resource is not set big enough, vch is not able to be restarted, and new container is not able to be created.

**Comment by emlin** [comment]
@hickeng @karthik-narayan 
This resource setting is out of endpoint VM, which is not persisted by guestinfo, only one settings for the parent resource pool/vApp.
So it's not possible to keep old value to a vm snapshot, and then it's hard for us to revert. If one update finished without interrupt, and with errors, we could revert the old value from memory. But if the reconfigure is interrupted, or succeeded, and user wants one step rollback, we cannot go back.

My question is do we need to support revert on this resource? 
And do need to support this resource reconfiguration from vic-machine?

**Comment by emlin** [comment]
@karthik-narayan As this issue is pulled into 1.2 again, I would like to get a confirmation for if we need to support configuration rollback for this particular reconfiguration.
This resource limitation is not part of VCH appliance VM, so it cannot be persisted by vm snapshot. If we do need to have a consistent user experience for this resource change, I mean same to other reconfiguration, e.g. proxy, we'll need additional effort on it.

**Comment by emlin** [comment]
Currently, VCH configuration is persisted in guestinfo, but VCH memory/cpu is not part of guesinfo configuration and not VM device configuration.
vic-machine reconfigure is relying on VM snapshot to keep old version's configuration, so that can be rollback for any failure configuration change or one step roll back, so this is why VCH memory/CPU cannot be managed in the same way right now.

If @karthik-narayan think that we should keep same behavior with all other operations, additional support should be done:
- persist VCH memory/cpu configuration in guestinfo
- update that value each time configure command is executed, as well as the resource pool limitation
- add upgrade plugin to add the information for old version's VCH

Issues of this solution:
- if vc admin updated the resource limitation from VC UI, the information in guestinfo will be inconsistent with real value
- every time the value is updated from vic-machine, the inconsistency could be fixed

**Comment by emlin** [comment]
Talked with @karthik-narayan just now. The decision is that we still do rollback for VCH memory/cpu if reconfiguration failed, cause user might specify sth wrong for the configuration, if we don't rollback resource limitation, rollback other configuration might not help to bring back VCH services.

But we do not use the VM snapshot to persist VCH resource pool memory/cpu configuration, because there is inconsistency between the VCH resource pool configuration and our persisted value. 
In the future, even user need to rollback network configuration, for resource limitation, they might just want to set new values, so at this time, we don't worry about the resource pool configuration rollback after a successful reconfiguration.
