### ISSUE TITLE
vic-machine reconfigure: Update or reset the HTTP and HTTPS proxy values

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4531]
**User Statement:**

As a VIC operation user, I need the ability to update or reset the HTTP and HTTPS proxy values. The proxy is used only when pulling images.

**Details:**
- supported operations:
  - update (or add) the HTTP and HTTPS proxy values
  - remove existing HTTP and HTTPS proxy values
- hot update:
  - no; need to restart the VCH to make the changes take effect.
- input/output data format:
  - input:  `--https-proxy http://proxy_server_address:port`. The `proxy_server_address` could be either an FQDN or an IP address.
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The VCH will use the updated proxy server to pull images.  
  - containerVMs: no. Note that configuring a VCH to use a proxy server does not configure proxy support on the containers that this VCH runs. Container developers must configure proxy servers on containers when they create them.
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
- add the ability to update the HTTP/HTTPS proxy values.
- add relevant test cases

**Comment by emlin** [comment]
- vic is setting environment for persona and vicadmin, though we might need the proxy only when pulling image.
- the operation should support proxy remove as well.

**Comment by morris-jason** [comment]
Note: Due to PR #5233 vicadmin is no longer using env vars for http[s] proxies.

>As a VIC operation user, I need the ability to update or reset the HTTP and HTTPS proxy values. The proxy is used only when pulling images.

Proxy is also used in vicadmin for wan health checks.

**Comment by ali5ter** [comment]
@emlin asked me to comment on the `vic-machine create` options for setting the proxy and if the short names can be improved. My 2 cents...

#### Existing options
`--http-proxy, --hproxy` 
`--https-proxy, -sproxy`

#### Recommendation
CLIs typically don't distinguish between https or http proxies because they use variations of `--proxy-host` and `--proxy-port`

I can't think of any good shortening of `--http-proxy` or `--https-proxy` and wonder at the benefit given that these may not be used that often.

I'd suggest we remove the short names.

**Comment by emlin** [comment]
@stuclem I remove the short name for http-proxy and https-proxy in vic-machine create and configure command because of the reason @ali5ter mentioned above.
Let you know in case there is doc change requirement

**Comment by stuclem** [comment]
Thanks @emlin. Just saw this. Created https://github.com/vmware/vic-product/issues/306 to update the doc.
