### ISSUE TITLE
vic-machine should be able to enable or disable ssh login to the VCH

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#4542]
**User Statement:**

As a VIC admin, I need the ability to enable or disable ssh login to an existing VCH. This also relates to **vic-machine reconfigure**#2911.

**Details:**
- supported operations:
  - enable or disable ssh login to the VCH
- hot update:
  - yes
- input/output data format:
  - input: `--enable-ssh` and `--disable-ssh`
  - output: N/A
- impact on VCH/containerVMs:
  - VCH: The user should be able to login the VCH via SSH.
  - containerVMs: no. 
- is upgrade needed: 
   -  no, since no VCH configuration changes. 

**Acceptance Criteria:**
- add the ability to enable or disable ssh login to the VCH.
- add relevant test cases

**Comment by chengwang86** [comment]
**enable-ssh** could be achieved by `vic-machine debug --enable-ssh`. **disable-ssh** could be achieved by restarting the VCH since the VCH is stateless.

**Comment by emlin** [comment]
@corrieb @karthik-narayan @hickeng 
We've already supported enable-ssh, and disable-ssh is reachable through vch restart. Need to confirm if this is one requirement part of VCH reconfigure.

**Comment by hickeng** [comment]
@emlin You can also stop the ssh service by running `systemctl stop sshd` without rebooting the appliance. I think this issue is addressed unless we want to flesh out the debug tests somewhat.
One example is what happens if you use `vic-machine debug --rootpw=password` and set a password that would be rejected as a dictionary match when done interactively. We use `chpasswd` to perform the change, but don't know if that enforces complexity policy.

**Comment by emlin** [comment]
enable-ssh: done
disable-ssh: restart vch
so close this story, and use bug to track the `chpasswd` issue
