### ISSUE TITLE
vic-machine inspect: show existing VCH configuration

### ISSUE THREAD

**Issue by emlin** [vmware/vic#4618]
As vic admin, I need to know existing VCH configurations easily to regenerate reconfigure or create command line, so that I can reconfigure VCH or use it recreate another VCH with similar configuration.

Refer to #4497 for the command design and output format

Update:  a scenario exists wherein resources can be renamed through the vSphere UI, rendering the output of this command inaccurate. Special checks need to be made to ensure truthful output in this situation on the following items:
- [ ] networks/portgroups (bridge, client, public, management, container) - possibly using the slot number?
- [ ] datastore resources (image store, volume store, container store)
- [ ] compute resources

**Comment by jzt** [comment]
The first iteration implemented in #5046. Currently, we simply store the formatted command options originally used to create the VCH. The next step is to actually verify the resources on the backend in the event that any were renamed, as well as detecting the OS on which the `inspect` command is being run, so that we format the output correctly.
