### ISSUE TITLE
Not able to docker login into registry with self-signed certificates

### ISSUE THREAD

**Issue by shadjiiski** [vmware/vic#4681]
**User Statement:**

As a VIC-engine user, I want to be able to login from the command line (`docker login`) into registries (including harbor) that are secured with self-signed certificates.

**Details:**
I have a `--no-tls` VCH, configured with the `--insecure-registry X.X.X.X:443` flag. (This is the harbor registry, deployed as part of the 1.1 OVA rc4). Doing a `docker login` fails:
```
$ docker login X.X.X.X:443 -u admin -p <admin-pass>
Error response from daemon: Unexpected http code: 400, URL: http://X.X.X.X:443/v2/
```

The error message suggests that a wrong schema is being used, however this is misleading - checking the docker personality logs reveals that the correct address is used first, but the connection fails, because the certificate is self-signed and untrusted. Then a http schema is applied for a second connection attempt that fails with the error that gets reported in the CLI.

**related docker-personality logs**
```
Apr 11 2017 13:44:34.444Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).AuthenticateToRegistry:289]
Apr 11 2017 13:44:34.445Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] https://10.192.189.62:443/v2/
Apr 11 2017 13:44:34.483Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [38.577614ms] https://10.192.189.62:443/v2/
Apr 11 2017 13:44:34.484Z ERROR Looking up OAuth URL failed: Head https://10.192.189.62:443/v2/: x509: certificate signed by unknown authority
Apr 11 2017 13:44:34.484Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] http://10.192.189.62:443/v2/
Apr 11 2017 13:44:34.485Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [1.289215ms] http://10.192.189.62:443/v2/
Apr 11 2017 13:44:34.485Z ERROR Looking up OAuth URL failed: Unexpected http code: 400, URL: http://10.192.189.62:443/v2/
Apr 11 2017 13:44:34.485Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).AuthenticateToRegistry:289] [41.698195ms] 
Apr 11 2017 13:44:34.485Z ERROR Handler for POST /v1.24/auth returned error: Unexpected http code: 400, URL: http://10.192.189.62:443/v2/
```

**Acceptance Criteria:**

`docker login` should suceed and the user should be able to push images in the secured registry.

**VIC version:**

```
$ ./vic-machine-windows.exe version
vic-machine-windows.exe version v1.1.0-rc4-9633-b89ebff
```

**Deployment details:**

vic-v1.1.0-rc4-fd3af9d7.ova deployed on a DRS-enabled cluster in vSphere. A `--no-tls` VCH is deployed on the cluster and is configured with the `--insecure-registry` option.

**Additional info**
`docker login` fails and seems to ignore the configured insecure registry, however, `docker pull` from that registry works just fine.

**Comment by jzt** [comment]
@shadjiiski Thanks for creating the issue. This has exposed a bug in how we handle insecure registry certs, as well as how and when it is acceptable to fall back to using http.

The only currently known workaround for this is to download the root cert from Harbor (or other private registry), and deploy your VCH this time using the `--registry-ca /path/to/root/cert` option.

Tagging @stuclem for documenting this workaround, and @hickeng & @sflxn for discussion. It appears we conflate the term "insecure" between "falling back to http" and "skipping cert verification". We should allow fallback to http if a user adds an http registry using `--insecure-registry`, and we should skip cert verification but not fall back to http when a user adds an https registry with `--insecure-registry`. In the case when only an IP address is added with `--insecure-registry`, we should attempt https, skipping cert verification, and, if that fails, falling back to http.

This applies to both the `PullImage` and the `docker login` paths. It would probably make sense to factor this logic out into a function/package that does all this checking/verification in one place.

**Comment by lcastellano** [comment]
The behavior of the pull image path was fixed with: https://github.com/vmware/vic/pull/4396. However I agree it would make sense to have common code for pull and login.

**Comment by stuclem** [comment]
@jzt Registry deployed from the OVA always uses HTTPS, with no option for HTTP. So, is this an issue for vic-product?

**Comment by jzt** [comment]
@stuclem yes, it currently is an issue. We are not skipping cert verification for registries we have added as insecure, but only in the `docker login` path (thanks for the heads up, @lcastellano).

**Comment by stuclem** [comment]
Thanks @jzt. Belatedly, here's an attempt at a write up:

-----

- <b>Cannot login to insecure registries that use self-signed certificates. [#4681](https://github.com/vmware/vic/issues/4681)</b><br> If you deploy a VCH with the --insecure-registry option, and if that registry uses self-signed certificates, attempts to use `docker login` to log in to the registry fail with `Error response from daemon: Unexpected http code: 400, URL: http://X.X.X.X:443/v2/`. However, performing `docker pull` from that registry without attempting `docker login` succeeds.

Workaround: Download the self-signed certificate from the registry and redeploy the VCH, specifying the path to this certificate in the `--registry-ca` option.

-----

Is this OK? Thanks!

**Comment by RobertEShaw** [comment]
I can validate creating VCH's in vic 1.1 using the --registry-ca option works in terms of connecting to the VCH and then logging into its Harbor registry successfully to pull down images. Too bad the default Harbor OVA ships with 0 local images to test other than templates that depend on registry access to Docker hub. I can upload images to the Harbor appliance using SCP, then using Docker load I can add images and see them using Docker images on the Harbor appliance but, the Harbor registry does not appear to first try local images before going straight to the registry defined in Harbor which is "https://registry.hub.docker.com" when doing a Docker run from a VCH logged into its registry.

However, the issue I am having is getting my Docker client to successfully log into the Harbor registry to push images to it since we do not have Internet access. I tried adding the ca.crt from Harbor into the Docker client configuration using both IP and FQDN for the registry. I tried adding EXTRA_ARGS and DOCKER_ARGS to also specify using the insecure registry flag and it seems to be ignored in the client.  
My Docker client can pull images from Docker, just not log into the Harbor registry to load them. 
VCH can log into the registry, Docker client cannot even with certificates added. 
Any help or advice on this? Thanks
Details of client:
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Connected to the VCH...logged into the registry.

docker@default:/mnt/sda1/var/lib/boot2docker$ docker login xxx.xxx.xxx.xxx
Username: admin
Password:
Login Succeeded

docker@default:/mnt/sda1/var/lib/boot2docker$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

docker@default:/mnt/sda1/var/lib/boot2docker$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v1.1.0-9852-e974a51
Storage Driver: vSphere Integrated Containers v1.1.0-9852-e974a51 Backend Engine
VolumeStores:
vSphere Integrated Containers v1.1.0-9852-e974a51 Backend Engine: RUNNING
 VCH CPU limit: 358572 MHz
 VCH memory limit: 2.922 TiB
 VCH CPU usage: 34319 MHz
 VCH memory usage: 1.878 TiB
 VMware Product: VMware vCenter Server
 VMware OS: win32-x64
 VMware OS version: 6.0.0
Plugins:
 Volume:
 Network: bridge
Swarm: inactive
Security Options:
Operating System: win32-x64
OSType: win32-x64
Architecture: x86_64
CPUs: 358572
Total Memory: 2.922 TiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io
docker@default:/mnt/sda1/var/lib/boot2docker$

**Comment by sflxn** [comment]
This is fixed in an upcoming PR for whitelisting registries.

**Comment by RobertEShaw** [comment]
Thank you!

**Comment by samhitendra** [comment]
This is the issue with the VIC as it has self signed certificate and the registry or vch does not recognize it.
To resolve this issue, go to the management portal, navigate to administration and then to configuration. Download the root registry certificate from the portal and keep it handy.
Next, login to the VIC machine and create a folder called certs.d under /etc/docker. Now create a a folder with the name same as the VIC. Now create a file under the VIC named folder called ca.crt. Copy the root registry certificate to this file.
Next while deploying the VCH, use --ca-registry and give the path to where the root registry certificate got downloaded on the local machine.
This should fix the issue.
Thanks.
