### ISSUE TITLE
UI plugin install for windows - edit install.sh needs to be better

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#4692]
This step needs to be better, at a minimum we need to support windows as our primary install target not darwin or linux.

```
(Optional) If you unpacked vSphere Integrated Containers Engine on a Windows system, open the /vic/ui/HTML5Client/install.sh file in a text editor and point PLUGIN_MANAGER_BIN to the Windows UI executable.

Before:

if [[ $(echo $OS | grep -i "darwin") ]] ; then
    PLUGIN_MANAGER_BIN="../../vic-ui-darwin"
  else
    PLUGIN_MANAGER_BIN="../../vic-ui-linux"
After:
if [[ $(echo $OS | grep -i "darwin") ]] ; then
    PLUGIN_MANAGER_BIN="../../vic-ui-darwin"
   else
    PLUGIN_MANAGER_BIN="../../vic-ui-windows"
```

**Comment by stuclem** [comment]
@jooskim and @mhagen-vmware, by my understanding, the shell scripts are for deploying the UI to VCSAs, and the batch script is for installing the UI on VCs that run on Windows. The type of VC deployment is independent of the platform on which you use VIC Engine.

- If  you are deploying the UI plug-in to a VC that runs on Windows, you must use the `install.bat` script. You therefore must run it on a Windows machine. So, if you are a habitual Linux user who downloaded VIC Engine to a Linux machine, you have to download VIC Engine to a Windows machine in order to run the `install.bat` script to install the UI on a VC that runs on Windows.
- On the other hand, if you are a habitual Windows user (the majority of our customers), and if you downloaded VIC Engine to a Windows machine but your target VC is a VCVA, there is no `install.bat` script. The only script for installing the UI on a VCSA is `install.sh`. That's why I included the instruction to hack `install.sh` in the VCSA deployment doc and to run it in Cygwyn or Git bash. 

My logic was that habitual Linux users who are deploying the UI to a Windows VC have access to the Windows machine where VC is running, so they can run the `install.bat` script on that machine to install the UI. However, there's no guarantee that habitual Windows users will have access to a Linux machine if their target VC is a VCSA.

**Comment by jooskim** [comment]
Thanks for clarifying your point Stuart. What you said was true for the deployment method without a web server which involved SSHing and copying the plugin contents to the target vCenter Platform Services Controller. SSHing to vCenter for Windows will not work and that's how we ended up agreeing that `install.bat` should be run on Windows for vCenter for Windows instances. Now that we do not support the no-webserver approach in the user document (`install.sh` is still capable of doing this) this restriction has been lifted. What either `install.bat` or `install.sh` does now is simply read the plugin manifest file and call `vic-ui-$platform` to register the plugin with the target VC using vSphere API, which means either script doesn't care which type of VC instance the target is.

**Comment by stuclem** [comment]
@jooskim I'm confused. Are you saying that you **_can_** use `install.bat` to deploy the UI to a VCSA, and `install.sh` to install to VC on Windows?

**Comment by stuclem** [comment]
@jooskim, just to clarify, I'm talking about 1.1 here. If it is now possible to deploy the UI across platforms, is this change in 1.1, or did you merge it afterwards? Thanks!

**Comment by jooskim** [comment]
@stuclem Yes you are correct that you can use `install.bat` to deploy UI to a VCSA and `install.sh` to a VC Windows, as we support only the installation scenario using a web server. The previous restriction on script to use was exclusively because of the fact we had to support the no-webserver scenario. And this changes was made around 1.1 RC3 so it should be the same in the GA version.

**Comment by jooskim** [comment]
It must be quite confusing to you and Dani, as we didn't set aside time to discuss this change, but the overall experience got a little better, as the user no longer has to figure out which script to use based on which type of vCenter they're running aside from the guest operating system on which they run the script.

**Comment by stuclem** [comment]
@jooskim, I see. If the changes went into RC3 then it's quite probable that I based the doc on an earlier build.

**Comment by corrieb** [comment]
@mhagen-vmware has this been resolved to your satisfaction? Let's close if so
