### ISSUE TITLE
ESX agent: vSocket relay Proof-of-concept

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#472]

**Comment by hickeng** [comment]
@dougm this needs to happen relatively soon so that we can start to figure out the problems that come with it - it's one of the big unknowns at this point.

**Comment by corrieb** [comment]
I have asked @kreamyx to take on this piece of work. The way I see it, we have to move away from Serial Port communications ASAP due to the known issues, the most significant of which is https://github.com/vmware/vic/issues/3492. I'm aware this issue is closed, but the fix is far from ideal.

**(1)** The first step we need to address is what the scope of this work will be. Eg.
- Is the vSocket relay with ESX agent the only option here, or is there further investigation to be done about the potential for other solutions?
- If we are going down the path of introducing an ESX agent, what constraints do we want to place on that work? Should it be written in Go (dependency on vmware/vic#3623)? Should it incorporate the firewall work we're looking at here (https://github.com/vmware/vic/issues/3821)
- Should this just be for attach (stdout, stderr, stdin, tty) or should it also cover the file-backed serial ports used for logging?
We don't have to have definitive answers to all these questions to start making progress

**(2)** We then need to make sure that we're all clear on the benefits and limitations of the technologies we have available. Are we depending on things that are about to be deprecated for example? We really need a contact in vSphere to discuss this with. Suggest we start with @dilpreetbindra. This will be a research spike for @kreamyx.

**(3)** In parallel with (2), we need to lay out the requirements, workflows and basic spec. How do we expect the Appliance and containerVMs to connect to the relay on a respective host? How do the relays connect to each other? What grammar / format should be used for data flow? Does vCenter need to know about any of this, or does it all happen at a host level? What happens if a host agent isn't installed or is not functioning?

I am going to set up an initial meeting early next week to discuss

**Comment by corrieb** [comment]
Good call today to discuss this. Summary here:

Turns out the vSocket relay with ESX host is definitely not the only option and may even be the least desirable option. There was confirmation in the room that requiring ESX VIB installation prior to something being functional can significantly slow adoption as many customers have a security process that must be gone through before doing such a thing.

As such, we came up with three options to investigate:

**1) Virtual Serial Port Concentrator.** 
See https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-A779C84D-4324-4D32-AF43-BBD962ABC9E3.html. 
_The Virtual Serial Port Concentrator (vSPC) aggregates traffic from multiple serial ports onto one management console. vSPC behavior is similar to physical serial port concentrators. Using a vSPC also allows network connections to a virtual machine's serial ports to migrate seamlessly when you use vMotion to migrate the virtual machine. For requirements and steps to configure the Avocent ACS v6000 virtual serial port concentrator, see http://kb.vmware.com/kb/1022303_

The main objection to the VSPC from @hickeng was the performance overhead of the telnet protocol and the potential complexity of integration. However, this was cited as "the right way to do serial ports with vMotion" by the ESX experts and may present the best medium-term fix.

**2) VMCI**
VMCI is a way for a VM to talk to another VM via the backdoor, bypassing a network stack. It is limited to talking to other VMs on the same host and thus, when we'd considered this as a possibility, we'd talked about the need for a vSocket relay on each host. It is probably one of the most performant options, but it does drop the connection on vMotion. 

Given the agreement in the meeting to try to avoid ESX host agents, it was mentioned that some work had been done to integrate VMCI with Rabbit MQ and the work may have been abandoned. If that gives us the option to buffer output during the vMotion and is well-integrated into the vSphere appliance, that could be a good option. Downside is potential dev cost.

**3) Remote USB**
We learned in the meeting about "remote USB", which basically allows a VM with a USB connection to be vMotioned and for the connection to remain established subsequently. While it was acknowledged that this may come with a whole new set of problems, it's worth investigating as it could be a relatively simple drop-in replacement for the serial port connection.

#3937 has been created to track the investigation work of these three options

**Comment by hickeng** [comment]
This no longer belongs in vmotion support as the vSPC has ticked that box for now, even without this.
