### ISSUE TITLE
[ova] Add default VCH to default project in Admiral

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic#4732]
PRD 2.4 
* The “Default VCH” should be automatically added to the “Default project”
Depends on #4730 and #4731

**Comment by andrewtchin** [comment]
Reopening because this adds the demo VCH to Admiral's hosts, but we don't yet have an API to add it to the default project. The relationship between cluster and projects is unclear at this time as currently "Add/remove hosts to/from Clusters" is not implemented
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=230746111

**Comment by andrewtchin** [comment]
follow the first API example in confluence to create a default cluster with VCH; use tenantLinks to assign it to the default project

**Comment by karthik-narayan** [comment]
@andrewtchin can you comment on how much work is left here? We moved it out, but if its a simple fix, I'd like to get this back in.

**Comment by andrewtchin** [comment]
@karthik-narayan @morris-jason took care of this 👍

**Comment by morris-jason** [comment]
Done, closed with vic-product/#545 and vic-product/#542.
