### ISSUE TITLE
Swap space for cVM

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#4773]
Pardon me if my search skills weren't good. 

Is there a way, I could add Swap space for the cVMs? Its okay if its on a separate vmdk. Thanks.

**Comment by malikkal** [comment]
testing this in the entrypoint script along with other entrypoint workarounds. Any thoughts?

#Creating swap...
dd if=/dev/zero of=/swapfile bs=1024 count=4194304
mkswap /swapfile
chmod 0600 /swapfile
swapon /swapfile

downside is that I need a larger base image, although it doesn't slow down things much. It would've been nicer, if I could have a dedicated vmdk for swap for the cVM. probably difficult to implement...

**Comment by hickeng** [comment]
@malikkal The lack of a configured swap device currently is partly because we've not yet done testing to determine whether we're better off with in-guest swapping behaviour and a smaller amount of memory configured for the containerVMs, or host swapping and a larger amount of memory, and partly because it's not clear whether it's desirable in every circumstance.

The following, relatively simple, approaches are available to us:
1. configure a swap disk for every containerVM and configure automatically based on initial container memory configuration.
2. modify the volume logic to allow for raw devices (i.e. not mounted) and/or handling for custom types, i.e. `swapon` if a volume configure for swap if found - this would allow placement of swap on a specific volumestore which may be desirable from a performance perspective and could be useful for database use cases.

Does (2) work for your needs, or does it need to be completely invisible to the user of the containers?

A more involved future option would be to allow for addition of custom virtual devices, such as GPGPU, TPM, and pass-through configurations - these are already in-mind for the next revision of the port-layer, but will be potentially difficult to expose in a clean manner via the docker API.

**Comment by malikkal** [comment]
Understand. Thank you @hickeng .

The cVMs in the particular use-case will be right-sized with appropriate memory and guestOS swapping will be undesired. They intend to be part of a compute grid and any performance impact is unwelcome. Also, we don't expect host swapping to occur in our production environment, as the cluster resources are very well sized.

The need for swap came from certain applications that actually look for configured swap space, whether there would be eventual swapping or not. The application process would either fail to start (or at least that's the claim) or goes unsupported.

Given a choice, option (1) would be great, where an automatically configured vmdk relative to the configured memory size is part of the cVM. However, if you advise performance would be better via the volume store option, I would go with your recommendation. 

in the interim, do you foresee any issue with the script approach, though the init time increases based on the count configured for dd. :(

**Comment by mhagen-vmware** [comment]
@hickeng sized at a 1 for now just to answer the customer's last question on swapiness. For implementing a feature to make this configurable, we can create a different issue later if we want to.

**Comment by hickeng** [comment]
@malikkal I see no issue with the script, but I suggest you add a check for existing swap space before the creation so you don't have to rebuild the images when it's available.

@carlsone Do you have `swapiness` recommendations? I can comment but it would inherently be speculation.

**Comment by malikkal** [comment]
Thanks both. I will use `echo 1 > /proc/sys/vm/swappiness` for now.

**Comment by malikkal** [comment]
1. Using docker volume store for /swap/swapfile
2. changed above `dd if=/dev/zero of=/swapfile bs=1024 count=4194304` to
`fallocate -l xxG /swap/swapfile`
3. startup performance has noticeably improved.

**Comment by hickeng** [comment]
@dougm balloon driver support? ;)

**Comment by hickeng** [comment]
@jzt @matthewavery
I think we have the following options:
1. allow configuration of a swap partition in the scratch disk that is available for all subsequent containers (with LVM to allow for resizing)
2. allow for filesystem swap on a per container basis - based on swap config during create
3. support `fstype` option to the volume driver and add support for `linux-swap`

(1) is the least user overhead but also the most inflexible
(2) may need some custom masking to avoid committing swap files which would be a disaster given the type of information that goes into them
(3) most flexible and allows control of the disk type backing it, but requires the most user knowledge for effective use.

**Comment by YanzhaoLi** [comment]
I think swap is not usually used in cloud native environment, since Kubernetes requires  its node to swap off.   Mark this as won't fix.
