### ISSUE TITLE
Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied.

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#4817]
docker image created with RHEL base works fine on engine version v0.8.0-7315-c8ac999. However fails on engine version: v1.1.0-9852-e974a51.

cVM powers on and powers off immediately afterwards during docker run -itd. using -it throws "Server error from portlayer: ServerFaultCode: Permission to perform this operation was denied." to the console.

could it be something on the startup script that offends the new engine? I change the hostname, modify hosts file and resolver etc. there.

I didn't find this in known issues. Also, I assume this release is enterprise [supported](https://github.com/vmware/vic/releases); will log a call shortly.

**Comment by dbarkelew** [comment]
Correct, if the release is download from VMware.com then it is enterprise supported official release. I see the case you opened up and ether I or my colleagues will communicate to you there. Thank you for informing us about this.

**Comment by chengwang86** [comment]
@malikkal Could you please copy-paste the `vic-machine create` cmd and also upload the log bundles?

**Comment by malikkal** [comment]
@chengwang86 Here you go.

vic-machine-windows create -t https://IP/DC --thumbprint <value> -u adminuser@domain --ops-user opsuser@domain --ops-password <password> -r CLUSTER -n hostname --endpoint-cpu 2 --endpoint-memory 8192 --base-image-size 16GB -i datastore1 --vs datastore2/hostname:default -b bridgeportgroup --pn userportgroup --mn mgmtportgroup --cn containerportgroup:igrid01 --cng containerportgroup:GWIP/24 --cnr containerportgroup:IPX-Y --no-tlsverify --registry-ca ca.crt --insecure-registry IP -f

logs are uploaded to the case 17439363XXX. let me know if you can see them. thanks.

**Comment by mdubya66** [comment]
@hickeng can you work with @dbarkelew on this issue.

**Comment by hickeng** [comment]
@malikkal I suspect this is missing privilege for the ops user endpoint role: `VirtualMachine.Config.EditDevice` - I believe that would map to the UI `Virtual Machine->Configuration->Modify Device Settings`

@stuclem This is incorrect in the current 1.1. docs: https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/set_up_ops_user.html and we also require `Virtual Machine->Configuration->Rename` now that @chengwang86 has added rename support.
I've updated #1689 which I'm using as a reference until we are automatically adding the requisite roles to the specified ops user during vic-machine create. @dougm is currently working on #764 for the SSO theme, which should allow us to automatically create a suitably configured ops-user per VCH without viadmin intervention.

**Comment by hickeng** [comment]
@malikkal The part I cannot usefully comment on at this time is:
> cVM powers on and powers off immediately afterwards during docker run -itd
From the logs it looks as though the script exited almost immediately with an exit code of `-1`.

I suggest correcting the privileges for running with `-it` and then launching the script interactively or with `-x`.

**Comment by malikkal** [comment]
@hickeng Thank you. Modified the ops role privileges and added as below:

```
Virtual Machine->Configuration->Modify Device Settings
Virtual Machine->Configuration->Rename
```

Although the permission error doesn't appear with -it, I can't even drop into the container shell to run interactively...

**Comment by hickeng** [comment]
@malikkal This appears to be because a recent updated to the Photon kernel configuration to reflect [current security best-practice](https://einsteinathome.org/content/vsyscall-now-disabled-latest-linux-distros) - they have disabled vsyscall emulation and legacy support:
https://github.com/vmware/photon/blob/4419063cbff8572b1db5cb24abc56cb152e71edd/SPECS/linux/config-esx-4.9.13#L458

This shows up in dmesg for the container as follows (note the `vsyscall=none`):
```
[   38.680829] yum[211] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffde0b8f198 ax:ffffffffff600400 si:7f399d98dfc0 di:0
```

Some additional details [here](https://cateee.net/lkddb/web-lkddb/X86_VSYSCALL_EMULATION.html)

I've tried rhel6.9 and rhel7.0 images and it appears that the glibc version in rhel7 image has been updated not to depend on the vsyscall emulation.
```
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker run -it registry.access.redhat.com/rhel6.9 /bin/bash
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker run -it registry.access.redhat.com/rhel7/rhel /bin/bash
Unable to find image 'registry.access.redhat.com/rhel7/rhel:latest' locally
Pulling from rhel7/rhel
e50b1d9e90ba: Pull complete
93b630859c0e: Pull complete
Digest: sha256:bb546e8d8a4fd16e038b91f35e036cda0d27a0d82ee34c3657a3937ec4d9f96f
Status: Downloaded newer image for rhel7/rhel:latest
[root@9d60cdb936ba /]#
```

Possible solutions:
1. move to rhel7 as the base image
2. we build a bootstrap ISO with a Photon kernel that has the emulation
3. we add an option that allows us to replace the glibc version in the container image [I don't think this is a good idea, but it would work in many cases]

**Comment by malikkal** [comment]
Thanks @hickeng . I had to understand what vsyscall is all about and [here](https://lwn.net/Articles/446528/) and [here](http://stackoverflow.com/questions/19938324/what-are-vdso-and-vsyscall) was a good start. :-)

However, it's a tough convincing the app folks to move to rhel7, particularly for the first few projects that are now being piloted for VIC.

Can we go with option 2, please? thanks.

**Comment by sguyennet** [comment]
I had the exact same issue with a Centos6 image running on QubeOS the other day.
Changing the kernel option to vsyscall=emulate solved the issue.

**Comment by hickeng** [comment]
@stuclem Regarding diagnostics for this - I actually modified the top layer of the RHEL7 image to add in a static busybox so that we could bypass whatever was going wrong with anything using glibc.
There's an easier way to accomplish this for future diagnostics and that is to create any arbitrary container with a volume, let's call it `debug`, populate that volume with diagnostic binaries of interest and potentially their library dependencies, then relaunch the problem image with that volume mounted and running a binary from within it. E.g.
```
run -v debug:/debug rhel6.8 /debug/bin/ash
```
