### ISSUE TITLE
Align server certificate argument names with filenames and be consistent across TLS options

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4901]
**Story**
As an admin I'd like vic-machine certificate options to be clear and not counter-intuitive

**Detail**
Currently we have `--cert` and `--key` as the option names for providing the VCH server certificate. The _filenames_ that docker client requires in order to use _DOCKER_CERT_PATH_ are `cert.pem` and `key.pem` but for the **client** certificate. This misalignment of naming causes confusion.

The vic-machine options should be renamed to the following to align with server certificate file names. The TLS prefix is to be consistent with other TLS related options:
`--tls-server-cert=` and `--tls-server-key=`
`--cert-path` becomes `--tls-cert-path`

**Acceptance**
- [ ] vic-machine options are renamed as specified
- [ ] help output from vic-machine is updated, e.g. `Unable to make directory to hold certificates (set via --cert-path)`
- [ ] tests are updated to reflect new names (primarily the 06-13 TLS group)
- [ ] the usage documentation and examples in the repo are updated with the revised names

**Comment by andrewtchin** [comment]
@gigawhitlocks

**Comment by hickeng** [comment]
Adding to Sprint12 as it has potential impact on generated command in UI for example - we should aim to get this done soon so we can identify follow up work.

**Comment by gigawhitlocks** [comment]
@hickeng I hate the way `--cert-path` is used, both as an input dir and an output dir. I find this to be one of the key sources of confusion in both using the certificate options as well as reasoning about the logic of the code inside the installer. I opened this issue a few days ago in order to expand on some of my thoughts w/r/t the usage of vic-machine cert options https://github.com/vmware/vic/issues/5525 and I suspect this issue (4901) is supposed to address those concerns, however, I'm not convinced that just renaming the flags to be more consistent will entirely address the usability issues with the certificates and I'd like to get the permission and agency here to fix these usability issues once and for all

**Comment by hickeng** [comment]
@gigawhitlocks This issue wasn't targeted at cert-path usage problems at all - was specifically about the confusion between the `cert.pem` NOT being what should be supplied to the `--cert` argument.
The only impact on cert-path was making the naming consistent.

Cert path was added because:
1. we need somewhere to save generated certificates and I didn't want to make people specify every filename in full every time
2. certificate consistency when re-deploying a VCH so as not to invalidate existing client certs - the necessity for this decreases as we add reconfigure support as you're less likely to deploy a fresh VCH to replace an existing one.

If we need to alter this behaviour for usability then I'd prefer to make it explicit and split the client/server configuration:
a. explicitly state that client certificates should be generated and saved in M, or that client CA should be loaded from N
b. explicitly state the server certificates should be generated and saved in P, or that server certificate chain should be loaded from Q

If we're loading client certificates then we should _try_ to load the actual client cert in order to do API validation, but should tolerate failure to do so and skip those final checks.

**Comment by gigawhitlocks** [comment]
I was not targetting `cert-path` due to a misunderstanding of what this issue is requesting, but rather out of a deep understanding of what makes the certificate flags difficult to understand. `cert-path` introduces a plethora of implicit behavior and makes the actual code much harder to follow as well. 

That said, I will not be attempting any of the suggestions in #5525 nor will I change the `cert-path` behavior as it does not appear that I have the agency to do so. Instead I will merely align the flags requested in this issue.
