### ISSUE TITLE
Docker Personality: Map source of metadata in VIC

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#498]
We need a good map of where all the metadata used in VIC, from the docker personality perspective, comes from, how they are generated, and how they are used.

Example:

When imagec pulls an image from docker, there is metadata associated with each layer (?).  There is also metadata created by VIC (storage and execution port layer).  There is also metadata override when a user interacts with the Docker personality server (via Docker CLI and curl).  How are the metadata overrides used?

Just to be complete and make sure we know whether we're complete, we should map this out and document it.

Attached to #338.

**Comment by fdawg4l** [comment]
@sflxn The storage layer is stateless.  It persists metadata but does not need to maintain any of its own (*).  Metadata persisted to the storage layer is defined in the interface.  This is currently in PR but you can take a look here (https://github.com/vmware/vic/pull/495/files#diff-2cf9c31763b0316d758f2ff6b90fdbcdR39).  Pay attention to the `Image` struct, and the `WriteImage` interface.  `GetImage` will get the image with its metadata.

Please define "overrides".  What do you mean?

(*)  Getting parent->child relationships of delta disks are not yet ready in vsphere.  We are keeping track of this relationship in a blob in the datastore until the API is available. See #482 for details.

**Comment by sflxn** [comment]
Overrides may or may not be the right description.  When you call docker create, you can set options such as env var and CMD.  I don't know all the scenarios, but I believe some of those options overrides or add to the metadata that is stored with image.  Caglar added a name resolution hack last week that illustrates this.

Right now, the important task is to figure out everything we need to know.  I think everyone has pieces of the puzzle, but to make sure we actually have this implemented correctly, we need to put together the whole puzzle.

**Comment by cgtexmex** [comment]
This is a documentation task.  The created document will be a "living" document in the sense that it will be updated / expanded as our work on the docker "personality" continues.  The initial iteration will look to achieve the following:

- Focus on the CLI commands of docker and identify commands and options that generate or consume metadata
- The documentation will leverage the docker CLI Compatibility matrix that was previously created
- Provide an approach / template to metadata documentation
-  Initial high-level mapping of docker metadata elements to VIC attributes / metadata

**Comment by cgtexmex** [comment]
Since we are mapping to a docker personality I think it might be wise to have an automated way to compare versions of the docker client / api.  For example if we start with support of 1.10.3 and then extend support to 1.11.0 we should be able to quickly identify differences in the CLI / API and generate the appropriate documentation.  At a minimum it the tool should be able to dump a markdown template that lists the docker command, options and differences from a previous / stated version.

**Comment by cgtexmex** [comment]
A few simple sequence diagrams have been created to illustrate the system interaction with regards to docker and vic.  Those are available to VMware employees at the following [link](https://docs.google.com/a/vmware.com/presentation/d/18RCf2CmIyzmoKyyBD68gZ-b_htEV8PtL2M2tOpFBOXc)

This issue is a prerequisite to issue #678 -- that architecture and this issue is targeted to be completed by May 20th

**Comment by cgtexmex** [comment]
Mapping of metadata is being completed in the various epics and issues where metadata is required.  The basic architecture was outlined in issue #678 , but that's a point in time snapshot and the ultimate architecture will be decided in the implementation of the related issues.
