### ISSUE TITLE
Exec echo test failure: Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5015]
```Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface != Help me, Obi-Wan Kenobi. You're my only hope.```

[integration_logs_10275_3bf485a6d108954f125adbadd01911b85f4fda43.zip](https://github.com/vmware/vic/files/976222/integration_logs_10275_3bf485a6d108954f125adbadd01911b85f4fda43.zip)

from personality:
```
May  3 2017 21:04:49.974Z ERROR container attach: stdout (2278f5bc074baa258e28bb3d1d3a637a82920bc3428050727bf930b20bfd8d1b): Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
May  3 2017 21:04:49.974Z ERROR container attach: stderr (2278f5bc074baa258e28bb3d1d3a637a82920bc3428050727bf930b20bfd8d1b): Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
May  3 2017 21:04:49.974Z INFO  cleaned up connections to 2278f5bc074baa258e28bb3d1d3a637a82920bc3428050727bf930b20bfd8d1b. Checking errors
May  3 2017 21:04:49.974Z ERROR container attach error: Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
```

weirdly, the portlayer seems to report success...
```
May  3 2017 21:04:50.010Z DEBUG op=259.30 (delta:28.377µs): ID: "2278f5bc074baa258e28bb3d1d3a637a82920bc3428050727bf930b20bfd8d1b"
May  3 2017 21:04:50.010Z DEBUG op=259.30 (delta:33.935µs): Path: "/bin/echo"
May  3 2017 21:04:50.010Z DEBUG op=259.30 (delta:45.111µs): Args: []string{"/bin/echo", "Help me, Obi-Wan Kenobi. You're my only hope."}
May  3 2017 21:04:50.010Z DEBUG op=259.30 (delta:51.564µs): Running: 0
May  3 2017 21:04:50.010Z DEBUG op=259.30 (delta:55.274µs): ExitCode: 0
```

**Comment by hickeng** [comment]
Portlayer does not report success. Port layer reports that it never got a report that the exec session was available for attach. The fragment @mhagen-vmware referenced is for an inspect call and is the same values as if the exec session had never been launched. We should add logging to disambiguate these cases:
```
May  3 2017 21:04:49.951Z ERROR attach connector: Connection not found error for id:2278f5bc074baa258e28bb3d1d3a637a82920bc3428050727bf930b20bfd8d1b: context deadline exceeded
```

Items of note from tether.debug - we never see any indication that the session IDs are reported to the portlayer. This would be the following messages (or similar):
1. `HandshakeServer: Connection established.`
2. `received global request type container-ids`
3. `Returning 2 keys`

The most important of which is (1) - it seems likely that the handshake never succeeded fully. We do get told that the tether received 15 bytes while expecting a syn, so this is likely because the portlayer thinks the handshake succeeded:
```
May  3 2017 21:04:19.927Z DEBUG HandshakeClient: Sending syn.
May  3 2017 21:04:19.928Z DEBUG HandshakeClient: Server didn't accept sync. Trying one more time.
May  3 2017 21:04:19.928Z DEBUG HandshakeClient: HandshakeServer: Server declined handshake request
May  3 2017 21:04:19.938Z DEBUG HandshakeClient: Sending syn.
May  3 2017 21:04:19.939Z DEBUG HandshakeClient: Sending ack.
May  3 2017 21:04:19.939Z DEBUG HandshakeClient: Connection established.
May  3 2017 21:04:19.939Z DEBUG attach connector: New connection
```

The handshake code is at fault - we need to check what occurs if we re-use position codes.

Workaround: retry attach - this should use the Ping check for liveliness which will fail, then the connection will get evicted from the portlayer.
