### ISSUE TITLE
Implement lower level API to manage snapshots/layers/images from containerd

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#5053]
Problem statement
===============
containerd is fully responsible for downloading and unpacking images into prepared layers/snapshots mounts, however, VIC does all that in one shot inside port layer, thus that makes it improssible to integrate it with containerd in a reasonable way.

Expected result
============
Port layer should expose API that is responsible for creating, attaching, mounting, unmounting delta vmdk which can be used by containerd VIC plugin to prepare image disk file system. So, instead of a single WriteImage call, containerd can create delta vmdk and unpack image content on them directly.

Exposed API should not overlap with existing WriteImage implementation, so it is safe to keep this functionality in parallel with no risk to affect core VIC workflow.

Details
=====
Requirements are relatively abstract and will be clarified during implementation and integration process. Requirements can be reduced or extended depending on the outcome.

**Comment by hickeng** [comment]
I completely disagree that we should implement yet more API surface. What you're describing is not compatible with the expressed intent of the port layer and will break completely were we to move the storage part of the portlayer to an agent which is the longer term plan.

If this is the same workflows that depended on the graph driver previously then they're written assuming that mounts are cheap, and for us they very much are not.

We should talk about how you're planning on doing containerd integration because I thought the previous conversation was about implementing the containerd API on top of the portlayer, not implementing a lower level API that containerd code is currently using.

**Comment by vburenin** [comment]
There is actually a reason for that. I think the best way to understand why is that necessary is would be reading a design doc of a snapshotter API in containerd

https://github.com/containerd/containerd/blob/master/design/snapshots.md

Here is a Snapshotter interface that we need to support:
https://github.com/containerd/containerd/blob/master/snapshot/snapshotter.go

**Comment by fdawg4l** [comment]
@vburenin , I have to agree with @hickeng here.  Looking at the design you've linked and the `snapshotter` interface defined, they completely overlap with what we've already built into the portlayer.  

Yes, `WriteImage` is our canonical call to create the new `delta` (or snapshot in `containerd` parlance). We also have API calls to enumerate, delete, and mount the `delta` images in our system, just like the `snapshotter` interface defines in its interface.

I'm concerned about the model being represented here.  It sounds like from your initial issue summary that the intent is to modify `containerd` to do what the PL already does by having `containerd` manage snapshots, mounts, commits, etc.  Is there a reason for that preference?

**Comment by fdawg4l** [comment]
One more detail which may be a bit forward looking, but a lot of work went into managing the lifecycle of our delta images.  We support CRD (we don't support Update since our images are immutable) without maintaining any state on the VCH.  Having to port this into a low level library outside of the PL is possible, but not trivial.  There will be lifecycle problems without thinking through the data model.

**Comment by vburenin** [comment]
Taking into account recent changes in containerd and high level abstraction that has been just implemented (diff service), extension of PortLayer with such low level API calls is not need for now.
