### ISSUE TITLE
Docker login responds with poor message with bad user/pass

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5195]
As a VIC user, I should be able to use a bad password with docker login and get a message that the username or password was incorrect.

---

Standard docker returns the following message when the user cannot be authenticated,

```
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

This is what VIC responds:
```
Error response from daemon: download cancelled during retry delay
```

There's a bug in our OAuth code for bad user/pass.

**Comment by sflxn** [comment]
@rogeliosanchez Tried with 1.1.1 release.  I tried with 1.1.1 code tag.

**Comment by sflxn** [comment]
The underlying code seems to take different paths depending on whether I used Harbor or docker hub.

**Comment by mdubya66** [comment]
not a high priority. probably needs a release note due to the difference in behavior.  we should release note the behavior as it is different from docker

**Comment by willsherwood** [comment]
I have identified that we get the correct OAuth URL by parsing out the bearer field of the www-authenticate header. Then we attempt to fetch the auth token which internally calls Fetch. Then, the process diverges:

Incorrect password: At this point, Fetch sees that the connection is unauthenticated (HTTP 401) and goes to get the bearer field from the www-authenticate header. Now, Docker only sends `www-authenticate: Basic realm="auth.docker.io"`. Since there is no bearer field, a retryable error is bubbled up to fetch. It retries to parse the field endlessly until timeout, which produces the final error `download cancelled during retry delay`.

Correct password: Fetch sees the connection is authenticated and correctly retrieves and returns the token.

**Comment by sflxn** [comment]
This issue still persist with Harbor.  @willsherwood, can you relook at this against Harbor?

**Comment by willsherwood** [comment]
I'm having trouble reproducing the issue with a harbor instance.

Using vanilla docker, I can authenticate just fine. (i.e. `docker login <harbor ip>`), but I can't authenticate at all through a VCH (i.e. `docker --tls -H <VCH ip> login <harbor ip>`). The error I receive is that it cannot verify the certificate, but I don't see how that can be the case when I can pull & push images.

**Comment by willsherwood** [comment]
Pending an integration test. The Harbor robot utility package currently does not function properly to copy server certificates since the removal of Harbor UI. When Admiral provides the necessary API for accessing Harbor instances, the test should be trivial to write:

1) Start an instance of harbor, or use an existing one
2) Login with an incorrect password and verify that an 'invalid username or password' message is shown, and not another obscure error.
3) Login with a correct password and verify that we can correctly pull a private image.
