### ISSUE TITLE
Nightly 6.5 VSAN Complex test failure:  vic-machine failed to validate datastore path

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5209]
```
May 21 2017 04:50:10.304Z ERROR error parsing datastore path: parse ds://vsanDatastore%20%281%29/test: invalid URL escape "%20"
```
Path supplied:
```
May 21 2017 04:50:04.933Z DEBUG --volume-store=vsanDatastore (1)/test:default
```
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1019868/5-6-2-VSAN-Complex.zip)

**Comment by matthewavery** [comment]
Looking at this, it is likely that the input must be wrapped in quotations. Since there is a space in the volume store path. This often occurs because we do not get a deterministic volumestore path target. Depending on the order that the stores we target get made in nimbus. We should take a look at how we formulate the Vic machine create command.

**Comment by mhagen-vmware** [comment]
dupe #5354 
closing in favor of that with more details and actively being worked.
