### ISSUE TITLE
Research spike: requirements for docker diff

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5254]
**User Statement:**

As a developer, I would like to know the requirements for successfully implementing `docker diff`.

**Details:**

The `docker diff` epic needs to be decomposed, and issues that currently exist within the epic need to be checked for validity. Issues already in the epic should be removed if they don't belong, and those that do should be checked for proper acceptance criteria and estimation.

**Acceptance Criteria:**

The technical details behind `docker diff` should be spelled out understandably with issues that are broken down into reasonably-sized tasks.

**Comment by hickeng** [comment]
The diff workflow for powered-off containers looks as follows:
1. identify the container vmdk and its parent
2. attach both the parent and the container disk as non-persistent disks to the applianceVM
3. mount the parent and container disks
4. run the diff operation and package the results as a docker tar archive
5. return the archive to the user

2 - 4 are port layer operations.

If we are also to consider powered on containers (I __highly__ recommend against it for this release) then we also need to implement the backend operations for pause/resume: #4756
An alternative would be to create a snapshot for the running VM that we can use for out of cycle diff, however that has the following issues:
1. no assurance of file consistency as could split an in-flight operation
2. rapid exhaustion of maximum delta layers or a need to pause/resume the container VM in order to perform consolidation operations (consolidation requires the VM be powered off or suspended, see `llpm.consolidateDisks`).
