### ISSUE TITLE
Nightly 6.5 5-2-Cluster failure: govc cluster.add duplicate host

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#5278]
From `output.xml` (attached):

Test `5-2-Cluster`

```
govc cluster.add -hostname=10.192.248.134 -username=root -dc=ha-datacenter -password=e2eFunctionalTest -noverify=true 2>&1'.	
20:22:17.645	INFO	${out} = 
[K[26-05-17 01:22:17] adding 10.192.248.134 to cluster /ha-datacenter/host/cls... 
[K[26-05-17 01:22:17] adding 10.192.248.134 to cluster /ha-datacenter/host/cls... Error: The name '10.192.248.134' already exists.
govc: The name '10.192.248.134' already exists.' does not contain 'OK'
```

[5-2-Cluster.zip](https://github.com/vmware/vic/files/1033002/5-2-Cluster.zip)

**Comment by mhagen-vmware** [comment]
In this case, nimbus actually gave us a duplicate IP address for a totally differently named server:
```
19:36:40.151	INFO	${esx1} = svc.victestuser-ESX-4387	
19:36:40.151	INFO	${esx1-ip} = 10.192.248.134
```
```
19:57:06.304	INFO	${esx2} = svc.victestuser-ESX-8720	
19:57:06.304	INFO	${esx2-ip} = 10.192.248.134
```

**Comment by mhagen-vmware** [comment]
After thinking on it overnight, I could put in some protections against this, but a properly behaving DHCP server and network should not do this.  Instead of putting in some hackery into our test, I am going to close this for now.  Please reopen if we see this again, but hopefully this was just some weird networking/DHCP server blip that we don't see again.
