### ISSUE TITLE
github.io link to VIC docs is wrong

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5375]
See https://vmware.github.io/vic-product/#documentation

The link "GO" takes you to https://vmware.github.io/vic-product/files/html/1.1/index.html which gives 404 not found.

![screen shot 2017-06-05 at 3 41 11 pm](https://cloud.githubusercontent.com/assets/1699842/26806419/9d1c9d16-4a05-11e7-8fa2-092940b91bf4.png)
![screen shot 2017-06-05 at 3 40 52 pm](https://cloud.githubusercontent.com/assets/1699842/26806420/9d1c8632-4a05-11e7-8407-1a29ed3e2a90.png)

**Comment by anchal-agrawal** [comment]
Pinging @stuclem - please move this issue to vic-product if necessary.

**Comment by stuclem** [comment]
This started with the overhaul by Web marketing of the landing pages, to use the Clarity look and feel. It looks like they keep on making changes without sync'ing, thus overwriting the fix every time I fix the link. I will fix it again and will sync up with them to make sure that they stop overwriting my changes!

**Comment by stuclem** [comment]
Fixed: https://vmware.github.io/vic-product/#documentation so that the link now works again.

Also fixed the title for https://vmware.github.io/vic-product/#gettingVIC to make "Container" plural, updated the links in https://vmware.github.io/vic-product/archive/ and reinstated the link to https://console.cloud.google.com/storage/browser/vic-engine-builds/ in the Download section.

Details are in https://github.com/vmware/vic-product/pull/268 and https://github.com/vmware/vic-product/pull/269.

@anchal-agrawal can you please cast another set of eyes over the page to make sure that all links are now working correctly? 

Thanks!

**Comment by anchal-agrawal** [comment]
@stuclem Thanks for fixing the links! The fact that website UI changes affect availability of docs is very concerning (pinging @mdubya66) - doc availability should take precedence over any UI enhancements. Is there a way to prevent this w/o manual sync-up? If the UI changes go into the vic-product repo, we should setup a PR review system (VIC Engine uses pullapprove.com). Please let me know if you'd like to setup pullapprove for vic-product, it's quick and easy.

**Comment by anchal-agrawal** [comment]
I see it's already been addressed in https://github.com/vmware/vic-product/issues/266 - awesome!

**Comment by stuclem** [comment]
Hi @anchal-agrawal no problem - and to clarify, I'm talking about the Clarity look and feel on the vmware.github.io pages, no in the UI.
