### ISSUE TITLE
OVA VIC Engine Web Installer firewall update

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5393]
**User Statement:**
As a VI admin I want to be able to run `vic-machine update firewall` command from the VIC Engine Web Installer.

**Details:**

**Acceptance Criteria:**
Specific deliverable and actionable items that the story needs to deliver in order to be considered complete, the more detail here the more accurate the implementation will be.

- [ ] Checkbox that runs `vic-machine update firewall`
- [ ] Docs

**Comment by stuclem** [comment]
I'm in the process of documenting the VCH Web Installer. The fact that you still have to download the VIC Engine bundle in order to run `vic-machine update firewall`  before you can use the Web Installer is not ideal. The whole purpose of the Web Installer, in 1.2 at least, is to provide a quick n easy way to start playing with VCHs without having to go through the whole process. 

So, @mdubya66, is there a way to get this into 1.2?

**Comment by andrewtchin** [comment]
Closing as this will be deprecated soon
