### ISSUE TITLE
Implement function to attach a non-persistent disk to an existing vmdk

### ISSUE THREAD

**Issue by jzt** [vmware/vic#5422]
As a developer, I need to be able to attach a non-persistent disk to an existing VDMK.

Details:

Currently, the disk layer in the storage component does not provide the ability to attach a non-persistent disk to an existing VMDK. We need this functionality to make it possible to produce a change set between two VMDKs. This is required for `diff`/`commit`/`push`/`save`/`export`/etc...

Requirements:
- [ ] A function that abstracts the following:
- Creation of a disk spec with capacity 0 and non-persistent flag (and other appropriate flags) that is then passed to `Attach`
- A subsequent call to `Mount` so that the disk path can be presented to the caller
- [ ] Unit test(s)

**Comment by hickeng** [comment]
@caglar10ur @jzt if viable, please write this in such a way that non-persistent can be toggled based on a read-only/read-write flag. Otherwise we'll need a separate path to support copyTo.

If the code is small enough then I'm fine with having a separate function for creating the different spec, but do not want to have a separate attach path.

**Comment by hickeng** [comment]
@jzt is this closed by the virtual disk config changes?
