### ISSUE TITLE
OVA fileserver includes docs link

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5459]
**User Statement:**

As a user I want a link to the docs to be easily accessible on the OVA fileserver. 

**Details:**

**Acceptance Criteria:**
- [ ] OVA fileserver has a link to the docs

**Comment by stuclem** [comment]
@andrewtchin I'm not convinced that this is a good idea. As a company we are moving away from embedding docs into products. Once docs are bundled with a product, they are completely static and rapidly go out of date, and cannot be updated until we release the next version or patch. For example, I have posted two updates of the 1.1.x docs to vmware.github.io since 1.1 GA, and have a third update in the pipeline that I hope to post by the end of this week. By putting a copy of the docs in the OVA, we have to accept that the bundled version will very likely go out of date shortly after a given GA, and that it will not be in sync with the online version.

When we were talking about prettifying the landing page of the file server at yesterday's demo, my suggestion was to include a link to the online docs in that page. Then, if you go to https://vmware.github.io/vic-product/assets/files/html/1.1/, you see a link to **Printable PDFs** in the left TOC column. These PDFs provide customers with an offline version of the doc, and they are updated whenever I generate and publish a new version of the HTML. So, I think that users with no internet connections are covered.

Incidentally, I will change **Printable** to **Downloadable** in the TOC.

**Comment by andrewtchin** [comment]
OK, updated the issue

**Comment by andrewtchin** [comment]
Moved to include this in https://github.com/vmware/vic/issues/5458
