### ISSUE TITLE
Docker logs --since sometimes does not work

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#5477]
From build: https://ci.vcna.io/vmware/vic/11532

In 1-08-Docker-Logs, Docker logs with timestamps and since certain time test:

```
${rc} = OperatingSystem . Run And Return Rc docker %{VCH-PARAMS} run busybox sh -c 'for i in $(seq 0 9) ; do sleep 1 && echo line $i; done'
BuiltIn . Should Be Equal As Integers ${rc}, 0
${rc}, ${containerID} = OperatingSystem . Run And Return Rc And Output docker %{VCH-PARAMS} ps -a -q |head --lines=1
BuiltIn . Should Be Equal As Integers ${rc}, 0
${rc}, ${lines} = OperatingSystem . Run And Return Rc And Output docker %{VCH-PARAMS} logs --since=5s ${containerID} |wc -l
```

In this sequence we echo to the logs 1 line per 1 sec over the course of 10 seconds, any follow on docker logs --since=5s should never provide all 10 lines.

**Comment by jzt** [comment]
@mhagen-vmware have we seen this at all recently? This is an inherently racy test dealing with time - if the process in the container completes, but the container VM shutdown takes close to or more than 10 seconds to complete, our time window is hosed and this test will fail. 

I don't know of a better way to test this since we are relying on the passage of time as a variable to the test, but its the one thing we can't really control in this scenario when it comes to vSphere, network, whatever else.

**Comment by jzt** [comment]
The only thing I can think to attribute this to is a clock skew. Client issues the `docker logs --since` command but has a system time significantly earlier than that of the VCH, allowing all 10 lines to show up even though the test started >10s ago. It's the docker client that actually constructs the timestamp to send up to the docker daemon. Having them on separate hosts is what allows this to be an issue, also the fact that we (at the time of this issue) were still not using ntp. If we are using ntp now, I suspect we won't see this issue anymore.

**Comment by mdubya66** [comment]
Closing.
