### ISSUE TITLE
nightly test 21-1-whitelist unable to confirm secure registry

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#5538]
Seen on vsphere 6.5 

[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1089156/21-1-Whitelist.zip)

also 6.0
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1089167/21-1-Whitelist.zip)

From vic-machine log
```
Jun 20 2017 08:26:17.631Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [606.93µs] http://harbor.ci.drone.local/v2/
Jun 20 2017 08:26:17.631Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jun 20 2017 08:26:17.631Z DEBUG URL: 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [40.38µs] 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z WARN  Unable to confirm secure registry 10.160.126.191 is a valid registry at this time.
Jun 20 2017 08:26:17.631Z INFO  Insecure registries = harbor.ci.drone.local
Jun 20 2017 08:26:17.631Z INFO  Whitelist registries = 10.160.126.191, harbor.ci.drone.local
```

**Comment by corrieb** [comment]
This is continuing to fail:

```Jun 22 2017 19:04:26.025Z WARN Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.```

**Comment by corrieb** [comment]
Still failing on 6/26

**Comment by hickeng** [comment]
I would not expect `harbor.ci.drone.local` to resolve in the nightly environment - i've opened #5598 to address the fact it's present in the nightlies at all.
Looking at the drone output the IP we're trying to connect to (`10.192.180.174` in the 21-1-Whitelist bundle for 6.0) appears to be correct and the page pulled down by curl during the harbor deployment looks correct.

Looking at the timestamps there's no 10s delay as with the `harbor.ci.drone.local` attempt which likely means connection refused or similar rather than timeout. Unfortunately we're not logging the error even at debug level:
```go
		if _, err = registry.Reachable(w.String(), w.URL().Scheme, "", "", pool, registryValidationTime, false); err != nil {
			log.Warnf("Unable to confirm secure registry %s is a valid registry at this time.", w)
		}
```
should be (or similar):
```go
		if _, err = registry.Reachable(w.String(), w.URL().Scheme, "", "", pool, registryValidationTime, false); err != nil {
			log.Warnf("Unable to confirm secure registry %s is a valid registry at this time.", w)
			log.Debugf("Attempt to access registry failed: %s", err)
		}
```
