### ISSUE TITLE
Improve H5 plugin install.sh

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5552]
**Story**
As a viadmin I want to be able install/upgrade the H5 plugin with as minimal interaction as possible

**Detail**
The current install and upgrade scripts for the H5 client requires editing of a config file before running the scripts. The bulk of the edits are for the connection data for the OVA file server.
This issue should generate the config file that's returned, injecting the URL, and thumbprint for the OVA file server.
User should still be prompted for:
* vCenter IP
* vCenter credentials

It's possible that the config file should be removed completely and these changes be injected into the install/upgrade scripts - this would allow a single file instead of needing a tar or multiple downloads.

**Comment by jooskim** [comment]
Assigning myself to this issue along with Emma, as I wrote the scripts

**Comment by emlin** [comment]
@hickeng Per discussion with @jooskim , we prefer to keep the current config file, as that will keep similar user experience.
And also cause the configuration is separated, user could easily know what server information is used. In the worst case, if there is anything wrong happens during ova data population, it is still easy to manually correct the separate config file instead of search in a long script file.

**Comment by andrewtchin** [comment]
After the user enters the credentials and target, I would like this to display the fingerprint and prompt the user to accept it so they can verify it if they want

**Comment by jooskim** [comment]
I think that's a good addition. @emlin what do you think? Assuming we ask the VC IP in `install.sh`, then it should prompt the user four times - VC IP, VC admin ID, VC admin PW and thumbprint verification.

I can modify the script such that it calls `vic-ui` twice for Flex and H5 Client plugins.

**Comment by emlin** [comment]
@andrewtchin are you talking about VC thumbprint or file server's thumbprint?

**Comment by andrewtchin** [comment]
That's for vcenter fingerprint since we don't want to give vcenter creds to man in the middle

**Comment by jooskim** [comment]
btw, if we want to verify the VC fingerprint how do we get it from the machine where the script is run? we don't assume the user has `openssl` or something

**Comment by emlin** [comment]
@jooskim that's what I'm typing. With this requirement, vic-ui command should be updated to get back this information.
In your script, you can printed out the thumbprint got from vic-ui, and then user could simply trust that information, or try to get back that information from web browser, and posted into the command

**Comment by emlin** [comment]
@karthik-narayan @bradmeiseles @mdubya66 

To improve user experience of installing UI plugin in 1.2 release, we're planning to improve the script a little bit. Then the user experience will look like following:
- Go to ova file server URL
- Download file package
- Untar files
- Execute install script on Linux or Window

In the last step, user doesn't have to modify config file as shown right now, but to execute command, user still need VC URL and Credentials, so that the script can talk to VC for extension registration.

The ideal solution for plugin install/uninstall should be part of one web page, and user just need to click the button.
But we do not have any UI mockup for this function yet, and do not have any web server launched.  So in 1.2, we'll not have any UI work for this feature.
How do you think?

**Comment by jooskim** [comment]
@emlin yeah, as long as we can get the thumbprint from `vic-ui`, then it should be ok. so it should be that if the user decides to provide the thumbprint manually, then he/she types "n" (for no) when asked to trust the provided fingerprint, and then gets prompted for a thumbprint to be typed in.

**Comment by mdubya66** [comment]
Not having to edit the config file is a good step forward. Limiting the prompts to just the username password is also a better experience. As stated, we can make further improvements in future versions.

**Comment by emlin** [comment]
@mdubya66 one more thing is the VC URL, that one is still required

**Comment by jooskim** [comment]
@mdubya66 What do you think about Andrew's suggestion above? Since the user will have to provide the IP to the VC manually, I feel that fingerprint verification is needed, but it will result in 4 prompts in total.

**Comment by morris-jason** [comment]
@karthik-narayan @bradmeiseles @mdubya66 @jooskim
To @emlin's comment above - it may be very easy to add this functionality as a simple ui like the demo vch installer. The code is already impletemented to ask for vc url & admin user and password on the auth.html page. There's already a web server set up too, and it's tls. 
Im not saying we add it to engine-installer, but it would be easy to add a button that sends those variables to an updates install.sh script.
We already moved one project from file downloads to using a UI. Why not do the same here if most of the code is reusable?

**Comment by jooskim** [comment]
@morris-jason Yes we're already aware of that, and that could come as part of what @andrewtchin  demoed two weeks ago. I briefly told him about the concept today such that the web server would interface with not only vic-machine API but also vic-ui API eventually. Given only three weeks of time window though, we're not doing it now. It will be targeted for 1.3 release. @andrewtchin can you confirm the demo vch installer is not targeted for 1.2?

**Comment by andrewtchin** [comment]
Yes I'd say stick with the improved script that doesn't require editing config files for 1.2 and plan for a "click to install UI plugin" in the 1.3 "OVA Initialization" UI that the user will be required to visit after powering on the OVA VM. @karthik-narayan

**Comment by jooskim** [comment]
All PRs merged. Closing the issue.
