### ISSUE TITLE
Add mount data from portlayer to replenish persona container cache on VCH restart

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5558]
As a user of VIC, I expect docker inspect to return mount information for a container after a VCH restarts.

Acceptance Criteria
- [ ] Updated robot scripts to verify that the docker inspect returns valid mount data after a VCH restarts

---
This is the second part of the docker inspect/mount data issue.  This task is to add either a new portlayer call to get the mount data for a container or add the data to our current ContainerInfo call.  It also requires replenishing the container cache on start.  This missing data is needed for docker cp.

**Comment by sflxn** [comment]
This is the docker mount data in inspect:

```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "loc-test",
                "Source": "/var/lib/docker/volumes/loc-test/_data",
                "Destination": "/test",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
```

**Comment by sflxn** [comment]
I figured out a way to do this without a new portlayer call.

**Comment by sflxn** [comment]
Reopened.  After more investigation, our volume config structure is not getting correctly populated for GetContainerInfo and GetContainerList in the container portlayer.  Volume config's mountpoint is and readwrite is not correct.

Once those are corrected, we need to build the binds for hostconfig in the inspect data and also config.volumes.

**Comment by sflxn** [comment]
Make sure to complete the code under the first comment in mountsFromContainerInfo().

**Comment by matthewavery** [comment]
@sflxn we should likely not set source for now. Since that usually indicates where the data of the disk is stored and that would either be a remote nfs target or a vspher disk uri.

**Comment by emlin** [comment]
@hickeng @sflxn @matthewavery 
I'm now trying to refill the container cache with correct mount information. But there is one problem for the HostConfig.Binds. The information is cached during container creation from create config directly, but we don't actually support bind mount for volumes.
All volumes end up with non bind mode, and because of that, we don't have any way to figure out that back. Even the volume list information does not actually show which one is bind or not. Because volume create is called exactly same for named volume or anonymous volume.

As we don't really have any bind mount, I'm thinking to remove the bind mount information in container inspect, instead of persist that information in manifest file. This will make our container inspect slightly different with docker inspect, but that will be consistent before and after VCH restart.

**Comment by sflxn** [comment]
@emlin As long as we can still get Mounts from inspect data, I think it's fine with what you're describing.  However, are we sure that docker doesn't specify shared storage in the bind section?  Unless we try docker with a volume plugin, I can't give a definitive answer on whether vanilla docker saves this information in binds or not.  If you done the research and believe it, then go ahead and change it.  Mounts is what we really need.

**Comment by emlin** [comment]
@sflxn as our discussion, fill the hostconfig.binds and config.volumes with exactly same value right now. The mounts works well, but the inspection result after VCH restart will be different with docker
