### ISSUE TITLE
tests: attempts to use in-use volumes or r/w layer should return useful errors

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5562]
**Story**
As a user I want errors due to in-use conflicts to return useful, actionable information

**Detail**
As we're adding `cp` support it increases the probability of a user attempting to perform a container operation that cannot be completed due to a volume or r/w VMDK being currently in use. Examples:
* volume is mounted on appliance for active cp command
* container r/w layer is mounted on appliance for active cp command
* volume is in use by container and cp command cannot access it

Error messages returned should identify:
* that this _should be_ a temporary condition
* which storage object is in use and unavailable
* what the storage object is in use _by_
* documentation that clearly notes the different concurrency behaviours for different volume store types

**Acceptance**
Tests that:
- [ ] assert the error contains the necessary IDs to determine what is in use by what
- [ ] assert that in-use condition is temporary and succeeds after locking operation completes
- [ ] NFS volumes do _not_ have this concurrent usage limitation

**Comment by hickeng** [comment]
Currently, attempting to use a volume that's in use returns the following completely useless error:
```
docker: Error response from daemon: Server error from portlayer: File system specific implementation of LookupAndOpen[file] failed.
```

**Comment by jialin-li** [comment]
Attempts to use in-use volumes should be handled by current design of failover to online. Test cases in 1-44-Docker-CP-Online should cover in use cases. NFS can't be tested until NFS data source is in.

**Comment by matthewavery** [comment]
@jialin-li I think in this case the main concern we should have is in the event of commands like `docker run` which will not only configure a container to use a volume but attempt to start them as well. A standard docker create should likely not fail since we are only doing a HardwareConfig update. But if you attempt to start that container while an offline CP is being performed then we should expect to get an in use style error. And we want that error to human readable and indicate that the state is only temporary until the `cp` operation is complete.
