### ISSUE TITLE
vic-machine configure registry-ca

### ISSUE THREAD

**Issue by pescerosso** [vmware/vic#5616]
#For stories, please include the information below:

**User Statement:**

As an VI admin I would like to update the ca of the Harbor registry after VCH install.

**Details:**
Any details of what you want that might clarify for the developer how to approach the implementation.

**Acceptance Criteria:**
Specific deliverable and actionable items that the story needs to deliver in order to be considered complete, the more detail here the more accurate the implementation will be.

#For bug reports, please include the information below:

**VIC version:**

x.y.z / master / commit ID

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Logs:**

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by guillierf** [comment]
VIC version 1.1.1

Basically, Harbor comes with a certificate and this certificate needs to be specified when deploying a VCH (so the VCH can access the Harbor registry):
 
 vic-machine-darwin create --target <VCenter IP> --user administrator@vsphere.local --password VMware1! --public-network DPortGroup-VCH --bridge-network DPortGroup-CONTAINERS --compute-resource Cluster-VIC --image-store vsanDatastore --volume-store vsanDatastore:default --registry-ca=/tmp/ca.crt --no-tlsverify --force
 
 
the problem is that if the same VCH needs to access a different Harbor instance (for any reasons), there is no way to dynamically redefine a new registry-ca.
the only option today is to delete the existing VCH and recreate a new one using the new Harbor certificate

**Comment by emlin** [comment]
move this issue to sprint 12

**Comment by emlin** [comment]
The configurate command option will be exactly same with create command.
If user updated registry ca in configure command, the old value for this will be completely override. 
If old value is not specified in configure command, that means the old registry ca is removed.
If registry ca file is updated, the new value will be uploaded and used in VCH.

**Comment by emlin** [comment]
@sflxn 
In vic-machine create, the secure registry address will be added into registry white list, if that's configured.
Then what is expected, if that secure registry ca is removed during vic-machine configure? If we remove that value, might misdealt white list registry

**Comment by gigawhitlocks** [comment]
NOTE: this issue has been interpreted in implementation to only support add/replace registry-ca. Work to allow removal of a registry CA will be tracked in #5745
