### ISSUE TITLE
Headless Chrome could not be started during UI plugin test

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#5642]
**Steps to reproduce:**
PR #5471, once merged, will cause any build to fail

**Actual behavior:**
Tests fail because Chrome could not be started in the non privileged Drone container

**Expected behavior:**
Build and tests should succeed

**Logs:**
![image](https://user-images.githubusercontent.com/3834071/27875953-cd2e5486-617a-11e7-9234-cef9d9e2f2f8.png)

**Additional details as necessary:**
PR #5471 upgrades the UI plugin base code framework from Angular 2 to 4 and Clarity 0.8 to 0.9, which is a pre-requisite task for the VCH Creation Wizard. Along with upgrading the frameworks, I also changed the browser used to unit test the plugin code from PhantomJS to Chrome 59 which supports native headless mode. The rationale behind it is that some portion of the platform JS code that bridges the H5 Client and the UI plugin was generating warning messages when tested on the PhantomJS browser after upgrading.

**Comment by gigawhitlocks** [comment]
Commenting because I recognize this error from messing about with trying to run Chrome in a container in a personal project back in January. This issue https://github.com/jessfraz/dockerfiles/issues/65 mentions that `--no-sandbox` when Chrome is called will keep it from trying to move to a new namespace. Not something you'd want to do on a persistent system, but in a container this should be able to get you past this error.

**Comment by jooskim** [comment]
@gigawhitlocks This helped me solve the issue. Thanks!
