### ISSUE TITLE
Container Cache is not refreshed properly after a hard VCH restart leading to unexpected behavior

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#5654]
**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

bin/vic-machine-linux create --name='inspect-test' --target=10.192.60.158 --user=Administrator@vsphere.local --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=*<redacted>* --force=true --bridge-network=bridge --public-network=vm-network --compute-resource=cls --timeout 30m -vs *<redacted>*:nfs-store -vs datastore1/test:default --debug 1 --no-tls

**Steps to reproduce:**

1) docker volume create --name test-vol
2) docker create --name inspect-test --it -v test-vol:/mydata busybox
3) docker inspect inspect-test > before_power
4) restart the VCH(power off then on)
5) docker instpect inspect-test > after_power
6) diff before_power after_power
7) see this output:
(left = pre-restart, right = post-restart)
```
33,35c33
<             "Binds": [
<                 "test-vol:/mydata"
<             ],
---
>             "Binds": null,
39c37
<                 "Config": {}
---
>                 "Config": null
44c42
<                 "Name": "no",
---
>                 "Name": "",
53,54c51,52
<             "DnsOptions": [],
<             "DnsSearch": [],
---
>             "DnsOptions": null,
>             "DnsSearch": null,
108,119c106
<         "Mounts": [
<             {
<                 "Type": "volume",
<                 "Name": "test-vol",
<                 "Source": "test-vol",
<                 "Destination": "/mydata",
<                 "Driver": "vsphere",
<                 "Mode": "",
<                 "RW": true,
<                 "Propagation": ""
<             }
<         ],
---
>         "Mounts": null,
134,137c121
<             "Cmd": [
<                 "sh"
<             ],
<             "ArgsEscaped": true,
---
>             "Cmd": null,
139c123
<             "Volumes": {},
---
>             "Volumes": null,
143c127
<             "Labels": {}
---
>             "Labels": null
```

**Actual behavior:**

we see the above differences in an inspect after the restart. ]

**Expected behavior:**

The container inspect output should be the same even after any number of subsequent VCH restarts. 

**Logs:**

[Inspect-Test.zip](https://github.com/vmware/vic/files/1128557/Inspect-Test.zip)

**Comment by matthewavery** [comment]
This may only be affecting the `inspect` piece based on a little more investigation. With some logging we can see that the mounts are being communicated back to the persona properly.

**Comment by emlin** [comment]
Found that after VCH restart, the container cache is not refilled correctly. The layer ID is incorrectly set to container ImageID, https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container_proxy.go#L1949

The result is that everything rely on container layerID will not work. For example, before restart, docker diff will only show the change in container R/W layer, but after restart, it will show all files up to scratch image layer.

**Comment by hickeng** [comment]
#5712 has two parts - the outstanding portion not fixed in #5700 is shortIDs matching after restart.

**Comment by corrieb** [comment]
I would assume this is also true for upgrade, right? That's also effectively a power-cycle. If our caches are inconsistent or wrong post-upgrade leading to undefined behavior, that's something I would suggest is a must-fix for 1.2. I'm making this high priority unless I can be persuaded that it doesn't impact upgrade.

**Comment by sflxn** [comment]
The HostConfig.Binds and Config.Volumes are filled differently, depending on whether the volume is anonymous or named.  For anonymous volumes, Binds is null and volumes is filled.  For named volumes, Binds are filled and volumes is null.  We don't save this info anywhere so it's currently not possible to replicate Docker's behavior so whatever we do on VCH restart cannot match Docker's.

Since we cannot actually fill this correctly, what is the least bad approach?  George and I discussed this yesterday, and he thinks we should fill both Binds and Volumes whether the volume is anonymous or named.  I don't know what software out there uses these two inspect data so I can't form an opinion on which way we should take.

**Comment by sflxn** [comment]
Also, there is an older issue that is focused on the Mounts data, #5558.

**Comment by emlin** [comment]
Just one comment for the mismatch of hostconfig.binds and config.volumes. The reason of this issue is that we didn't persist those two attributes anywhere.
The meaning of hostconfig.binds is to use existing volumes, and config.volumes is to create new volumes during container creation.

It's not anonymous volume or not, because one volume A is created with container A, could be reused by container B, and while container B is created, the volume A becomes existing one.
For container A, volume A is not existed before container is created, so it's in config.volumes, but for container B, volume A already exists, it should be in hostconfig.binds. 

So this is simply one container creation option. If we do find the value to differentiate them, we'll need to persist more metadata for the container.

**Comment by matthewavery** [comment]
I suspect this may just be us not filling in data properly when rehydrating the persona cache, I will operate with that moving forward since other problems should become apparent while fixing that issue.

**Comment by matthewavery** [comment]
This may get resurrected in the future. the biggest concern here was the `cmd` section missing. Some of the other problems may be fixed in the future. @emlin has also fixed the mount/volume missing information.
