### ISSUE TITLE
Switch to github from pullapprove

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#5673]
Github announced code owners feature (https://github.com/blog/2392-introducing-code-owners) that plus being able create teams (https://help.github.com/articles/about-teams/) should provide enough to remove external pullapprove service.

**Comment by anchal-agrawal** [comment]
I looked at Github's code owner feature and overall I think PullApprove's file format is more readable and intuitive. Also, PullApprove has the following advantages that are missing in Github:

* **Setting a minimum number of reviews required**
* Ability to also exclude file paths from a review group (I think this is still possible with Github since it uses the `gitignore` syntax, but it's way less intuitive

One advantage for Github's feature is that it automatically requests reviews from code owners when a PR is opened. While this is useful for our project, there are times when a PR isn't ready for review yet (WIP).

Since setting a minimum number of reviews required is a critical feature we need, I'm inclined to keep PullApprove. Closing for now - let's reconsider in the future once Github adds more features.
