### ISSUE TITLE
Docker exec always returns 0 - ignores exit code of process

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5692]
**User Statement:**

As a container developer, I need to know the exit code of a process so that I can determine success or failure of the command I've run via docker exec.

**Details:**

Docker exec is the most obvious and cleanest way to test if a container has come up correctly. This is particularly important in multi-container deployments as you may need to block one container starting until another has come up.

Eg. 

```
while true; do
   docker exec -it db mysqladmin --user=$DB_USER --password=$DB_PASSWORD version
   if [ $? -eq 0 ]; then
      break
   fi
   sleep 5
done
```
As it stands - with master build 12207 - docker exec always returns 0. This is not consistent with the behavior of docker engine. Makes no difference whether -it is used or not. 

Obviously in the case of -d, we wouldn't expect this to work because docker exec exits before the process completes.

There is a simple testcase for this:

```
$ more Dockerfile 
FROM debian
COPY exit.sh /

$ more exit.sh 
#!/bin/bash
echo returning $1
exit $1

$ docker run --name test -d bensdoings/exit sleep 1000
b7b22cfb2271ee4d0e8b398b7df52869b7e791eddaf54913fc7367d5b1312722
$ docker exec test /exit.sh 5
returning 5
$ echo $?
0
```

**Acceptance Criteria:**

It should be relatively easy to test for this. We should add a regression test based on the above

Making this high priority. Given that we haven't implemented health check, the ability to determine health by running docker exec is an important capability.

**Comment by corrieb** [comment]
@caglar10ur believes this may be fixed. Will re-try tomorrow, but leave the bug open

**Comment by caglar10ur** [comment]
not just a belief but also following is what I get with current master :)

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] docker exec -it a sh -c 'exit 4'
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] echo $?
4
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)]
```

**Comment by corrieb** [comment]
@caglar10ur if I knew of a specific commit this was tied to, I'd have more confidence :)

**Comment by anchal-agrawal** [comment]
Build 12207 (https://ci.vcna.io/vmware/vic/12207) is at https://github.com/vmware/vic/commit/addc8b11817ac008a83d6efab92618bb7fd04b4a.

**Comment by corrieb** [comment]
@caglar10ur I built the latest master myself and got the same result. Tested on ESX and it works. Tested on vSphere and it doesn't. That's why we were seeing different results.

**Comment by mdubya66** [comment]
Belief is this is tied to vSphere host sync delay.

**Comment by stuclem** [comment]
An attempt at a release note entry:

-----

- <b>`docker exec` always returns 0 and ignores the exit code of processes. [#5692](https://github.com/vmware/vic/issues/5692)</b><br>`docker exec` always returns 0, even if you specify `-it`. This is potentially due to a delay in vSphere host synchronization.

-----

@corrieb @anchal-agrawal @mdubya66 is this OK? Thanks!

**Comment by stuclem** [comment]
@caglar10ur can you also please take a look at the release note above?

**Comment by shadjiiski** [comment]
@stuclem, some additional info: the `docker exec` functionality is exposed in Admiral in the form of a health configuration for a command-based healthcheck. More technically, a user-defined command is executed in the container and the healthcheck action is successful if the exit code of that command is 0. Because of this issue, command-based healthcheck is always successful for containers provisioned on affected VCH hosts, even if the user-specified command does not exist in the scope of the container.

If we are documenting this as a known issue, we should probably add something about the command-based health configuration as well. If you are not familiar with the feature, some information is available in the [GitHub wiki](https://github.com/vmware/admiral/wiki/User-guide#health-config). cc @sergiosagu

**Comment by stuclem** [comment]
Thanks @shadjiiski and @sergiosagu. I updated the Release Note as follows:

- <b>`docker exec` always returns 0 and ignores the exit code of processes. [#5692](https://github.com/vmware/vic/issues/5692)</b><br>`docker exec` always returns 0, even if you specify `-it`. This issue is potentially due to a delay in vSphere host synchronization.  If you configure [command-based health checks](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/configuring_health_checks.html) in vSphere Integrated Containers Management Portal, the health checks are always successful for containers that are provisioned on affected VCHs, even if the user-specified command does not exist in the scope of the container. This is because command-based health checks are considered to be successful if the exit code of that command is 0.

Is this OK? Do we need to include this in the Admiral 1.3.0 RNs too?

**Comment by shadjiiski** [comment]
@stuclem, thanks for the update, looks good. Yes, please update the Admiral release notes as well.

**Comment by stuclem** [comment]
@shadjiiski, done: https://github.com/vmware/admiral/releases/tag/vic_v1.3.0

Thanks!

**Comment by hickeng** [comment]
This is now blocking a product go-live

**Comment by zjs** [comment]
> This is now blocking a product go-live

It seems like a customer wrap whatever command they want to run with logic to always print the return code via standard out. Then, whatever logic wants to check the command could look at the last line of `exec`'s standard out instead of `exec`'s RC.

This is inelegant, but it seems like it would unblock things in the short term.

**Comment by shadjiiski** [comment]
> It seems like a user could wrap whatever command they want to run with logic to always print the return code via standard out

I just want to clarify that this is not going to resolve the [healthcheck issue on the Admiral side](https://github.com/vmware/vic/issues/5692#issuecomment-359733206) without additional effort from the Admiral team (that was not planned for the upcoming release). Admiral checks the exit code of the comment and makes no use of its standard output. cc @lazarin, @martin-borisov 

Also, I am not sure if VCH now has an equivalent to the native Docker healthcheck, but if it does, I  I think you might still hit the exact same issue there. According to the [Docker docs](https://docs.docker.com/engine/reference/builder/#healthcheck) the healthcheck also executes a command and checks its exit code.

**Comment by hickeng** [comment]
Running healthcheck via an exec is a terrible pattern for a cVM and comes with various overheads. It also means that healthcheck will not continue to run while the endpointVM is down.

If integrating with vSphere HA it makes much more sense for the healthcheck process to be dispatched from within the cVM and tied in to application heartbeat support. In this case the healthcheck on the docker API side can then watch for health alerts instead of performing heavyweight polling.

I would highly recommend some longevity/performance testing on the impact of dispatching an exec into a container every few minutes if Admiral is using this mechanism for health checking. IIRC we are not garbage collecting the exec configurations in any aggressive manner which means that list will grow significantly over time. Other than that testing I would not conflate this issue with healthcheck at all.

**Comment by gigawhitlocks** [comment]
I have a proof of concept fix for this bug stored locally. I'm going to push that to a branch today and @mavery will be taking the lead on turning that stopgap fix into a maintainable redesign of the exec flow.

**Comment by sgairo** [comment]
Increasing estimate to 5 in order to account for design.
