### ISSUE TITLE
Investigate and address client side errors for chown and xattr during copy

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5716]
Applies to #5700 

Currently there are client side errors when copying files from a container:
* operation not permitted - I believe this is related to an attempt to chown the file to `root` while running as a non-root user. This should be aligned with regular docker behaviour - we may need to pass configuration as to whether uid/gid should be included in the resulting archive.
* operation not supported - I believe this is related to the extended attributes added to denote addition/change/deletion. These should be framed as optional so that the client doesn't object during unpack.

It is possible that this issue go away if moving adopting the `pkg/archive` code mentioned in #5714 so that should be addressed first.

**Comment by hickeng** [comment]
We can also try using PAXHeaders instead of extended attributes: https://golang.org/src/archive/tar/writer.go#L275
These are ignored by the docker client so wouldn't cause issues irrespective of path.

**Comment by morris-jason** [comment]
#### Observations:
- Line 507 produces the `operation not supported` error mentioned in the issue above: https://github.com/vmware/vic/blob/master/vendor/github.com/docker/docker/pkg/archive/archive.go#L489-L507
- Line 232 here creates pax headers out of xattr headers. https://golang.org/src/archive/tar/writer.go#L232. This is confirmed by the following copy with xattrs enabled in archive.Diff.
```bash
$ docker cp nginx:/usr/share/nginx/html/index.html -
PaxHeaders.0/index.html0000000000000000000000000000003613131146477013523 xustar000000000000000030 SCHILY.xattr.change_type=A
index.html0100644000000000000000000000114413131146477011251 0ustar0000000000000000
```

#### Concerns
 - Cannot reproduce `operation not permitted` on offline or online copy. I believe this was caused by an improper permissions bug resulting from a bad statpath mode that has since been fixed.
 - `cp nginx:/usr/share/nginx/html test/` (with xattrs enabled in archive.Diff) will succeed in ubuntu with `operation not supported` warnings, but will completely fail on os x with a `platform and architecture is not supported` output from the cli. This is the `ErrNotSupportedPlatform` error being thrown from one of these method calls: /Users/morrisjason/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/pkg/system/xattrs_unsupported.go, probably in archive.go L490. 
I assume this is an issue with the pax headers, but I can't track it down at the moment.
 - We can't call `createPaxHeaders` manually. It's called automatically by WriteHeader.

#### Possible Solutions
 - a) Disable xattrs entirely for copy by adding a bool flag to archive.Diff on wether to include xattrs. Easy solution.
 - b) Don't use WriteHeader. Encode the header ourselves with only pax headers and see if that causes another issue or resolves the cli xattr issue.
 - c) other?

**Comment by hickeng** [comment]
@morris-jason
`operation not supported` and variants - this is because of xattr being present on platforms/filesystem that doesn't support extended attributes
`operation not permitted` - this was because of trying to copy a file owned by `root` as a non-root local user. This results in trying to `chown` the file to `root` locally when unpacking and obviously fails as it should.

PAX headers were suggested as an alternative to xattr as a way of noting add/change/delete that gets ignored by the client when extracting. It sounds as though this isn't going to work as the client fails even with xattr being converted to PAX headers. Is that correct?

I agree with using A - I suggest we simply don't provide the change data when file data is included for now.

The problematic piece is the `chown` issue when copying - please try running again as a non-root user as I'm unaware of any changes made that would have fixed it. I'd also like to know how it's handled with regular docker when it's a remote docker server where the uid for the calling user isn't available.

**Comment by morris-jason** [comment]
>It sounds as though this isn't going to work as the client fails even with xattr being converted to PAX headers. 

Correct.

I will look into the chown issue.

**Comment by morris-jason** [comment]
@hickeng 
I found two issues while investigating this with a vic backend:
 - a) Our CopyFrom implementation *does not inlcude* tar headers for directories if you pad a trailing slash on the end your src path, ie `docker cp:/a/b/destdir/ -`. However, tar headers *are included* if there's no trailing slash on the src path.
 - b) When directory tar headers *are* included, the cli *will not* throw chown errors in my experience. It will throw chown error if the directory tar headers are missing.

Vanilla docker does not exhibit this issue. It always included tar headers for directories regardless of the presence of a trailing slash on the src path.

>I'd also like to know how it's handled with regular docker when it's a remote docker server where the uid for the calling user isn't available.

Not sure about this. If the uid/gid maps aren't available it looks like they will default to 0 based on these lines:
https://github.com/vmware/vic/blob/master/vendor/github.com/docker/docker/pkg/archive/archive.go#L734
https://github.com/vmware/vic/blob/master/vendor/github.com/docker/docker/pkg/idtools/idtools.go#L59
https://github.com/morris-jason/vic/blob/master/vendor/github.com/docker/docker/pkg/archive/archive.go#L823-L848

**Comment by hickeng** [comment]
@morris-jason This seems to have addressed the problems I was seeing. `operation not permitted` was simply a very misleading error from the looks of it and was unrelated to the uid/gid mapping.
Moving this to verify as the #5835 PR addresses the problems I was observing.

**Comment by morris-jason** [comment]
@hickeng great news, will close with PR tomorrow morning.
