### ISSUE TITLE
Concurrent run / ps test deadlocks VIC engine

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#5736]
**User Statement:**

As a container user, I want to be able to control VIC engine from multiple clients concurrently. This may be because I want to look at logs while something is coming up; one client may be a CI pipeline and I need to interact with an existing container... there are numerous cases where multiple clients are important.

**Details:**

This issue was found by a customer.

It's relatively easy to deadlock VIC engine with multiple clients. At the point of deadlock, the control plane will blocks for every client indefinitely. I can reproduce with both VIC engine and ESX and with a variety of commands. 

Rebooting the endpoint VM corrects the problem.

The easiest way to reproduce is to run the following commands in two shells:

```
while true; do date; docker run --rm ubuntu sleep 10; done
while true; do date; docker ps; sleep 1; done
```

It's so simple to reproduce, there's not much point attaching logs. I can reproduce with a recent master build. The Port Layer seems to get stuck here:

```
[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:284]
```

**Acceptance Criteria:**

While it's impossible to test every combination of command concurrently, we should be testing common scenarios such as getting logs and stats concurrent with container lifecycle operations.

I am making this very high priority to fix

**Comment by mhagen-vmware** [comment]
See the following for patterns to use for this:
https://github.com/vmware/vic/pull/5681

https://github.com/vmware/vic/blob/master/tests/test-cases/Group1-Docker-Commands/1-05-Docker-Start.robot#L93

**Comment by karthik-narayan** [comment]
I believe that we have concurrent test already running. @lgayatri can you comment / add these tests to ensure that this is captured?

**Comment by lgayatri** [comment]
@karthik-narayan , we have concurrency tests executed from a single client. Will have to add this scenario

**Comment by corrieb** [comment]
@lgayatri Can you describe how a concurrency test from a single client would work? If you're using & so that the client calls don't block, then a single client will probably show the same problem.

**Comment by lgayatri** [comment]
@corrieb 
I have 50 VCHs on which I need to create 50 containers each, so 2500 containers in total.
I run a multi threaded Java program which creates 50 threads to create one container on each VCH. Input looks like 
...
docker -H 10.197.37.164:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
docker -H 10.197.37.165:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
docker -H 10.197.37.166:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
docker -H 10.197.37.167:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
docker -H 10.197.37.168:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
docker -H 10.197.37.169:2376 --tls run --cpuset-cpus 1 -d photon sleep 5d
...
Each thread will hit one VCH. Here I did not see the deadlock so far.

**Comment by corrieb** [comment]
@lgayatri yea, that's concurrent within the context of vSphere. What we're talking about here is concurrency within the context of a VCH. @karthik-narayan Note the distinction here. I don't think concurrency on a single endpoint is being tested

**Comment by cgtexmex** [comment]
[This](https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container_cache.go#L69) is the cause of the deadlock.

When calling `docker ps` the user is asking for all running containers.  The above code locks because the container is Read locked by the cache and the `CurrentState` func wants a Read/Write lock -- the `CurrentState` func will now block until it obtains the lock, but it never will because of the cache's Read lock.

Now to figure out why that was added....

**Comment by cgtexmex** [comment]
My previous explanation was incorrect -- if that was true Vic would deadlock on each docker ps....

**Comment by cgtexmex** [comment]
I was close with the initial triage -- the lock is caused by the `--rm` which in some cases causes a `docker ps` and a `docker rm` to happen at the same time on the same container.  This falls out like such:

1. portLayer locks container 123 for removal
2. portLayer locks container cache for `docker ps`
3. portLayer cache requests lock on container 123 for State, but is blocked by step 1 (remove)
4. open successful removal from vSphere portLayer attempts to remove from cache -- which requires a lock, but is blocked by cache (step 2)
5. madness ensues...also known as a deadlock

The cache shouldn't require a lock on the container for state info -- the cache can simply read it and move on...by removing the need for the cache to lock the container for state we remove this deadlock.
