### ISSUE TITLE
vic-2a6a4ac2 (1.2) : after VIC VM reboot, docker ps is empty

### ISSUE THREAD

**Issue by guillierf** [vmware/vic#5778]
after rebooting the VIC VM, docker ps is empty.

It should normally show Harbor and Admiral containers

**Comment by anchal-agrawal** [comment]
Build `vic-2a6a4ac2` of the OVA includes part of the new PSC workflow (signing in to `$OVA-VM-IP:9443` with admin credentials) before the Admiral and Harbor containers are started. I checked with @guillierf over Slack and this issue was resolved after entering the credentials.

More PSC work has been added after commit https://github.com/vmware/vic-product/commit/2a6a4ac2006b8acfd078cb453c7fad5b5517101f. I will be uploading a new dev OVA build on top of the current master branch (https://github.com/vmware/vic-product/commit/ab0c24effa5b4354e70617ac18c4010672e48872)  soon.
