### ISSUE TITLE
enhance drone process: leveraging bintray image

### ISSUE THREAD

**Issue by emlin** [vmware/vic#579]
We're doing container build every time from drone test, based on e.g. go 1.6.2, the env build up is kind of time consuming.
We should integrate our CI process with bintray, to persist clean build image with every dependencies installed and configured correctly in bintray, and then config drone to use that cached imaged from bintray to run test for every one. This could save env build up time during drone test.
Think about we have 10 tasks in .drone.yml file already. All of them are executed in different container built from golang.

With this support, every time to run test, the only thing need to be updated is our VIC code, and binary, not any dependencies.

While we have dependency changes, we should update the bintray image as well, and then the new image will be used by next CI test.

**Comment by hickeng** [comment]
It's only the 'integration' tests that rebuild everything and the only reason it's running from golang:1.6.2 is because they _are_ rebuilding those binaries.

We need to fix the integration tests to use the already built components before we start optimizing the images that it's based on as that's where the bulk of the wasted time is currently.
