### ISSUE TITLE
docker cp fails to target correct device for anonymous volumes

### ISSUE THREAD

**Issue by jialin-li** [vmware/vic#5845]
When trying to copy to or copy from a container with anonymous volume, we fail to get the correct device when the target is the anonymous volume.

Steps to reproduce:
`docker create -i -v /vol1 busybox`
`docker cp test.txt cid:/vol1`

Right now if we repeat  that cp command multiple times, we can see that the personality gives a different device ID each time. And the deviceID given by the personality is not consistent with what we see in `docker volume ls` or `docker inspect cid`

Cause:
mountsFromContainer uses processVolumeParam which is not the right way to look up anonymous volumes because it creates a new UUID for anonymous volumes instead of looking it up.

**Comment by matthewavery** [comment]
I have talked with @emlin And we are including the fix for this in PR #5830 as it is already addressing issues in this area of the code base. It would not make sense for us to not merge it with her change since this bug actually affects inspect as well. The proposed fix for this issue for now is such. During a container create a uuid is generated and a volume is created using that uuid. We do not store that uuid anywhere on the personality side after this. To resolve the existing problems with inspect and cp(in feature branch currently) during the create we will update the config of the container after the anonymous volumes are created to reflect the ID associated with the volume which owns a specific path in the container. to do this we will us the newly generated `HostConfig.Mounts` to inform the `Volumes` config of the container. Once this is fixed the `mountsFromContainer` function will no longer detect that there is a need to generate a UUID and it will simply supply the given UUID for the anonymous volume.
