### ISSUE TITLE
Add data validation for docker commit

### ISSUE THREAD

**Issue by emlin** [vmware/vic#5850]
Story:
Have integration test to verify the vic archive file contains same content with docker archive, so that we can make sure docker commit command, based on VIC archive in PL, works correctly.

The test process is to get tar from docker save, and also get VIC generate tar file through imagec #5848. And then compare those two tar files.

For this test story, the criteria is as following:
- same files, no more no less
- same single file digest

We're not verifying tar file digest at this time, that is a goal for docker push

**Comment by jzt** [comment]
@emlin I just realized how we could improve this scenario:  If we save our images by blobsum (instead of layer ID) for the `imagec save` command, it would be trivial to compare image layers between ours and dockers. We could sort by filename, and compare the sha256 of each, comparing contents if they don't match in order to ensure that they aren't different for reasons other than these:  https://github.com/vmware/vic/issues/5997

**Comment by emlin** [comment]
Moved this issue out of commit epic, because this is for test code only, and it's useful for docker cp/commit/diff
