### ISSUE TITLE
Nightly 5-22: container creation failed because context deadline exceeded

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5940]
8/6, build 12979, vSphere 6.5
[5-22-NFS-Volume.zip](https://github.com/vmware/vic/files/1206468/5-22-NFS-Volume.zip)

CDE error during container handle commit.  From portlayer logs:

```
Aug  7 2017 07:03:40.008Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:36] [3m13.826296994s] 4b312973d580e04b972a4f4fdda677672157c090f329d442d77ced9001824475
Aug  7 2017 07:03:40.008Z ERROR CommitHandler error on handle(cc33a23b46aa0f9439355fa4d958cfab) for 4b312973d580e04b972a4f4fdda677672157c090f329d442d77ced9001824475: &errors.errorString{s:"unable to wait for process launch status: Post https://10.160.131.72/sdk: context deadline exceeded"}
Aug  7 2017 07:03:40.008Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:216] [3m13.826798326s] handle(cc33a23b46aa0f9439355fa4d958cfab)
```

**Comment by emlin** [comment]
@sflxn @hickeng @caglar10ur 
This error is because our nimbus nightly test environment is super slow.

Our current docker attach timeout is 30s, if tether is slow, like in our nightly test environment, attach timeout before tether start to wait for clear to launch. So even after the connection is established after 30s, attach already quit, so no one will send the clear to launch for tether, and then tether stuck in the waiting clear to launch status.

But in the other hand, docker commit does not timeout after 30s. The default property collector timeout is 3m.
In one docker run command, docker attach will be called first, and then docker start, so docker attach will timeout first even with same timeout settings.
But now we have much shorter attach timeout, 30s, so literally, PL will do nothing after first 30s until property collector timeout after 3m.

This is the reason for the nightly test failure, so the suggestion is to bump docker attach timeout to 3m, same to PL internal timeout. At least it will accommodate the slow environment a little bit.

**Comment by rajanashok** [comment]
Seen this again on 6.0 8/22 nightly run. The zip file is too big to attach. Log URL below.

https://storage.cloud.google.com/vic-ci-logs/functional_logs_08_22_18_30_vic_13338.tar.gz.zip?authuser=1

**Comment by rajanashok** [comment]
Spoke to Emma, looks like this error is another issue, will create a new one and closing this.
