### ISSUE TITLE
VIC engine should render the error message in a similar way as docker does

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic#5951]
This is a suggestion.

Harbor will return 412 when the image violates the "project level content trust" and "vulnerable" policy.

The response body is a json:
```
{"code":412,"message":"The image is not signed in Notary.","details":"The image is not signed in Notary."}
```
The response json is following the convention of docker, so when user issues `docker pull` a more meaningful error message will be returned:
```
Error response from daemon: unknown: The image is not signed in Notary.
```

It would be better if VIC engine can extract error message from the response to show more information to user.

**Comment by sflxn** [comment]
@reasonerjt How can we produce this error?  Can you describe a scenario for us to create this?

**Comment by AngieCris** [comment]
Reopen the issue:

In https://github.com/vmware/vic/pull/6067, fixed the error response returned from Docker, assuming Docker error response body follows this json format (from Docker documentation: https://docs.docker.com/registry/spec/api/#errors-2)
```
{
	"errors:" [
	    {
            "code": <error code>,
            "message": "<error message>",
            "detail": ...
        },
        ...
    ]
}
```

After I reproduced the exact 412 error, the error response json from Harbor gives me this (in VCH docker-personality log):
```
{ "code: <error code>,
  "message": <error message>,
  "detail": 
}
```
Just the same as @reasonerjt described in the issue. 
Since I assumed Harbor follows the exact same json format as Docker, json marshalling failed when reading the error response body, and the issue remains not solved.
