### ISSUE TITLE
Enhance vic-machine to stream a creation log to the VCH's datastore folder

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6036]
Enhance `vic-machine` to stream a creation log to the VCH's datastore folder.

As a VCH is created, logs should be written to a file in the VCH's datastore folder.

**Comment by zjs** [comment]
See "Log Management" in #6124

**Comment by AngieCris** [comment]
confusion about where to put the creation log:

if we want to stream it to VCH's datastore folder, once the vch creation fails, the VCH's datastore folder will be removed, and the log file will be gone as well. in this case, the client can only see the file if the creation succeeds, or if the creation hangs at somewhere before the vch datastore folder is removed. is that what we want?  @zjs  @andrewtchin 

also, do we also want to keep the local creation log as well (vic-machine.log)?
If multiple VCH's are created, all of the logs would be in this single file. if log is streamed to VCH's datastore folder, that will be separate log for each VCH
also if VCH creation fails, the local log is still accessible, so we might want to keep that?

**Comment by zjs** [comment]
> Firstly, where to put the creation log?
> if we want to stream it to VCH's datastore folder, once the vch creation fails, the VCH's datastore folder will be removed, and the log file will be gone as well. in this case, the client can only see the file if the creation succeeds, or if the creation hangs at somewhere before the vch datastore folder is removed. is that what we want?

I think we it in the VCH's datastore folder. When creation is initiated from the `vic-machine` CLI, I think it's fine if the log gets cleaned up when a failure occurs.

We'll want to suppress deletion of the log when creation is occurring via the API, but we can track that as a separate issue.

Using the VCH's folder does complicate things, but it simplifies others: we essentially piggyback on the existing RBAC functionality and avoid introducing new persistence requirements.

> Secondly, log it real time vs. upload the log file to datastore
> there're two ways of logging here:
> 
>   1. log it real time
>       *  this is only okay after the VCH's datastore folder is created. is it implementable tho? need to track when the datastore folder is created?
>  2.  upload the local log vic-machine.log file to VCH's datastore folder
>       * simpler to implement. but again the log would be gone if creation fails

I think we want to log it in real time. One of the main use cases for this feature is for allowing users of the vSphere client plugin to monitor the creation process, both for VCHs they've created and for VCHs being created by other users (who may be using the `vic-machine` CLI). Eventually, we even want the log data to live-update in the UI.

You're right that it does complicate the design. Essentially, I think we'll need to buffer log data in-memory until we can write it to the datastore.

I'm not yet familiar with golang logging patterns/libraries, but in most logging libraries I've used there's a way to register some sort of listener/handler for log messages. Sometimes, libraries have some sort of pattern for holding log data in memory until a file is available to write to (e.g., between when the application starts, and when the configuration file is read which says where log data should be written to), so it may be possible to re-use existing functionality.

If we have to implement our own buffering, I think it looks a lot like a producer/consumer problem: calls to the log methods produce log events which need to queued for consumption, and the consumer gets registered and begins consuming once the datastore folder is available.

> Thirdly, what to do with local log file
> do we also want to keep the local creation log as well (vic-machine.log)?
> If multiple VCH's are created, all of the logs would be in this single file. if log is streamed to VCH's datastore folder, that will be separate log for each VCH
> also if VCH creation fails, the local log is still accessible, so we might want to keep that?

We want to keep the local creation log. I'd think about this issue as a adding functionality, not replacing anything.

**Comment by AngieCris** [comment]
Figuring out the design has taken me more time than expected (it took me a few days to get familiar with vic-machine workflow):

1. Multiple layers are involved: 
(1) the cmd layer is responsible for redirecting logs to streams (currently stdout and a local file stream `vic-machine.log`), and the redirection applies for all vic-machine commands (create, inspect, etc.).
(2) the management layer is responsible for actually streaming the log real-time to the datastore folder. 
2. Suppose the logs are redirected to a reader/writer stream, the writes to the writer stream happen at multiple layers too: the cmd layer and management layer. But reads from the correspondent reader stream only happen at management layer, and after the VCH datastore folder is up. So internal buffering is necessary to prevent blocking of concurrent reads and writes. 
Just like @zjs suggested (thanks a lot for the clarification), this is essentially a consumer/producer problem on a buffer of log bytes.
3. The log streaming should apply for all vic-machine commands (currently it does locally in `vic-machine.log`) so a new package under `lib\install` must be created to implement our own reader/writer streams with buffering. There could be scenarios where multiple vic-machine processes are running on the same VCH, so the buffer must be synchronized in some way

The design I came up with is like this:
1. Redirect vic-machine cmd logs to a writer stream in `cmd`, and pass the ReadWriter to management layer
2. In VCH creation logic in management layer, after appliance is created and before image files are uploaded (to ensure the VCH datastore folder is up), upload the reader of the ReadWriter to VCH datastore via govmomi.
3. The writer in ReadWriter simply puts everything in an internal memory buffer no matter what (the logs are just KBs so should be okay to hold), and the reader will grab from the buffer when it's not empty (otherwise it's EOF error).
Essentially a producer/consumer problem on a bytes buffer.

**Comment by mdubya66** [comment]
Keep in mind that we support syslogs now as well. @hmahmood added that.

**Comment by AngieCris** [comment]
@hmahmood can you elaborate on how it works?

**Comment by AngieCris** [comment]
Talked with @emlin and @andrewtchin about my design

Currently the design is like this:
1. make a reader/writer stream to hold logs
2. propagate the stream to management level (where the vic-machine logic is actually implemented)
2. upload the log stream to VCH's datastore folder via govmomi's upload function

This design is implementable but it does not look very good because:
1. propagating stream from cmd to management looks ugly 
2. this approach might be deprecated (as mentioned by @emlin from our previous discussion, ping her for more details) 
3. internal buffering is a must (tho there could only be KBs but could there be potential performance/memory related issue?)
4. once we separate the CLI to use the API, this approach would have to change (since it has dependency from cmd to management layer)

It seems to be the only way to do it if we want upload logs via govmomi. cmd is responsible for redirecting log output to a stream, and it only makes sense to upload in the management layer. It seems a bit twisted

Other options are:
1. Read from the local `vic-machine.log` file and upload real-time (performance might drop)
2. syslogs (as @mdubya66 mentioned, but not sure if it works in this scenario)
If it works then the problem scenario is changed: we no longer put logs in datastore folder but syslogs.

Ultimately if we want an API which both the web UI and vic-machine will use, we want the logs being persistent after the API's there.
I'm stuck at this moment. What option is favorable? @zjs

**Comment by zjs** [comment]
> Keep in mind that we support syslogs now as well.

The goal is to allow log information to be show to end-users of the UI in near-real-time. Syslog is good for log aggregation, but I'm not sure how it would help with this usecase.

> propagating stream from cmd to management looks ugly

I know very little about VIC internals at this point, but could we pass down some sort of "stream handler" instead of passing up a stream? (That is, can we invert the relationship to avoid the ugliness?)

> this approach might be deprecated (as mentioned by @emlin from our previous discussion, ping her for more details)

@emlin: Could you clarify which aspect of the design might be deprecated?

> internal buffering is a must

Regardless of the approach, I think internal buffering will be required; we have valuable information being logged before the place we want to put it is available. Given that, I'm not sure I consider this a disadvantage of this particular proposal.

> once we separate the CLI to use the API, this approach would have to change

I'm not sure we expect the CLI to use the REST API. The current design document talks only about both the CLI and REST API being refactored so that they both use a common internal go API. I don't think we've settled on any specifics though, and just generally want to minimize any duplication between the two, so I don't know if we want to constrain ourselves at this point. It seems like if we can get streaming logging working from the CLI, we can find a way to replicate that same behavior with the API.

> Read from the local vic-machine.log file and upload real-time (performance might drop)

This feels like it would require a very similar design, but we essentially buffer on disk instead of in memory (and pass a reference to the file around, instead of a stream of the data).

**Comment by emlin** [comment]
@zjs I'm just curious why do you need a vic-machine log file in datastore folder. There should have many options to show the vic-machine output in UI.
Are you trying to get vic-machine logs without a vic-machine service running? If you have a vic-machine service running some where, UI could simply call vic-machine API to get log.

While talking with @AngieCris, I thought you just want to enhance the vic-machine log, so it's easy for user to collect VCH logs, including vic-machine logs.
But if this is for UI enhancement, it's a different story.

For this requirement, you'll need to think about following points for this work:
- Do you need all command logs, including inspect, debug, configure, etc? Suppose so, right?
- vic-machine CLI will write logs to one log file, for all commands, all managed VCHs. If do not change this, the streamed log to one VCH folder will include all logs for other VCHs.
- vic-machine log file assume this is only one vic-machine running, so if other vic-machine tried to access the same VCH as well, or it's simply want to inspect one VCH, the log streamed to one VCH will need to coordinate with multiple clients. Does the vSphere API works that way?
- vic-machine does not have one operation ID, like what portlayer did, so if multiple vic-machine stream to the same log file, we don't know which log is from where.

My understanding is that in the future, if vic-machine API is ready, vic-machine CLI will be only one command parser, and all work currently in validator and management package will end up in server side, which means the vic-machine log could be retrieved from server only.
And server log is not working in this way, even we're using datastore file to persist log. At that time, we'd likely to have a VM serial port device configured for the service VM, or something else could replace serial port, and that could write directly to datastore file. So in the service side, we can write log similar to write one normal file, instead of calling govmomi to upload data stream, which is broken while VC is not there.

**Comment by zjs** [comment]
> I'm just curious why do you need a vic-machine log file in datastore folder.

Storing the `vic-machine` log with the VCH allows us to:

- Display the logs (via the API and UI) for all VCHs regardless of how they were, or are being, created or managed (via UI, API, or CLI).
- Ensure that only users with a reasonable set of permissions can access the logs without inventing new permissions or a new access control model.
- Avoid a persistence requirement for the `vic-machine` API service. And, in doing so avoid a uniqueness requirement for the `vic-machine` API service; if there is no persistence, supporting a variety of horizontal scale-out models is trivial.

Storing the log on the datastore seems to be the natural choice for storing the file with the VCH (as there does not seem to be a suitable place in, for example, the VM's metadata). 

> * Do you need all command logs, including inspect, debug, configure, etc? Suppose so, right?

Initially, the UX mockups call only for creation logs. However, I think from a completeness point of view, it would be good to store logs for all mutation operations.

> * vic-machine CLI will write logs to one log file, for all commands, all managed VCHs. If do not change this, the streamed log to one VCH folder will include all logs for other VCHs.
> * vic-machine log file assume this is only one vic-machine running, so if other vic-machine tried to access the same VCH as well, or it's simply want to inspect one VCH, the log streamed to one VCH will need to coordinate with multiple clients. Does the vSphere API works that way?
> * vic-machine does not have one operation ID, like what portlayer did, so if multiple vic-machine stream to the same log file, we don't know which log is from where.

As noted above (https://github.com/vmware/vic/issues/6036#issuecomment-327621007), I think we should store one timestamped log per operation when writing to the datastore.

> My understanding is that in the future, if vic-machine API is ready, vic-machine CLI will be only one command parser, and all work currently in validator and management package will end up in server side, which means the vic-machine log could be retrieved from server only.

This has not (yet?) been proposed. I hope to maximize code reuse between the API and CLI, but I don't think that dictates a design where the CLI calls the API. My current thinking is that the API and CLI packages would each call into a common go package to perform operations.

>  And server log is not working in this way, even we're using datastore file to persist log. At that time, we'd likely to have a VM serial port device configured for the service VM, or something else could replace serial port, and that could write directly to datastore file. So in the service side, we can write log similar to write one normal file, instead of calling govmomi to upload data stream, which is broken while VC is not there.

I'm not sure I understand this paragraph.

I think we would ideally write to a datastore file directly, and would only use govmomi upload if that's not feasible.

Regardless, it seems unlikely that anyone will be using the UI plugin without VC (I don't think that's possible), so I'm not sure that's a particularly important use case. (Ideally we'd have a solution that would work the same way in all deployments, but if that's not feasible a solution that works in the primary deployment model would be the next best thing.)

**Comment by AngieCris** [comment]
Several questions:

1. Do we want the CLI and UI to both use the same vic-machine API, where the CLI serves just a command parser? If it's not proposed yet, can you elaborate on our current plan about the CLI and vic-machine API?  @zjs 

Currently, the CLI is calling functions in management package (and the management package does real vic-machine work). Later if we want the CLI to use the vic-machine API, the CLI has to be separated from the management package and use the API instead. 
If we want to stream vic-machine logs via govmomi, any design will depend on the current linkage between CLI and management package. This is because currently the CLI sets log output to streams (using `log.SetOutput`), but only in management package can we access datastore path and upload via govmomi the log stream set before in CLI layer. And there's necessary internal buffering within the linkage. The linkage will likely break in the future when we separate the CLI from management package. So if log streaming via govmomi is enabled for now, it's very likely going to change in the long run.
If separating CLI from management is what we want to achieve, then management will be in the server, and persisting all vic-machine logs in the server (via syslogs/serial port/etc.) would seem like a more natural choice.

2.
@zjs , can you elaborate on "It seems like if we can get streaming logging working from the CLI, we can find a way to replicate that same behavior with the API" ?
Stream logging needs changes in both CLI and management package, since datastore path is only available in management package. I'm not sure how can the future API replicate that?

**Comment by zjs** [comment]
> Do we want the CLI and UI to both use the same vic-machine API, where the CLI serves just a command parser? If it's not proposed yet, can you elaborate on our current plan about the CLI and vic-machine API? 

I think we're more likely to end up with an architecture where the API and CLI both call into the management package (or, perhaps, both call into a new package which in turn calls into the management package).

> "It seems like if we can get streaming logging working from the CLI, we can find a way to replicate that same behavior with the API" ?
> Stream logging needs changes in both CLI and management package, because datastore path is only available in management package. I'm not sure how can the future API replicate that?

I'd expect to _either_ have the API to do setup work that's analogous to the CLI _or_ have the new intermediate package do the setup work for both, and then have the management package do the heavy lifting.

**Comment by zjs** [comment]
Note that even if we start with the model described above, and then decide to implement a new CLI that invokes the API, we can continue to use the strategy described above for all of the server-side logging.

In this diagram, the big box and UI are what I think we're currently planning, and the small box in the upper right is potential future work:

![image](https://user-images.githubusercontent.com/408880/30174921-9500d0a2-93b1-11e7-9cc1-28d2a445f6cb.png)

Even if we pursue that future work, the logging for everything in the big box would all still work ―  it just wouldn't include logs from the client-side functionality of the new CLI (which is okay; the logs would look just like the logs for a UI-initiated operation).

**Comment by AngieCris** [comment]
got it working with an experimental design. The WIP pr: https://github.com/vmware/vic/pull/6387

the design is to use a buffered pipe, pass down the pipe from cmd to management layer, and concurrently upload the stream to VCH datastore folder via govmomi.
The detailed design is described in the pr. also listed down my concerns of improving this design (specifically avoid the ugliness of passing a pipe down from cmd to management). Any input is appreciated @zjs @emlin @andrewtchin thanks

**Comment by AngieCris** [comment]
Quoting from design doc (https://github.com/zjs/vic/blob/ac2663395580dbe30b6a097ed67e1f5ce3d384e6/doc/design/vic-machine/service.md#log-management):

> When invoking the vic-machine CLI, real-time information is provided to stdout and log files can be persisted on the filesystem. The REST API needs to provide equivalent functionality.

Can you elaborate on "equivalent functionality"? Is this functionality live log streaming feature? 
As mentioned, now the real-time information is provided to stdout. If we just want to persist the log file, live streaming would not be part of the story.
Can you elaborate on exactly what use case where client want to live consume the logs? 

> Logs will be streamed to the VCH's datastore folder as vic-machine-service executes. Access to logs is then restricted to those vSphere users who can read those files from the datastore.

I have some questions about responsibility assignment: 
currently in the impl in my WIP pr, the CMD layer is responsible for firing the background logger. Do we want the API to take on the job by CMD and be responsible for the live log streaming in the future? 
Then the API will have to handle concurrent vic-machine processes on a single VCH, and the concurrent clients accessing the same vic-machine-service. Although they're different problem scenarios, is it better to plan ahead and address the concurrency problem in a more specific way to ease the future development of API?

=======================================================================
Quoting from original comments:

> Display the logs (via the API and UI) for all VCHs regardless of how they were, or are being, created or managed (via UI, API, or CLI).

It seems counter-intuitive to stream creation log to a place that depends on the creation process itself. Clients would very possibly care about the logs only when things failed, so they can identify problems. The datastore folder path is ready pretty late in the creation process - after all the params parsing, configuration validation, etc. If the creation fails before the datastore folder is ready (like a govc/network failure), we won't be able to persist the logs in datastore folder since it's not there.

On the other hand, streaming to VCH does avoid authentication headache, but I'm wondering if this is the reason why we are not considering persisting logs in other places, such as syslogs.

> Avoid a persistence requirement for the vic-machine API service. And, in doing so avoid a uniqueness requirement for the vic-machine API service; if there is no persistence, supporting a variety of horizontal scale-out models is trivial.

Can you elaborate on how it avoids the persistence requirement, and the uniqueness requirement for vic-machine API service? And why is that "if there is no persistence, supporting a variety of horizontal scale-out models is trivial"?

I'm not sure if I misunderstand the problem scenario, but to deal with the scenario of concurrent vic-machine acting on a single VCH, unique identifier for vic-machine might be necessary. Also, since the only way to talk to VCH datastore folder is via govmomi, and govmomi upload does not append, so each vic-machine process needs to write to a different log file, and these log files must be named differently with an identifier of some sort.
If we want to leverage any working solution to the API impl in the future, these above scenarios should be correctly addressed in a specific way as well.

> Initially, the UX mockups call only for creation logs. However, I think from a completeness point of view, it would be good to store logs for all mutation operations.
> As noted above (#6036 (comment)), I think we should store one timestamped log per operation when writing to the datastore.

Right now the only way to stream to VCH datastore folder is via govmomi, and the upload does not append. Which means for each vic-machine command (configure, inspect, etc), the log stream can't be appended to the original creation log, so we might need to have a different log file for each vic-machine operation. We might end up having a lot of log files, each named by a vic-machine identifier (like timestamp, operation ID, etc.), in the datastore folder. Is that what we want?

Naturally we would like to have a single log file for each VCH, not for each vic-machine, because multiple vic-machines can map to the same VCH. But it's very difficult to do that via govmomi. 

> I think we would ideally write to a datastore file directly, and would only use govmomi upload if that's not feasible.

Currently the only way is via govmomi. Do we have a plan in the future to have a VM serial port for `vic-machine-service` VM that writes directly to datastore file? 
Doing it via govmomi is not ideal since govmomi depends on the creation process of VCH itself.

=========================================================================

I think these design questions need to be addressed in a detailed way before a ready-to-merge pr. The WIP pr I opened for now might influence the future development of API, but the WIP remains not ideal if the above design questions are not thoroughly discussed. What do we think?
@zjs @jzt

**Comment by AngieCris** [comment]
UPDATE:

Summarized from discussions with @zjs 

1. Why streaming to datastore?

The `vic-machine-service` is stateless and requires only ephemeral storage. The service does not have its own access control policies (we can just rely on the existing RBAC by VCH if we stream to datastore folder). 

* syslogs
Introducing a remote server for logs to be aggregated generates more work: the new server needs to be updated, configured, maintained, backed up and updated. This makes installation more complicated which is a step backwards from what we want.

* VM serial port device on service VM to directly write to datastore folder
This approach is a complete different one from using govmomi. This requires that the vic-machine is run from within a VM on an ESX host with access to datastore. This doesn't seem to be a reasonable restriction to place on the deployment topology.

2. What if the creation fails before the datastore path is ready? 

In the future UI and API plan:
VCH creation is partitioned into two phase, a synchronous portion and an asynchronous portion.
**synchronous portion**: params parsing, parameter validation, talking to vSphere for setup works, etc. Upon success, vSphere tasks are returned. The errors are shown on the tasks instead of in the logs, and will be rendered within the create wizard.
**asynchronous portion**: http request and response that sends data to datastore 
For all failures during the synchronous portion, we can use the task's failure status to summarize what went wrong. 
For failures after the datastore is available, the client can also check the logs for more information. 

The steps involved in creation VCH before datastore folder is ready (after params parsing and validation):
(details see `vic/lib/install/management/create.go`)
`checkExistence`: finds existing vApp and prompts user to delete if there is one
`createPool`: creates resource pool
`createBridgeNetwork`: creates portgroup and virtual switch 
parts of `createAppliance`: datastore folder path is created along with the VM. vSphere may add a suffix to the folder name (that's why appliance gets created before the image files are uploaded to datastore folder)

These are essentially operations talking to vSphere and can be partitioned into one or more vSphere tasks (no http response is involved).
We'll also be creating "parent" task to track overall VCH creation process (as part of another story).
The order of these steps are inherited from bonneville. These operations can be rearranged (e.g. create the network after VCH and attaching it during reconfigure step).

3. Multiple vic-machine services running on a single VCH

Every `vic-machine-service` writes to a different log file, named with unique identifier (like operation ID/timestamp/etc.). 
Every VCH maps to a set of different log files.
The API is responsible for the complexity of having a set of log files instead of a single one. The UI could combine all files into a single response.

**Comment by AngieCris** [comment]
pr merged, close this issue
