### ISSUE TITLE
H5 Client plugin is not showing up on vSphere 6.5U1

### ISSUE THREAD

**Issue by jooskim** [vmware/vic#6052]
This is a customer-found issue as reported from the 'vic-product' channel from VMware {code} Slack.

**VIC version:**
1.1.1-56a309fb

**Deployment details:**
ESXi 6.5u1
vCenter Server 6.5u1

**Steps to reproduce:**
1. Deploy the 1.1.1 OVA
2. Download the vic_1.1.1.tar.gz file and untar it
3. Deploy a VCH and install the H5 Client plugin
4. Log into H5 Client, navigate to the VCH endpoint VM and click on the Summary tab
5. Look for a portlet called 'Virtual Container Host'
6. Return to the 'Shortcuts' view by clicking the 'vSphere Client' icon on the top navbar
7. In the 'Inventories' section click the 'vSphere Integrated Containers' shortcut.

Note that any version of H5 Client plugin will fail to deploy on a VCSA 6.5u1 setup.

**Actual behavior:**
Plugin would not show up at all

**Expected behavior:**
1. In step 5 above the portlet should appear.
2. In the 'vSphere Integrated Containers' view, the datagrid should show up listing all VCHs and Container VMs installed

**Logs:**
![image](https://user-images.githubusercontent.com/3834071/29388081-d6a46a92-82a8-11e7-92ed-d98d2c568e09.png)

**Additional details as necessary:**
At the point of filing this issue, I already fixed an issue regarding the error message in the screenshot above, but the 'vSphere Integrated Containers' view is still broken. It seems that 1) there was some breaking changes to the way a custom object is extended in H5C, or 2) some portion of the vic-service package is not working properly.

**Comment by jooskim** [comment]
@mdubya66 This is a different issue from #4981 and needs high attention, as I was able to reproduce the issue in a 6.5u1 setup. FYI I've already started conversations with the H5C team to fix the issue as soon as possible.

Also pinging @jak-atx @cristianfalcone

**Comment by jooskim** [comment]
I just confirmed a fix from Vladimir (from H5C team) works on 6.5u1, however I need to test if the fix is backwards-compatible, especially with 6.5.0d or e.

**Comment by stuclem** [comment]
@jooskim we do already recommend that people restart the clients after installing/upgrading the plug-ins. So, are we covered?

**Comment by mhagen-vmware** [comment]
closing based on merge of master

**Comment by jooskim** [comment]
I confirm this issue is present in 1.1.1 and is a regression introduced by vSphere 6.5u1. Now working on a workaround.

**Comment by stuclem** [comment]
Added the following in the 1.1.1 release notes:

-----

- <b>HTML5 vSphere Client plug-in does not work with vCenter Server 6.5u1. [#6052](https://github.com/vmware/vic/issues/6052)</b><br>If you deployed the HTML5 vSphere Client plug-in for vSphere Integrated Containers with vCenter Server 6.5.0, and then subsequently upgraded vCenter Server to version 6.5u1, the plug-in no longer works. Attempts to install the HTML5 plug-in on vCenter Server 6.5u1 fail.

  Workaround: This issue is resolved in vSphere Integrated Containers 1.2. Upgrade to vSphere Integrated Containers 1.2, upgrade the HTML vSphere Client plug-in, and restart the vSphere Client service. For information about upgrading to vSphere Integrated Containers 1.2, see [Upgrading vSphere Integrated Containers](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrading_vic.html).

-----

@jooskim @jak-atx is this OK?
