### ISSUE TITLE
port-layer ignores proxy configuration

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#6053]
When creating a VCH with option  `--https-proxy` or `--http-proxy` the VCH UI connections and connections to registries will use the proxy. Connections over the management network to vCenter for example from port-layer service will not use the proxy configuration. 

First the question is should port-layer use the proxy. Also can this function be added. 

bug1940913

**Comment by dbarkelew** [comment]
Bug 1940913

**Comment by hickeng** [comment]
I don't want to start assuming that a single proxy is accessible from all interfaces, and definitely don't want to accidentally start routing management traffic via the other interfaces.
We could add a specific option for a management network proxy given outbound connections should only be initiated on the public and management networks.

Another option would be to generalize the proxy configuration to something like below (little through applied to specific form, just an example) although this approach would be to be able to handle a network role, e.g. public, as well as a CIDR for the case where we've got DHCP:
`--proxy-server=protocol://proxy:port:destination-network-1,destination-server-A,...`

Third option is that we are very, very specific about where another proxy can be used and couple it explicitly with `vSphere SDK` access rather than a specific network. Open ended is whether the proxy would need to be used to access to the ESX hosts for `docker log -f` tailing or whether those are reachable directly.

@corrieb I think this is one of those configurations I'd really prefer to be able to punt on until we move to a manifest configuration.

**Comment by mdubya66** [comment]
not a requirment for 1.3, removing

**Comment by renmaosheng** [comment]
Dani,
       is this still an issue? thanks.

**Comment by renmaosheng** [comment]
I've resolved the bugzilla PR, closing this as well. I've left https://github.com/vmware/vic/issues/5862 opened for tracking.
