### ISSUE TITLE
vic-machine delete failure: ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6079]
8 out of 50 VCH - Delete VCH failed with -
```
Aug 22 2017 05:39:20.844-04:00 INFO  ### Removing VCH ####
Aug 22 2017 05:39:21.790-04:00 INFO  Validating target
Aug 22 2017 05:39:22.881-04:00 INFO
Aug 22 2017 05:39:22.881-04:00 INFO  VCH ID: VirtualMachine:vm-15275
Aug 22 2017 05:39:23.032-04:00 INFO  Removing VMs
Aug 22 2017 05:40:42.373-04:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-15940"
Aug 22 2017 05:40:42.962-04:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-17869"
...
Aug 22 2017 05:42:59.980-04:00 INFO  Specify --force to force delete
Aug 22 2017 05:42:59.980-04:00 INFO  Collecting da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log
Aug 22 2017 05:43:00.111-04:00 ERROR Failed to destroy VM "VirtualMachine:vm-15647": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess
Aug 22 2017 05:43:00.117-04:00 ERROR --------------------
Aug 22 2017 05:43:00.117-04:00 ERROR vic-machine-linux delete failed: delete failed
[vic-machine.zip](https://github.com/vmware/vic/files/1241611/vic-machine.zip)
```
Attached is the vic-machine log

**Comment by cgtexmex** [comment]
@lgayatri how did you get to this point?  Was this initiated via Admiral?  If so what were the steps that lead up to this issue?  The logs for the specific VCH that failed deletion would be helpful as well.

**Comment by lgayatri** [comment]
@cgtexmex I have 50 VCHs which I delete concurrently using vic-machine-linux delete option. In the next instance of this issue, I will collect the logs from those 8 VCHs. In the first bug comment, I added logs from the client

**Comment by cgtexmex** [comment]
@lgayatri how do you execute `vic-machine-linux delete`?  Shell script?  If so can you provide the details?  Also are all 50 VCH on the same vSphere cluster?

**Comment by lgayatri** [comment]
@cgtexmex I have a multithreaded java code that runs delete concurrently from a linux client. All 50 VCHs are in the same cluster. I emailed you the java code.

**Comment by lgayatri** [comment]
@cgtexmex, I hit this issue again and uploaded the VCH logs

Aug 24 2017 05:20:10.651-04:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-24748"
Aug 24 2017 05:22:26.213-04:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-23382"
Aug 24 2017 05:24:15.864-04:00 INFO  Specify --force to force delete
Aug 24 2017 05:24:15.864-04:00 INFO  Collecting da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log
Aug 24 2017 05:24:15.949-04:00 INFO  da2ca126-f532-4bc0-9b6d-b7cc879b569e vpxd.log rolled over
Aug 24 2017 05:24:15.960-04:00 ERROR Failed to destroy VM "VirtualMachine:vm-22798": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess
Aug 24 2017 05:24:15.980-04:00 ERROR --------------------
Aug 24 2017 05:24:15.980-04:00 ERROR vic-machine-linux delete failed: delete failed

[container-logs (2).zip](https://github.com/vmware/vic/files/1248422/container-logs.2.zip)
[container-logs (3).zip](https://github.com/vmware/vic/files/1248427/container-logs.3.zip)

**Comment by lgayatri** [comment]
I have given the required details and shared the test bed as well, please remove me from need-info.

**Comment by anchal-agrawal** [comment]
Adding this issue to the CI vCenter epic.

**Comment by hickeng** [comment]
Suggest deferring work on this until we've moved to resource-pool only.

**Comment by anchal-agrawal** [comment]
Also seen while running `1-04-Docker-Create` on a 5-node vCenter with vSAN.

**Comment by mhagen-vmware** [comment]
This is unrelated to our effort to port our tests to work with VC, removing from the EPIC.

**Comment by lgayatri** [comment]
I am still seeing this issue on VIC 1.3. This time 35/50 concurrent delete VCH threads failed
```
Nov 13 2017 06:55:15.582-05:00 INFO  Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-7962"
Nov 13 2017 06:55:22.469-05:00 INFO  Specify --force to force delete
Nov 13 2017 06:55:22.469-05:00 INFO  Collecting e53fcd49-9375-46f0-9370-1da83c764012 vpxd.log
Nov 13 2017 06:55:22.495-05:00 INFO  e53fcd49-9375-46f0-9370-1da83c764012 vpxd.log rolled over
Nov 13 2017 06:55:22.511-05:00 ERROR Failed to destroy VM "VirtualMachine:vm-7189": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess
Nov 13 2017 06:55:22.556-05:00 ERROR --------------------
Nov 13 2017 06:55:22.556-05:00 ERROR vic-machine-linux delete failed: delete failed
```
```
/home/vmlib/VIC/VIC-1.3/vic# cat vpxd.log | grep e53fcd49-9375-46f0-9370-1da83c764012
2017-11-13T11:54:10.856Z info vpxd[7F77D02DA700] [Originator@6876 sub=vpxLro opID=qfnwop_e53fcd49-9375-46f0-9370-1da83c764012:VirtualApp:resgroup-v6568_virtualMachine:01-45] [VpxLRO] -- BEGIN lro-443698 -- ResourceModel -- cis.data.provider.ResourceModel.query -- 52a956c2-a78b-7b21-512b-827063375024(52961b2d-8adf-8474-daf6-d2285b3aaa6b)
```
Logs attached:
[container-logs (4).zip](https://github.com/vmware/vic/files/1469027/container-logs.4.zip)

**Comment by lgayatri** [comment]
I still see this issue even on RC2 build : vic-v1.3.0-rc2-2628-9e2a95b6.ova

```time="2017-12-07T22:52:14-05:00" level=error msg="Failed to destroy VM \"VirtualMachine:vm-19069\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to destroy VM \"VirtualMachine:vm-18538\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to fetch guest info of appliance vm: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: read tcp 10.133.152.229:40184->10.133.146.15:443: read: connection reset by peer\nFailed to destroy VM \"VirtualMachine:vm-20301\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to destroy VM \"VirtualMachine:vm-18648\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to destroy VM \"VirtualMachine:vm-20237\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to destroy VM \"VirtualMachine:vm-20039\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF\nFailed to destroy VM \"VirtualMachine:vm-18739\": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-18383\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-19832\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-18985\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-20170\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-19946\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-17809\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-18311\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: EOF then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-17813\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-20004\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused\nFailed to destroy VM \"VirtualMachine:vm-19610\": Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused then failed to unregister VM: Post https://wdc-stvc3944-146-dhcp15.eng.vmware.com/sdk: dial tcp 10.133.146.15:443: getsockopt: connection refused"
time="2017-12-07T22:52:14-05:00" level=warning msg="Proceeding with delete of VCH due to --force"
time="2017-12-07T22:52:14-05:00" level=info msg="Removing image stores"
time="2017-12-07T22:55:01-05:00" level=info msg="Removing volume stores"
time="2017-12-07T22:55:01-05:00" level=info msg="Removing appliance VM network devices"
time="2017-12-07T22:55:03-05:00" level=info msg="Unregistered VM to cleanup after failed destroy: \"VirtualMachine:vm-17563\""
time="2017-12-07T22:55:43-05:00" level=info msg="Removing Resource Pool \"U-VIC-0001\""
time="2017-12-07T22:55:43-05:00" level=warning msg="VCH resource pool is not removed: Resource pool is not empty: \"\""
time="2017-12-07T22:55:43-05:00" level=info msg=----------
time="2017-12-07T22:55:43-05:00" level=info msg="If firewall changes were made for VIC during install, they were not reverted during delete"
time="2017-12-07T22:55:43-05:00" level=info msg="To modify firewall rules see vic-machine update firewall --help"
time="2017-12-07T22:55:43-05:00" level=info msg=----------
time="2017-12-07T22:55:43-05:00" level=info msg="Completed successfully"
```

**Comment by lgayatri** [comment]
Since the VCH gets deleted in the first instance, the second attempt with vic-machine-delete will fails with below error:
```
time="2017-12-07T23:56:09-05:00" level=info msg="### Removing VCH ####"
time="2017-12-07T23:56:09-05:00" level=info msg="Validating target"
time="2017-12-07T23:56:10-05:00" level=error msg="Didn't find VM \"U-VIC-0001\" in resource pool \"ResourcePool:resgroup-17562\""
time="2017-12-07T23:56:10-05:00" level=error msg="Failed to get Virtual Container Host U-VIC-0001"
time="2017-12-07T23:56:10-05:00" level=error msg="Didn't find VM \"U-VIC-0001\" in resource pool \"ResourcePool:resgroup-17562\""
time="2017-12-07T23:56:10-05:00" level=error msg=--------------------
time="2017-12-07T23:56:10-05:00" level=error msg="vic-machine-linux delete failed: delete failed\n"
```

**Comment by lgayatri** [comment]
@mdubya66 

Seeing this issue with RC3 as well.
```
time="2017-12-11T07:28:48-05:00" level=info msg="Unregistered VM to cleanup after failed destroy: \"VirtualMachine:vm-21200\""
time="2017-12-11T07:29:00-05:00" level=info msg="Removing image stores"
time="2017-12-11T07:29:33-05:00" level=error msg="vic/pkg/trace.(*Operation).Err: vic-machine-linux error: context deadline exceeded\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux"
time="2017-12-11T07:29:33-05:00" level=error msg="vic/pkg/trace.(*Operation).Err: vic-machine-linux error: context deadline exceeded\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux"
time="2017-12-11T07:29:33-05:00" level=error msg="vic/pkg/trace.(*Operation).Err: vic-machine-linux error: context deadline exceeded\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux"
time="2017-12-11T07:29:33-05:00" level=error msg="vic/pkg/trace.(*Operation).Err: vic-machine-linux error: context deadline exceeded\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux"
time="2017-12-11T07:29:33-05:00" level=error msg="vic/pkg/trace.(*Operation).Err: vic-machine-linux error: context deadline exceeded\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux"

```

**Comment by lgayatri** [comment]
Did not see this error when deleted VCHs running few hours of uptime with RC3 build.

**Comment by AngieCris** [comment]
@lgayatri Can you send me via email the java code that runs this concurrent VCH delete?

**Comment by lgayatri** [comment]
@AngieCris - Email sent .

**Comment by AngieCris** [comment]
The reproducing steps are:
1. create 50 VCHs
2. run 50 containers in each VCH
3. destroy all the VCHs concurrently. 
However following the steps I'm having trouble reproducing this failure. 
@lgayatri Have you been seeing this error again in rc3 build? 

Tracking down the code, this should be how the failure happened:

When destroying a VCH, we destroy the container VMs first, and then the VCH appliance VM. To destroy the container VMs of one of the containers hosted on the VCH, for each container VM we run the vSphere API function `destroy_Task`.
This `destroy_Task` API function can be explicitly disabled so that when somebody wants to force remove it after it's disabled, they will get a `method disabled by ...` response from the API. In VIC, we disable `destroy_Task` on container create. And then we re-enable it on container remove. 

In the case of this error, during the destroy process of one of the container VMs on a VCH, we hit the `method disabled by ...` response. 
And then, after we hit this response, we try to just unregister the container VM, and it failed subsequently with the error `ServerFaultCode: vim.fault.ConcurrentAccess`. This failure could be a direct result of the disabled destroy.
```
Aug 22 2017 05:43:00.111-04:00 ERROR Failed to destroy VM "VirtualMachine:vm-15647": ServerFaultCode: The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess
```

The weird thing is that we have explicitly enabled the vm destroy on container remove: https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L624. If this line is executed, we shouldn't be able to hit the `method disabled by ...` response.

**Comment by lgayatri** [comment]
I have not seen this issue in RC3

**Comment by lgayatri** [comment]
Seen again in RC5. https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-rc5-2996-f8cc7317.ova 

See https://github.com/vmware/vic/issues/7020

**Comment by stuclem** [comment]
@anchal-agrawal @lgayatri I have no idea how to write this up in the release notes. What are the obvious symptoms? Thanks!

**Comment by AngieCris** [comment]
@stuclem @anchal-agrawal Maybe sth along the lines of:

- <b>Deleting multiple VCHs fails. [#7020](https://github.com/vmware/vic/issues/7020)</b><br>Deleting multiple VCHs at the same time fails with the error `ServerFaultCode: The method is disabled by 'VIC'`.

   Workaround: Try the delete operation again.

Does this look okay?

**Comment by lgayatri** [comment]
Looks good.

**Comment by stuclem** [comment]
Thanks @lgayatri and @AngieCris

**Comment by AngieCris** [comment]
Root cause identified:

**Steps to reproduce**
1. Create 50 VCH
2. Spin 50 containers in each VCH with `docker run`
3. Delete the VCHs concurrently with `vic-machine delete`
Then during the delete of one/some of the 50 VCHs, it fails with the error message:
```
The method is disabled by 'VIC' then failed to unregister VM: ServerFaultCode: vim.fault.ConcurrentAccess
```

**Explanation of each step**
1. Create 50 VCH
2. Spin 50 containers in each VCH with `docker run`
When we create these container VMs, to prevent user from destroying container VM in vSphere UI, we explicitly disabled the destroy method on the container VM from portlayer.
Only the same session that disabled the destroy can evoke destroy. For any other session, for example vic-machine session, it would have to enable destroy explicitly in order to destroy the VM. 
3. Delete the VCHs concurrently with `vic-machine delete`
Before destroying the appliance VM, we destroy all container VMs first.
Essentially two steps happened here:
(1)  For each container VM, since we created it using docker run, the destroy method on this VM was already disabled by portlayer session. However, vic-machine delete is a different session, we won't be able to destroy this VM directly, since this method is disabled. So the destroy will result in a `This method is disabled by VIC` error message. 
(2) Since the destroy failed, we attempt to unregister the container VM instead, and then manually cleanup the datastore files. For most container VMs, unregistration succeeds; but for some container VMs, the unregistration fails due to concurrent access. In this case, we see the `ServerFaultCode: vim.fault.ConcurrentAccess` error message in the log.
The above two steps happen for every container VM that has not been removed by `docker rm`. The reason why we don't see the `This method is disabled by VIC` error for every container VM, is because if unregistration succeeds, we ignore this error message. We can only see the failure from destroy if unregistration fails too.

**Problems**
There are two problems that need to be fixed here:
1. We should check first if destroy is disabled by another session, and then enable the destroy in vic-machine for the container VM. Any code path that uses `vm.Destroy` should do the conditional check. Currently since we don't have the check, we unregister every container VM, and most of them is unnecessary work if we can directly destroy the container VM. 
2. Even if we enable destroy on container VM, destroy could still fail in errors such as `vim.fault.ConcurrentAccess`, or other. This means we need to keep the unregister step if destroy fails.
3. We can't guarantee that unregistration will succeed. We need to properly handle failure from unregistering the VM.

**Fix**
The proposed fix has two steps:
1. Enable destroy on the container VM from dispatcher, conditionally if the session is unauthorized.
2. Wrap the destroy and unregister steps in a retry pattern. 
PR addressing the proposed fix coming up.
