### ISSUE TITLE
ESXi compute resource default

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#612]
When installing directly against ESXi with no Virtual Center then the vic-machine installer should be able to determine the compute resource path and not require the user to provide it.

**Comment by hickeng** [comment]
This is the behaviour we had with Bonneville but the differences between VC and ESX, and particularly the confusion around -datacenter -cluster and -host was significant. It's viable to automatically determine the datacenter in the case of ESX or simple VC config, but not any sub-pools.

Let's go with the unix model for execution and always require a path, even it's it's `./`. If nothing else it makes the documentation easier to read due to reduced if/then/else... logic.

@cgtexmex comment on the vic-machine usage examples PR - I am leaning towards having a separate datacenter flag.
