### ISSUE TITLE
docker run ls of a volume mounted folder does not exit

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6371]
I copied some data into a container that had a volume mounted, then I attempted to ls the data in the volume from a different container and the terminal never returned from the docker ls command, until I ctrl-c out of it:
```
anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.185:2376 --tls cp app/ copier:/mydata
anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.185:2376 --tls run -it -v vol1:/mydata busybox ls /mydata
app                package-lock.json



^C
```

[container-logs (1).zip](https://github.com/vmware/vic/files/1307701/container-logs.1.zip)

**Comment by hickeng** [comment]
There is a missing nil check in the fix for #6283 - no idea how all three of us missed it in authoring and review, too much hurrying I'd guess. I don't know if that's actually the problem, but definitely _a_ problem and proximate to the faulty code path.

@mhagen-vmware I suggest we add scanning logic for panics in the log bundles, even after successful runs - there can be some legitimate use of panic, however there should also be handlers for those to turn them into sanitized and useful errors.
