### ISSUE TITLE
Update CI downstream trigger to allow upstream job to specify a specific build to use

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic#6554]
**User Statement:**
As a developer, I want vic repo pass its build artifact name to the triggered downstream vic-product build, so to avoid missing builds due to race condition. 

As a developer, I want to be able to trigger downstream builds as a result of pull requests.

**Details:**
Pass build artifact name as is so we can include it in building OVA.

**Acceptance Criteria:**
Downstream vic-product build picks up the exact vic build version from the vic build which triggered it.

Downstream builds clearly convey the event which triggered them and the artifacts which were included. The type of upstream artifacts included in a build affect the way the downstream artifacts are published (e.g., if a downsteam push build on a `master` branch is re-run using consuming upstream artifacts from a `develop` branch or upstream artifacts from a `pull_request` event, those artifacts should not be published alongside "pure" push builds on `master`).

**Comment by mhagen-vmware** [comment]
This should be quite easy now with the new downstream trigger I have added:
https://github.com/vmware/vic/blob/master/infra/integration-image/Dockerfile.downstream

Should just need to add 
`   --param, -p [--param option --param option]	custom parameters to be injected into the job environment. Format: KEY=value`
to the fork call

**Comment by renmaosheng** [comment]
@zjs could you please close this issue if we already fixed? thanks.

**Comment by zjs** [comment]
This is not yet fixed.

**Comment by renmaosheng** [comment]
Lu, is this issue in our list? thanks.

**Comment by luwang-vmware** [comment]
We already have CI downstream trigger for each push and tag event.  
For the pull request to trigger CI downstream, I do not think it is critical to implement it now due to the following reasons.
1. Developer always rebuild multi times to pass the build for 1 pull request. If we enable PR to trigger CI downstream, it will lead more jobs running on the vic-product to cost vic-product CI testbed resources(we have limited vic-product CI testbed resource), which will make the jobs waiting in the queue.  Guarantee vic-product pull request/push/tag event to test immediately is our highest priority.
2. in current phase, we do not have request on it.

So close it now. Reopen it if we have strong request in future.
