### ISSUE TITLE
Update symlink handling in tar archives

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6618]
Symlink handling in archive processing needs to be consistent, irrespective of the actual link definition.
This applies to:
- [ ] pull
- [ ] save/export/commit
- [ ] cp to/from

bug 1973536 & 1994971

**Comment by mdubya66** [comment]
This is a ship criteria for 1.3. if we don't have the fix then we need to get an exception.

**Comment by jzt** [comment]
```go
package main

import (
	"fmt"
	"path/filepath"
	"os"
	"strings"
)

func main() {
	dest := "/mnt/files/foo/bar"
	headerPath := "../../../../../../../etc/shadow"  // arbitrarily excessive number of "../"'s
	
        path := filepath.Join(dest, headerPath)
	fmt.Printf("full path: %s\n", path)
	p, _ := filepath.Rel(dest, path)
	fmt.Printf("relative path: %s", p)
	
	if strings.HasPrefix(p, ".."+string(os.PathSeparator)) {
		fmt.Printf("\nError: %s is outside of target directory, bailing out\n", p)
	}
}
```

Result:
```
full path: /etc/shadow
relative path: ../../../../etc/shadow
Error: ../../../../etc/shadow is outside of target directory, bailing out
```

@hickeng @gigawhitlocks would this work for all files (symlink or not)?

**Comment by jzt** [comment]
Actually, for symlinks we would need to check the header `Linkname` field instead of (in addition to?) the `Name` field.

**Comment by sflxn** [comment]
I believe bug 1994971 is also covered under this issue's umbrella.

**Comment by gigawhitlocks** [comment]
Additional concerns regarding symlinks to directories as outlined by George:

Dockerfile contains:
```
# My app expects to find a hosts file in /foo/hosts so let's be lazy
RUN ln -s /foo /etc

# App expects to find some other files in /foo so add them from internet
ADD sample-shadow.file /foo/shadow
```
This is a dumb example, but should result in a functioning image for us because the contents of some-ur-to-archive will be unpacked into `/etc` in the image so the generated layer archive will have `/etc/shadow` as modified.

Your archive will contain:
```symlink: /foo -> /etc
regfile: /etc/shadow
```

We will unpack that cleanly:
1. create symlink `root_of_image_mount/foo ->/etc`
2. create regfile `root_of_image_mount/etc/shadow` (edited)

The malicious form is done simply by messing a little with the archive:
```
symlink: /foo -> /etc
regfile: /foo/shadow
```
(note that the regular file now uses the symlink based path, not the canonical path)

We will unpack that as:
1. create symlink `root_of_image_mount/foo -> /etc`
2. create regfile `root_of_image_mount/foo/shadow`
  a. os finds the directory `root_of_image_mount/foo`
  b. os resolves the directory symlink to `/etc/` canonical path
   c. os creates regular file `/etc/shadow`
  d. os wags its tail because it did _exactly_ what we told it to

**Comment by sgairo** [comment]
@gigawhitlocks is this accurately estimated? Is it worth updating?

**Comment by mdubya66** [comment]
an epic, removing kind/bug to prevent double counting

**Comment by mdubya66** [comment]
added proposed-1.3.1 to the only issue planned.

**Comment by gigawhitlocks** [comment]
Sub-tasks are complete and this is ready to be closed.
