### ISSUE TITLE
Longevity failure: container name in use

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6697]
It appears that we randomly tried to pick the same name we already had randomly given to a container:
```
Nov  5 2017 22:56:06.890Z ERROR Handler for POST /v1.23/containers/create returned error: conflict. The name "happy_hoover" is already in use by container 70af98fc862598113ed501952be1f14675abcf5ba2539f5a5b5da9665699364d. You have to remove (or rename) that container to be able to re use that name.
```

[container-logs.zip](https://github.com/vmware/vic/files/1446910/container-logs.zip)

**Comment by anchal-agrawal** [comment]
This is likely due to https://github.com/vmware/vic/blob/cb687c09be5b88934d20f8d10e230a35b8e5248b/lib/apiservers/engine/backends/container.go#L2012

The `GetRandomName` func has a retry parameter which, if non-zero, causes the name to be appended by a random number b/w 0 and 10. We can also have an ad-hoc retry mechanism:

* get name, retry if it exists in the persona container cache, retry again with the retry parameter if needed
* get a bunch of names at once and take the first one that doesn't exist

Both approaches aren't foolproof theoretically but offer a best-effort strategy that will work in most use cases (given that the original error is rare as it is). For true randomness, we could consider appending the name with a UUID.

**Comment by mhagen-vmware** [comment]
Do we really need randomness?  We own all of the container VMs within a resource pool.. can we not just ensure we don't use an already used name?

**Comment by anchal-agrawal** [comment]
See https://github.com/vmware/vic/pull/6742.

**Comment by hickeng** [comment]
@sgairo I ended up creating a PR for this as it failed in a PR build for a different issue of mine this morning. Didn't realize there was an existing issue.
