### ISSUE TITLE
VCH List API may return 500 if a VCH is being deleted

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6792]
**Steps to reproduce:**
1. Populate a system with several VCHs
2. Run test suite 23-02
3. While the suite is running, delete the VCHs added in step 1.

**Actual behavior:**

Get a `500` with a body like:

```
{"message":"Failed to search VCHs in : Failed to query children VM in resource pool \"/dc1/host/cluster1/Resources/concurrent-d-1\": Unable to find VM(concurrent-d-1): ServerFaultCode: The object ...
```

**Expected behavior:**

The response succeeds. The response may or may not include the VCH being deleted.

**Comment by andrewtchin** [comment]
defer, not in 1.3

**Comment by zjs** [comment]
Proposing for Sprint 22 to get this API functionality stable before we build on in post-1.3.

**Comment by AngieCris** [comment]
In both cases described in the previous comment, the partially created/destroyed VCH should be created in the list, and the user needs to know the status of the VCH. The VCH list API should not abort and return error if one/any of the VCHs being listed is in bad state.
Discussed with @zjs , there are two possible ways:
1. In the output of VCH list API, every VCH being listed includes a status of:
   * partially created (if the VCH is being created or partially deleted)
   * powering on (the endpoint VM is being powered on)
   * starting (endpoint VM has started, portlayer hasn't)
   * running
2. For every VCH being listed, if there is an error listing it, the error should be included in the output of VCH list API, and the API will move to list the next VCH. It's left to the user's judgement as to what causes the bad state of that particular VCH and how to resolve it. 
(The UI can use this error info and display the error as a tooltip or something)

For option 1, it's hard to determine if the VCH is being partially created, or if the VCH is broken. However the `powering on` and `starting` states are useful information for the user, for example, for some VCH in starting state where portlayer is not up yet, it's possible to be detected by the list API (if I got it right?)
So maybe we could adopt a combination of both approaches: display the partial/powering on/starting/running state of each VCH, and also include an error field if the VCH is partial.

**Comment by zjs** [comment]
I think option 2 would be a good addition to the API, and should not be particularly complicated. I think option 2 would continue to be useful even if we add option 1 later (e.g., as a part of #6889).

Let's focus on option 2 in this issue.

**Comment by AngieCris** [comment]
The process that an API ls operation goes thru is:
1. search for all resource pools under a datacenter or compute path
2. for each pool, if it's a VCH pool and the VM inside is a VCH appliance VM, list that VCH
3. for each VCH found, grab from its extra config and fill in swagger API response model

When an API VCH list operation and API VCH delete operation are running concurrently, there are 4 possible scenarios:
1. delete operation runs faster. The VCH resource pool is already removed when ls operation goes thru step 1 of listing all pools.
2. When ls operation goes thru step 2 of listing all pools, the concurrent delete operation has not removed the VCH pool yet, but the endpoint VM within that pool has already been destroyed. 
3. When ls operation goes thru step 2 of listing all pools, the concurrent delete operation has already destroyed the endpoint VM within the pool, and is in the process of removing the VCH pool.
3. delete operation runs slower. When ls operation goes thru step 1-2, the pool and VCH VM have not been moved yet, but when ls operation goes thru step 3, the extra config for that partial VCH is already gone. 

What would happen under each one of the scenarios above is:

**Result of scenario 1**
Both delete and ls operation succeed. Ls operation outputs a list of VCHs without the deleted VCH.
**Result of scenario 2** 
delete operation succeeds, ls operation fails with 500 Internal Server Error. The error json output is:
```
{"message":"Failed to search VCHs in : Failed to query children VM in resource pool \"/ha-datacenter/host/Cluster1/Resources/vch-7\": Unable to find VM(vch-7): ServerFaultCode: The object 'vim.ResourcePool:resgroup-563' has already been deleted or has not been completely created"}
```
This is because in this scenario there is no children VM under that VCH pool because the endpoint VM is removed by the background delete operation.
**Result of scenario 3**
delete operation succeeds, ls operation fails with 500:
```
{"message":"Failed to search VCHs in : Failed to search resource pools for datacenter \"/ha-datacenter\": ServerFaultCode: The object 'vim.ResourcePool:resgroup-553' has already been deleted or has not been completely created"}
```
This is because the VCH pool is being deleted at the same time when it's being listed. 
**Result of scenario 4**
This is specific to API implementation where we grab the extra config and fill in swagger model. If the extra config does not exist, we simply log a warning message and move on to the next VCH.

The proposed fix for each scenario is:

**Fix of scenario 1**
Nothing to fix
**Fix of scenario 2**
When the ls operation is searching VCHs from a list of pools under datacenter, it should skip it if it is not able to get child VCH from that pool, instead of aborting and returning an error. This is just a logic change in function `getChildVCHs` under `/management/finder.go`.
**Fix of scenario 3**
This scenario is tricky, because the failure results from not being able to list all resource pools under a datacenter, when one of the pools is being deleted by a concurrent operation. The resource pool list operation involved here is a govmomi call. The error it returned has type `ManagedObjectNotFound`. 
One thing we could do is to simply retry the list operation. If a background delete operation is indeed removing resource pools, the subsequent retries should succeed pretty soon. But we're not sure as to other cases where listing resource pool might fail with `ManagedObjectNotFound` error.
Or govmomi could change the logic of listing resource pools to skip any errors or at least give us a list containing the leftover pools. I'm not sure if it's a reasonable thing to do. Pining relevant people for input: @dougm 
**Fix of scenario 4**
Current behavior of skipping the VCH without a config is totally fine. 

Also, a bigger change that would get all of these problems around is to filter all VMs in a cluster/dc based on tag. Then we will get around the resource pool search. But that's a bigger fix that goes well beyond the scope of this ticket.

@zjs @hickeng

**Comment by dougm** [comment]
Finder could probably ignore `ManagedObjectNotFound` errors, but this hasn't come up before.  Feel free to open a PR or issue in govmomi.

**Comment by AngieCris** [comment]
@dougm Thanks! New ticket submitted in govmomi: https://github.com/vmware/govmomi/issues/1087
