### ISSUE TITLE
Failed upgrades create multiple snapshots

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7083]
VIC Engine - v1.2.1-13858-c3db65f > v1.3.0-**15556**-473375a

User statement: As a customer of VIC, I would like to have upgrade and reversion to be seamless. Upgrade process could also check if there's an existing Snapshot (due to earlier failure) before creating a new one of the same name.

time="2018-01-11T18:28:25+08:00" level=info msg="Rolling back upgrade"
time="2018-01-11T18:28:25+08:00" level=info msg="Reverting to snapshot reconfigure for **15556**"
time="2018-01-11T18:28:40+08:00" level=error msg="Failed to revert appliance to snapshot: Failed to roll back upgrade: \"reconfigure for 15556\" resolves to 2 snapshots."

if upgrade is successful, vic-machine could optionally prompt to delete the snapshot taken.

**Comment by AngieCris** [comment]
Cc: @andrewtchin

**Comment by andrewtchin** [comment]
@malikkal Did you manually delete the snapshots and retry upgrade? Was it successful after that?

**Comment by emlin** [comment]
@malikkal @andrewtchin is correct, you should be able to workaround this issue by manually delete the older snapshots.

For this particular issue, what's the command to get this error? Failed upgrade command or rollback command? 

From the code, I think it's rollback command. Failed upgrade command could remove snapshot successfully, but if same name snapshot exists, rollback command will fail. https://github.com/vmware/vic/blob/master/lib/install/management/configure.go#L203 is still rollback using snapshot name, but this method https://github.com/vmware/vic/blob/master/lib/install/management/configure.go#L212 is rolling back using snapshot reference.

Ideally, the code should make sure only one snapshot exists, and the old one should be deleted in next whatever command. If that's not the case, we should fix the multiple snapshots issue, unless that's because failed snapshot delete. Did you still remember why there were multiple snapshots?

In addition, the code should always tolerant multiple snapshots scenario, in case there is anything unexpected happen, e.g. failed to delete snapshot in previous command execution.

@AngieCris if the error is as what I said, you could fix the rollback code, to revert to current snapshot directly in this method: https://github.com/vmware/vic/blob/master/lib/install/management/configure.go#L203, and before this line, check if the current snapshot is one reconfigure or upgrade snapshot.

@gigawhitlocks ever worked on this refactor, please correct me if there is anything wrong.

**Comment by malikkal** [comment]
@emlin, @andrewtchin thanks; yes, this is what was done. It wasn't a show stopper.

Just highlighted here so that you could fix it in the next release, if possible. Thank you.

**Comment by emlin** [comment]
Thanks @malikkal for your confirmation. Just a bit more questions, was this happened during rollback command? Do you still happen to remember what steps caused the multiple snapshots?

**Comment by mdubya66** [comment]
Removing from the 1.3.1 release and including in the following release. Adding kind/note.

**Comment by stuclem** [comment]
Just noticed that this has the kind/note flag. Attempted RN:

- <b>Failed upgrades create multiple snapshots. [#7083](https://github.com/vmware/vic/issues/7083) If upgrade fails, the snapshot that is taken prior to the attempted upgrade is retained. Multiple attempts to upgrade can lead to multiple snapshots being created.

@emlin does this cover it? Thanks!
