### ISSUE TITLE
docker commit - use case question

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7119]
Assuming I did a commit on a stopped container after making some changes, which is saved into the VCH image cache; may I know what would be the right way to take it out; i.e. push to a repository if needed. Thanks.

**Comment by AngieCris** [comment]
Cc: @anchal-agrawal

**Comment by hickeng** [comment]
@malikkal honestly the use case for `commit` in a VCH was always a little flimsy - I could see obvious use in `diff` for audit of files that should/shouldn't be modified by a well behaved application. `commit` lets you preserve the state for later investigation.

It was added due to a PM desire to move towards full support for the build/push cycle, but that's not what we'd engineered the VCH for - it was specifically for the far right end of the CI/CD pipeline, with docker or other image authoring tools being the means by which images are built and pushed into registries.

I'd find it much easier to express reasons why `commit` _shouldn't`_ be allowed from a production system. The only use-case I was ever able to really assemble for commit+push from production systems was for archiving production bits directly from production when performing upgrades/security analysis/audit/etc.

Regardless, without push implemented it's mostly an orphaned capability. Push was mostly implemented for 1.2 but I wanted a lot more testing to ensure we were always providing well-formed and consistent images/layers from the perspective of the rest of the registry; I really wasn't sure on the implications of pushing an image to public repos that wasn't consistent with semantic custom, even if it's consistent with the spec. Absent actual requests from customers for push from VCH, and several commenting that they'd need a way to disable it, it's not raised in priority again.
