### ISSUE TITLE
Named volumes incorrectly detected as anonymous, getting deleted when container is removed

### ISSUE THREAD

**Issue by coreydinkens** [vmware/vic#7138]
#For bug reports, please include the information below:

**VIC version:**

1.3.0 / Commit ID# 473375a

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
vic-machine-windows --target=https://X.X.X.X --thumbprint=<thumbprint> --name=dev-vch --compute-resource=/AWN-DC-H5/host/AWN Production/Resources/Servers --ops-user=administrator@vs
phere.local --image-store=ds://Servers-AFA --volume-store=ds://Servers-AFA/docker-volumes:default --dns-server=X.X.X.X --bridge-network=vic-bridge --bridge-network-range=172.32.0.0/12 --public-network=Manage
ment --public-network-gateway=X.X.X.X --public-network-ip=X.X.X.X/24 --container-network=WWW:vic-www --container-network=Management:vic-mgmt --container-network-gateway=Management:X.X.X.X/24 --container-
network-gateway=WWW:X.X.X.X/24 --container-network-ip-range=WWW:X.X.X.X/25 --container-network-ip-range=Management:X.X.X.X/29 --container-network-dns=Management:X.X.X.X --container-network-dns=
WWW:X.X.X.X --memory-shares=500 --cpu-shares=500

**Steps to reproduce:**

_**The image being used for testing is sebp/elk:611**_

These are the steps I have been performing when I experience the bug:

1. Follow procedure for backing up/restoring VMDK's for docker volumes (vic 1.3 documentation)
2. restart VCH to detect new volumes 
3. Run container using the following: docker -H vch.awninc.local:2376 --tls run --name elk-node2 -p 9200 -p 9300 -it --rm -m 4G -e LOGSTASH_START=0 -e KIBANA_START=0 -e MAX_MAP_COUNT=262144 --memory-swap -1 --network vic-mgmt -v elk-node2-config:/etc/elasticsearch/ -v elk-node2-data:/var/lib/elasticsearch vic.awninc.local/utilities/elk:611 bash 
4. Stop container by exiting bash, using 'exit'

**Actual behavior:**
Container is stopped and removed from VCH; 2nd named volume gets deleted (in this case, elk-node2-data)
**Expected behavior:**
Container stops and is removed, all named volumes remain intact.
**Logs:**

[logs (1).zip](https://github.com/vmware/vic/files/1648043/logs.1.zip)

**Additional details as necessary:**
Named volumes in question that are being attached to the containers were moved from another datastore.

**Comment by matthewavery** [comment]
```

**Comment by matthewavery** [comment]
##Alright Full Analysis: 

The situation that is occuring here effects two docker operations. `docker rm -v` and `docker run --rm`. This **WILL** lead to data loss is the below scenario.

###The issue: 
named disks are deleted when overlapping them on top of the path which is marked for volume usage in the targeted image.

in the issue description the `sebp/elk:611` image is used. This has a volume at `/var/lib/elasticsearch`. So if a user were to do what was done above ---> `docker run --rm -v my-named-volume:/var/lib/elasticsearch sebp/elk:611` then `my-named-volume` will be interpreted as an anonymous volume. This is caused because we do not remove entries in the containers `config.volumes` map. This map indicates where a volume is mounted if it is not considered a bind. In VIC the `Binds` map is a map of the named volumes that are being joined to the container. in this case we are joining `my-named-volume` to the container and this supersedes the need for an anonymous volume to be created. Unfortunately we do not clear that path from the `volumes` section so at deletion time `my-named-volume` is interpreted as an anonymous volume...

###To fix this:

The Volumes entry for the superseded image volume must be removed from the metadata of the container before we make the anonymous volume metadata pass. This will need to occur between when we establish the `finalizedVolumeList` and when we do the `AnonymousVolumeMetadata` pass. Roughly here: https://github.com/vmware/vic/blob/8129f41a80a0d10d895de9748b836b04e4c46445/lib/apiservers/engine/backends/container_proxy.go#L392  

We will also be including new tests in both the `docker run` and the `docker rm` suite that will ensure correctness going forward with how volumes are treated. Along with tests in the `docker volume` test suite that will ensure correctness in the metadata of the volumes going forward. 

If time permits some tests surrounding backup and restore of volume stores as well(likely to become a separate ticket due to time constraints)
