### ISSUE TITLE
Migrate endpointVM and containerVM to Photon2.0

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7231]
**Story**
As a VIC developer I want to use the latest released version of dependencies whenever technically viable, avoiding forced upgrade scenarios when dealing with CVE mitigation or similar.

**Details**
Upgrading to Photon2.0 will gain us a couple of perks:
1. shift to the more granular package dependencies, reducing footprint
2. easier path to adopt/request additional features (e.g. gpgpu driver support)
3. alignment with Photon dev team focus

My preference would be to have this work done in conjunction with #5352 and leveraging the investigation and preliminary work done in https://github.com/hickeng/vic/tree/custom-iso.
This gives us a mechanism by which we can support Photon1.0 and Photon2.0 in parallel while the dev/acceptance work is occuring, and also progresses us towards a customer request.

This *will* require updates to the ISO generation scripts to shift us to using `tdnf` for initial package installation as the new dependency format isn't understood by `yum`.
I suggest allowing the "repo" definitions in that branch to define which package manager they require and a script interface to abstract the differences - this is optional if the photon2.0 tdnf understands the older centos6.9 packages correctly, but suspect it's worth the minor time cost anyway.

Requires further design decomposition:
- [ ] Design
  - [ ] Identify per repo/kernel elements that need to be abstracted
  - [ ] Define abstraction approach for identified elements
  - [x] Plan appropriate file structure (current structure in branch is just for prototyping)
  - [x] Plan how a customer specified custom ISO will be configured - this doesn't need to be supremely polished, but should be easily understood and well documented.
- [ ] Add Photon2.0 tdnf into build image, OR
  - [x] start building in Photon2.0 based image
- [x] Update script functions for caching and install for tdnf
- [x] Identify which packages can be switched to `toybox` and do so

**Comment by hickeng** [comment]
@morris-jason For the per repo/kernel elements mentioned above, there are the following examples:
* package repository
* package tool (yum for now, will need to shift to tdnf for photon2.0)
* entropy daemon (basic abstraction [hacked in here](https://github.com/hickeng/vic/blob/custom-iso/isos/base/repos/photon-2.0/init.sh) )
* iptables and associated dynamically loaded modules
* kernel package/file

The custom-iso branch has most of this hacked into place as preliminary pass at what currently needs separation based on:
* centos-6.9
* photon-1.0 local repo
* photon-1.0 official remote repo
* photon-2.0
* photon-1.0 with pass through (talk to @mhagen-vmware )

I would recommend figuring out what needs to change to get the photon2.0 support in that branch working again before committing to an approach. Last week it was failing due to what looked like an incorrect package dependency, which I suspect is due to photon2.0 transitioning to "rich dependencies" which are unsupported by yum.
As such I suggest I recommend getting `tdnf` into the build image, [updating the script checks](https://github.com/hickeng/vic/blob/custom-iso/isos/base/utils.sh#L179) and adding a version of [this shell function](https://github.com/hickeng/vic/blob/custom-iso/isos/base/utils.sh#L270) that uses tdnf.
I have a strong preference to preserve the package caching mechanism as it has significant build time impact for development environments.

**Comment by morris-jason** [comment]
@hickeng @mdubya66 posting an update here:

### To @hickeng on 5/3/18
My branch is here~ build the build image: vic/infra/build-image/Dockerfile

The photon2 portion of the build is running fine. The custom-iso portion is not.

Here is the problem breakdown:
1. The centos build, ie /Users/morrisjason/go/src/github.com/vmware/vic/isos/base/repos/centos-6.9, needs yum to install dependencies. Tdnf does not work for centos repos here because of its rich dependencies resolution.
2. Therefore, we must have yum installed on the build image. However, photon2 will not allow yum to be installed. So…
3. We may consider a linuxkit approach here, where each distro build has a separate base dockerfile to gather the right dependencies. I could image having a Dockerfile.tdnf and Dockerfile.yum build image we need before executing the respective base/appliance/bootstrap builds. This introduces a new dependency on multiple os versions that may cause conflicts with our os agnostic build scripts.
4.  Other than this issue, I anticipate the build scripts to function correctly with centos/rhel builds.

 On a final note, there is still work to be done on my branch with regards to documentation and comment cleanup.

## Update
I've added a separate dockerfile that includes yum to do centos builds: vic/infra/build-image/Dockerfile.yum

### Notable process changes:
1. Builds must happen in a docker container because tdnf is not available on packaged as an executable for any linux distro other than photon linux. We could compile TDNF on each developer's machine to build isos, but why not use a docker file for this?
2. Distribution specific options - such as packages, kernel, init, and name - now exist in json config files under each repo name, such as `vic/isos/base/repos/photon-2.0/repo-spec.json`
3. The photon 2.0 appliance does not use toybox, but the photon 2.0 bootstrap does.
4. I've updated the scripts to use a proper getty auto login (tech debt).

### To do:
- [ ] Rebase on master (lots of changes since March).
- [ ] General build script cleanup and documentation
- [ ] Verify scripts work on a sysvinit system, as I've only tested with systemd.
- [ ] Implement CI mechanisms to build dockerfile.tdnf and dockerfile.yum to build isos.
- [ ] Promote usage of `vic/infra/build-image/setup-repo.sh`
- [ ] Document how the customer is actually going to build their custom iso.
- [ ] Verify functionality of iptables
- [ ] Verify a functional debug photon 2.0 iso.
