### ISSUE TITLE
Test 12-01-Delete doesn't remove the VCH certs directory

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic#7302]
Seen in https://ci.vcna.io/vmware/vic/16168. The `Suggest resources - Invalid datacenter` test in `Group6-VIC-Machine.6-05-Create-Validation` failed because of a VCH name collision with a previous VCH (from test `Group12-VCH-BC.12-01-Delete`) whose certs dir was not cleaned up.

I think this is due to https://github.com/vmware/vic/blob/19c47c4212dbd35d70ce9adcc5ecfe7b54a918a0/tests/test-cases/Group12-VCH-BC/12-01-Delete.robot#L58

The test doesn't cleanup the certs directory after deleting the VCH. Also, it deletes the VCH directly instead of using the `Cleanup VIC Appliance On Test Server` or a similar secret keyword that redacts the username and password.

**Acceptance criteria:**
* [x] Test cleans up the certs dir
* [x] Test uses a secret keyword to delete the VCH

**Comment by zjs** [comment]
It seems like the cleanup of old certificate directories is supposed to happen as a part of `Set Test Environment Variables`:

https://github.com/vmware/vic/blob/19c47c4212dbd35d70ce9adcc5ecfe7b54a918a0/tests/resources/VCH-Util.robot#L76-L77

This keyword is called from the `Suggest resources - Invalid datacenter` test in `Group6-VIC-Machine.6-05-Create-Validation`:

https://github.com/vmware/vic/blob/19c47c4212dbd35d70ce9adcc5ecfe7b54a918a0/tests/test-cases/Group6-VIC-Machine/6-05-Create-Validation.robot#L24

However, a few lines later in the test, the VCH name is changed:

https://github.com/vmware/vic/blob/19c47c4212dbd35d70ce9adcc5ecfe7b54a918a0/tests/test-cases/Group6-VIC-Machine/6-05-Create-Validation.robot#L24-L28

Calling `Set Test Environment Variables` and then calling `Set Test VCH Name` seems to be a recurring pattern for tests in this suite. However, `Set Test VCH Name` is already called as a part of `Set Test Environment Variables`:

https://github.com/vmware/vic/blob/19c47c4212dbd35d70ce9adcc5ecfe7b54a918a0/tests/resources/VCH-Util.robot#L75

This suggests that one way to avoid failures due to re-use of the certificates directory would be to remove the explicit calls to `Set Test VCH Name`.

The deletion test failing to use a secret keyword that redacts credentials seems to be a separate issue, which we can also fix.
