### ISSUE TITLE
Implement portlayer support for VM-Host Affinity

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7558]
This is likely to involve moving the hard-coded portions from the prototyping work out of the portlayer and into the install code.

This may also involve refactoring of `Commit`, as it is "getting excessively large and should be broken out into a separate subfunction with the addition of this logic" (https://github.com/vmware/vic/issues/6461#issuecomment-332584964).

Failure of the operation to update the `ClusterVmGroup` should be treated as a fatal error.

No operations requiring `Host.Inventory.EditCluster` should be performed when no DRS VM Group has been specified.

**Comment by andrewtchin** [comment]
includes unit tests if vcsim works for this

**Comment by zjs** [comment]
For testing, consider: https://github.com/vmware/vic/pull/7585#discussion_r177091957

**Comment by zjs** [comment]
>  We use unregister/re-register to fix invalid VM states (as is doc'd in kb database) - does that remove the VM from the group? If so then we'll need to add it back in on register.
(https://github.com/vmware/vic/pull/7585#discussion_r177091126)

**Comment by zjs** [comment]
For testing, consider: https://github.com/vmware/vic/pull/7585#issuecomment-376295619

**Comment by AngieCris** [comment]
Two problems need to be addressed/verified:

* VM unregister removes VM group membership
In fix VM logic for invalid states, we unregister and re-register the VM. Since unregistration removes VM group membership, we need to restore the VM group membership from session config.

* Potential race condition in cVM creation and adding newly created cVM to VM group.
The current workflow is: add cVM to cache, retrieve list of cVMs from cache and add the endpoint VM from self reference, commit the new VM list for cluster reconfigure.
This workflow could cause race condition because if there is some cVM that retrieves container cache before everyone else finishes adding to cache, this cVM would end up committing a partial VM list to cluster reconfigure. 

For example, suppose that we already have a cVM named `foo`, and we create two cVMs `bar` and `barz` at the same time. The following order of steps could happen:

current cache state: [`foo`]
`bar` adds to cache: [`foo`, `bar`]
`bar` retrieves cache list: [`foo`, `bar`]
`baz` adds to cache: [`foo`, `bar`, `baz`]
`baz` pushes to reconfigure: [`foo`, `bar`, `baz`]
`bar` pushes to reconfigure: [`foo`, `bar`]
In this case, the cluster ends up with a VM group containing the VMs from [`foo`, `bar`] that `bar` pushes in the last step, without container `baz`.

One possible fix would be to introduce locking and make the process of retrieving cache and committing new list an asynchronous operation.
