### ISSUE TITLE
Error response from daemon: page not found

### ISSUE THREAD

**Issue by brockz** [vmware/vic#7699]
When i do an docker build to an remote vch  from an linux docker client
I getting  the following Error:

docker build -t my_reg/default-project/test-container .
Error response from daemon: page not found

Normal Docker commands working successfully against vch.

xxxx@gt-ubuntu01:~/test$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: v1.3.1-16055-afdab46
Storage Driver: vSphere Integrated Containers v1.3.1-16055-afdab46 Backend Engine
VolumeStores: hch-volumes
vSphere Integrated Containers v1.3.1-16055-afdab46 Backend Engine: RUNNING
 VCH CPU limit: 9520 MHz
 VCH memory limit: 27.9 GiB
 VCH CPU usage: 952 MHz
 VCH memory usage: 25.3 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.5.0
 Registry Whitelist Mode: enabled
 Whitelisted Registries: xxxxxx
Plugins:
 Volume: vsphere
 Network: bridge
Swarm: inactive
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 9520
Total Memory: 27.9 GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false

**Comment by mdubya66** [comment]
Docker build is not implemented in VIC. To do docker build you need to use a DCH. Keeping this open because the error message could be improved. 

https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/build_push_images.html talks about getting setup with the dch-photon container.

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/issues/4741 is the Epic for implementing docker build in VIC

**Comment by brockz** [comment]
I think this is still the Problem.
I following the Manual:
https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/photon_cert_custom.html

On Step 5:
In the same folder, build the Dockerfile as a new image and give it a meaningful new tag.

docker build -t registry_address/default-project/dch-photon:1.13-cert .

i got an:
xxx@xxxx:~/dch-photon$ docker build -t xxxx/default-project/dch-photon:1.13-cert .
Sending build context to Docker daemon  5.12 kB
Error response from daemon: page not found

**Comment by morris-jason** [comment]
@brockz Thank you for your interest in vSphere Integrated Containers! 

I've successfully completed all steps in [Add the Registry Certificate to a Custom Image](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/photon_cert_custom.html) without experiencing your issue. I believe you are experiencing the following problem:

On step 5, are running `docker build -t registry_address/default-project/dch-photon:1.13-cert .` with the `DOCKER_HOST` environment variable set?

As @mdubya66 pointed out, this is directing the VCH to build the dch-photon-cert image. As this is not a supported action, the documentation expects that all `docker` operations are occurring against your local docker host. All build operations must be targeted against a local docker instance.

Please ensure you are following the documentation with the DOCKER_HOST environment variable unset. To refer to the VCH in the later half of the document, please use the `docker -H <vch_address>:2376` syntax instead of setting the DOCKER_HOST variable.

I'm closing this issue now as I successfully followed the documentation, but please reach out if you continue to experience this issue. Please upload a screencast or a list of commands and their outputs that lead you to this problem.
