### ISSUE TITLE
11-01-Upgrade: Fail to vic-machine ls VCH that was upgraded and rolled back

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7800]
Test steps:
1. Start with 1.2.1 VCH
2. Upgrade to latest master
3. Roll back to 1.2.1
4. vic-machine ls <---- at this point no VCH is listed, but vic-machine inspect by name still works

Seen here:
https://ci-vic.vmware.com/vmware/vic/18592/7
https://ci-vic.vmware.com/vmware/vic/18590/7
https://ci-vic.vmware.com/vmware/vic/18561/7
https://ci-vic.vmware.com/vmware/vic/18564/7

It does seem to pass sometimes, so maybe a race/eventual consistency?

**Comment by cgtexmex** [comment]
Also to be noted -- the `Install VIC with version to Test Server` is NOT installing the specified version.  If you look at the output from the first test (`Upgrade Present in vic-machine`) you'll see the following version: `v1.4.0-dev-18592-f1c9787` -- the test passes because our versioning is a bit screwed up so it shows an available upgrade even thought it's the current version...

Also it appears that the keyword `Check Original Version` has a few issues:
- It's running `./bin/vic-machine` -- the specified installed version is in `./vic/vic-machine`
- It's comparing the version returned against the `%INITIAL_VERSION` var...which is (as far as I can tell) just the string passed to the `Install` keyword...I don't think it's ever set via `vic-machine version` after install...basically I'd expect us to verify that what we said we wanted to install we actually install...

**Comment by mhagen-vmware** [comment]
Not sure where you are getting that from, I am looking at build 18592 ( the first in the list above ):
![image](https://user-images.githubusercontent.com/19393273/39132009-6f09eb3a-46d6-11e8-9253-dbe7c67d7c7b.png)

I am seeing it wget the correct version, 1.2.1, untar it to vic and run /vic/vic-machine-linux to install it.  And the later Check Original Version:
![image](https://user-images.githubusercontent.com/19393273/39132127-b94b28f8-46d6-11e8-8a76-3a417493460c.png)

Also appears correct to me, it is just expecting that initial version (was set to 1.2.1 in the install)  is present in the output, which it is.

**Comment by cgtexmex** [comment]
@mhagen-vmware I'm looking at `log.html` from `integration_logs_18592_f1c9787f7a03a79612c2ff8a3e16ed4513551f79`

![screen shot 2018-04-23 at 12 10 26 pm](https://user-images.githubusercontent.com/726112/39139422-de0d48ec-46ef-11e8-8783-a5cdd48de91f.png)

**Comment by mhagen-vmware** [comment]
That is correct though as well, `Upgrade Present in vic-machine` doesn't look like the purpose is really documented at all within the md but it looks like to me the purpose is just verifying that the current vic-machine which should be the built one (1.4... in this build) not the 1.2.1 one has upgrade present as an option.

**Comment by cgtexmex** [comment]
This is happening because the there is only a vApp installed (default install of 1.2.1) -- as such the cluster only has one resource pool so `ls` doesn't look for a vApp since it _assumes_ DRS is disabled.
