### ISSUE TITLE
Investigation into Docker Pull speed 

### ISSUE THREAD

**Issue by sgairo** [vmware/vic#7841]
As per @hickeng 's comment in https://github.com/vmware/vic-planning/issues/103, we need to know where the majority of time performing a docker pull is spent. 

Deliverable:
A breakdown of the docker pull process and the speeds of the different components. 
A decision on a path to improvement

**Comment by jzt** [comment]
This is a first-look at the docker pull end-to-end operation. I referenced the pull code while digging into the logs using the `BEGIN` and `END` tracing between calls.

I would have preferred to generate a [flamegraph](https://github.com/brendangregg/FlameGraph) using `pprof` data. Unfortunately, there is currently no method to generate the graphs for off-cpu (blocking) operations with `pprof`, which accounts for most of the time we spend (docker waiting on portlayer, portlayer waiting on vSphere).

I was, however, able to get some decent numbers around where most of our time is spent. This is not a compilation of data across many runs of `docker pull`, but I did run the end-to-end pull many times and saw similar behavior each time. This was intended to serve as a rough sketch to see if our expectations lined up with reality, and for the most part, the numbers are as we expected. Apart from the total end-to-end time, this does not account for the time it takes to download the layer data, for two reasons: The first is that the layers are pulled concurrently and written serially from parent->child. The second is that download speed is not something we can control programmatically outside of raising the max number of concurrent layer downloads (currently 3).

Test environment:
VIC: 1.4.0
VC 6.7 build 8126527, Nimbus
ESXi 6.7 build 8126342
Registry: Docker Hub
Image:  `library/nginx`

The entire `library/nginx` pull operation took 1 minute and 8 seconds (compare to a normal docker pull - 12.45 seconds). Obviously the system load and network play a big role in how long this takes.
```
May  7 2018 18:38:56.849Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ImageBackend).PullImage:323] [1m8.055186845s]
```
The point at which time becomes a factor in the image pull path is in imagec's [`DownloadLayers`](https://github.com/vmware/vic/blob/master/lib/imagec/download.go#L106) function. This function spawns goroutines to download each layer, with a concurrent maximum of 3 layers, in parent->child order.

The workflow for one of these goroutines is as follows:
- downloading the layer data
- streaming it to the portlayer to be written to the datastore ([`imagec.WriteImageBlob`](https://github.com/vmware/vic/blob/master/lib/imagec/imagec.go#L320:19)) 
- saving the layer metadata to the k/v store in VC (['kv.Put'](https://github.com/vmware/vic/blob/master/pkg/kvstore/kvstore.go#L117))

This behavior can be visualized as a sliding window, 3 layers (goroutines) wide, moving over the list of layers to be downloaded in parent->child order.

The vast majority of the time spent from here (50.17 seconds in this test) was unsurprisingly spent in calls to `imagec.WriteImageBlob`. 
The remaining 18 seconds or so were all the somewhat small operations that are interleaved between these calls, including the actual time taken to download layer data from the registry (not considered in the following breakdown).
The most time consuming of the operations outside of `imagec.WriteImageBlob` are saves to the layer cache after each layer is pulled (each write to this VC-side k/v store costs about ~1s second on average, adding about ~9.2s when pulling nginx). 

`imagec.WriteImageBlob` is expected to take time, as we are attaching/detaching/mounting/unmounting disks on the backend, and writing to the datastore on the vSphere across the VCH <-> vSphere API boundary.
What happens once we cross the docker persona -> portlayer boundary inside `imagec.WriteImageBlob` begins at the storage handler's `WriteImage` function. Here is what the flow typically looks like (these times taken from the first layer in the nginx image being downloaded). Note: some steps are skipped as they are not really relevant (checking if the layer already exists in the cache, etc) and add no significant time (tens of microseconds):

1. If the layer is not already in the cache, a datastore lookup is triggered via [`GetImage`](https://github.com/vmware/vic/blob/master/lib/portlayer/storage/image_cache.go#L327)  (~300ms)
2. If not in the datastore, [a new directory is created for the incoming layer, and some metadata written within](https://github.com/vmware/vic/blob/master/lib/portlayer/storage/vsphere/image.go#L346). (~900ms)
3. We call [`CreateAndAttach`](https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk_manager.go#L152) to create a new VMDK for the layer and attach it to the appliance. The call took 1.26 seconds total, and the majority of the time was spent in [attach](https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk_manager.go#L329) at 1.13 seconds (`WaitForResult`). (1.26s)
4. The disk is [mounted](https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk.go#L257)  (~300ms)
5. The layer data is written to the disk, ~22.5 MB in this case (not currently traced in our code, but captured in bottom chart). (~1.1s)
6. The disk is [unmounted](https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk.go#L365) (~2.35s)
7. The disk is [detached](https://github.com/vmware/vic/blob/master/pkg/vsphere/disk/disk_manager.go#L382) (~580ms)

The total time in the portlayer's `WriteImage` for this layer (`6be50030`): 6.7 seconds. Total round-trip time in `imagec.WriteImageBlob` for this `6be50030`: 7.23 seconds. This is pretty consistent for all non-empty layers, as illustrated by the following tables. 

In this table, each row represents a complete flow through the storage portlayer's [`WriteImage`](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/storage_handlers.go#L319) (one row per layer). Some fast/local ops are omitted for brevity:

| Layer ID | Blobsum | Layer Size | GetImage | CreateAndAttach (attach) | Mount | Write To Datastore | Unmount | Detach |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 6be50030 | f2aa67a3 | 22.5 MB | 294ms | 1.27s  (1.13s) |  275ms | 1.1s |  2.35s   |  579ms |  
| 0483928f | a3ed95ca | 32 B | 128ms | 1.35s  (1.16s) |  285ms | 11ms |  34ms |  509ms |
| b96755dc | a3ed95ca | 32 B | 116ms | 1.56s  (1.38s) |  338ms | 9ms |  15ms |  831ms |
| 5a12309a | a3ed95ca | 32 B | 119ms | 1.33s  (1.17s) |  378ms    | 14ms |  33ms    |  962ms |
| 699c8955 | a3ed95ca | 32 B | 120ms | 1.45s  (1.27s) |  305ms    | 11ms |  30ms    |  922ms |
| 4be96ef4 | 3c091c23 | 22.5 MB | 81ms | 1.65s   (1.46s)  | 359ms     | 970ms | 1.53s    | 612ms  |
| 4b2bbde9 | 4a99993b | 201 B | 118ms | 2.62s  (2.43s) |  295ms    | 50ms |  54ms    |  609ms |
| fd4eb13d | a3ed95ca | 32 B | 115ms | 2.64s   (2.48s) |  317ms    | 12ms |  34ms    |  675ms |
| dac93c72 | a3ed95ca | 32 B | 130ms | 1.75s  (1.57s) |  286ms    | 4ms |  6ms     |  780ms |
| 01133ef0  | a3ed95ca | 32 B | 117ms | 3.03s  (2.9s)  |  337ms | 33ms | 720ms | 782ms |

The next table is from the docker personality view ([`imagec.DownloadLayers`](https://github.com/vmware/vic/blob/master/lib/imagec/download.go#L106)). Each row represents the call to `imagec.WriteImageBlob` followed by the call to store the layer data in the k/v store on vSphere. Data transfer time from the registry is omitted as it's not useful, and some fast/local ops are omitted for brevity.

| Layer ID | Blobsum | Layer Size | WriteImageBlob | k/v Put() | Empty layer | Total Time (s) |
| --- | --- | --- | --- | --- | --- | --- |
| 6be50030 | f2aa67a3 | 22.5 MB | 7.23s | 815ms | No | 9.15 |
| 0483928f | a3ed95ca | 32 B | 3.78s | 706ms | Yes   | 4.2 |
| b96755dc | a3ed95ca | 32 B | 4.14s | 860ms | Yes  | 5.01 |
| 5a12309a | a3ed95ca | 32 B | 4.29s | 877ms | Yes | 5.18 |
| 699c8955 | a3ed95ca | 32 B | 4.06s | 839ms | Yes | 4.91 |
| 4be96ef4 | 3c091c23 | 22.5 MB | 6.61s | 957ms | No | 8.54 |
| 4b2bbde9 | 4a99993b | 201 B | 4.99s | 763ms | No | 5.80 |
| fd4eb13d | a3ed95ca | 32 B | 5.27s | 1.78s | Yes | 7.06 |
| dac93c72 | a3ed95ca | 32 B | 4.20s | 809ms | Yes | 5.01 |
| 01133ef0  | a3ed95ca | 32 B | 5.65s | 789ms | Yes | 6.45 |

#### Conclusion
Obviously more exhaustive tests (averaging results from a larger sample size - different images, more pulls per image, different testbed configurations, etc) should be performed. Some operations seem to take longer sometimes for no apparent reason (e.g. Unmount usually sometimes taking multiple seconds vs. the apparent norm of tens of milliseconds). That said, even this simple first-pass consisting of a single sample `docker pull` verifies what we expected and highlights some obvious steps we could take to improve performance. The two big examples:
- Batch write calls to the k/v store in order to save calls to vSphere and cut down on time (we could save `n-1` seconds on an `n`-layer image pull).
- Stop creating VMDKs for every empty layer. There were 7 empty layers in the `library/nginx` example, whose creation and writes took an accumulated 31.4 seconds (almost half of the total end-to-end pull time). Substantial improvements are possible, especially for images with many empty layers (`library/tomcat`, for example, has 21 empty layers.. this improvement would would result in a ~90 second reduction off the time required to pull `tomcat`).

Based on this rough data, with these two fixes in place, this pull (in theory) would have taken ~32 seconds instead of 1 minute 8 seconds, a ~53% improvement in pull speed.
