### ISSUE TITLE
Add integration tests for bash and zsh completion

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7850]
In addition to abstract unit testing of our shell completion functionality, we should provide tests to verify the functionality in an end-to-end way.

**Details:**
See https://github.com/vmware/vic/pull/7785#issuecomment-384732144 for some technical challenges.

**Acceptance Criteria:**
We verify that `vic-machine`, as it would be installed and used by an administrator, produces correct completion suggestions on each supported operating system.

**Comment by mhagen-vmware** [comment]
we have already been down this road before - see docker attach efforts... I know of no way to do this aside from keyboard/mouse/screen capture macro testing and I don't see us ever having the time or resources to ever do that. The only thing I would like to see done here is if this new functionality supports partial completion then we can easily throw in some tests like that:
```
vic-machine-linux creat
vic-machine-linux crea
vic-machine-linux cr
vic-machine-linux config
vic-machine-linux co
```
otherwise, I would close this and rely on team usage testing

**Comment by zjs** [comment]
As I understand it, partial completion are handled by the shell itself; this is how `zsh` is able to support mid-word suggestions even though`bash` only supports beginning-of-word suggestions.  (In other words, the shell's completion tool strips the incomplete argument, gets suggestions, and then applies its own filtering of those based on the incomplete argument before showing them to the user.)
