### ISSUE TITLE
Port Layer: list containers

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#798]
Port layer operation exec.List.

This returns the set of IDs that can be passed to Get to obtain a handle to the container.
This does not return any additional information about the containers, beyond an ID.

Implementation note:
This should not return handles from the LRU cache - the list needs to be stable and the set of handles within the cache is not - the list itself could potentially be long enough to evict some of it's own handles. This should return IDs that can be used with Get.

**Comment by cgtexmex** [comment]
@hickeng why would the call to List not return any additional container information?  Why make multiple calls for something that can be accomplished in one?

**Comment by corrieb** [comment]
We need to discuss this, both in the context of what we have and what we want. I am supportive of a List function that just returns IDs (ideally based on some kind of bitmask that can restrict them to a certain running state). However, we need to consider the performance impact of making a remote call to the port layer server for every single container. That might be OK when its co-located, but if it's on a remote host, it could be problematic.

**Comment by corrieb** [comment]
We need to consider all of the needs of port layer clients in getting state information about a container and have some sensible return types that aren't catch-all dumping grounds for everything. 

Further, I'd say that we should take each operation on merit. Just because we create one API call that does a bulk operation on an array of IDs, doesn't mean we have to do it for everything. Eg. A delete call, if it's synchronous (which I expect it would be), isn't going to return instantaneously, so looping over a delete call per container might be fine.

**Comment by cgtexmex** [comment]
one bit of color to add -- I'm looking at this specifically threw the eyes of returning state information about the running containers.  I just need a snapshot of what's happening now and do not need a handle to act on those containers -- essentially I'm looking at it as a reporting function for the PL.

**Comment by corrieb** [comment]
I would concur. A handle should only be required for any state change to the container. For any kind of querying of state, an ID should suffice

**Comment by sflxn** [comment]
Here's my opinion of whether it's a list of ids or more info.  For in-proc applications, it's fine to define interfaces that just returns an array of one thing.  For anything out-of-proc or that involves some communication transport, it's better practice to return as much data as necessary, reducing round trip calls.

**Comment by sflxn** [comment]
BTW, @cgtexmex and I just did a hangout to figure out how to accelerate docker ps as well as docker inspect containers.  We're going to split this work up.  I'll be defining the Swagger specifications for getting container metadata as well as for docker ps.  Clint can then worry about actual metadata work instead of learning swagger while doing it, and I will have some swagger definitions to stub out some code for docker inspect container.

**Comment by hickeng** [comment]
@sflxn sounds good - please talk to Ben about the Go interface for the function and put an outline of the swagger spec here before adding all the detail.
