### ISSUE TITLE
UI Plugin VC deployment

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#910]
Determine the correct procedures to deploy our VIC UI plugin on vSphere web client. We will need to find out the typical admin workflow and see if any of this can be automated.

Questions to answer:
Where are we putting the ui build artifact(s)?
How does the admin consume this and register with vc server?
Can any of this be automated and what is the best practice?

Acceptance criteria: User is able to successfully register the VIC UI extension in their VC

**Comment by jooskim** [comment]
I've been compiling multiple docs into one Word document. Based on further reading on the SDK-Tutorial.html. Putting up the draft file for reference.
[vsphere-client-sdk-plugin-deployment-guide-draft.docx](https://github.com/vmware/vic/files/292225/vsphere-client-sdk-plugin-deployment-guide-draft.docx)

**Comment by jooskim** [comment]
Updated the Word file according to Vladimir's solution to deploying plug-in packages. Now need to discuss how it could be integrated into VIC repo
[vsphere-client-sdk-plugin-deployment-guide-draft.docx](https://github.com/vmware/vic/files/300781/vsphere-client-sdk-plugin-deployment-guide-draft.docx)

**Comment by jooskim** [comment]
Now we have clear understanding about the constraint (no internet connection assumed) and possibly the best way to deploy UI plugins without internet connection.

1. Proof-of-concept script (in Bash) works on VCSA.
2. Need to test the script with a vCenter for Windows instance.
3. Documented the logics so that Andrew and Emma could start writing code based off of it

**Comment by andrewtchin** [comment]
`vic-machine` proposal in #1101

**Comment by jooskim** [comment]
Done with initial instruction and install scripts. Closing this issue in favor of issue #1101
