### ISSUE TITLE
Docker API tests

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#98]
Turns out docker have an API test suite - need to investigate what/where/how.

**Comment by sflxn** [comment]
Yes, we will be able to run this against VIC... However (!), it's not as easy as just running their tests.  A lot of their tests makes assumptions and the test init does a few pre-req operations.  Basically, the one test (image create) I tried failed because it attempts to do a few operations before hand, like container list and volume list (neither of which have been implemented).  I can only get the test to even run by hacking their code.

Also, there is the issue of vendoring their integration test.  It brings over all of them and running test on that package causes all files to build.  The clean up we'd need to do in their files that we do not use would make this untenable.  I'm thinking we need to vendor their integration test package and then have our make file run a script that copies specific files in that package to a temporary integration folder in VIC and run those tests.  This way, we can be sure of which version of the test we're pulling, and we simplify our running of those tests.  Otherwise, getting these tests to run flawlessly on VIC will require a lot of changes to their code.

**Comment by sflxn** [comment]
https://github.com/sflxn/vic/tree/docker-tests

Obviously, VIC fails right now because many operations are not yet implemented, but it shows we can run the test suite.  Please note, as described above, this WIP is selectively copying over tests from a vendored copy of their integration-cli package.

**Comment by sflxn** [comment]
Once we add docker images (list images), we can remove docker_utils.go.  A lot of tests appears to rely on list images and list containers.

**Comment by sflxn** [comment]
As far as completion of this task is concerned, the original goal of finding these tests and figuring out how to run them has been achieved by the WIP PR.

**Comment by sflxn** [comment]
We now have docker image list operation so I have removed the hacked file and updated the PR.

**Comment by sflxn** [comment]
I've updated the PR to include a fix for a bug found when running the script against regular docker.
